/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  AnalogTVResDefs.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  Define AnalogTV related resource IDs
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/
#ifndef _ANALOGTV_RES_DEF_H_
#define _ANALOGTV_RES_DEF_H_

#include "mmi_features.h"
#include "mmi_data_types.h"

#if defined(__MMI_ANALOGTV__)
/********************************************************************************/
/********************************************************************************/
typedef enum
{
	SCR_ID_ANALOGTV_APP = ANALOGTV_BASE + 1,
	SCR_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,
	SCR_ID_ANALOGTV_OPTION,
	SCR_ID_ANALOGTV_OPTION_SEARCH,
	SCR_ID_ANALOGTV_OPTION_CHANNEL_SELECT,
	SCR_ID_ANALOGTV_CHANNEL_LIST,
	SCR_ID_ANALOGTV_USER_CHANNEL_LIST,
	SCR_ID_ANALOGTV_CHANNEL_LIST_OPTION,
	SCR_ID_ANALOGTV_CHANNEL_LIST_OPTION_RENAME,
	SCR_ID_ANALOGTV_USER_CHANNEL_LIST_OPTION,
	SCR_ID_ANALOGTV_USER_CHANNEL_LIST_OPTION_RENAME,
	SCR_ID_ANALOGTV_MENU,
	SCR_ID_ANALOGTV_SETTING,
	SCR_ID_ANALOGTV_SETTING_STORAGE,
	SCR_ID_ANALOGTV_SETTING_EFFECT,
	SCR_ID_ANALOGTV_SETTING_EFFECT_BRIGHT,
	SCR_ID_ANALOGTV_SEARCH_AREA,
	SCR_ID_ANALOGTV_DELETE_CHANNEL_CONFIRM,	/*DAVID*/
	SCR_ID_ANALOGTV_PROCESS,
	SCR_ID_ANALOGTV_TOTAL_COUNT
	
} analogtv_scr_id_enum;

typedef enum
{
    /* camera app */
	STR_MENU_ID_ANALOGTV_MAIN = ANALOGTV_BASE + 1,
    /* Total string count */
	STR_MENU_ID_ANALOGTV_OPTION,
	STR_MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,
	STR_MENU_ID_ANALOGTV_OPTION_CHANNEL_SELECT,
	STR_MENU_ID_ANALOGTV_OPTION_ADD_USER_CHANNEL,
	STR_MENU_ID_ANALOGTV_OPTION_SEARCH_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_EFFECT,
	STR_MENU_ID_ANALOGTV_OPTION_RECORDER,
	STR_MENU_ID_ANALOGTV_OPTION_SETTING,

	STR_MENU_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,
	STR_MENU_ID_ANALOGTV_CHANNEL_MANUAL_SEARCH,
	STR_MENU_ID_ANALOGTV_CHANNEL_LIST,
	STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED,
//For TV169	
	STR_MENU_ID_ANALOGTV_OPTION_CHINA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_SHENZHEN_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_CHINA_TAIWAN_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_EUROP_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_AMERICA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_CHINA_MACAO_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_INDIA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_PAKISTAN_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_INDONESIA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_HONGKONG_AREA,
	/*STR_MENU_ID_ANALOGTV_OPTION_IRAN_AREA,*/
	/*STR_MENU_ID_ANALOGTV_OPTION_IRAQ_AREA,*/
	STR_MENU_ID_ANALOGTV_OPTION_YEMEN_AREA,
	/*STR_MENU_ID_ANALOGTV_OPTION_SAUDI_ARABIA_AREA,*/
	STR_MENU_ID_ANALOGTV_OPTION_BAHRAIN_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_ABU_DHABI_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_KUWAIT_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_THAI_AREA,
	/*STR_MENU_ID_ANALOGTV_OPTION_RUSSIAN_AREA,*/
	STR_MENU_ID_ANALOGTV_OPTION_PORTUGAL_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_SPAIN_AREA,
	/*STR_MENU_ID_ANALOGTV_OPTION_FRANCE_AREA,*/
	STR_MENU_ID_ANALOGTV_OPTION_PHILIPINES_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_MALAYSIA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_VIETNAM_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_BRAZIL_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_UK_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_SOUTH_AFRICA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_TURKEY_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_SINGAPORE_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_CAMBODIA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_LAOS_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_AFGHANISTA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_CANADA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_KOREA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_MEXICO_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_CHILE_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_VENEZUELA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_JAPAN_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_ARGENTINA_AREA,
#if 1
	STR_MENU_ID_ANALOGTV_OPTION_BURMA_AREA,
	STR_MENU_ID_ANALOGTV_OPTION_RUSSIA_AREA,
#endif
#ifdef __MMI_FACT_TEST__
    STR_MENU_ID_ANALOGTV_OPTION_RDAFACT_AREA,
#endif
	STR_MENU_ID_ANALOGTV_OPTION_MAXIMUM_AREA,

	STR_MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,
	STR_MENU_ID_ANALOGTV_OPTION_EFFECT_COLOR_DEPTH,

	STR_MENU_ID_ANALOGTV_CHANNEL_LIST_PLAY,
	STR_MENU_ID_ANALOGTV_CHANNEL_LIST_RENAME,
	STR_MENU_ID_ANALOGTV_CHANNEL_LIST_DELETE,  
	STR_MENU_ID_ANALOGTV_CHANNEL_LIST_ADD_USER_CHANNEL,
	STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_PLAY,
	STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_RENAME,

	STR_ID_CHANNEL_NAME,
	STR_MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,
	STR_MENU_ID_ANALOGTV_SETTING_STORAGE,
	STR_MENU_ID_ANALOGTV_SETTING_DELETE_ALL_CHANNEL,
	STR_ID_ANALOGTV_ERROR_FULL,
	STR_GLOBAL_SNAPSHOTTING, /*renxing for snap*/	
	
	STR_ID_ANALOGTV_TOTAL_COUNT 
} analogtv_str_id_enum;    

typedef enum
{
	IMG_ID_ANALOGTV_MAIN=ANALOGTV_BASE + 1,
	IMG_ID_ANALOGTV_PANNEL_BG,
	IMG_ID_ANALOGTV_CHANNEL_NORMAL,
	IMG_ID_ANALOGTV_CHANNEL_PRESSED,
	IMG_ID_ANALOGTV_CHANNEL_PRE_NORMAL,
	IMG_ID_ANALOGTV_CHANNEL_PRE_PRESSED,
	IMG_ID_ANALOGTV_CHANNEL_NEXT_NORMAL,
	IMG_ID_ANALOGTV_CHANNEL_NEXT_PRESSED,
	IMG_ID_ANALOGTV_VOL_INC_NORMAL,
	IMG_ID_ANALOGTV_VOL_INC_PRESSED,
	IMG_ID_ANALOGTV_VOL_DEC_NORMAL,
	IMG_ID_ANALOGTV_VOL_DEC_PRESSED,
	IMG_ID_ANALOGTV_VOL_LEVEL1,
	IMG_ID_ANALOGTV_VOL_LEVEL2,
	IMG_ID_ANALOGTV_VOL_LEVEL3,
	IMG_ID_ANALOGTV_VOL_LEVEL4,
	IMG_ID_ANALOGTV_VOL_LEVEL5,
	IMG_ID_ANALOGTV_VOL_LEVEL6,
	IMG_ID_ANALOGTV_VOL_LEVEL7,
	IMG_ID_ANALOGTV_MY_CHANNEL_NORMAL,
	IMG_ID_ANALOGTV_MY_CHANNEL_PRESSED,
	IMG_ID_ANALOGTV_BRIGHTNESS_NORMAL,
	IMG_ID_ANALOGTV_BRIGHTNESS_WEAK,
	IMG_ID_ANALOGTV_BRIGHTNESS_HIGH,
	IMG_ID_ANALOGTV_COL_DEPTH_NORMAL,
	IMG_ID_ANALOGTV_COL_DEPTH_WEAK,
	IMG_ID_ANALOGTV_COL_DEPTH_HIGH,
	IMG_ID_ANALOGTV_RECORD_NORMAL,
	IMG_ID_ANALOGTV_RECORD_PRESSED,
	IMG_ID_ANALOGTV_LSK_NORMAL,
	IMG_ID_ANALOGTV_LSK_PRESSED,
	IMG_ID_ANALOGTV_RSK_NORMAL,
	IMG_ID_ANALOGTV_RSK_PRESSED,
	IMG_ID_ANALOGTV_PANNEL_BG_SEARCH,
	IMG_ID_ANALOGTV_SPEAKER_VOICE,
	IMG_ID_ANALOGTV_SPEAKER_MUTE,
	IMG_ID_ANALOGTV_SEARCH_PROGRESS_BG,
	IMG_ID_ANALOGTV_SEARCH_PROGRESS_TIC,

	IMG_ID_ANALOGTV_MENU_ICON,
	
	IMG_ID_ANALOGTV_CHANNEL_NUM0,
	IMG_ID_ANALOGTV_CHANNEL_NUM1,
	IMG_ID_ANALOGTV_CHANNEL_NUM2,
	IMG_ID_ANALOGTV_CHANNEL_NUM3,
	IMG_ID_ANALOGTV_CHANNEL_NUM4,
	IMG_ID_ANALOGTV_CHANNEL_NUM5,
	IMG_ID_ANALOGTV_CHANNEL_NUM6,
	IMG_ID_ANALOGTV_CHANNEL_NUM7,
	IMG_ID_ANALOGTV_CHANNEL_NUM8,
	IMG_ID_ANALOGTV_CHANNEL_NUM9,

    IMG_ID_ANALOGTV_SIGNAL,
    IMG_ID_ANALOGTV_SIGNAL0,
    IMG_ID_ANALOGTV_SIGNAL1,
    IMG_ID_ANALOGTV_SIGNAL2,
    IMG_ID_ANALOGTV_SIGNAL3,
    IMG_ID_ANALOGTV_SIGNAL4,
    IMG_ID_ANALOGTV_SIGNAL5,
    IMG_ID_ANALOGTV_VOL_LEVEL,
    IMG_ID_ANALOGTV_BRIGHTNESS_DEC_NORMAL,
    IMG_ID_ANALOGTV_BRIGHTNESS_INC_NORMAL,
    IMG_ID_ANALOGTV_BRIGHTNESS_LEVEL,
    
	IMG_ID_ANALOGTV_TOTAL_COUNT

}analogtv_img_id_enum;
/********************************************************************************/
#endif
/********************************************************************************/
#endif /* _ANALOGTV_RES_DEF_H_ */ 

