/*
 * Copyright  1990-2009 Sun Microsystems, Inc. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 only, as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License version 2 for more details (a copy is
 * included at /legal/license.txt).
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 * 
 * Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
 * Clara, CA 95054 or visit www.sun.com if you need additional
 * information or have any questions.
 *
 */

/*
 * This file is auto generated by Configurator.
 */

#ifndef NULL
#define NULL (void*)0
#endif

char* javacall_static_properties_sections[] = {
    "application",
    "internal",
    NULL
};

char* javacall_internalKey[] = {
    "mmapi.content0",
    "mmapi.content1",
    "mmapi.content10",
    "mmapi.content2",
    "mmapi.content3",
    "mmapi.content4",
    "mmapi.content5",
    "mmapi.content6",
    "mmapi.content7",
    "mmapi.content8",
    "mmapi.content9",
    "system.jam_space",
    NULL
};

char* javacall_internalValue[] = {
    "CAPTURE_AUDIO audio/x-wav",
    "CAPTURE_RADIO audio/x-wav",
    "RTP_L16 audio/L16",
    "CAPTURE_VIDEO video/mpeg",
    "MPEG1_layer_3 audio/mpeg",
    "MS_PCM audio/x-wav audio/wav",
    "MIDI audio/midi audio/mid audio/x-midi",
    "SP_MIDI audio/sp-midi",
    "TONE audio/x-tone-seq audio/tone",
    "AMR audio/amr",
    "MPEG_1 video/mpeg",
    "1000000",
    NULL
};

char* javacall_systemKey[] = {
    NULL
};

char* javacall_systemValue[] = {
    NULL
};

char** javacall_static_properties_keys[] = {
    javacall_systemKey,
    javacall_systemValue,
    NULL
};

char** javacall_static_properties_values[] = {
    javacall_internalKey,
    javacall_internalValue,
    NULL
};
