/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  wgui_categories_defs.h
 * Project:
 * --------
 
 * Description:
 * ------------
 *  Common definitions of categories.
 *  Author:
 * -------
 
 *==============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/
#ifndef __WGUI_CATEGORIES_DEFS_H__
#define __WGUI_CATEGORIES_DEFS_H__

#include "mmi_features.h"
#include "gui_windows.h"

enum MMI_CATEGORY_ID_LIST
{
    MMI_LIST_CATEGORY_ID = 1,
    MMI_CATEGORY5_ID,
    MMI_CATEGORY6_ID,
    MMI_CATEGORY7_ID,
    MMI_CATEGORY9_ID,
 
#ifdef UI_SMALL_LIST_SCREEN
    MMI_CATEGORY10_ID,
#endif 
  
    MMI_CATEGORY12_ID,
    MMI_CATEGORY14_LIST_ID,
    MMI_CATEGORY14_MATRIX_ID,
    MMI_CATEGORY14_CIRCULAR_ID,
    MMI_CATEGORY14_ROTATE_ID,
    MMI_CATEGORY15_LIST_ID,
    MMI_CATEGORY15_MATRIX_ID,
    MMI_CATEGORY16_ID,
    MMI_CATEGORY18_ID,
    MMI_CATEGORY18_NORMAL_ID,
    MMI_CATEGORY18_STATUS_ICON_ID,
    MMI_CATEGORY18_NONE_ID,
    MMI_CATEGORY19_ID,
    MMI_CATEGORY20_ID,
    MMI_CATEGORY21_ID,
    MMI_CATEGORY22_ID,
    MMI_CATEGORY28_ID,
    MMI_CATEGORY29_ID,
    MMI_CATEGORY32_ID,
    MMI_CATEGORY33_ID,
    MMI_CATEGORY34_ID = MMI_CATEGORY33_ID,
    MMI_CATEGORY35_ID,
    MMI_CATEGORY36_ID,
    MMI_CATEGORY39_ID,
    MMI_CATEGORY52_ID,
    MMI_CATEGORY53_ID,
    MMI_CATEGORY57_ID,
    MMI_CATEGORY59_ID,
    MMI_CATEGORY61_ID,
    MMI_CATEGORY62_ID,
    MMI_CATEGORY63_ID,
    MMI_CATEGORY64_ID,
    MMI_CATEGORY65_ID,
    MMI_CATEGORY66_ID,
    MMI_CATEGORY66_NORMAL_ID,
    MMI_CATEGORY66_STATUS_ICON_ID,
    MMI_CATEGORY66_NONE_ID,
    MMI_CATEGORY69_ID,
    MMI_CATEGORY72_ID,
    MMI_CATEGORY73_ID,
    MMI_CATEGORY74_ID,
    MMI_CATEGORY75_ID, //qiff to aviod some window no content
    MMI_CATEGORY76_ID,
    MMI_CATEGORY77_ID,// qiff modify here =MMI_CATEGORY76_ID,
    MMI_CATEGORY78_ID,
    MMI_CATEGORY80_ID,
    MMI_CATEGORY81_ID,
    MMI_CATEGORY82_ID,
    MMI_CATEGORY84_ID,
    MMI_CATEGORY86_ID,
    MMI_CATEGORY86_NORMAL_ID,
    MMI_CATEGORY86_STATUS_ICON_ID,
    MMI_CATEGORY86_NONE_ID,
    MMI_CATEGORY87_ID,
    MMI_CATEGORY88_ID,
    MMI_CATEGORY88_1ITEM_ID,
    MMI_CATEGORY88_2ITEM_ID,
    MMI_CATEGORY88_3ITEM_ID=MMI_CATEGORY88_ID,
    MMI_CATEGORY89_ID,
    MMI_CATEGORY90_ID,
    MMI_CATEGORY91_ID,
    MMI_CATEGORY92_ID,
    MMI_CATEGORY93_ID,
 
#ifdef UI_SMALL_CATEGORY_EDITOR
    MMI_CATEGORY100_ID,
#endif 
  
    MMI_CATEGORY105_ID,
    MMI_CATEGORY106_ID,
    MMI_CATEGORY109_ID,
    MMI_CATEGORY111_ID,
   
#ifdef UI_SMALL_PIN_EDITOR_SCREEN
    MMI_CATEGORY112_ID,
#endif 
    
    MMI_CATEGORY115_ID,
    MMI_CATEGORY119_ID,
    MMI_CATEGORY120_ID,
    MMI_CATEGORY121_ID,
    MMI_CATEGORY122_ID,
    MMI_CATEGORY123_ID,
    MMI_CATEGORY123_NORMAL_ID,
    MMI_CATEGORY123_STATUS_ICON_ID,
    MMI_CATEGORY123_NONE_ID,
    MMI_CATEGORY124_STATUS_ICON_ID,
    MMI_CATEGORY124_TITLE_ID,
    MMI_CATEGORY124_NONE_ID,
    MMI_CATEGORY125_ID,
    MMI_CATEGORY128_ID,
    MMI_CATEGORY128_NORMAL_ID,
    MMI_CATEGORY128_STATUS_ICON_ID,
    MMI_CATEGORY128_NONE_ID,
    MMI_CATEGORY129_ID,
    MMI_CATEGORY131_ID,
    MMI_CATEGORY140_ID,
    MMI_CATEGORY141_ID,
    MMI_CATEGORY141_STATUS_ICON_ID,
    MMI_CATEGORY142_ID,
    MMI_CATEGORY142_STATUS_ICON_ID,
    MMI_CATEGORY143_ID,
    MMI_CATEGORY144_ID,
    MMI_CATEGORY145_ID,
    MMI_CATEGORY146_ID=MMI_CATEGORY145_ID,
    MMI_CATEGORY150_ID,
    MMI_CATEGORY151_ID,
    MMI_CATEGORY151_NORMAL_ID,
    MMI_CATEGORY151_STATUS_ICON_ID,
    MMI_CATEGORY151_NONE_ID,
    MMI_CATEGORY152_ID,
    MMI_CATEGORY153_ID,
    MMI_CATEGORY154_ID,
    MMI_CATEGORY154_STATUS_ICON_ID,
    MMI_CATEGORY155_ID,
    MMI_CATEGORY157_ID,
    MMI_CATEGORY161_ID,
    MMI_CATEGORY162_ID,
    MMI_CATEGORY163_ID,
    MMI_CATEGORY164_ID,
    MMI_CATEGORY165_ID,
    MMI_CATEGORY166_ID,
    MMI_CATEGORY170_ID,
    MMI_CATEGORY171_ID,
    MMI_CATEGORY172_ID,
    MMI_CATEGORY174_ID,
    MMI_CATEGORY176_ID,
    MMI_CATEGORY184_ID,
    MMI_CATEGORY186_ID,
    MMI_CATEGORY200_ID,
    MMI_CATEGORY201_ID=MMI_CATEGORY200_ID,
    MMI_CATEGORY204_ID,
    MMI_CATEGORY205_ID,
    MMI_CATEGORY212_ID,
    MMI_CATEGORY213_ID,
    MMI_CATEGORY214_ID,
    MMI_CATEGORY221_ID,
    MMI_CATEGORY222_ID,
    MMI_CATEGORY223_ID,
    MMI_CATEGORY223_NORMAL_ID,
    MMI_CATEGORY223_STATUS_ICON_ID,
    MMI_CATEGORY223_NONE_ID,
    MMI_CATEGORY226_ID1,
    MMI_CATEGORY226_ID2,
    MMI_CATEGORY227_ID,
    MMI_CATEGORY228_ID,
    MMI_CATEGORY229_ID=MMI_CATEGORY227_ID,
    MMI_CATEGORY257_ID,
    MMI_CATEGORY261_ID,
    MMI_CATEGORY262_ID,
    MMI_CATEGORY263_ID,
    MMI_CATEGORY264_ID,
    MMI_CATEGORY273_ID=    MMI_CATEGORY264_ID,
    MMI_CATEGORY275_ID,
    MMI_CATEGORY276_ID=    MMI_CATEGORY275_ID,
    MMI_CATEGORY301_ID,
    MMI_CATEGORY302_ID,
    MMI_CATEGORY303_ID,
    MMI_CATEGORY304_ID,
    MMI_CATEGORY305_ID,
    MMI_CATEGORY306_ID,
    MMI_CATEGORY307_ID,
    MMI_CATEGORY308_ID,
    MMI_CATEGORY309_ID,
    MMI_CATEGORY310_ID,
    MMI_CATEGORY311_ID,
    MMI_CATEGORY312_ID,
    MMI_CATEGORY313_ID,
    MMI_CATEGORY314_ID=    MMI_CATEGORY313_ID,
    MMI_CATEGORY331_ID,
    MMI_CATEGORY333_ID,
    MMI_CATEGORY334_ID=    MMI_CATEGORY333_ID,
    MMI_CATEGORY353_ID,
    MMI_CATEGORY357_ID=    MMI_CATEGORY353_ID,          
    MMI_CATEGORY400_ID,
    MMI_CATEGORY402_ID,
    MMI_CATEGORY403_ID,
    MMI_CATEGORY404_ID=    MMI_CATEGORY400_ID,
    MMI_CATEGORY414_ID,
    MMI_CATEGORY420_ID,
    MMI_CATEGORY425_ID,
    MMI_CATEGORY425_NO_TAB_ID=    MMI_CATEGORY425_ID,
    MMI_CATEGORY430_ID,
    MMI_CATEGORY435_ID,
    MMI_CATEGORY620_ID,
    MMI_INLINE_BOX_HISTORY_ID,
    MMI_CATEGORY_EMS_ID,
    MMI_CATEGORY_PE_ID,
    MMI_CATEGORY_WCLOCK,
    MMI_CATEGORY_FM_SCHED_RECORD,
    MMI_CATEGORY_VDOPLY,
    MMI_CATEGORY_VDOPLY_BUTTON,  
#ifdef __FT_IDLE_SMART_DIAL__
    MMI_CATEGORY_SmartDial_ID,
#endif
    MMI_CATEGORY_NSM275,
   #ifdef _KK_SUPPORT_
   MMI_CATEGORY57_WEP_VIDEO_CHAT_ID,
#endif 
#if defined(__MMI_PROJECT_S021__)
	MMI_CATEGORY64_TMP_ID,
#endif
#if defined(__COOLSAND_SUBMENU_LEVEL2_POPMENU__)
	MMI_CATEGORY_POPUPMENU_ID,
#endif
 #ifdef __SG_MMI_MEDIA_SPECIAL_MENU__ //katsu for media menu 20090305
 	MMI_CATEGORY_MEDIA_ID,
#endif

#if	defined(__PROJECT_GALLITE_C01__)//def __MMI_INTELIGENT_CALL_NUMBER__
    MMI_CATEGORY658_ID,		
#endif
};

#define UI_INCLUDE_INFORMATION_AREA_IN_MULTI_LINE 0

typedef enum
{
    WGUI_CATEGORY_DD_STRING_ID = CATEGORY_SCREENS_BASE,
    WGUI_CATEGORY_MM_STRING_ID,
    WGUI_CATEGORY_YYYY_STRING_ID,
    WGUI_CATEGORY_THH_STRING_ID,
    WGUI_CATEGORY_TMM_STRING_ID,
    WGUI_CATEGORY_CLEAR_STRING_ID,
    WGUI_CATEGORY_ABC_STRING_ID,
    WGUI_CATEGORY_abc_STRING_ID,
    WGUI_CATEGORY_123_STRING_ID,
    WGUI_CATEGORY_TSS_STRING_ID,
    WGUI_CATEGORY_EDIT_STRING_ID,
    WGUI_CATEGORY_CANCEL_STRING_ID,
    WGUI_CATEGORY_DONE_STRING_ID,
    WGUI_CATEGORY_ON_STRING_ID,
    WGUI_CATEGORY_OFF_STRING_ID,
    WGUI_CATEGORY_YYYY_MM_DD_STRING_ID,
    WGUI_CATEGORY_HH_MM_STRING_ID,

     
#if defined(__MMI_MULTITAP_THAI__)
    WGUI_CATEGORY_thai_STRING_ID,
#endif 

     
    WGUI_CATEGORY_SPANISH_STRING_ID,
    WGUI_CATEGORY_spanish_STRING_ID,
     
    WGUI_CATEGORY_DANISH_STRING_ID,
    WGUI_CATEGORY_danish_STRING_ID,
     
     
    WGUI_CATEGORY_POLISH_STRING_ID,
    WGUI_CATEGORY_polish_STRING_ID=   WGUI_CATEGORY_danish_STRING_ID,
     
    WGUI_CATEGORY_FRENCH_STRING_ID,
    WGUI_CATEGORY_french_STRING_ID,
    WGUI_CATEGORY_GERMAN_STRING_ID,
    WGUI_CATEGORY_german_STRING_ID,
    WGUI_CATEGORY_ITALIAN_STRING_ID,
    WGUI_CATEGORY_italian_STRING_ID,
    WGUI_CATEGORY_RUSSIAN_STRING_ID,
    WGUI_CATEGORY_russian_STRING_ID,
 
    WGUI_CATEGORY_BULGARIAN_STRING_ID,
    WGUI_CATEGORY_bulgarian_STRING_ID=    WGUI_CATEGORY_russian_STRING_ID,
  
    WGUI_CATEGORY_TURKISH_STRING_ID,
    WGUI_CATEGORY_turkish_STRING_ID,
     
    WGUI_CATEGORY_HEBREW_STRING_ID,
    WGUI_CATEGORY_hebrew_STRING_ID=   WGUI_CATEGORY_turkish_STRING_ID,
     
    WGUI_CATEGORY_PORTUGUESE_STRING_ID,
    WGUI_CATEGORY_portuguese_STRING_ID,
    WGUI_CATEGORY_INDONESIAN_STRING_ID,
    WGUI_CATEGORY_indonesian_STRING_ID,
     
    WGUI_CATEGORY_CZECH_STRING_ID,
    WGUI_CATEGORY_czech_STRING_ID= WGUI_CATEGORY_indonesian_STRING_ID,
     
    WGUI_CATEGORY_MALAY_STRING_ID,
    WGUI_CATEGORY_malay_STRING_ID,
    WGUI_CATEGORY_VIETNAMESE_STRING_ID,
    WGUI_CATEGORY_vietnamese_STRING_ID,
#if defined(__MMI_SMART_VIETNAMESE__)
	WGUI_CATEGORY_Smart_VIETNAMESE_STRING_ID,
	WGUI_CATEGORY_Smart_vietnamese_STRING_ID,
#endif
     
    WGUI_CATEGORY_FINNISH_STRING_ID,
    WGUI_CATEGORY_finnish_STRING_ID,
    WGUI_CATEGORY_HUNGARIAN_STRING_ID,
    WGUI_CATEGORY_hungarian_STRING_ID,
     
   
    WGUI_CATEGORY_SLOVAK_STRING_ID,
    WGUI_CATEGORY_slovak_STRING_ID,
    WGUI_CATEGORY_DUTCH_STRING_ID,
    WGUI_CATEGORY_dutch_STRING_ID,
     
    WGUI_CATEGORY_HINDI_STRING_ID,
     
    WGUI_CATEGORY_ARABIC_STRING_ID,
    WGUI_CATEGORY_PERSIAN_STRING_ID,
    WGUI_CATEGORY_URDU_STRING_ID,
    /* Norwegian start */
    WGUI_CATEGORY_NORWEGIAN_STRING_ID,
    WGUI_CATEGORY_norwegian_STRING_ID,
    //Norwegian end
 
     
    WGUI_CATEGORY_SWEDISH_STRING_ID,
    WGUI_CATEGORY_swedish_STRING_ID,
     
     
    WGUI_CATEGORY_CROATIAN_STRING_ID,
    WGUI_CATEGORY_croatian_STRING_ID,
    WGUI_CATEGORY_ROMANIAN_STRING_ID,
    WGUI_CATEGORY_romanian_STRING_ID,
    WGUI_CATEGORY_SLOVENIAN_STRING_ID,
    WGUI_CATEGORY_slovenian_STRING_ID,

    WGUI_CATEGORY_MYANMAR_STRING_ID,
     
     
    WGUI_CATEGORY_GREEK_STRING_ID,
    WGUI_CATEGORY_greek_STRING_ID=  WGUI_CATEGORY_vietnamese_STRING_ID,
     
    //CSD end

     
    STR_SUBLCD_CHI_SUNDAY,
    STR_SUBLCD_CHI_MONDAY,
    STR_SUBLCD_CHI_TUESDAY,
    STR_SUBLCD_CHI_WEDNESDAY,
    STR_SUBLCD_CHI_THURSDAY,
    STR_SUBLCD_CHI_FRIDAY,
    STR_SUBLCD_CHI_SATURDAY,

    STR_SUBLCD_ENG_SUNDAY,
    STR_SUBLCD_ENG_MONDAY,
    STR_SUBLCD_ENG_TUESDAY,
    STR_SUBLCD_ENG_WEDNESDAY,
    STR_SUBLCD_ENG_THURSDAY,
    STR_SUBLCD_ENG_FRIDAY,
    STR_SUBLCD_ENG_SATURDAY,
    TEMP_SUBLCD_ANIMATION_STR_ID
#ifdef __MMI_AUDIO_PLAYER__
        , AUDIO_SOFT_LABEL,
    AUDIO_CLASSIC_LABEL,
    AUDIO_ROCK_LABEL
        /* CSD end */
#endif /* __MMI_AUDIO_PLAYER__ */ 
        , STR_GUI_MONTH_BASE,
    STR_GUI_MONTH_JAN,
    STR_GUI_MONTH_FEB,
    STR_GUI_MONTH_MAR,
    STR_GUI_MONTH_APL,
    STR_GUI_MONTH_MAY,
    STR_GUI_MONTH_JUN,
    STR_GUI_MONTH_JLY,
    STR_GUI_MONTH_AUG,
    STR_GUI_MONTH_SEP,
    STR_GUI_MONTH_OCT,
    STR_GUI_MONTH_NOV,
    STR_GUI_MONTH_DEC,
    STR_GUI_TIME_AM,
    STR_GUI_TIME_PM,
    STR_GUI_DAY,
         
/*+ zhouqin 2011-02-16 modify for q6 320X240 */  
#if defined ( __MMI_UI_TECHNO_IDLESCREEN_BAR__) || defined (__MMI_SYMBIAN_STYLE_IDLE__)||defined(__PROJECT_GALLITE_C01__)
/*- zhouqin 2011-02-16 modify for q6 320X240 */
    STR_IDLESCREEN_SUNDAY,
    STR_IDLESCREEN_MONDAY,
    STR_IDLESCREEN_TUESDAY,
    STR_IDLESCREEN_WEDNESDAY,
    STR_IDLESCREEN_THURSDAY,
    STR_IDLESCREEN_FRIDAY,
    STR_IDLESCREEN_SATURDAY
#endif /* __MMI_UI_TECHNO_IDLESCREEN_BAR__ */ 
         
} STRINGID_COMMON_CATEGORY_STRINGS;

typedef enum
{SHOW_ARROW_UP = 1,
    SHOW_ARROW_DOWN = 2,
    SHOW_ARROW_LEFT = 4,
    SHOW_ARROW_RIGHT = 8
} NAVIGATION_KEYS_IMAGES;

typedef enum
{
    WGUI_CATEGORY_CLOCK = CATEGORY_SCREENS_BASE,	
    WGUI_VOLUME_LEVEL0,		
    WGUI_VOLUME_LEVEL1,
    WGUI_VOLUME_LEVEL2,
    WGUI_VOLUME_LEVEL3,
    WGUI_VOLUME_LEVEL4,
    WGUI_VOLUME_LEVEL5,
    WGUI_VOLUME_LEVEL6,
    WGUI_VOLUME_LEVEL7,
    WGUI_VOLUME_LEVEL8,
    WGUI_VOLUME_LEVEL9,    

     
#if defined(__MMI_TOUCH_SCREEN__)
    WGUI_VOLUME_UP_UP_IMAGE_ID,
    WGUI_VOLUME_UP_DOWN_IMAGE_ID,
    WGUI_VOLUME_DOWN_UP_IMAGE_ID,
    WGUI_VOLUME_DOWN_DOWN_IMAGE_ID,
#endif /* defined(__MMI_WALLPAPER_ON_BOTTOM__) */ 
     
    WGUI_SLIDE_CONTROL_BG_IMAGE_ID,
    WGUI_SLIDE_CONTROL_SI_IMAGE_ID,

    WGUI_INPUT_INFORMATION_ICON1,
    WGUI_INPUT_INFORMATION_ICON2,

     
    WGUI_ZI_EZITEXT_LOGO,
    WGUI_ZI_EZITEXT_BPMF_LOGO,
    WGUI_ZI_EZITEXT_PINYIN_LOGO,
    WGUI_ZI_EZITEXT_SM_STROKE_LOGO,
    WGUI_ZI_EZITEXT_TR_STROKE_LOGO,
    //CSD end
     
    WGUI_IME_MULTITAP_BPMF_IMG,
    WGUI_IME_MULTITAP_PINYIN_IMG,
    WGUI_IME_SMART_BPMF_IMG,
    WGUI_IME_SMART_PINYIN_IMG,
    WGUI_IME_SM_STROKE_IMG,
    WGUI_IME_TR_STROKE_IMG,
    WGUI_IME_SMART_ENGLISH_IMG,
    /* CSD end */

    COMPANY_LOGO_IMAGE_ID,
    UNDER_CONSTRUCTION_IMAGE_ID,
    RADIO_ON_IMAGE_ID,
    RADIO_OFF_IMAGE_ID,
    CHECKBOX_ON_IMAGE_ID,
    CHECKBOX_OFF_IMAGE_ID,
    CUSTOM_LOGO_IMAGE_ID,
    TEMP_SUBLCD_ANIMATION_IMAGE_ID,
    /*wuzc Modify Start For GDI/GUI Portting Ver:    on 2008-4-14 18:12 */
    RIGHT_RED_ARROW = TEMP_SUBLCD_ANIMATION_IMAGE_ID+11,
    /*wuzc Modify End  For GDI/GUI Portting Ver:    on 2008-4-14 18:12 */
    LEFT_RED_ARROW,
    IMG_HORIZONTAL_NORMAL_TAB,
    IMG_HORIZONTAL_FOCUSED_TAB,
    IMG_HORIZONTAL_BLINKING_TAB,
    IMG_HORIZONTAL_TAB_L_ARROW,
    /*wuzc Modify Start For GDI/GUI Portting Ver:    on 2008-4-14 18:53 */
    IMG_HORIZONTAL_TAB_R_ARROW = IMG_HORIZONTAL_TAB_L_ARROW,
    /*wuzc Modify End  For GDI/GUI Portting Ver:    on 2008-4-14 18:53 */
    IMG_HORIZONTAL_TAB_HINT_AREA,
     
#ifdef __MMI_UI_TAB_PANE__
    TAB_PANE_ICON_HIGHLIGHT,
    TAB_PANE_ICON_UN_HIGHLIGHT,
    TAB_PANE_TEXT_HIGHLIGHT,
    TAB_PANE_TEXT_UN_HIGHLIGHT,
#endif /* __MMI_UI_TAB_PANE__ */ 
     
     
    IMG_IDLE_MAINMENU_SHORCUT,
    IMG_IDLE_MESSAGE_SHORTCUT,
    IMG_IDLE_PHONEBOOK_SHORTCUT,
    IMG_IDLE_QQ_SHORTCUT,
    IMG_IDLE_JIAQUAN_SHORTCUT,
    IMG_IDLE_MAINMENU1_SHORCUT,
    IMG_IDLE_MESSAGE1_SHORTCUT,
    IMG_IDLE_MAINMENU_SHORCUT_PRESSED,//高亮调用
    IMG_IDLE_MESSAGE_SHORTCUT_PRESSED,
    IMG_IDLE_PHONEBOOK_SHORTCUT_PRESSED,
    IMG_IDLE_DIALING_SCREEN_SHORTCUT_PRESSED,
    IMG_IDLE_JIAQUAN_SHORTCUT_PRESSED,
    IMG_IDLE_MAINMENU1_SHORCUT_PRESSED,
    IMG_IDLE_MESSAGE1_SHORTCUT_PRESSED,
    IMG_IDLE_DIALING_SCREEN_SHORTCUT,

    /* ~] */

#if defined (__MMI_BLACKBERRY_QWERTY__)
    IMG_IDLE_RSK_LOCK,
#endif
#if defined(__MMI_MAINLCD_220X176__)|| defined(__MMI_STYLE_E71_QCIF_S__) || defined(__PROJECT_GALLITE_C01__)
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_MESSAGE,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_WEB,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_PHB,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_MP3,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_TOOLS,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_PROFILE,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_ALARM,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_CALENDAR,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_MP3_PLAYING,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_MESSAGE_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_WEB_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_PHB_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_MP3_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_TOOLS_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_PROFILE_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_ALARM_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SERIES_CALENDAR_SELECTED,
	IMG_IDLE_SHORTCUT_NOKIA_E_SELECTED_BG1,
	IMG_TEMP_MAINMENU_SELECT_BG,
	IMG_IDLE_LINE_H,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_CALLLOG,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_CONTACTS,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_MP3,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_BROWSER,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_MESSAGES,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_FILEMGR,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_TOOLS,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_MULTIMEDIA,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_BT,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_GAME,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_PROFILE,
	IMG_NOKIA_E_SERIES_MAINMENU_SELECTED_SETTING,
	IMG_NOKIA_E_SERIES_STATUS_BG,
	IMG_NOKIA_E_SERIES_BUTTON_BAR_BG,
#endif
#ifdef __MMI_AUDIO_PLAYER__
    AUDIO_PLAYER_TITLE,
    AUDIO_PLAYER_CLASSIC_GREY,
    AUDIO_PLAYER_SOFT_GREY,
    AUDIO_PLAYER_ROCK_GREY,
    AUDIO_PLAYER_CLASSIC_BLUE,
    AUDIO_PLAYER_SOFT_BLUE,
    AUDIO_PLAYER_ROCK_BLUE,
    AUDIO_PLAYER_PLAY_ICON,
    AUDIO_PLAYER_LINE,
    AUDIO_PLAYER_INDICATOR,
    AUDIO_PLAYER_BKG_IMAGE,
    AUDIO_PLAYER_DIRECTORY,
    AUDIO_PLAYER_TIME_BAR,
    AUDIO_PLAYER_VOLUME_IMG,
    AUDIO_PLAYER_BLANK_IMG,
#endif /* __MMI_AUDIO_PLAYER__ */ 
    UIELEMENT_ARROW_UP,
    UIELEMENT_ARROW_LEFT,
    UIELEMENT_ARROW_DOWN,
    UIELEMENT_ARROW_RIGHT,

    /* Inline select */
    IMG_H_SELECT_LEFT,
    IMG_H_SELECT_RIGHT,

    /* Virtual keyboard */
    IMG_VKBD_STANDARD,
    IMG_VKBD_EXTENDED,
    IMG_VKBD_TRAY,
    IMG_VKBD_NUMBER,
    IMG_VKBD_PINYIN,
    IMG_VKBD_PINYIN_DISPAREA,
    IMG_VKBD_BOPOMO,
    IMG_VKBD_BOPOMO_DISPAREA,
    IMG_VKBD_ARABIC,
    IMG_VKBD_FARSI_HUNGARIAN_ARABICSYMBOL,
    IMG_VKBD_FARSI_SYMBOL,
    IMG_VKBD_VIETNAMESE,
    IMG_VKBD_THAI,
    IMG_VKBD_CUSTOM_HIDE,
    IMG_VKBD_CUSTOM_SHOW,
    IMG_VKBD_CUSTOM_SWITCH_KEYBOARD,
    /*wuzc Modify End  For GDI/GUI Portting Ver:    on 2008-4-16 11:36 */
    IMG_VKBD_CUSTOM_SWITCH_HANDWRITING=    IMG_VKBD_CUSTOM_SHOW,
    /*wuzc Modify Start For GDI/GUI  idle dial screen Portting Ver:    on 2008-4-16 11:36 */
    IMG_VKBD_CUSTOM_BACKSPACE ,
    IMG_VKBD_CUSTOM_CAPSLOCK,
    IMG_VKBD_CUSTOM_SPACE,
    IMG_VKBD_CUSTOM_SYMBPICKER,
    IMG_VKBD_CUSTOM_EUROSYMB,
    IMG_VKBD_CUSTOM_ENTER,
    IMG_VKBD_CUSTOM_BRACKET,
    IMG_VKBD_CUSTOM_HIDE_SMALL,

    /* UI_SCROLLBAR_STYLE_3 */
    IMG_SCROLLBAR_BUTTON_UP,
    IMG_SCROLLBAR_BUTTON_DOWN,
    IMG_SCROLLBAR_V_BAR_TOP,
    IMG_SCROLLBAR_V_BAR_MIDDLE,
    IMG_SCROLLBAR_V_BAR_BOTTOM,
    IMG_SCROLLBAR_H_BAR_LEFT,
    IMG_SCROLLBAR_H_BAR_MIDDLE,
    IMG_SCROLLBAR_H_BAR_RIGHT,

    /* Transition Animation */
    IMG_PEN_WAITING_LONGPRESS,

    CHAT_LOCAL_IMG,
    CHAT_REMOTE_IMG,
    CHAT_SENDER_TRUNCATE_IMG,
    CHAT_RECEIVER_TRUNCATE_IMG,
     
    IMG_BOOTUP_SCANNING_LOGO,
#ifdef __FT_IDLE_SMART_DIAL__ 
	IMG_THEME1_DIALERBKG,
	IMG_THEME1_DYNLISTBKG,
#endif

    /* CSD end */
    IMG_MULTILINE_INPUTBOX_BKGRND,
    IMG_CONF_CALL_BKG,
    IMG_ACTIVE_CONF_CALL,
    IMG_ACTIVE_CONF_CALL_1,
    IMG_GREY_CONF_CALL,
    IMG_HOLD_CONF_CALL,
    IMG_OSIGNAL_CONF_CALL,
    IMG_NAME_CONF_CALL,
    IMG_SUBLCD_ANALOG_CLOCK,
    IMG_POPUP_TITLE,
    IMG_SCREEN_ROTATE_TITLE,
    IMG_SCREEN_ROTATE_BACKGROUND,
    IMG_SOFTKEY_BAR,
    IMG_DIALING_SCREEN,
    IMG_DIALING_KEY_1,
    IMG_DIALING_KEY_2,
    IMG_DIALING_KEY_3,
    IMG_DIALING_KEY_4,
    IMG_DIALING_KEY_5,
    IMG_DIALING_KEY_6,
    IMG_DIALING_KEY_7,
    IMG_DIALING_KEY_8,
    IMG_DIALING_KEY_9,
    IMG_DIALING_KEY_HASH,
    IMG_DIALING_KEY_0,
    IMG_DIALING_KEY_STAR,
#if defined(__PROJECT_GALLITE_C01__)
    IMG_DIALING_KEY_ADD,
    IMG_DIALING_KEY_P,
    IMG_DIALING_KEY_W,
    IMG_DIALING_KEY_BG,
    IMG_TIME_DOT,
#endif
     
#if defined (__MMI_TOUCH_DIAL_SCREEN_WITH_FUNCTION__)
    IMG_DIALING_KEY_FUNC,
    IMG_DIALING_KEY_PHB = IMG_DIALING_KEY_FUNC,
    IMG_DIALING_KEY_CALL,
    IMG_DIALING_KEY_CALL_SLAVE,
    IMG_DIALING_KEY_CALL_SLAVE_DISABLED,
    IMG_DIALING_KEY_PHB_DISABLED,
    IMG_DIALING_KEY_CALL_DISABLED,
#endif /* defined (__MMI_TOUCH_DIAL_SCREEN_WITH_FUNCTION__) */ 

     IMG_DIALING_KEY_PHB_SAVE,//roger
     IMG_DIALING_KEY_PHB_SAVE_DISABLE,
      IMG_DIALING_INPUTBOX_TOP,//roger

     
    IMG_PASSWD_KEYBOARD,
    IMG_PASSWD_KEYBOARD_PRESS,
    IMG_POPUP_BG,        
    IMG_TITLEBAR_BG,     
#if (defined __MMI_TOUCH_SCREEN__) && (defined __MMI_WGUI_CSK_ENABLE__)
    IMG_CSK_DIAL_ICON,
#endif 
    /* Calendar */
    IMG_CALENDAR_JAN,
#ifndef __MMI_SLIM_CALENDAR__
    IMG_CALENDAR_FEB,   /* Do not change the order */
    IMG_CALENDAR_MAR,
    IMG_CALENDAR_APR,
    IMG_CALENDAR_MAY,
    IMG_CALENDAR_JUN,
    IMG_CALENDAR_JUL,
    IMG_CALENDAR_AUG,
    IMG_CALENDAR_SEP,
    IMG_CALENDAR_OCT,
    IMG_CALENDAR_NOV,
    IMG_CALENDAR_DEC,
#endif /* __MMI_SLIM_CALENDAR__ */ 
    CAL_ENGLISH_DAYS_IMAGE,
    CAL_CHINESE_DAYS_IMAGE,
    CAL_LEFT_ARROW_UP_IMAGE,
    CAL_LEFT_ARROW_DOWN_IMAGE,
    CAL_RIGHT_ARROW_UP_IMAGE,
    CAL_RIGHT_ARROW_DOWN_IMAGE
         
#ifdef __MMI_UI_TECHNO_MAINMENU__
        ,
    MAIN_MENU_PAGE_BG,
    MAIN_MENU_PAGE_BG2,
    MAIN_MENU_PAGE_BG3,
    MAIN_MENU_PAGE_BG4,
    MAIN_MENU_PAGE_BG5
#endif /* __MMI_UI_TECHNO_MAINMENU__ */ 
         
#ifdef __MMI_UI_DALMATIAN_MAINMENU__
        ,
    MAIN_MENU_DALMATIAN_BALL
#endif /* __MMI_UI_DALMATIAN_MAINMENU__ */ 
#ifdef __MMI_UI_DALMATIAN_EDITOR__
        ,
    IMG_EDITOR_DALMATIAN_SMALL,
    IMG_EDITOR_DALMATIAN
#endif /* __MMI_UI_DALMATIAN_EDITOR__ */ 
         
         
         
#ifdef __MMI_UI_ANIMATED_TITLE_EFFECT__
        , IMG_TITLE_SCROLL
#endif 
#ifdef __MMI_UI_LIST_HIGHLIGHT_EFFECTS__
        /*wuzc Modify Start For GDI/GUI Portting 资源管理ID Ver:    on 2008-4-16 11:44 */
        , IMG_LIST_HIGHLIGHTER =CAL_RIGHT_ARROW_DOWN_IMAGE
        /*wuzc Modify End  For GDI/GUI Portting Ver:    on 2008-4-16 11:44 */
#endif 
         
         
/*+ zhouqin 2011-02-16 modify for q6 320X240 */
#if defined ( __MMI_UI_TECHNO_IDLESCREEN_BAR__) || defined (__MMI_STYLE_E71_QCIF_S__)
/*- zhouqin 2011-02-16 modify for q6 320X240 */
        ,
    IMG_TECHNO_IDLESCREEN_BAR,
    IMG_TECHNO_ANALOG_CLOCK,
    IMG_TECHNO_DIGITAL_CLOCK
#endif /* __MMI_UI_TECHNO_IDLESCREEN_BAR__ */ 
         
         
        , IMAGE_VIEW_TITLEBAR_BG
         
         
#ifdef __MMI_UI_TWO_LINE_MENUITEM_STYLES__
        ,
    TWO_LINE_VOLUME_IMAGE
#endif /* __MMI_UI_TWO_LINE_MENUITEM_STYLES__ */ 
         
         
#ifdef __MMI_UI_DALMATIAN_CALENDAR__
        /* ids for week bar based on month */
        ,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_JAN,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_FEB,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_MAR,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_APR,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_MAY,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_JUN,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_JUL,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_AUG,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_SEP,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_OCT,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_NOV,
    DALMATIAN_WEEK_HIGHLIGHTER_IMAGE_ID_DEC
#endif /* __MMI_UI_DALMATIAN_CALENDAR__ */ 
         
#ifdef __MMI_EDITABLE_AUDIO_EQUALIZER__
        , SOUND_EFFECT_AUDIO_EQ_BG, SOUND_EFFECT_AUDIO_EQ_ACTIVE_BAR, SOUND_EFFECT_AUDIO_EQ_VAL_INDICATOR
#endif 
        , IMG_PERCENTAGE_BAR_LEFT_IMAGE,
    IMG_PERCENTAGE_BAR_RIGHT_IMAGE,
    IMG_PERCENTAGE_BAR_BG_IMAGE,
    IMG_FLEXIBLE_TITLEBAR_BG,//093006 popup title
 //qiff add UI resource
#if 1//defined __MMI_MAINLCD_240X320__
    IMG_LIST_MENU_BG_IMAGE,
#endif
#if defined(__MMI_NOKIA_STYLE_N800__)
	WGUI_IMG_TEXT_BG_TOP,
	WGUI_IMG_TEXT_BG_BOTTOM,
	WGUI_IMG_TEXT_BG_MID,
#endif
     IMG_ID_NOKIA_PWR_LOGO,
    COMMON_IMG_END
} IMAGEID_COMMON_CATEGORY_SCREENS;

typedef struct _wgui_pop_up_description_string_type
{
    UI_string_type text_strings[MAX_POP_UP_DESCRIPTION_STRINGS];
} wgui_pop_up_description_string_type;

 
typedef struct _dialer_inputbox_category_history
{
    U16 history_ID;
    S32 n_lines;
    UI_buffer_type current_text_p;
    UI_buffer_type last_position_p;
    S32 UCS2_count;
    S32 cursor_x, cursor_y;
} dialer_inputbox_category_history;

 
#endif /* __WGUI_CATEGORIES_DEFS_H__ */ 

