////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//            Copyright (C) 2003-2007, Coolsand Technologies, Inc.            //
//                            All Rights Reserved                             //
//                                                                            //
//      This source code is the property of Coolsand Technologies and is      //
//      confidential.  Any  modification, distribution,  reproduction or      //
//      exploitation  of  any content of this file is totally forbidden,      //
//      except  with the  written permission  of  Coolsand Technologies.      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file                                                                     //
/// That file Implements the functions to register the module.
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "cs_types.h"

#include "hal_map_engine.h"

#include "rf_names.h"
#include "rfd_xcv.h"
#include "rfd_pa.h"
#include "rfd_sw.h"
#include "rfd_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#define RFD_VERSION_STRING "RFD for transceiver " STRINGIFY_VALUE(RFD_XCV_MODEL) \
    ", for PA " STRINGIFY_VALUE(RFD_PA_MODEL) \
    " and for switch " STRINGIFY_VALUE(RFD_SW_MODEL)
#include "rfdp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_rfdMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_rfdMapVersion = RFD_VERSION_STRUCT;



// =============================================================================
// g_rfdMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED RFD_MAP_ACCESS_T g_rfdMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// rfd_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID rfd_RegisterYourself(VOID)
{
    // Put transceiver name (ID) in the field "number" of the version.
    g_rfdMapVersion.number = rfd_XcvCalibGetDefault()->palcust.name;
    
    hal_MapEngineRegisterModule(HAL_MAP_ID_RFD, &g_rfdMapVersion, &g_rfdMapAccess);
}

