/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  IncomingScrIdDef.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

/**************************************************************

	FILENAME	: IncomingScrIdDef.h

  	PURPOSE		: Screen ID definitions for Incoming call

 

	 

	DATE		: nov' 07, 2002

**************************************************************/
#ifndef INCOMING_SCR_ID_DEF_H
#define INCOMING_SCR_ID_DEF_H
	/* Screen Ids */
	ITEMSCR_INCOMING_CALL,	/*1*/
	SUB_LCD_ITEMSCR_INCOMING_CALL,
	ITEM_SCR_INCOMING_OPTIONS,
	ITEM_SCR_INC_ACTIVE_OPN,
	ITEM_SCR_INC_HOLD_OPN,
	ITEM_SCR_INC_ACT_HOLD_OPN,
	ITEM_SCR_END_ACT_LIST,
	ITEM_SCR_INC_MACT_HOLD_OPN,
	ITEM_SCR_INC_MACT_OPN,
	ITEM_SCR_SS_NFY,			/*10*/
	ITEM_SCR_MO_NUM_CHANGE_NFY,
	ITEM_SCR_CCBS_IND,
	ITEMSCR_CCBS_INVOKE,
	ITEM_SCR_CCBS_ACTIVE_OPN,
	ITEM_SCR_CCBS_HOLD_OPN,
	ITEM_SCR_CCBS_MACT_OPN,
	ITEM_SCR_CCBS_MHLD_OPN,
	ITEM_SCR_CCBS_ACT_HLD_OPN,
	ITEM_SCR_CCBS_MACT_HLD_OPN,
	ITEM_SCR_CCBS_ACT_MHLD_OPN,	/*20*/
	ITEM_SCR_INC_ACT_MHOLD_OPN,
	ITEM_SCR_INC_MHOLD_OPN,

	ITEM_SCR_USSN_MSG,
	ITEM_SCR_USSR_MSG,
	ITEM_SCR_USSD_MSG,
//micha0524
	ITEM_SCR_USSR_EDIT,

	ITEM_SCR_CALL_DEFLECT_DIGIT_HANDLER_ID,
	ITEM_SCR_CONFIRM_DTMF_STRING,	/*28*/

#endif//INCOMING_SCR_ID_DEF_H


