//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetworkSimulator.rc
//
#define IDP_SOCKETS_INIT_FAILED         101
#define IDR_MAINFRAME                   102
#define IDC_TREECTRL                    103
#define IDS_STRING_MSG_ID               104
#define IDS_STRING_MSG_NAME             105
#define IDS_STRING_MSG_TIME             106
#define IDS_STRING_MSG_NAME_NOT_SUPPORTED 107
#define IDS_STRING_FORM_MESSAGE_ID      108
#define IDS_STRING_FROM_MESSAGE_ID      108
#define IDS_STRING_MESSAGE_NAME         109
#define IDS_STRING_MESSAGE_TIME         110
#define IDS_STRING_DLG_NWS              111
#define IDS_STRING_SEND_MESSAGE_ID      112
#define IDC_LIST_DATASET_DETAILS        1001
#define IDC_EDIT_MESSAGE_ID             1003
#define IDC_COMBO_MSG_RESPONSE          1004
#define IDC_COMBO_MSG_RESPONSE_VALUE    1005
#define IDC_COMBO_MSG_RESPONSE2         1006
#define IDC_STATIC_MSG_DETAIL           2022
#define IDC_EDIT_OUTGOING_MSG_NAME      2026
#define IDC_EDIT_OUTGOING_MSGID         2027
#define IDC_STATIC_OUTGOING_MSG_NAME    2028
#define IDC_EDIT_INCOMING_MSG_NAME      2029
#define IDC_STATIC_OUTGOING_MSG_ID      2030
#define IDC_STATIC_INCOMING_MSG_NAME    2031
#define IDC_STATIC_INCOMING_MSG_ID      2032
#define IDC_EDIT_INCOMING_MSG_ID        2034
#define ID_BUTTON_MAKEBUFFER            2035
#define IDC_BUTTON_ONCLOSE              2041
#define IDC_STATIC_INC_MSG_DETAILS      2057
#define IDC_STATIC_OUTGOING_MSG_DETAILS 2058
#define IDC_STATIC_DS_DETAILS           2059
#define IDC_STATIC_MSGID                2060
#define IDC_STATIC_RESP_MSG             2061
#define IDC_STATIC_RESP_VAL             2062
#define IDC_LISTE_STOCK_MESSAGE         13005
#define IDC_BTN_ADD                     13007
#define IDC_BTN_DELETE                  13008
#define IDC_COMBO_AYSNC_NAME            13010
#define IDC_LISTE_ASYNC_MESSAGE         13011
#define IDC_BTN_ADD_MESSAGE             13012
#define IDC_BTN_DELETE_MESSAGE          13014
#define IDC_TREE_BOOT                   15000
#define CG_ID_VIEW_MYDIALOGBAR          15001
#define IDS_STRING_UPDATE_SCRIPT_FAILD  15002
#define IDD_DIALOG_GENERIC_INPUT        15003
#define IDS_STRING_WANT_TO_SAVE_CHANGES 15003
#define IDS_STRING_MODI_BOOT_SEQ_TITLE_TEXT 15004
#define IDC_STATIC_GROUP                15004
#define IDS_STRING_MODI_BOOT_SEQ_GRP_BOX_TEXT 15005
#define IDC_LIST_INCOMING_MESSAGES      15005
#define IDS_STRING_SAVE                 15006
#define IDC_LIST_OUTGOING_MESSAGES      15006
#define IDS_STRING_CLOSE                15007
#define IDC_STATIC_INC_MSGS             15007
#define IDS_STRING_UPDATE_BOOTUP_FAILED 15008
#define IDC_STATIC_OUTGOING_MSGS        15008
#define IDS_STRING_SEND_MESSAGE         15009
#define IDS_STRING_DLG_SEND_EVENTS      15010
#define IDS_STRING_SEND                 15011
#define IDS_STRING_PLEASE_SELECT_MESSAGES 15012
#define IDS_STRING_PLEASE_SELECT_ITEM   15013
#define IDS_STRING_EMPTY                15014
#define IDB_BITMAP_BOOTUP               15045
#define IDB_BITMAP_BATTERY              15046
#define IDB_BITMAP_PBOOK                15047
#define IDB_BITMAP_INCALL               15048
#define IDB_BITMAP_2ND_CALL             15049
#define IDB_BITMAP_DROP                 15050
#define IDB_BITMAP_CHLD                 15051
#define IDB_BITMAP_DIAL_IND             15052
#define IDB_BITMAPOUTGOING_CONNECT      15053
#define IDB_BITMAP_SS_NOT               15054
#define IDB_BITMAP_DTMF                 15055
#define IDB_BITMAP_USSD                 15056
#define IDB_BITMAPNEW_SMS               15057
#define IDB_BITMAP_CLASS0               15058
#define IDB_BITMAP_CBSMS                15059
#define IDB_BITMAP_WAITING_MSG          15060
#define IDB_BITMAP_PNLIND               15061
#define IDB_BITMAP_PLNM_STATUS          15063
#define IDB_BITMAP_SAT                  15064
#define IDB_BITMAP_SAT_SEL              15065
#define IDB_BITMAP_SAT_DISP             15066
#define IDB_BITMAP_SAT_INKEY            15067
#define IDB_BITMAP_SAT_INPUT            15068
#define IDB_BITMAP_SL_IND               15069
#define IDB_BITMAP_SGT_IND              15070
#define IDB_BITMAP_NW_TZ_CHG_INFO       15071
#define IDB_BITMAP_CALL_FWD             15072
#define IDB_BITMAP_CPHS                 15073
#define IDB_BITMAP_CAL_BAR_RESP         15074
#define IDB_BITMAP1_FWD_RESP            15075
#define IDB_BITMAP_NO_SIM               15076
#define IDB_BITMAP_GPIO                 15077
#define IDB_BITMAP_LI                   15078
#define IDB_BITMAP_CAL_HIST             15079
#define IDB_BITMAP_USB                  15080
#define IDD_DLG_ASYNC_MESSAGE           15085
#define IDD_DLG_BOOT_MESSAGE            15086
#define IDD_DLG_SEND_MESSAGE            15087
#define IDD_DLG_NETWORK_SIMULATOR       15088
#define IDD_DLG_SELECT_MESSAGE          15089
#define ID_MENU_EXIT                    32771
#define IDM_SEND_MESSAGE                32772
#define IDM_SEND_MESSAGES               32772
#define IDM_MODIFY_BOOT_MSG             32773
#define ID_MENUITEM32774                32774
#define IDM_MODIFY_ASYNC_MESSAGES_SEQUENCE 32774
#define ID_HELP_CONTENTS                32775
#define ID_ABOUT_ME                     32776
#define ID_BUTTON_MSG1                  32777
#define ID_BUTTON_MSG2                  32778
#define ID_BUTTON_MSG3                  32779
#define ID_BUTTON_MSG4                  32780
#define ID_BUTTON_MSG5                  32781
#define ID_BUTTON_MSG6                  32782
#define ID_BUTTON_MSG7                  32783
#define ID_BUTTON_MSG8                  32784
#define ID_BUTTON_MSG9                  32785
#define ID_BUTTON_MSG10                 32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        15090
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         15010
#define _APS_NEXT_SYMED_VALUE           15002
#endif
#endif
