
#ifndef _HOST_MSG_H

#define _HOST_MSG_H

#define EXTERNAL_TASK_MASK      0x4000

#define LINK_Q   0x0101
#define A2DP_Q      0x0200
#define AVRCP_Q    0x0300
#define HFP_Q        0x0400
#define HSP_Q        0x0800


#define RDABT_LINK_PRIM_BASE      ((u_int16) (0x8000))

typedef enum
{
	LINK_DISCOVERY_RESULT_IND = RDABT_LINK_PRIM_BASE,   
	LINK_DISCOVERY_CNF,		
       LINK_DISCOVERY_CANCEL_CNF,
       LINK_WRITE_SCANENABLE_MODE_CNF,
       LINK_WRITE_LOCALADDR_CNF,
       LINK_WRITE_AUTHENTICATION_MODE_CNF,
	LINK_PIN_CODE_IND
} HOST_LINK_ENUM;



typedef enum{
    A2DP_SIGNAL_CONNECT_CNF = 0,
    A2DP_SIGNAL_DISCONN_CNF,
    A2DP_SEND_SEP_DISCOVER_CNF,
    A2DP_SEND_SEP_GET_CAPABILITIES_CNF,
    A2DP_SEND_SEP_SET_CONFIG_CNF,
    A2DP_SEND_SEP_OPEN_CNF,
    A2DP_SEND_SEP_START_CNF,
    A2DP_SEND_SEP_PAUSE_CNF,
    A2DP_SEND_SEP_CLOSE_CNF,
    A2DP_SEND_SEP_ABORT_CNF,
    A2DP_ACTIVATE_CNF,
    A2DP_DEACTIVATE_CNF,
    A2DP_SIGNAL_CONNECT_IND,
    A2DP_SIGNAL_DISCONNECT_IND,
    A2DP_SEND_SEP_DISCOVER_IND,
    A2DP_SEND_SEP_GET_CAPABILITIES_IND,
    A2DP_SEND_SEP_SET_CONFIG_IND,
    A2DP_SEND_SEP_OPEN_IND,
    A2DP_SEND_SEP_START_IND,
    A2DP_SEND_SEP_PAUSE_IND,
    A2DP_SEND_SEP_CLOSE_IND,
    A2DP_SEND_SEP_ABORT_IND,
        A2DP_SEND_SEP_SET_RECONFIG_CNF
}AV_Q_T;


typedef enum{
    AVRCP_ACTIVATE_CNF = 0,
    AVRCP_DEACTIVATE_CNF,
    AVRCP_CONNECT_CNF,
    AVRCP_CONNECT_IND,
    AVRCP_DISCONNECT_CNF,
    AVRCP_DISCONNECT_IND,
    AVRCP_CMD_FRAME_CNF,
    AVRCP_CMD_FRAME_IND
}AVRCP_Q_T;


typedef enum{
    HFG_ACTIVATE_CNF=0,
    HFG_DEACTIVATE_CNF,
    HFG_ACL_CONNECT_CNF,
    HFG_ACL_DISCONNECT_CNF,
    HFG_SCO_CONNECT_CNF,
    HFG_SCO_DISCONNECT_CNF,
    HFG_REJECT_INCOMING_CALL_CNF,
    HFG_DISCONNECT_FROM_HF_IND,
    HFG_BLDN_FROM_HF_IND,
    HFG_RING_CNF,
    HFG_ACL_CONNECT_IND,
    HFG_ACL_DISCONNECT_IND,
    HFG_SPEAKER_GAIN_IND,
    HFG_MIC_GAIN_IND
}HFP_Q_T;


typedef enum{
    HSG_ACTIVATE_CNF=0,
    HSG_DEACTIVATE_CNF,
    HSG_ACL_CONNECT_CNF,
    HSG_ACL_DISCONNECT_CNF,
    HSG_REJECT_INCOMING_CALL_CNF,
    HSG_DISCONNECT_FROM_HS_IND,
    HSG_BLDN_FROM_HS_IND,
    HSG_RING_CNF,
    HSG_ACL_CONNECT_IND,
    HSG_ACL_DISCONNECT_IND,
    HSG_SPEAKER_GAIN_IND,
    HSG_MIC_GAIN_IND
}HSP_Q_T;

#endif
