/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * EngineerModeDef.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   This file is intends for engineer mode defination
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/


 
#include "mmi_features.h" 
//CSD End

#ifdef __MMI_ENGINEER_MODE__  


#ifndef _ENGINEER_MODE_DEF_H
#define _ENGINEER_MODE_DEF_H


#include "gui_data_types.h"

#define EM_NOTIFY_DURATION					UI_POPUP_NOTIFYDURATION_TIME
#define EM_HIGHTLIGHT_DURATION		   1000

#define EM_ASCII_BUF_LEN            80
#define EM_UNICODE_BUF_LEN      160

/*Menu item IDs			*/
/*
//#define ENGINEER_MODE_BASE             7000
#define EM_NETWORK_BASE                ENGINEER_MODE_BASE+100
#define EM_AUDIO_BASE                  ENGINEER_MODE_BASE+200
#define EM_DEVICE_BASE                 ENGINEER_MODE_BASE+300
#define EM_GPRS_ACT_BASE                ENGINEER_MODE_BASE+400
#define EM_BAND_SEL_BASE                ENGINEER_MODE_BASE+500
#define EM_MISC_BASE                ENGINEER_MODE_BASE+600
#define EM_AUTO_TEST_SETTING_BASE    ENGINEER_MODE_BASE+700
#define EM_DEBUG_INFO_BASE    ENGINEER_MODE_BASE+800
#define EM_SOCKET_BASE			ENGINEER_MODE_BASE+900
#define EM_TOUCHSCREEN_BASE				ENGINEER_MODE_BASE+950
#define EM_BT_BASE    EM_TOUCHSCREEN_BASE+50
#define EM_BT_BASE_LAST    EM_BT_BASE+50
*/

/*	Main menu string IDs	*/
typedef enum{
   EM_SCR_BASE = ENGINEER_MODE_BASE,
   EM_MAIN_MENU_SCR,
   EM_NETWORK_MENU_SCR,
   EM_AUDIO_MENU_SCR,
   EM_AUD_RING_TONE_MENU_SCR,
   EM_AUD_SET_MODE_MENU_SCR,
   EM_AUD_NORMAL_MODE_MENU_SCR,
   EM_AUD_LOUDSP_MODE_MENU_SCR,
   EM_AUD_HEADSET_MODE_MENU_SCR,
   EM_AUD_SET_VOLUME_MENU_SCR,
   EM_AUD_FIR_MENU_SCR,
   EM_AUD_SPEECH_MENU_SCR,
   EM_AUD_KEY_TONE_MENU_SCR,
   EM_AUD_MELODY_MENU_SCR,
   EM_AUD_SIDE_TONE_MENU_SCR,
   EM_AUD_CALL_TONE_MENU_SCR,
   EM_AUD_SOUND_MENU_SCR,
   EM_AUD_MICROPHONE_MENU_SCR,
   EM_AUD_SET_ECHO_PARAM_MENU_SCR,
   EM_AUD_PARAM_EDITOR_SCR, 
   EM_DEVICE_MENU_SCR,
   EM_DEV_DEFAULT_USB_APP_MENU_SCR,
   EM_DEV_SET_UART_MENU_SCR,
   EM_DEV_INLINE_CONFIG_UART_MENU_SCR,
   EM_DEV_SLEEPMODE_MENU_SCR,
   EM_GPRS_ACT_MENU_SCR,
   EM_GPRS_ACTIVATE_PDP_MENU_SCR,
   EM_GPRS_SEND_DATA_MENU_SCR,
   EM_GPRS_SEND_DATA_EDITOR_SCR,
   EM_BAND_SEL_MENU_SCR,
   EM_MISC_MENU_SCR,
   EM_WAP_MENU_SCR,
   EM_WAP_USER_AGENT_MENU_SCR,
   EM_WAP_ACCEPT_HEADER_MENU_SCR,
   EM_WAP_ENABLE_DEBUG_MENU_SCR,
   EM_WAP_OFFLINE_PAGE_MENU_SCR,   
   EM_WAP_MMS_VERSION_MENU_SCR,
   EM_POWER_ON_DURATION_MENU_SCR,
   EM_AUTO_TEST_REMOVE_MENU_SCR,
   EM_AUTO_TEST_ENTER_PRIORITY_MENU_SCR,
   EM_AUTO_TEST_CHANGE_PRIORITY_MENU_SCR,
   EM_AUTO_TEST_ADD_MENU_SCR,
   EM_AUTO_TEST_SETTING_MENU_SCR,
   EM_AUTO_TEST_OPTIONS_MENU_SCR,
   EM_PWR_DOWN_CONTROL_MENU_SCR,
   EM_SERIAL_PORT_EN_MENU_SCR,
   EM_DEBUG_INFO_SCR,
   EM_LAST_EXCEPTION_SCR,
   EM_SOCKET_MENU_SCR,
   EM_SOCKET_DNS_INPUT_SCR,
   EM_SOCKET_DNS_OPTION_SCR,
   EM_SOCKET_HTTP_INPUT_SCR,
   EM_SOCKET_HTTP_OPTION_SCR,
   EM_SOCKET_ECHO_INPUT_SCR,
   EM_SOCKET_DATE_INPUT_SCR,
   EM_SOCKET_ECHO_STRING_INPUT_SCR,
   EM_SOCKET_PROGRESS_SCR,
   EM_SOCKET_RESULT_SCR,
   EM_TOUCHSCREEN_TEST_SCR,
   EM_TOUCHSCREEN_TEST_OPTION_SCR,
   EM_TOUCHSCREEN_TEST_STATISTICS_SCR,
//Lisen 011605
   EM_MMI_DEBUG_SCR,
   EM_MEMORY_DUMP_SCR,

   /* Device */
   EM_DEV_LCD_EDITOR_SCR_ID,
   EM_DEV_GPIO_SCR_ID,
   EM_DEV_GPIO_LIST_SCR_ID,
   EM_DEV_GPIO_EDITOR_SCR_ID,
   EM_DEV_PWM_EDITOR_SCR_ID,
   EM_DEV_HW_LEVEL_EDITOR_SCR_ID,

   EM_DEV_EXT_CAMERA_SCR_ID,
   EM_DEV_EXT_CAMERA_WRITE_SCR_ID,
   EM_DEV_EXT_CAMERA_READ_SCR_ID,

   EM_DEV_GPIO_VIEWER_SCR_ID,
   EM_DEV_PWM_VIEWER_SCR_ID,

   /* GPRS ACT */
   EM_GPRS_PING_SCR_ID,

	/* DBG Trace */
   SCR_ID_EM_FS_TRACE,

	/* Bluetooth */
   SCR_ID_EM_BT,
   
    EM_BT_SCR_ID,
    
    EM_BT_GENERNAL_TEST_SCR_ID,
    EM_BT_GET_CHIP_VERSION_SCR_ID,
    
    EM_BT_LOOKBACK_SCR_ID,
    EM_BT_PROGRESS_SCR,

   EM_SET_SWDBG_SCR,
    /* BT RF Test */
    EM_DEV_BT_RF_TEST_SCR_ID,
    EM_DEV_BT_RF_TEST_TXRX_SCR_ID,
    
    EM_DEV_BT_RF_TEST_BD_ADDR_SCR_ID,
    EM_DEV_BT_RF_TEST_TESTING_SCR_ID,
     #ifdef __BT_RDA5868__
      EM_DEVICE_RDA_BT_TEST_VCO_SCR,      
	EM_DEVICE_RDA_BT_TEST_SINGLEHOP_SCR,
	EM_DEVICE_RDA_BT_TEST_CMU200_SCR,   
	EM_DEVICE_RDA_BT_TEST_TC3000_SCR,  
	EM_DEVICE_RDA_BT_TEST_N4010_SCR,    
#endif
	EM_CELL_ENVIRONMENT_SCR,
	EM_AUTO_TEST_LIST,
#ifdef __MMI_EM_AUDIO_SPEECH_ENHANCEMENT__
	EM_AUD_SPH_ENH_MAIN_SCR,
	EM_AUD_SPH_ENH_PARA_LIST_SCR,
	EM_AUD_SPH_ENH_VOICE_FLOW_SCR,
	EM_AUD_SPH_ENH_PARA_LEVEL_SCR,
	EM_AUD_SPH_ENH_PARA_EDIT_SCR,
	EM_AUD_SPH_ENH_MICROPHONE_FLOW_SCR,
	EM_AUD_SPH_ENH_SAVE_PROGRESS_SCR,
#endif
	EM_SCR_END
}EM_SCR_IDS;

typedef enum{
   ENGINEER_MODE_STR_BASE = ENGINEER_MODE_BASE,
    ENGINEER_MODE_TEXT,		
    EM_SET_LSK_TEXT,        
    EM_TOGGLE_LSK_TEXT,     
    
    EM_NOTICE_WARNING_TEXT,
    EM_NOTICE_SUCCESS_TEXT,
    
//Lisen 09062005
    EM_NOTICE_SUCCESS_REBOOT_TEXT,
    EM_UPDATE_TITLE_TEXT,   
    EM_UPDATE_QUERY_TEXT,  
    EM_UPDATE_ERROR_TEXT,  
    EM_UPDATE_SUCCESS_TEXT,

    EM_STR_GPIO_EDITOR,
    EM_STR_GPO_EDITOR,
    EM_STR_GPIO_MODE,
    EM_STR_GPIO_DIRECTION,
    EM_STR_GPIO_LEVEL,

   EM_STR_EXT_CAMERA_TEXT,
   EM_STR_EXT_CAMERA_WRITE_TEXT,
   EM_STR_EXT_CAMERA_READ_TEXT,
   EM_STR_EXT_CAMERA_COMMAND_TEXT,
   EM_STR_EXT_CAMERA_PARA_TEXT,
    
    EM_STR_PWM_EDITOR,
    EM_STR_PWM_FREQUENCY,
    EM_STR_PWM_DUTY,
    EM_STR_PWM_LEVEL,
    EM_STR_PWNDOWN_CTRL_PDN_CON0,
    EM_STR_PWNDOWN_CTRL_PDN_CON1,
    EM_STR_PWNDOWN_CTRL_PDN_CON2,
    EM_STR_PWNDOWN_CTRL_PDN_CON3,

   /* Network */
   EM_NETWORK_TEXT,
   EM_NET_RR_CELL_SEL_TEXT,   
   EM_NET_RR_CH_DSCR_TEXT,   
   EM_NET_RR_CTRL_CH_TEXT,   
   EM_NET_RR_RACH_CTRL_TEXT, 
   EM_NET_RR_LAI_INFO_TEXT,   
   EM_NET_RR_RADIO_LINK_TEXT, 
   EM_NET_RR_MEAS_REP_TEXT,  
   EM_NET_RR_CTRL_MSG_TEXT,  
   EM_NET_CC_CHAN_INFO_TEXT, 
   EM_NET_CC_CALL_INFO_TEXT,  
   EM_NET_CB_INFO_TEXT,       
   EM_NET_SS_INFO_TEXT,       
   EM_NET_MM_INFO_TEXT,       
   EM_NET_UEM_INFO_TEXT,
   EM_CELL_ENVIRONMENT_TEXT,
   EM_GPRS_TEST_TEXT,

	/* Audio */
   EM_AUDIO_TEXT,
   EM_AUD_FIR_TEXT,
   EM_AUD_SET_VOLUME_TEXT,     
   EM_AUD_SPEECH_TEXT,         
   EM_AUD_SIDE_TONE_TEXT,      
   EM_AUD_KEY_TONE_TEXT,       
   EM_AUD_CALL_TONE_TEXT,      
   EM_AUD_MELODY_TEXT,
   EM_AUD_SOUND_TEXT,
   EM_AUD_MEDIA_TEXT,          
   EM_AUD_MICROPHONE_TEXT,    
   EM_AUD_RING_TONE_TEXT,      
   EM_AUD_MELODY_KEY_TEXT,      
   EM_AUD_SET_MODE_TEXT,
   EM_AUD_NORMAL_MODE_TEXT,   
   EM_AUD_LOUDSP_MODE_TEXT,   
   EM_AUD_HEADSET_MODE_TEXT,  
   EM_AUD_SET_ECHO_PARAM_TEXT,
   EM_AUD_SET_ENERGY_1_TEXT,
   EM_AUD_SET_DELAY_1_TEXT,
   EM_AUD_SET_ENERGY_2_TEXT,
   EM_AUD_SET_DELAY_2_TEXT,
   EM_AUD_SET_MAX_SWING_TEXT,
   EM_AUD_VOLUME_0_TEXT,       
   EM_AUD_VOLUME_1_TEXT,       
   EM_AUD_VOLUME_2_TEXT,       
   EM_AUD_VOLUME_3_TEXT,       
   EM_AUD_VOLUME_4_TEXT,       
   EM_AUD_VOLUME_5_TEXT,       
   EM_AUD_VOLUME_6_TEXT,       
   EM_AUD_FIR_0_TEXT,
   EM_AUD_FIR_1_TEXT,
   EM_AUD_FIR_2_TEXT,
   EM_AUD_FIR_3_TEXT,
   EM_AUD_FIR_4_TEXT,
   EM_AUD_FIR_5_TEXT,
   EM_AUD_DIRECT_APPLY_TEXT,   
   EM_AUD_SET_SUCCESS_TEXT,   
   EM_AUD_SET_ERROR_TEXT,
#ifdef __MMI_EM_AUDIO_SPEECH_ENHANCEMENT__
   EM_AUD_SPEECH_ENHANCEMENT_TEXT,
   EM_AUD_BT_EARPHONE_MODE_TEXT,
   EM_AUD_PARAMETER_LEVEL1_TEXT,
   EM_AUD_PARAMETER_LEVEL2_TEXT,
   EM_AUD_PARAMETER_LEVEL3_TEXT,
   EM_AUD_PARAMETER_LEVEL4_TEXT,
   EM_AUD_PARAMETER_LEVEL5_TEXT,
   EM_AUD_PARAMETER_LEVEL6_TEXT,
   EM_AUD_PARAMETER_LEVEL7_TEXT,
   EM_AUD_ENH_VOICE_FLOW,
   EM_AUD_ENH_MUSIC_FLOW,
   EM_AUD_ENH_SIDE_TONE,
   EM_AUD_ENH_MICROPHONE,
   EM_AUD_ENH_DIGIT_GAINS_STR,
   EM_AUD_ENH_ANALOG_GAINS_STR,
   EM_AUD_ENH_MICROPHONE_GAIN_STR,
   EM_AUD_ENH_GAIN_IN_VOC_STR,
   EM_AUD_ENH_FM_MODE_STR,
   EM_AUD_ENH_TV_MODE_STR,
   EM_AUD_ENH_SET_DEFAULT,
#endif
	/* Device */
   EM_DEVICE_TEXT,		    
   EM_DEV_SET_UART_TEXT,
   EM_DEV_SET_UART_TST_TEXT,
   EM_DEV_SET_UART_PS_TEXT,
   EM_DEV_SET_UART_PORT_TEXT,
   EM_DEV_SET_UART_BUAD_TEXT,
   EM_DEV_DEFAULT_USB_APP_TEXT,
   EM_DEV_DEFAULT_USB_DATA_TEXT,
   EM_DEV_DEFAULT_USB_DEBUG_TEXT,
   EM_DEV_UART_1_TEXT,
   EM_DEV_UART_2_TEXT,
   EM_DEV_UART_3_TEXT,
   EM_DEV_UART_IRDA_TEXT,
   EM_DEV_UART_USB_TEXT,
   EM_DEV_BAUD_AUTO_TEXT,
   EM_DEV_BAUD_75_TEXT,
   EM_DEV_BAUD_150_TEXT,
   EM_DEV_BAUD_300_TEXT,
   EM_DEV_BAUD_600_TEXT,
   EM_DEV_BAUD_1200_TEXT,
   EM_DEV_BAUD_2400_TEXT,
   EM_DEV_BAUD_4800_TEXT,
   EM_DEV_BAUD_7200_TEXT,
   EM_DEV_BAUD_9600_TEXT,
   EM_DEV_BAUD_14400_TEXT,
   EM_DEV_BAUD_19200_TEXT,
   EM_DEV_BAUD_28800_TEXT,
   EM_DEV_BAUD_33900_TEXT,
   EM_DEV_BAUD_38400_TEXT,
   EM_DEV_BAUD_57600_TEXT,
   EM_DEV_BAUD_115200_TEXT,
   EM_DEV_BAUD_230400_TEXT,
   EM_DEV_BAUD_460800_TEXT,
   EM_DEV_BAUD_921600_TEXT,
   EM_DEV_SLEEPMODE_TEXT,
   EM_DEV_SLEEPMODE_ON_TEXT,
   EM_DEV_SLEEPMODE_OFF_TEXT,
   
   EM_DEV_LCD_TEXT,
   EM_DEV_LCD_MAIN_TEXT,
   EM_DEV_LCD_SUB_TEXT,
   EM_DEV_LCD_SET_CONSTRAST_TEXT,
   EM_DEV_LCD_SET_BIAS_TEXT,
   EM_DEV_LCD_SET_LINERATE_TEXT,
   EM_DEV_LCD_SET_TEMPERATURE_TEXT,
   EM_DEV_LCD_SET_PARAM_1_TEXT,
   EM_DEV_LCD_SET_PARAM_2_TEXT,
   EM_DEV_LCD_SET_PARAM_3_TEXT,
   EM_DEV_LCD_SET_PARAM_4_TEXT,
   EM_DEV_LCD_SET_PARAM_5_TEXT,

   EM_DEV_GPIO_TEXT,
   EM_DEV_GPIO_LIST_TEXT,
   EM_DEV_GPIO_SET_TEXT,
   EM_DEV_GPO_SET_TEXT,
  
   EM_DEV_PWM_TEXT,
   EM_DEV_PWM_START_TEXT,
   EM_DEV_PWM_STOP_TEXT,
   EM_DEV_PWM_SET_FREQ_TEXT,
   EM_DEV_PWM_SET_DUTY_TEXT,
  
   EM_DEV_EINT_TEXT,
   EM_DEV_ADC_TEXT,
   EM_DEV_NAND_FORMAT_TEXT,
   EM_DEV_VDROP_TEXT,
   EM_DEV_CLAM_TEXT,

   EM_DEV_HW_LEVEL_TEXT,
   EM_DEV_HW_LEVEL_MLCD_CON_TEXT,
   EM_DEV_HW_LEVEL_SLCD_CON_TEXT,
   EM_DEV_HW_LEVEL_BATTERY_TEXT,
   EM_DEV_HW_LEVEL_PWM1_TEXT,
   EM_DEV_HW_LEVEL_PWM2_TEXT,
   EM_DEV_HW_LEVEL_PWM3_TEXT,

   /* GPRS Act */
   EM_GPRS_ACT_TEXT,		 
   EM_GPRS_AUTO_ATTACH_TEXT,    
   EM_GPRS_ACTIVATE_PDP_TEXT,   
   EM_GPRS_DEACTIVATE_PDP_TEXT, 
   EM_GPRS_SEND_DATA_TEXT,      
   EM_GPRS_SEND_DATA_NORM_TEXT,
   EM_GPRS_SEND_DATA_HDR_TEXT,
   EM_GPRS_PING_TEXT,
   EM_GPRS_PINGIP_TEXT,
   EM_GPRS_PINGSIZE_TEXT,
   EM_GPRS_PINGCOUNT_TEXT,
   EM_GPRS_PINGTIMEOUT_TEXT,
   EM_GPRS_PDP_CONTEXT_1_TEXT,  
   EM_GPRS_PDP_CONTEXT_2_TEXT,  
   EM_GPRS_PDP_CONTEXT_3_TEXT,  
   EM_GPRS_PDP_CONTEXT_4_TEXT,  
   EM_GPRS_PDP_CONTEXT_5_TEXT,  
   EM_GPRS_PDP_CONTEXT_6_TEXT,  
   EM_GPRS_PDP_CONTEXT_7_TEXT,  
   EM_GPRS_PDP_CONTEXT_8_TEXT,  
   EM_GPRS_PDP_CONTEXT_9_TEXT,  
   EM_GPRS_PDP_CONTEXT_10_TEXT, 
   EM_GPRS_PDP_CONTEXT_11_TEXT, 
   EM_GPRS_PDP_CONTEXT_12_TEXT, 
   EM_GPRS_PDP_CONTEXT_13_TEXT, 
   EM_GPRS_PDP_CONTEXT_14_TEXT, 
   EM_GPRS_PDP_CONTEXT_15_TEXT,

	/* Band Selection */
   EM_BAND_SEL_TEXT,		 
   EM_BAND_900_TEXT,  
   EM_BAND_1800_TEXT, 
   EM_BAND_DUAL_TEXT, 
   EM_BAND_1900_TEXT, 
   EM_BAND_850_TEXT,  
//Lisen 05312005	
   EM_BAND_AUTO_TEXT,	

   /* Misc. WAP */
   EM_MISC_TEXT,		 
   EM_AUTO_ANSWER_TEXT,		 
   EM_HIGHSPEED_SIM_MENUID_TEXT,   
   EM_HIGHSPEED_SIM_MENUID_ICON,   
   EM_BACKLIGHT_TEXT,		 
   EM_SERIAL_PORT_EN_TEXT, 
   EM_WAP_TEXT,
   EM_WAP_ENABLE_DEBUG_TEXT,
   EM_WAP_OFFLINE_PAGE_TEXT,
   EM_WAP_USER_AGENT_TEXT,
   EM_WAP_USER_AGENT_MAUI_E800_TEXT,	
   EM_WAP_USER_AGENT_SONY_P800_TEXT,	
   EM_WAP_USER_AGENT_NOKIA_7250i_TEXT,
   EM_WAP_USER_AGENT_SHARP_GX21_TEXT,	
   EM_WAP_USER_AGENT_SONY_T610_TEXT,	
   EM_WAP_USER_AGENT_SAMSUNG_TEXT,	
   EM_WAP_USER_AGENT_NOKIA_6230_TEXT,
   EM_WAP_USER_AGENT_MOTO_V303_TEXT,
   EM_WAP_ACCEPT_HEADER_TEXT,
   EM_WAP_ACCEPT_HEADER_WAP121_TEXT,
   EM_WAP_ACCEPT_HEADER_WAP20_TEXT,
   EM_WAP_ACCEPT_HEADER_WML_TEXT,
   EM_WAP_ACCEPT_HEADER_XHTML_TEXT,	
   EM_WAP_ACCEPT_HEADER_HTML_TEXT,
   EM_WAP_MMS_VERSION_TEXT,
   EM_WAP_MMS_VERSION_MMS_DEFAULT_TEXT,
   EM_WAP_MMS_VERSION_MMS10_TEXT,
   EM_WAP_MMS_VERSION_MMS11_TEXT,
   EM_WAP_MMS_VERSION_MMS12_TEXT,
   EM_POWER_ON_DURATION_TEXT,
   EM_J2ME_TCK_TEXT, 
   EM_AUTO_RESET_TEXT, 
   EM_PWR_DOWN_CONTROL_TEXT,
   EM_AMR_TEXT, 
   EM_RAM_TEST_TEXT,
   EM_TVOUT_TEXT,
   EM_VIDEO_HI_BITRATE_TEXT,   

	/* Auto Test */
   EM_AUTO_TEST_SETTING_TEXT,		 
   EM_AUTO_TEST_OPTIONS_TEXT,		 
   EM_AUTO_TEST_ADD_TEXT,		 
   EM_AUTO_TEST_ENTER_PRIORITY_TEXT, 
   EM_AUTO_TEST_CHANGE_PRIORITY_TEXT, 
   EM_AUTO_TEST_REMOVE_TEXT,		 

	/* DBG Trace */
   STR_ID_EM_DEBUG_INFO,		 
   STR_ID_EM_FS_TRACE,
   STR_ID_EM_LAST_EXCEPTION,

	/* Bluetooth */
   STR_ID_EM_BT,
    EM_BT_STR_ID,
    EM_BT_GENERNAL_TEST_STR_ID,
    EM_BT_GET_CHIP_VERSION_STR_ID,
    EM_BT_ENTRY_TSMOD_STR_ID,
    EM_BT_ENTRY_FW_VERSION_STR_ID,
    EM_BT_ADD_SCO_LNK_STR_ID,
    EM_BT_RMV_SCO_LNK_STR_ID,
    EM_BT_ENTRY_TEST_STR_ID,
    EM_BT_DEBUG_TRACE_STR_ID,
    EM_BT_ADD_AUDIO_CONNECTION_STR_ID,
    EM_BT_REMOVE_AUDIO_CONNECTION_STR_ID,
    EM_BT_LOOKBACK_STR_ID,
    EM_BT_BD_ADDR_STR_ID,
    EM_BT_BD_PASSWORD_STR_ID,
    EM_BT_EXIT_TEST_MODE_STR_ID,
    EM_BT_AVRCP_CMD_LIST_STR_ID,

	/* Socket */
   EM_SOCKET_TEXT,
   EM_SOCKET_DNS_TEXT,
   EM_SOCKET_HTTP_TEXT,		
   EM_SOCKET_ECHO_TEXT,
   EM_SOCKET_DATE_TEXT,
   EM_SOCKET_DNS_DOMAIN_NAME_TEXT,	
   EM_SOCKET_HTTP_URL_TEXT,		
   EM_SOCKET_ECHO_SERVER_IP_TEXT,	
   EM_SOCKET_ECHO_STRING_TEXT,	
   EM_SOCKET_IN_PROGRESS_TEXT,	
   EM_SOCKET_RESULT_TEXT,		

   EM_SOCKET_ERROR_INVAL_PARA_TEXT,
   EM_SOCKET_ERROR_PEER_NOT_REACHABLE_TEXT,
   EM_SOCKET_ERROR_PEER_NO_RESPONSE_TEXT,
   EM_SOCKET_ERROR_CNT_RESET_BY_PEER_TEXT,
   EM_SOCKET_ERROR_BEARER_FAIL_TEXT,
   EM_SOCKET_ERROR_UNKNOWN_APP_TEXT,
   EM_SOCKET_ERROR_BUSY_TEXT,
   EM_SOCKET_ERROR_NO_MEMORY_TEXT,

	/* Touch Screen */
	EM_TOUCHSCREEN_TEXT,
	EM_TOUCHSCREEN_TEST_STATISTICS_TEXT,
	EM_TOUCHSCREEN_TEST_EXIT_TEXT,
	EM_TOUCHSCREEN_TEST_TEXT,
   //Lisen 011605
   EM_MMI_DEBUG_TEXT,
   EM_MEMORY_DUMP_TEXT,
    EM_GLOBAL_PROCESSING_TEXT,

   EM_SWDBG_TEXT,
   EM_SWDBG_OFF_TEXT ,
   EM_SWDBG_DSP_L1_TEXT ,
   EM_SWDBG_DSP_PS_TEXT ,
   EM_SWDBG_L1_PS_TEXT ,
   EM_SWDBG_MCU_TEXT ,
   EM_SWDBG_DSP_L1_PS_TEXT ,
       /* RF Tool */
    EM_RF_TEST_TOOL_TEXT,
    /* GSM */
    EM_RF_TEST_GSM_CONFIRM_NOTIFY_TEST,
    EM_RF_TEST_GSM_TEST,
    /* GSM -- TX */
    EM_RF_GSM_TX_TEST_TEXT,
    EM_RF_GSM_TX_BAND_TEXT,
    EM_RF_GSM_TX_BAND_GSM850_TEXT,
    EM_RF_GSM_TX_BAND_GSM900_TEXT,
    EM_RF_GSM_TX_BAND_DCS1800_TEXT,
    EM_RF_GSM_TX_BAND_PCS1900_TEXT,
    EM_RF_GSM_TX_ARFCN_TEXT,
    EM_RF_GSM_TX_TSC_TEXT,
    EM_RF_GSM_TX_PCL_TEXT,
    EM_RF_GSM_TX_AFC_TEXT,
    EM_RF_GSM_TX_BURST_TYPE_TEXT,
    EM_RF_GSM_TX_BURST_NB_TEXT,
    EM_RF_GSM_TX_BURST_NBALL_TEXT,
    EM_RF_GSM_TX_BURST_AB_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX00_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX11_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX01_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX_RANDOM_TEXT,
    EM_RF_GSM_TX_GAIN_TEXT,
     
    EM_RF_GSM_RX_TEST_TEXT,
    EM_RF_GSM_RX_BURST_CONT_RX_TEXT,
    EM_RF_GSM_RX_BURST_BURST_RX_TEXT,
    /* GSM -- Power Scan */
    EM_RF_GSM_POWER_SCAN_TEXT,
    /* BT RF Test */
    EM_DEV_BT_RF_TEST_TEXT,
    EM_DEV_BT_RF_TEST_TX_TEXT,
    EM_DEV_BT_RF_TEST_RX_TEXT,
    EM_DEV_BT_RF_TEST_BD_ADDR_TEXT,
    EM_DEV_BT_RF_TEST_MODE_TEXT,
    #ifdef __BT_RDA5868__
	EM_DEVICE_RDA_BT_TEST_VCO_TEXT,      
	EM_DEVICE_RDA_BT_TEST_SINGLEHOP_TEXT,
	EM_DEVICE_RDA_BT_TEST_CMU200_TEXT,   
	EM_DEVICE_RDA_BT_TEST_TC3000_TEXT,  
	EM_DEVICE_RDA_BT_TEST_N4010_TEXT,    
   #endif
    EM_DEV_BT_RF_TEST_NO_HOPING_TEXT,
    EM_DEV_BT_RF_TEST_HOPING_TEXT,
    EM_DEV_BT_RF_TEST_CHANNEL_TEXT,
    EM_DEV_BT_RF_TEST_CTRL_PWR_LEVEL_TEXT,

    EM_DEV_BT_RF_TEST_PACKET_TYPE_TEXT,
    EM_DEV_BT_RF_TEST_PACKET_TYPE_DH1_TEXT,
    EM_DEV_BT_RF_TEST_PACKET_TYPE_DH3_TEXT,
    EM_DEV_BT_RF_TEST_PACKET_TYPE_DH5_TEXT,
    
    EM_DEV_BT_RF_TEST_DATA_LEN_TEXT,
    EM_DEV_BT_RF_TEST_POLL_PERIOD_TEXT,
    EM_DEV_BT_RF_TEST_TURN_OFF_BT_TEXT,
   ENGINEER_MODE_STR_END
}EM_STR_IDS;


typedef enum{
   ENGINEER_MODE_ICON_BASE = ENGINEER_MODE_BASE,

	/* Common */
    ENGINEER_MODE_ICON,		  
    ENGINEER_MODE_LSK_ICON,
    ENGINEER_MODE_RSK_ICON,

	/* Network */
   EM_NETWORK_ICON,	      
   EM_NET_RR_CELL_SEL_ICON,   
   EM_NET_RR_CH_DSCR_ICON,   
   EM_NET_RR_CTRL_CH_ICON,   
   EM_NET_RR_RACH_CTRL_ICON, 
   EM_NET_RR_LAI_INFO_ICON,   
   EM_NET_RR_RADIO_LINK_ICON,
   EM_NET_RR_MEAS_REP_ICON,  
   EM_NET_RR_CTRL_MSG_ICON,  
   EM_NET_CC_CHAN_INFO_ICON, 
   EM_NET_CC_CALL_INFO_ICON, 
   EM_NET_CB_INFO_ICON,       
   EM_NET_SS_INFO_ICON,       
   EM_NET_MM_INFO_ICON,       
   EM_NET_UEM_INFO_ICON,      

   	/* Audio */
   EM_AUDIO_ICON,		    
   EM_AUD_SET_VOLUME_ICON,    
   EM_AUD_FIR_ICON,
   EM_AUD_SPEECH_ICON,         
   EM_AUD_SIDE_TONE_ICON,      
   EM_AUD_KEY_TONE_ICON,       
   EM_AUD_CALL_TONE_ICON,      
   EM_AUD_MELODY_ICON,
   EM_AUD_SOUND_ICON,
   EM_AUD_MEDIA_ICON,          
   EM_AUD_MICROPHONE_ICON,    
   EM_AUD_RING_TONE_ICON,     
   EM_AUD_SET_MODE_ICON,
   EM_AUD_NORMAL_MODE_ICON,  
   EM_AUD_LOUDSP_MODE_ICON,   
   EM_AUD_HEADSET_MODE_ICON,  
   EM_AUD_SET_ECHO_PARAM_ICON,
   EM_AUD_SET_ENERGY_1_ICON,
    EM_AUD_BT_EARPHONE_MODE_ICON,
    EM_AUD_BT_CORDLESS_MODE_ICON,
   EM_AUD_SET_DELAY_1_ICON,
   EM_AUD_SET_ENERGY_2_ICON,
   EM_AUD_SET_DELAY_2_ICON,
   EM_AUD_SET_MAX_SWING_ICON,
   EM_AUD_VOLUME_0_ICON,      
   EM_AUD_VOLUME_1_ICON,      
   EM_AUD_VOLUME_2_ICON,      
   EM_AUD_VOLUME_3_ICON,      
   EM_AUD_VOLUME_4_ICON,      
   EM_AUD_VOLUME_5_ICON,      
   EM_AUD_VOLUME_6_ICON,      
   EM_AUD_DIRECT_APPLY_ICON,

#ifdef __MMI_EM_AUDIO_SPEECH_ENHANCEMENT__
   EM_AUD_SPEECH_ENHANCEMENT_ICON,
   EM_AUD_COMMON_PARAMETERS_ICON,
   EM_AUD_AUX1_MODE_ICON,
   EM_AUD_AUX2_MODE_ICON,
   EM_AUD_AUX3_MODE_ICON,
#endif

	/* Device */
   EM_DEVICE_ICON,
   EM_DEV_SET_UART_ICON,
   EM_DEV_SET_UART_PORT_ICON,
   EM_DEV_SET_UART_BUAD_ICON,
   EM_DEV_DEFAULT_USB_APP_ICON,
   EM_DEV_DEFAULT_USB_DATA_ICON,
   EM_DEV_DEFAULT_USB_DEBUG_ICON,
   EM_DEV_UART_1_ICON,
   EM_DEV_UART_2_ICON,
   EM_DEV_UART_3_ICON,
   EM_DEV_BAUD_115200_ICON,
   EM_DEV_BAUD_230400_ICON,
   EM_DEV_BAUD_460800_ICON,
   EM_DEV_BAUD_921600_ICON,
   EM_DEV_SLEEPMODE_ICON,
   EM_DEV_SLEEPMODE_ON_ICON,
   EM_DEV_SLEEPMODE_OFF_ICON,
  
   EM_DEV_LCD_ICON,
   EM_DEV_LCD_MAIN_ICON,
   EM_DEV_LCD_SUB_ICON,
   EM_DEV_LCD_SET_CONSTRAST_ICON,
   EM_DEV_LCD_SET_BIAS_ICON,
   EM_DEV_LCD_SET_LINERATE_ICON,
   EM_DEV_LCD_SET_TEMPERATURE_ICON,
   EM_DEV_LCD_SET_PARAM_1_ICON,
   EM_DEV_LCD_SET_PARAM_2_ICON,
   EM_DEV_LCD_SET_PARAM_3_ICON,
   EM_DEV_LCD_SET_PARAM_4_ICON,
   EM_DEV_LCD_SET_PARAM_5_ICON,
   EM_DEV_GPIO_ICON,
   EM_DEV_GPIO_LIST_ICON,
   EM_DEV_GPIO_SET_ICON,
   EM_DEV_GPO_SET_ICON,
  
   EM_DEV_EXT_CAMERA_ICON,
   EM_DEV_EXT_CAMERA_WRITE_ICON,
   EM_DEV_EXT_CAMERA_READ_ICON,

   EM_DEV_PWM_ICON,
   EM_DEV_PWM_START_ICON,
   EM_DEV_PWM_STOP_ICON,
   EM_DEV_PWM_SET_FREQ_ICON,
   EM_DEV_PWM_SET_DUTY_ICON,
  
   EM_DEV_EINT_ICON,
   EM_DEV_ADC_ICON,
   EM_DEV_NAND_FORMAT_ICON,
   EM_DEV_VDROP_ICON,
   EM_DEV_CLAM_ICON,
  
   EM_DEV_HW_LEVEL_ICON,
   EM_DEV_HW_LEVEL_MLCD_CON_ICON,
   EM_DEV_HW_LEVEL_SLCD_CON_ICON,
   EM_DEV_HW_LEVEL_BATTERY_ICON,
   EM_DEV_HW_LEVEL_PWM1_ICON,
   EM_DEV_HW_LEVEL_PWM2_ICON,
   EM_DEV_HW_LEVEL_PWM3_ICON,

	/* GPRS */
   EM_GPRS_ACT_ICON,	 
   EM_GPRS_AUTO_ATTACH_ICON,    
   EM_GPRS_ACTIVATE_PDP_ICON,    
   EM_GPRS_DEACTIVATE_PDP_ICON, 
   EM_GPRS_SEND_DATA_ICON,      
   EM_GPRS_SEND_DATA_NORM_ICON,
   EM_GPRS_SEND_DATA_HDR_ICON,
   EM_GPRS_PING_ICON,
   EM_GPRS_PINGIP_ICON,
   EM_GPRS_PINGSIZE_ICON,
   EM_GPRS_PINGCOUNT_ICON,
   EM_GPRS_PINGTIMEOUT_ICON,
   EM_GPRS_PDP_CONTEXT_1_ICON,  
   EM_GPRS_PDP_CONTEXT_2_ICON,  
   EM_GPRS_PDP_CONTEXT_3_ICON,  
   EM_GPRS_PDP_CONTEXT_4_ICON,  
   EM_GPRS_PDP_CONTEXT_5_ICON,  
   EM_GPRS_PDP_CONTEXT_6_ICON,  
   EM_GPRS_PDP_CONTEXT_7_ICON,  
   EM_GPRS_PDP_CONTEXT_8_ICON,  
   EM_GPRS_PDP_CONTEXT_9_ICON,  
   EM_GPRS_PDP_CONTEXT_10_ICON, 
   EM_GPRS_PDP_CONTEXT_11_ICON, 
   EM_GPRS_PDP_CONTEXT_12_ICON, 
   EM_GPRS_PDP_CONTEXT_13_ICON, 
   EM_GPRS_PDP_CONTEXT_14_ICON, 
   EM_GPRS_PDP_CONTEXT_15_ICON,

	/* Band Selection */
   EM_BAND_SEL_ICON,	 
   EM_BAND_900_ICON,  
   EM_BAND_1800_ICON, 
   EM_BAND_DUAL_ICON,
   EM_BAND_1900_ICON,
   EM_BAND_850_ICON,
//Lisen 05312005	
   EM_BAND_AUTO_ICON,	

   /* MISC. WAP */
   EM_MISC_ICON,	 
   EM_AUTO_ANSWER_ICON,	 
   EM_BACKLIGHT_ICON,
   EM_SERIAL_PORT_EN_ICON,
   EM_WAP_ICON,
   EM_WAP_ENABLE_DEBUG_ICON,
   EM_WAP_OFFLINE_PAGE_ICON,
   EM_WAP_USER_AGENT_ICON,
   EM_WAP_USER_AGENT_MAUI_E800_ICON,	
   EM_WAP_USER_AGENT_SONY_P800_ICON,	
   EM_WAP_USER_AGENT_NOKIA_7250i_ICON,
   EM_WAP_USER_AGENT_SHARP_GX21_ICON,	
   EM_WAP_USER_AGENT_SONY_T610_ICON,	
   EM_WAP_USER_AGENT_SAMSUNG_ICON,	
   EM_WAP_USER_AGENT_NOKIA_6230_ICON,
   EM_WAP_USER_AGENT_MOTO_V303_ICON,
   EM_WAP_ACCEPT_HEADER_ICON,
   EM_WAP_ACCEPT_HEADER_WAP121_ICON,
   EM_WAP_ACCEPT_HEADER_WAP20_ICON,
   EM_WAP_ACCEPT_HEADER_WML_ICON,
   EM_WAP_ACCEPT_HEADER_XHTML_ICON,	
   EM_WAP_ACCEPT_HEADER_HTML_ICON,
   EM_WAP_MMS_VERSION_ICON,
   EM_WAP_MMS_VERSION_MMS_DEFAULT_ICON,
   EM_WAP_MMS_VERSION_MMS10_ICON,
   EM_WAP_MMS_VERSION_MMS11_ICON,
   EM_WAP_MMS_VERSION_MMS12_ICON,
   EM_POWER_ON_DURATION_ICON,
   EM_J2ME_TCK_ICON,
   EM_AUTO_RESET_ICON, 
   EM_PWR_DOWN_CONTROL_ICON,
   EM_AMR_ICON,
   EM_MMI_DEBUG_ICON,
   EM_MEMORY_DUMP_ICON,
   EM_RAM_TEST_ICON,

   EM_SWDBG_ICON,

   EM_SWDBG_OFF_ICON ,
   EM_SWDBG_DSP_L1_ICON ,
   EM_SWDBG_DSP_PS_ICON ,
   EM_SWDBG_L1_PS_ICON ,
   EM_SWDBG_MCU_ICON ,
   EM_SWDBG_DSP_L1_PS_ICON ,
	/* Auto test */
   EM_AUTO_TEST_SETTING_ICON,	 
   EM_AUTO_TEST_OPTIONS_ICON,	 
   EM_AUTO_TEST_ADD_ICON,	 
   EM_AUTO_TEST_ENTER_PRIORITY_ICON,
   EM_AUTO_TEST_CHANGE_PRIORITY_ICON, 
   EM_AUTO_TEST_REMOVE_ICON,

	/* DBG Info */
   IMG_ID_EM_DEBUG_INFO,
   IMG_ID_EM_FS_TRACE,
   IMG_ID_EM_LAST_EXCEPTION,

	/* Bluetooth */
   IMG_ID_EM_BT,
   IMG_ID_EM_BT_ENTRY_TSMOD,
	IMG_ID_EM_BT_ENTRY_FW_VERSION,
   IMG_ID_EM_BT_ADD_SCO_LNK,
   IMG_ID_EM_BT_RMV_SCO_LNK,
    EM_BT_IMG_ID,
    EM_BT_ENTRY_TSMOD_IMG_ID,
    EM_BT_ENTRY_FW_VERSION_IMG_ID,
    EM_BT_ADD_SCO_LNK_IMG_ID,
    EM_BT_RMV_SCO_LNK_IMG_ID,
    EM_BT_ENTRY_TEST_IMG_ID,
    EM_BT_DEBUG_TRACE_IMG_ID,
    EM_BT_ADD_AUDIO_CONNECTION_IMG_ID,
    EM_BT_REMOVE_AUDIO_CONNECTION_IMG_ID,

	/* Socket */
   EM_SOCKET_ICON,
   EM_SOCKET_DNS_ICON,
   EM_SOCKET_HTTP_ICON,		
   EM_SOCKET_ECHO_ICON,
   EM_SOCKET_DATE_ICON,
   EM_SOCKET_DNS_OPTION_ICON,
   EM_SOCKET_DNS_DONE_ICON,
   EM_SOCKET_DNS_INPUT_METHOD_ICON,
   EM_SOCKET_HTTP_OPTION_ICON,
   EM_SOCKET_HTTP_DONE_ICON,
   EM_SOCKET_HTTP_INPUT_METHOD_ICON,
   
   ENGINEER_MODE_ICON_END
}EM_ICON_IDS;







typedef enum{

   EM_MENU_SERIAL_PORT_EN_1 = 0x0,
   EM_MENU_SERIAL_PORT_EN_2,
   EM_MENU_SERIAL_PORT_EN_3,

   EM_MENU_SERIAL_PORT_EN_MAX
   
} EM_SERIAL_PORT_EN_MENU_ITEM;



 enum EM_SOCKET_ECHO_INLINE_ITEM{
	ENUM_SERVER_IP_CAPTION = 0,
	ENUM_SERVER_IP,
	ENUM_ECHO_STRING_CAPTION,
	ENUM_ECHO_STRING,
	ENUM_ECHO_TOTAL
};
 
enum EM_SOCKET_DATE_INLINE_ITEM{
	ENUM_DATE_SERVER_IP_CAPTION = 0,
	ENUM_DATE_SERVER_IP,
	ENUM_DATE_TOTAL
};

#if (defined(MT6229) || defined(MT6227) || defined(MT6228)) 
#if  (defined(MT6227) || defined(MT6228))
typedef enum{

   EM_SWDBG_OFF ,
   EM_SWDBG_DSP_L1_PS ,
   EM_SWDBG_L1_PS ,
   EM_SWDBG_MCU ,
   EM_SWDBG_MAX  
} EM_SWDBG_ITEM;

#else 

typedef enum{

   EM_SWDBG_OFF ,
   EM_SWDBG_DSP_L1 ,
   EM_SWDBG_DSP_PS ,
   EM_SWDBG_L1_PS ,
   EM_SWDBG_MCU ,
   EM_SWDBG_MAX  
} EM_SWDBG_ITEM;

#endif
#endif

/****** CONSTANT *********/

#define MAX_EM_MODE 32


#define DEFAULT_CHANNEL 8
#define RR_IDLE_STATE 1
#define RR_DEDICATE_STATE 4
#define RR_CELL_SELECTION 9

#define AUD_MIDI     1
#define AUD_IMELODY 2
#define AUD_TONE     3
#define AUD_SOUND     4


#define MAX_EM_VOLUME_LEVEL 7

#define MAX_VOLUME 255
#define MIN_VOLUME 0
#define VOLUME_STEP 4
#define INIT_VOLUME 128

#define MAX_KEY_SHIFT 20

#define MAX_HINT_STRING_LEN  60


#define MAX_ENERGY_VAL  31
#define MIN_ENERGY_VAL	0
#define MAX_DELAY_VAL  30
#define MIN_DELAY_VAL  0
#define AUD_PARAM_STEP 1

/*
#ifndef MMI_ON_HARDWARE_P
#define NVRAM_EF_AUDIO_PARAM_SIZE 512
#endif
*/

#define EM_TCM_PDU_HDR 0

#define BACKLIGHT_FOREVER   0
#define BACKLIGHT_NORMAL    1

#ifdef __TCPIP__ 
#define EM_SOCKET_MAX_INPUT_LEN	64
#define EM_SOCKET_IP_LEN	4
#endif /* __TCPIP_ */

#endif /* _ENGINEER_MODE_DEF_H */

#endif /* __MMI_ENGINEER_MODE__ */

