/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   CameraMenuItems.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   Camera menu items id define. 
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

   /******** Start of ID ********/
MAIN_MENU_ANALOGTV_MENUID, 

MENU_ID_ANALOGTV_MAIN,
// 1 CLASS
//OPTION
MENU_ID_ANALOGTV_OPTION,
MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,
MENU_ID_ANALOGTV_OPTION_CHANNEL_SELECT,
MENU_ID_ANALOGTV_OPTION_ADD_USER_CHANNEL,
MENU_ID_ANALOGTV_OPTION_SEARCH_AREA,
MENU_ID_ANALOGTV_OPTION_EFFECT,
MENU_ID_ANALOGTV_OPTION_RECORDER,
MENU_ID_ANALOGTV_OPTION_SETTING,

// 2 CLASS
//SEARCH OPTION
MENU_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,
MENU_ID_ANALOGTV_CHANNEL_MANUAL_SEARCH,
//SELECT OPTION
MENU_ID_ANALOGTV_CHANNEL_LIST,
MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED,
//AREA OPTION

//EFFECT OPTION
MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,
MENU_ID_ANALOGTV_OPTION_EFFECT_COLOR_DEPTH,

// 3 CLASS
// OF MENU_ID_ANALOGTV_CHANNEL_LIST
MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,
MENU_ID_ANALOGTV_CHANNEL_LIST_PLAY,
MENU_ID_ANALOGTV_CHANNEL_LIST_RENAME,
MENU_ID_ANALOGTV_CHANNEL_LIST_ADD_USER_CHANNEL,
MENU_ID_ANALOGTV_CHANNEL_LIST_DELETE, 

//OF MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED
MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_OPTION,
MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_PLAY,
MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_RENAME,


MENU_ID_ANALOGTV_SETTING_STORAGE,
MENU_ID_ANALOGTV_SETTING_STORAGE_PHONE,
MENU_ID_ANALOGTV_SETTING_STORAGE_CARD,
MENU_ID_ANALOGTV_SETTING_DELETE_ALL_CHANNEL,



