/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	  CameraMenuItems.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   Camera menu items id define. 
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

	/******** Start of ID ********/

	MENU_ID_CAMERA_APP, //1471

	/* option menu */
	MENU_ID_CAMERA_OPTION,
	MENU_ID_CAMERA_TO_IMGVIEW,
#ifdef __PRJ_WITH_SPICAM__
	MENU_ID_CAMERA_TO_CAPTURE,
#endif
#ifndef __MMI_DISABLE_DUAL_SENSOR__
	MENU_ID_CAMERA_SWITCH_SENSOR,
#endif

	MENU_ID_CAMERA_CAMERA_SETTING,
	MENU_ID_CAMERA_IMAGE_SETTING,
	MENU_ID_CAMERA_EFFECT_SETTING,
	MENU_ID_CAMERA_SHOT_MODE, //1477
	MENU_ID_CAMERA_ADD_FRAME,
	MENU_ID_CAMERA_CONT_SHOT,
	MENU_ID_CAMERA_DELAY_TIMER,
	MENU_ID_CAMERA_SELF_CAPTURE,
	MENU_ID_CAMERA_STORAGE,
	MENU_ID_CAMERA_RESTORE_DEFAULT,
	
	/* Effect Setting */
	MENU_ID_CAMERA_EFFECT_NORMAL,
	MENU_ID_CAMERA_EFFECT_GRAYSCALE,
	MENU_ID_CAMERA_EFFECT_SEPIA,
	MENU_ID_CAMERA_EFFECT_SEPIA_GREEN,
	MENU_ID_CAMERA_EFFECT_SEPIA_BLUE,
	MENU_ID_CAMERA_EFFECT_COLOR_INVERT,
	MENU_ID_CAMERA_EFFECT_GRAY_INVERT,
	MENU_ID_CAMERA_EFFECT_BLACKBOARD,
	MENU_ID_CAMERA_EFFECT_WHITEBOARD,
	MENU_ID_CAMERA_EFFECT_COPPER_CARVING,
	MENU_ID_CAMERA_EFFECT_BLUE_CARVING,	
	MENU_ID_CAMERA_EFFECT_EMBOSSMENT,
	MENU_ID_CAMERA_EFFECT_CONTRAST,
	MENU_ID_CAMERA_EFFECT_JEAN,
	MENU_ID_CAMERA_EFFECT_SKETCH,
	MENU_ID_CAMERA_EFFECT_OIL,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_1,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_2,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_3,
	//add by gugogi
	MENU_ID_CAMERA_EFFECT_ANTIQUE,
	MENU_ID_CAMERA_EFFECT_REDRISH,
	MENU_ID_CAMERA_EFFECT_GREENRISH,
	MENU_ID_CAMERA_EFFECT_BLUERISH,
	MENU_ID_CAMERA_EFFECT_BLACKWHITE,
	MENU_ID_CAMERA_EFFECT_NEGATIVENESS,
	
	
	
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_SET_OPTION,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_SET,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_EFFECT,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_OPTION,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_SAVE,
	MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_RESTORE_DEFAULT,

	/* Shot Mode */
	MENU_ID_CAMERA_SHOT_MODE_AUTO,
	MENU_ID_CAMERA_SHOT_MODE_SHUTTER_PRI,
	MENU_ID_CAMERA_SHOT_MODE_APERTURE_PRI,
	MENU_ID_CAMERA_SHOT_MODE_PORTRAIT,	
	MENU_ID_CAMERA_SHOT_MODE_LANDSCAPE,
	MENU_ID_CAMERA_SHOT_MODE_SPORT,
	MENU_ID_CAMERA_SHOT_MODE_FLOWER,
	MENU_ID_CAMERA_SHOT_MODE_NIGHT,

	/* Add Frame */
	MENU_ID_CAMERA_ADD_FRAME_OFF,
	MENU_ID_CAMERA_ADD_FRAME_1,
	MENU_ID_CAMERA_ADD_FRAME_2,
	MENU_ID_CAMERA_ADD_FRAME_3,
	MENU_ID_CAMERA_ADD_FRAME_4,	
	MENU_ID_CAMERA_ADD_FRAME_5,		
	MENU_ID_CAMERA_ADD_FRAME_6,			
	MENU_ID_CAMERA_ADD_FRAME_7,				
	MENU_ID_CAMERA_ADD_FRAME_8,				
	MENU_ID_CAMERA_ADD_FRAME_9,					
	MENU_ID_CAMERA_ADD_FRAME_10,					
	MENU_ID_CAMERA_ADD_FRAME_CUSTOM_1,					
	MENU_ID_CAMERA_ADD_FRAME_CUSTOM_2,					
	MENU_ID_CAMERA_ADD_FRAME_CUSTOM_3,					
	MENU_ID_CAMERA_ADD_FRAME_CUSTOM_4,					
	MENU_ID_CAMERA_ADD_FRAME_CUSTOM_5,						
	
	MENU_ID_CAMERA_ADD_FRAME_OPTION,
	MENU_ID_CAMERA_ADD_FRAME_VIEW,				
	MENU_ID_CAMERA_ADD_FRAME_SET,
	MENU_ID_CAMERA_ADD_FRAME_DE_ASSOCIATE,
	MENU_ID_CAMERA_ADD_FRAME_REPLACE,

	/* Cont shot */
	MENU_ID_CAMERA_CONT_SHOT_OFF,
	MENU_ID_CAMERA_CONT_SHOT_1,
	MENU_ID_CAMERA_CONT_SHOT_2,
	MENU_ID_CAMERA_CONT_SHOT_3,
	MENU_ID_CAMERA_CONT_SHOT_BURST,	
	MENU_ID_CAMERA_CONT_SHOT_TILE,	

	/* Delay timer */
	MENU_ID_CAMERA_DELAY_TIMER_OFF,
	MENU_ID_CAMERA_DELAY_TIMER_1,
	MENU_ID_CAMERA_DELAY_TIMER_2,
	MENU_ID_CAMERA_DELAY_TIMER_3,

	/* Storage */
	MENU_ID_CAMERA_STORAGE_PHONE,
	MENU_ID_CAMERA_STORAGE_MEMORY_CARD,
	/*+ zhouqin modify for dual t-flash card 20110503*/
	#if defined(DUAL_TFLASH_SUPPORT)
	MENU_ID_CAMERA_STORAGE_MEMORY_SEC_CARD,
	#endif
	/*- zhouqin modify for dual t-flash card 20110503*/

	/******** End of ID ********/


