/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  FileManagerMenuItems.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/


MENU_FMGR_NAND_FLASH,
MENU_FMGR_NOR_FLASH,
MENU_FMGR_REM_DEVICE,

MITEM_FMGR_DRIVE_OPTIONS,
MITEM_FMGR_APP_DRIVE_OPTIONS,
MENU_FMGR_DRIVE_OPEN,
MENU_FMGR_DRIVE_FORMAT,
MENU_FMGR_DRIVE_CHECK,
MENU_FMGR_DRIVE_UNMOUNT,
MENU_FMGR_SELECT_DONE,

MITEM_FMGR_FOLDER_OPTIONS,
MITEM_FMGR_APP_FOLDER_OPTIONS,
MENU_FMGR_FOLDER_CREATE,

MITEM_FMGR_TREE_OPTIONS,
MENU_FMGR_TREE_OPEN,
MENU_FMGR_TREE_SELECT,

MITEM_FMGR_IMG_TYPE_OPTIONS,
MITEM_FMGR_AUD_TYPE_OPTIONS,
MITEM_FMGR_VID_TYPE_OPTIONS,
MITEM_FMGR_EXE_TYPE_OPTIONS,
MITEM_FMGR_GEN_TYPE_OPTIONS,
MITEM_FMGR_APP_IMG_TYPE_OPTIONS,
MITEM_FMGR_APP_AUD_TYPE_OPTIONS,
MITEM_FMGR_APP_VID_TYPE_OPTIONS,
MITEM_FMGR_APP_EXE_TYPE_OPTIONS,
MITEM_FMGR_APP_TYPE_OPTIONS,
MITEM_FMGR_THEME_TYPE_OPTIONS,
MITEM_FMGR_JPG_IMG_TYPE_OPTIONS,
MITEM_FMGR_DRM_IMG_TYPE_OPTIONS,
MITEM_FMGR_DRM_AUD_TYPE_OPTIONS,
MITEM_FMGR_DRM_EXE_TYPE_OPTIONS,
MITEM_FMGR_DRM_GEN_TYPE_OPTIONS,

MITEM_FMGR_IMG_TYPE_NO_SIM_OPTIONS,
MITEM_FMGR_AUD_TYPE_NO_FWD_OPTIONS,
MITEM_FMGR_VID_TYPE_NO_SIM_OPTIONS,
MITEM_FMGR_EXE_TYPE_NO_SIM_OPTIONS,
MITEM_FMGR_GEN_TYPE_NO_SIM_OPTIONS,

MENU_FMGR_ACTIVATE_THEME,
MENU_FMGR_THEME_DELETE,

MENU_FMGR_IMG_OPTION_VIEW,
MENU_FMGR_IMG_OPTION_EDIT,
MENU_FMGR_AUD_OPTION_PLAY,
MENU_FMGR_VID_OPTION_PLAY,
MENU_FMGR_EXE_OPTION_EXECUTE,

MENU_FMGR_GEN_OPTION_OPEN,
MENU_FMGR_GEN_OPTION_SORT,
MENU_FMGR_FWD_OPTION_IMG,
MENU_FMGR_FWD_OPTION_IMG_DRM,
MENU_FMGR_FWD_OPTION_AUD,   //1643
MENU_FMGR_FWD_OPTION_AUD_NO_SIM,
MENU_FMGR_FWD_OPTION_VID,   //1645
/*WUZC Modify Start For MMIFS Ver:    on 2007-1-12 14:39 */
MENU_FMGR_FWD_OPTION_VID_NO_SIM,
MENU_FMGR_FWD_OPTION_VCARD,
MENU_FMGR_FWD_OPTION_VCARD_NO_SIM,
MENU_FMGR_FWD_OPTION_VCAL,
MENU_FMGR_FWD_OPTION_VCAL_NO_SIM,
MENU_FMGR_FWD_OPTION_GEN,
MENU_FMGR_GEN_OPTION_FORWARD,
/*Wuzc Modify Start For FMGR Ver:    on 2007-2-27 18:10 */
MENU_FMGR_GEN_OPTION_RENAME,
MENU_FMGR_GEN_OPTION_JPG_DETAIL,
MENU_FMGR_GEN_OPTION_DETAIL ,
MENU_FMGR_GEN_OPTION_COPY ,
MENU_FMGR_GEN_OPTION_DELETE_ALL,
MENU_FMGR_GEN_OPTION_DELETE,
/*Wuzc Modify End  For FMGR Ver:    on 2007-2-27 18:11 */
MENU_FMGR_GEN_OPTION_MOVE,
/*WUZC Modify End  For MMIFS Ver:    on 2007-1-12 14:39 */

MENU_FMGR_FWD_WALLPAPER,  //1660
MENU_FMGR_FWD_SUB_WALLPAPER,  //1661
MENU_FMGR_FWD_SCREENSAVER, //1662
MENU_FMGR_FWD_POWER_ON,  //1663
MENU_FMGR_FWD_POWER_OFF, //1664
MENU_FMGR_FWD_PHB,  //1665
MENU_FMGR_FWD_TODOLIST,  //1666
MENU_FMGR_FWD_SMS,  //1667
MENU_FMGR_FWD_MMS,  //1668
MENU_FMGR_FWD_EMS,  //1669
MENU_FMGR_FWD_EMAIL, //1670
MENU_FMGR_FWD_IRDA,  //1671
/*WUZC Modify Start For MMIFS Ver:    on 2007-1-12 11:38 */
MENU_FMGR_FWD_BT, //1672
MENU_FMGR_FWD_PROFILE,//1673
MENU_FMGR_FWD_BGSOUND, //1674
/*WUZC Modify End  For MMIFS Ver:    on 2007-1-12 11:38 */

MENU_FMGR_SORT_BY_NAME,
MENU_FMGR_SORT_BY_TYPE,
MENU_FMGR_SORT_BY_TIME,
MENU_FMGR_SORT_BY_SIZE,
MENU_FMGR_SORT_NONE,

MITEM_FMGR_EDITOR_OPTION,
MENU_FMGR_EDITOR_DONE,
MENU_FMGR_INPUT_METHOD,

