/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  j2me_menu_items.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/



//CSD: JF added for Wap menu tree
   J2ME_MENU_FULLSCREEN_EDITOR_OPTION,
   J2ME_MENU_FULLSCREEN_EDITOR_OPTION_DONE,
   J2ME_MENU_FULLSCREEN_EDITOR_OPTION_CANCEL,
   J2ME_MENU_FULLSCREEN_EDITOR_OPTION_INPUT_METHOD,

//CSD: JF end

 
	MENU3108_JAVA,
	MENU_JAVA,
	MENU_JAVA_EM,
	MENU_JAVA_EM_TCK,
	MENU_JAVA_APP_MIDS_OPTION,
	MENU_JAVA_APP_MIDSN1_OPTION,
	MENU_JAVA_APP_MIDSN2_OPTION,
	MENU_JAVA_APP_MIDS11_OPTION,
	MENU_JAVA_APP_MIDS12_OPTION,

	MENU_JAVA_APP_OPTION_SELECT,
	MENU_JAVA_APP_OPTION_LAUNCH,
	MENU_JAVA_APP_OPTION_UPDATE,
	MENU_JAVA_APP_OPTION_SETTING,
	MENU_JAVA_APP_OPTION_INFO,
	MENU_JAVA_APP_OPTION_DELETE,

	MENU_JAVA_SETTING_NETWORK_ACCESS,
	MENU_JAVA_SETTING_AUTO_INVOCATION,
	MENU_JAVA_SETTING_MESSAGING,
	MENU_JAVA_SETTING_RECORDING,

	MENU_JAVA_PERM,
	MENU_JAVA_PERM_ALWAYS,
	MENU_JAVA_PERM_MAYBE,
	MENU_JAVA_PERM_NEVER,

	MENU_JAVA_EM_NORMAL,
	MENU_JAVA_EM_CLDC_TCK,
	MENU_JAVA_EM_MIDP_TCK,
	MENU_JAVA_EM_WMAPI_TCK,
	MENU_JAVA_EM_MMAPI_TCK,

	MENU_JAVA_DOWNLOADING,
	MENU_JAVA_DELETING,
 

