
#define  _MMI_EBOOKDEFS_H
#include "mmi_features.h"

#include "mmi_data_types.h"

typedef enum
{
    EBOOK_SCREENID = EBOOK_BASE + 1,
    EBOOK_SELECT_DRIVE_SCREEN_ID,
    EBOOK_OPEN_OPTION_SCREENID,
    EBOOK_BOOKSHELF_SCREENID,
    EBOOK_OPEN_SCREENID,
    EBOOK_INFO_SCREENID,
    EBOOK_SEARCH_SCREENID,
    EBOOK_SEARCH_STR_SCREENID,
    EBOOK_JUMPTO_SCREENID,
    EBOOK_SETTINGS_SCREEID,
    EBOOK_BOOK_SETTINGS_SCREENID,
    EBOOK_REMOVE_BOOKMARK_SCREENID,
    EBOOK_GOTO_BOOKMARK_SCREENID,
    EBOOK_BOOK_SETTINGS,
    EBOOK_ADD_BOOK_MARK_SCREEN_ID,
    EBOOK_JUMPTO_SCREEN_ID,
    EBOOK_DUMMY_SCREEN_ID,
    EBOOK_JUMPTO_DONE_SCREEN_ID,
    EBOOK_BOOK_SHELF_SETTINGS_SCREEN_ID,
    EBOOK_BOOK_SETTINGS_SCREEN_ID,
    SCR_ID_EBOOK_WAITSCREEN,
    SCR_EBOOK_ENTER_PERCENTAGE_SCREEN_ID,
    DUMMY_SCREEN_ID,
    SCR_EDIT_BOOK_MARK_NAME,
    EBOOK_HELP_SCREEN,
    SCR_ID_EBOOK_FILE_MOVE_WAITSCREEN,
} SCREENID_LIST_EBOOK;

typedef enum
{
    EBOOK_TITLE_STRINGID = EBOOK_BASE + 1,
    EBOOK_DRIVE_SELECT_TYPE,
    STR_SETTINGS_PHONE_MEMORY,
    STR_SETTINGS_CARD_MEMORY,
    STR_SETTINGS_SELECT_MEMORY,
    EBOOK_TITLE_BOOKSHELF,
    EBOOK_BKSLF_OPTION,
    STR_OPEN_CARD_DRV,
    STR_OPEN_PRIVATE_DRV,
    STR_REFRESH_EBOOK,
    STR_OPEN_BOOK_OPTION,
    STR_RENAME_BOOK_OPTIONS,
    STR_OPEN_EBOOK,
    STR_INFO_EBOOK,
    STR_DELETE_EBOOK,
    STR_HELP_EBOOK,
    STR_SETTINGS_EBOOK,
    STR_FIND_EBOOK,
    STR_FIND_NEXT_EBOOK,
    STR_JUMP_EBOOK,
    STR_GOTO_BOOKMARK_EBOOK,
    STR_ADD_BOOKMARK_EBOOK,
    STR_RMV_BOOKMARK_EBOOK,
    STR_BOOK_INFO_EBOOK,
    STR_BOOK_SETTINGS_EBOOK,
    STR_CLOSE_EBOOK,
    STR_SRCH_CASE_EBOOK,
    STR_SRCH_CASEIN_EBOOK,
    STR_JMP_BEG_EBOOK,
    STR_JMP_MID_EBOOK,
    STR_JMP_END_EBOOK,
    STR_JMP_PERCENTAGE_EBOOK,
    STR_SETTINGS_FONT_STYLE,
    STR_SETTINGS_FONT_SIZE,
    STR_SETTINGS_SCROLL_BY,
    STR_SETTINGS_AUTO_SCROLL,
    STR_SETTINGS_AUTO_SCROLL_SPEED,
    STR_SETTINGS_FULL_SCREEN,
    STR_SETTINGS_ENCODING_FORMAT,
    STR_SETTINGS_FONT_STYLE_BOLD,
    STR_SETTINGS_FONT_STYLE_ITALIC,
    STR_SETTINGS_FONT_STYLE_NORMAL,
    STR_SETTINGS_FONT_SIZE_LARGE,
    STR_SETTINGS_FONT_SIZE_SMALL,
    STR_SETTINGS_FONT_SIZE_MEDIUM,
    STR_SETTINGS_SCROLL_BY_PAGE,
    STR_SETTINGS_SCROLL_BY_LINE,
    STR_SETTINGS_AUTO_SCROLL_ON,
    STR_SETTINGS_AUTO_SCROLL_OFF,
    STR_SETTINGS_FULL_SCREEN_ON,
    STR_SETTINGS_FULL_SCREEN_OFF,
    STR_SETTINGS_AUTO_SCROLL_SPEED_1,
    STR_SETTINGS_AUTO_SCROLL_SPEED_2,
    STR_SETTINGS_AUTO_SCROLL_SPEED_3,
    STR_SETTINGS_AUTO_SCROLL_SPEED_4,
    STR_SETTINGS_AUTO_SCROLL_SPEED_5,
    STR_EBOOK_BOOKMARK_ADDED,
    STR_DELETED,
    STR_MAX_BOOK_MARK,
    STR_EBOOK_HELP_DESCRIPTION,
	STR_EBOOK_TOUCH_SCREEN_HELP,
    STR_DELETE_EBOOK_CONFIRM,
    STR_DELETE_BOOK_MARK,
    STR_BOOK_SHELF_REFRESHED,
    STR_DUPLICATE_BOOK_MARK,
    STR_WRONG_PERCENTAGE_VALUE,
    STR_FULL_SCREEN_OFF,
    STR_FULL_SCREEN_ON,
    STR_AUTO_SCROLL_ON,
    STR_AUTO_SCROLL_OFF,
    STR_SETTINGS_ENCODING_FORMAT_UCS2,
    STR_SETTINGS_ENCODING_FORMAT_UTF8,
    /* For File Manager */
    STR_FMGR_EBOOK_OPTION,
    STR_ADD_TO_BOOK_SHELF,
    STR_ERROR_OPENINIG_BOOK,
    STR_ADD_TO_EBOOK_FOLDER,
    STR_OPEN_BOOK_ERROR,
    STR_EBOOK_FORMAT_NOT_SUPPORTED,
    STR_EBOOK_SEARCH_UN_SUCESSFULL,
    STR_WAIT_STRING,
    STR_PERCENTAGE_SCREEN,
    STR_DELETE_ALL_EBOOK,
    STR_RESTORE_DEFAULT,
    STR_SUCESSFULL_RESTORE_DEFAULT,
    STR_UNSUCESSFULL_RESTORE_DEFAULT,
    STR_DELETE_ALL_EBOOK_CONFIRM,
    STR_RESTORE_DEFAULT_SETTINGS,
    STR_EBOOK_WAIT,
    STR_CHANGE_CARD_TO_PHONE,
    STR_CHANGE_PHONE_TO_CARD,
    STR_MEMORY_TYPE_CHANGED,
    STR_NO_BOOK_MARK_PRESENT,
    STR_CONFIRM_SAVE_SETTINGS,
    STR_BOOK_MARK_NAME_IS_EMPTY,
    STR_EBOOK_INPUT_METHOD,
    STR_EBOOK_DONE,
    STR_BOOK_TOO_SMALL,
    STR_EBOOK_LIST_LSK_EDIT,
    STR_EBOOK_MEMORY_LESS,
    STR_INCOMPLETE_SEARCH_STRING,
    STR_EBOOK_BOOK_INFO_TITLE,
    STR_EBOOK_BOOK_INFO_SIZE,
    STR_EBOOK_BOOK_INFO_FORMAT,
    MAIN_MENU_EBOOK_TEXT,
#ifdef __MMI_CHSET_BIG5__
    STR_SETTINGS_ENCODING_FORMAT_BIG5,
#endif 

#ifdef __MMI_CHSET_GB2312__
    STR_SETTINGS_ENCODING_FORMAT_GB2312,

#endif /* __MMI_CHSET_GB2312__ */ 

#ifdef __MMI_CHSET_TURKISH_ISO__
    STR_SETTINGS_ENCODING_FORMAT_TURKISH_ISO,
#endif 

#ifdef __MMI_CHSET_TURKISH_WIN__
    STR_SETTINGS_ENCODING_FORMAT_TURKISH_WIN,
#endif 
#ifdef __MMI_CHSET_BALTIC_ISO__
    STR_SETTINGS_ENCODING_FORMAT_BALTIC_ISO,
#endif 
#ifdef __MMI_CHSET_BALTIC_WIN__
    STR_SETTINGS_ENCODING_FORMAT_BALTIC_WIN,
#endif 
#ifdef __MMI_CHSET_CEURO_ISO__

    STR_SETTINGS_ENCODING_FORMAT_CUEURO_ISO,
#endif /* __MMI_CHSET_CEURO_ISO__ */ 
#ifdef __MMI_CHSET_CEURO_WIN__
    STR_SETTINGS_ENCODING_FORMAT_CUEURO_WIN,
#endif 
#ifdef __MMI_CHSET_GREEK_ISO__
    STR_SETTINGS_ENCODING_FORMAT_GREEK_ISO,
#endif 
#ifdef __MMI_CHSET_GREEK_WIN__
    STR_SETTINGS_ENCODING_FORMAT_GREEK_WIN,
#endif 
#ifdef __MMI_CHSET_HEBREW_ISO__
    STR_SETTINGS_ENCODING_FORMAT_HEBREW_ISO,
#endif 
#ifdef __MMI_CHSET_LATIN_ISO__
    STR_SETTINGS_ENCODING_FORMAT_LATIN_ISO,
#endif 
#ifdef __MMI_CHSET_NORDIC_ISO__
    STR_SETTINGS_ENCODING_FORMAT_NORDIC_ISO,
#endif 
#ifdef __MMI_CHSET_SEURO_ISO__
    STR_SETTINGS_ENCODING_FORMAT_SEURO_ISO,

#endif /* __MMI_CHSET_SEURO_ISO__ */ 
#ifdef __MMI_CHSET_WESTERN_ISO__
    STR_SETTINGS_ENCODING_FORMAT_WESTERN_ISO,
#endif 
#ifdef __MMI_CHSET_WESTERN_WIN__
    STR_SETTINGS_ENCODING_FORMAT_WESTERN_WIN,
#endif 
#ifdef __MMI_CHSET_ARABIC_ISO__
    STR_SETTINGS_ENCODING_FORMAT_ARABIC_ISO,

#endif /* __MMI_CHSET_ARABIC_ISO__ */ 
#ifdef __MMI_CHSET_ARABIC_WIN__
    STR_SETTINGS_ENCODING_FORMAT_ARABIC_WIN,

#endif /* __MMI_CHSET_ARABIC_WIN__ */ 
#ifdef __MMI_CHSET_HEBREW_WIN__
    STR_SETTINGS_ENCODING_FORMAT_HEBREW_WIN,
#endif 
    STR_USB_IS_PLUGGED_IN,
    STR_EBOOK_SEARCH_INVALID,
    STR_EBOOK_DEFAULT_BOOKMARK,
    STR_EBOOK_DELETE_INQUIRE,
    STR_EBOOK_QUESTION_SIGN,
    STR_EBOOK_CONFIRM_JUMP,
    STR_EBOOK_WAIT_FOR_MOVING_FILE,
    STR_SETTINGS_LEFT_ALIGNMENT,
    STR_SETTINGS_RIGHT_ALIGNMENT,
    STR_SETTINGS_ALIGNMENT_STYLE,
    STR_EBOOK_BOOKMARK_ADD_FAIL,
    STR_EBOOK_IS_INITIALIZING,
    STR_SCR_EBOOK_TOTAL
} STRINGID_LIST_EBOOK;

typedef enum
{
    MAIN_MENU_EBOOK_ICON = EBOOK_BASE + 1,
    EBOOK_TITLE_IMAGEID,
    IMAGE_EBOOK_WAIT,
    IMG_SCR_EBOOK_TOTAL
} IMAGEID_LIST_EBOOK;

typedef enum
{
    EBR_FONT_STYLE_NORMAL = 0,
    EBR_FONT_STYLE_ITALIC,
    EBR_FONT_STYLE_BOLD
} ebr_font_style_enum;

typedef enum
{
    EBR_FONT_SIZE_SMALL = 0,
    EBR_FONT_SIZE_MEDIUM,
    EBR_FONT_SIZE_LARGE
} ebr_font_size_enum;

typedef enum
{
    EBR_SCROLL_BY_LINE = 0,
    EBR_SCROLL_BY_PAGE
} ebr_scroll_type_enum;

typedef enum
{
    EBR_AUTO_SCROLL_SPEED_1 = 0,
    EBR_AUTO_SCROLL_SPEED_2,
    EBR_AUTO_SCROLL_SPEED_3,
    EBR_AUTO_SCROLL_SPEED_4,
    EBR_AUTO_SCROLL_SPEED_5
} ebr_scroll_speed_enum;

typedef enum
{
    EBR_SCROLL_OFF = 0,
    EBR_SCROLL_ON
} ebr_scroll_status_enum;

typedef enum
{
    EBR_FULL_SCREEN_OFF = 0,
    EBR_FULL_SCREEN_ON
} ebr_full_screen_status_enum;

typedef enum
{
    EBR_ALIGNMENT_LEFT = 0,
    EBR_ALIGNMENT_RIGHT
}ebr_alignment_style_enum;

typedef enum
{
    EBOOK_WESTERN_WINDOWS,          /* windows-1252 */
    EBOOK_UCS,
    EBOOK_UTF8,
#ifdef __MMI_CHSET_BIG5__
    EBOOK_BIG5,             /* big5 */
#endif 

#ifdef __MMI_CHSET_GB2312__
    EBOOK_GB2312,   /* gb2312 */
#endif 

#ifdef __MMI_CHSET_TURKISH_ISO__
    EBOOK_TURKISH_ISO,
#endif 

#ifdef __MMI_CHSET_TURKISH_WIN__
    EBOOK_TURKISH_WINDOWS,  /* windows-1254 */
#endif 

#ifdef __MMI_CHSET_BALTIC_ISO__
    EBOOK_BALTIC_ISO,   /* iso-8859-13 */
#endif 

#ifdef __MMI_CHSET_BALTIC_WIN__
    EBOOK_BALTIC_WINDOWS,   /* windows-1257 */
#endif 

#ifdef __MMI_CHSET_CEURO_ISO__
    EBOOK_CENTRAL_EUROPEAN_ISO, /* iso-8859-2 */
#endif 

#ifdef __MMI_CHSET_CEURO_WIN__
    EBOOK_CENTRAL_EUROPEAN_WINDOWS, /* windows-1250 */
#endif 

#ifdef __MMI_CHSET_GREEK_ISO__
    EBOOK_GREEK_ISO,    /* iso-8859-7 */
#endif 

#ifdef __MMI_CHSET_GREEK_WIN__
    EBOOK_GREEK_WINDOWS,    /* windows-1253 */
#endif 

#ifdef __MMI_CHSET_HEBREW_ISO__
    EBOOK_HEBREW_ISO,   /* iso-8859-8-i */
#endif 

#ifdef __MMI_CHSET_HEBREW_WIN__
    EBOOK_HEBREW_WINDOWS,   /* windows-1255 */
#endif 

#ifdef __MMI_CHSET_LATIN_ISO__
    EBOOK_LATIN_ISO,    /* iso-8859-15 */
#endif 

#ifdef __MMI_CHSET_NORDIC_ISO__
    EBOOK_NORDIC_ISO,   /* iso-8859-10 */
#endif 

#ifdef __MMI_CHSET_SEURO_ISO__
    EBOOK_SOURTH_EUROPEAN_ISO,  /* iso-8859-3 */
#endif 

#ifdef __MMI_CHSET_WESTERN_ISO__
    EBOOK_WESTERN_ISO,  /* iso-8859-1 */
#endif 

#ifdef __MMI_CHSET_ARABIC_ISO__
    EBOOK_ARABIC_ISO,   /* iso-8859-6 */
#endif 

#ifdef __MMI_CHSET_ARABIC_WIN__
    EBOOK_ARABIC_WINDOWS,   /* windows-1256 */
#endif 
    
#ifdef __MMI_CHSET_GB18030__
        EBOOK_GB18030,
#endif /* __MMI_CHSET_GB18030__ */ 

    EBOOK_UNSPECIFIED_CHARSET,
/*+ zhouqin modify for dual t-flash card 20110503*/
#if defined(DUAL_TFLASH_SUPPORT)
    STR_SETTINGS_SEC_CARD_MEMORY,
#endif
/*- zhouqin modify for dual t-flash card 20110503*/

    MMI_EBOOK_MAX_CHARSET   /* internal used by e-mail protocol entity */
} ebook_charset_enum;

