/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	  VdoPlyImgEnum.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   Video Play Image ID Enum.
 *
 * Author:
 * -------
 *	  Bear Wang
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 * $Log$
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/
#ifndef _MMI_VDOPLYIMGENUM_H
#define _MMI_VDOPLYIMGENUM_H

typedef enum {
	IMG_ID_VDOPLY_APP_ICON	= VDOPLY_BASE+1,
	IMG_ID_VDOPLY_SUBLCD_ICON,
	IMG_ID_VDOPLY_LOADING,

	/********** OSD **********/
	IMG_ID_VDOPLY_OSD_BG,            //     40004
	IMG_ID_VDOPLY_OSD_BUTTOM_BAR_BG,  // 40005

	/* play speed */
	IMG_ID_VDOPLY_OSD_SPEED_START,	//40006
	IMG_ID_VDOPLY_OSD_SPEED_0, 	//40007
	IMG_ID_VDOPLY_OSD_SPEED_1,	//40008
	IMG_ID_VDOPLY_OSD_SPEED_2,	//	40009
	IMG_ID_VDOPLY_OSD_SPEED_3,	//		400010
	IMG_ID_VDOPLY_OSD_SPEED_4,	//40011
	IMG_ID_VDOPLY_OSD_SPEED_5,//40012
	IMG_ID_VDOPLY_OSD_SPEED_6,//40013
	IMG_ID_VDOPLY_OSD_SPEED_7,//40014
	IMG_ID_VDOPLY_OSD_SPEED_8,//40015

	/* volumn */
	IMG_ID_VDOPLY_OSD_VOLUME_START,//40016
	IMG_ID_VDOPLY_OSD_VOLUME_1,//40017
	IMG_ID_VDOPLY_OSD_VOLUME_2,//40018
	IMG_ID_VDOPLY_OSD_VOLUME_3,	//40019
	IMG_ID_VDOPLY_OSD_VOLUME_4,//40020
	IMG_ID_VDOPLY_OSD_VOLUME_5,//40021
	IMG_ID_VDOPLY_OSD_VOLUME_6,//40022
	IMG_ID_VDOPLY_OSD_VOLUME_7,//40023	

	/* progress */
	IMG_ID_VDOPLY_OSD_PROGRESS_BG,//40024
	IMG_ID_VDOPLY_OSD_PROGRESS_FILL,//40025
	IMG_ID_VDOPLY_OSD_PROGRESS_EMPTY,	//40026
	    /* connecting */
    IMG_ID_VDOPLY_OSD_CONNECTING,
    
    /* bt connecting */
    IMG_ID_VDOPLY_OSD_BT_CONNECTING,

    /* opening */
    IMG_ID_VDOPLY_OSD_OPENING,    
	/* timer */
	IMG_ID_VDOPLY_OSD_TIMER_BG,//40027
	IMG_ID_VDOPLY_OSD_TIMER_0,//40028
	IMG_ID_VDOPLY_OSD_TIMER_1,//40029
	IMG_ID_VDOPLY_OSD_TIMER_2,//40030
	IMG_ID_VDOPLY_OSD_TIMER_3,//40031
	IMG_ID_VDOPLY_OSD_TIMER_4,//40032
	IMG_ID_VDOPLY_OSD_TIMER_5,//40033
	IMG_ID_VDOPLY_OSD_TIMER_6,//40034
	IMG_ID_VDOPLY_OSD_TIMER_7,//40035
	IMG_ID_VDOPLY_OSD_TIMER_8,//40036
	IMG_ID_VDOPLY_OSD_TIMER_9,//40037
	IMG_ID_VDOPLY_OSD_TIMER_COL,	//40038

	/* status */
	IMG_ID_VDOPLY_OSD_STATE_PLAY,//40039
	IMG_ID_VDOPLY_OSD_STATE_PAUSE,	//40040
	IMG_ID_VDOPLY_OSD_STATE_STOP,//40041
	IMG_ID_VDOPLY_OSD_STATE_SNAP,//40042
	

	/********** Fullscreen OSD **********/
	IMG_ID_VDOPLY_FULLSCR_OSD_BG,//40043
	
	/* play speed */
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_START,//40044
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_0,//40045
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_1,	//40046
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_2,//40047		
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_3,	//40048		
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_4,	//	40049	
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_5,//40050
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_6,//40051
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_7,//40052
	IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_8,	//40053

	/* volumn */
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_START,//40054
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_1,//40055
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_2,//40056
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_3,//40057
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_4,//40058
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_5,//40059
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_6,//	40060
	IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_7,		//40061

	/* progress */
	IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_BG,//40062
	IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_FILL,//40063
	IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_EMPTY,	//40064
	
	/* timer */
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_0,//40065
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_1,//40066
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_2,//40067
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_3,//40068
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_4,//40069
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_5,//40070
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_6,//40071
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_7,//40072
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_8,//40073
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_9,//40074
	IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_COL,	//40075

	/* status */
	IMG_ID_VDOPLY_FULLSCR_OSD_STATE_PLAY,//40076
	IMG_ID_VDOPLY_FULLSCR_OSD_STATE_PAUSE,//	40077
	IMG_ID_VDOPLY_FULLSCR_OSD_STATE_STOP,//40078
	IMG_ID_VDOPLY_FULLSCR_OSD_STATE_SNAP,//40079

	/********** Touch Screen OSD **********/
	IMG_ID_VDOPLY_TOUCH_OSD_SPEED_INC,//40080
	IMG_ID_VDOPLY_TOUCH_OSD_SPEED_INC_SEL,//40081
	IMG_ID_VDOPLY_TOUCH_OSD_SPEED_INC_DIS,	//40082
	IMG_ID_VDOPLY_TOUCH_OSD_SPEED_DEC,//40083
	IMG_ID_VDOPLY_TOUCH_OSD_SPEED_DEC_SEL,//	40084
	IMG_ID_VDOPLY_TOUCH_OSD_SPEED_DEC_DIS,	//40085	
	IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_INC,//40086
	IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_INC_SEL,//40087
	IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_INC_DIS,	//40088
	IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_DEC,//40089
	IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_DEC_SEL,//40090
	IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_DEC_DIS,//40091
	IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_INC,//40092
	IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_INC_SEL,//40093
	IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_DEC,//40094
	IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_DEC_SEL,//40095
	IMG_ID_VDOPLY_TOUCH_OSD_SNAPSHOT,//40096
	IMG_ID_VDOPLY_TOUCH_OSD_SNAPSHOT_SEL,//40097	
	IMG_ID_VDOPLY_TOUCH_OSD_FULLSCREEN,//40098
	IMG_ID_VDOPLY_TOUCH_OSD_FULLSCREEN_SEL,	//40099	
	IMG_ID_VDOPLY_TOUCH_OSD_PLAY,//40100
	IMG_ID_VDOPLY_TOUCH_OSD_PLAY_SEL,//40101
	IMG_ID_VDOPLY_TOUCH_OSD_PAUSE,//40102
	IMG_ID_VDOPLY_TOUCH_OSD_PAUSE_SEL,	//40103
	IMG_ID_VDOPLY_TOUCH_OSD_STOP,//40104
	IMG_ID_VDOPLY_TOUCH_OSD_STOP_SEL,//40105

	IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_INC,//40106
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_INC_SEL,//40107
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_INC_DIS,	//40108
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_DEC,//40109
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_DEC_SEL,	//40110
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_DEC_DIS,		//40111
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_INC,//40112
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_INC_SEL,//40113
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_INC_DIS,	//40114
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_DEC,//40115
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_DEC_SEL,//40116
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_DEC_DIS,//40117
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_INC,//40118
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_INC_SEL,//40119
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_DEC,//40120
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_DEC_SEL,//40121
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PLAY,//40122
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PLAY_SEL,//40123
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PAUSE,//40124
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_PAUSE_SEL,	//40125
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_STOP,//40126
	IMG_ID_VDOPLY_TOUCH_FULL_OSD_STOP_SEL,//40127

	/* softkey image */
	IMG_ID_VDOPLY_RSK_BACK,//40128
	IMG_ID_VDOPLY_RSK_BACK_SEL,//40129
	IMG_ID_VDOPLY_RSK_STOP,//40130
	IMG_ID_VDOPLY_RSK_STOP_SEL,	//40131	
	IMG_ID_VDOPLY_LSK_PLAY,//40132
	IMG_ID_VDOPLY_LSK_PLAY_SEL,	//40133
	IMG_ID_VDOPLY_LSK_PAUSE,//40134
	IMG_ID_VDOPLY_LSK_PAUSE_SEL,	//40135
	IMG_ID_VDOPLY_LSK_RESUME,//40136
	IMG_ID_VDOPLY_LSK_RESUME_SEL,	//40137

	IMG_ID_VDOPLY_OSD_PROGRESS_BG_LEFT, //40138
	IMG_ID_VDOPLY_OSD_PROGRESS_BG_RIGHT,//40139

	IMG_ID_VDOPLY_RSK_BG,   //40140
	IMG_ID_VDOPLY_LSK_BG,   //40141

	IMG_ID_VDOPLY_TOTAL_COUNT   //40142

} IMG_ID_VDOPLY_ENUM;

	

#endif /* _MMI_VDOPLYIMGENUM_H */


