// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CScreen;
class CKeypad;

/////////////////////////////////////////////////////////////////////////////
// CCoolPhone wrapper class

class CCoolPhone : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCoolPhone)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xab9d831b, 0x277b, 0x4927, { 0x8f, 0x89, 0xc1, 0xcb, 0xbe, 0xb9, 0xe6, 0x11 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CScreen Screen();
	CScreen SubScreen();
	CKeypad Keypad();
	BOOL LoadPhoneScript(LPCTSTR lpszScript);
	BOOL SetBackgroundImage(LPCTSTR lpszImageFile);
	void LoadSkinProfile(LPCTSTR lpszSkinProfile);
	void ShowSkinSetupDlg();
	void ShowExtendKeyboard(BOOL bShow);
	void ShowExtendKeyboardEx(long xPos, long yPos, BOOL bShow);
	void AboutBox();
};
