// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "coolbitmapinfoheader.h"


/////////////////////////////////////////////////////////////////////////////
// CCoolBitmapInfoHeader properties

long CCoolBitmapInfoHeader::GetBiWidth()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiWidth(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CCoolBitmapInfoHeader::GetBiHeight()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiHeight(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

short CCoolBitmapInfoHeader::GetBiPlanes()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiPlanes(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

short CCoolBitmapInfoHeader::GetBiBitCount()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiBitCount(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

long CCoolBitmapInfoHeader::GetBiCompression()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiCompression(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CCoolBitmapInfoHeader::GetBiSizeImage()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiSizeImage(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CCoolBitmapInfoHeader::GetBiXPelsPerMeter()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiXPelsPerMeter(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

long CCoolBitmapInfoHeader::GetBiYPelsPerMeter()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiYPelsPerMeter(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

long CCoolBitmapInfoHeader::GetBiClrUsed()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiClrUsed(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

long CCoolBitmapInfoHeader::GetBiClrImportant()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CCoolBitmapInfoHeader::SetBiClrImportant(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCoolBitmapInfoHeader operations
