#ifndef __VC_RESID_DEF_H__
#define __VC_RESID_DEF_H__

#include "mmi_data_types.h"


#ifdef _KK_SUPPORT_

#define VC_RES_STR_ID_VC_BASE			(KK_BASE + 1)
#define VC_RES_ICON_ID_VC_BASE		(KK_BASE + 1)
#define VC_RES_SCR_ID_VC_BASE			(KK_BASE + 1)


enum VC_STR_ID_ENUM_LIST
{
 VC_STR_RES_ID_BEGIN = VC_RES_STR_ID_VC_BASE,
 VIDEOCHAT_MENU_STRINGID,
 VC_STR_RES_ID_END
};

enum VC_ICON_ID_ENUM_LIST
{
    VC_ICON_RES_ID_BEGINE = VC_RES_ICON_ID_VC_BASE,

    
	IMG_VIEWCHAT_000,
	IMG_VIEWCHAT_001,
	IMG_VIEWCHAT_002,
	IMG_VIEWCHAT_CHECKBOX1,
	IMG_VIEWCHAT_CHECKBOX2,
	IMG_VIEWCHAT_WAITING,
	IMG_VIEWCHAT_SLOGO,
	IMG_VIEWCHAT_LOGO,
	IMG_VIEWCHAT_UP_ARROW,
	IMG_VIEWCHAT_DOWN_ARROW,
	//bruce091210
	IMG_VIEWCHAT_V2_KK_TITLE,
	IMG_VIEWCHAT_V2_KK_TITLE_MIDDLE,
	IMG_VIEWCHAT_V2_KK_TITLE_MINI,
	IMG_VIEWCHAT_V2_KK_VIDEO_TITLE_CH,
	IMG_VIEWCHAT_V2_KK_VIDEO_TITLE_EN,
	IMG_VIEWCHAT_V2_CHAT_WAITING,
	IMG_VIEWCHAT_V2_CHAT_WAITING_MINI,
	IMG_VIEWCHAT_V2_BUDDY_NAME,
	IMG_VIEWCHAT_V2_DURING_TIME,
	IMG_VIEWCHAT_V2_GPRS_SIG00,
	IMG_VIEWCHAT_V2_GPRS_SIG11,
	IMG_VIEWCHAT_V2_GPRS_SIG22,
	IMG_VIEWCHAT_V2_GPRS_SIG33,
	IMG_VIEWCHAT_V2_GPRS_SIG44,


    VC_ICON_RES_ID_END
};

//SCREEN ID
enum VC_SCR_ID_ENUM_LIST
{
    VC_SCR_RES_ID_BEGINE = VC_RES_SCR_ID_VC_BASE,

    SCR_ID_VIDEOCHAT_MENU,

    VC_SCR_RES_ID_END
};
#endif



#endif  /* __VC_RESID_DEF_H__ */

