/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * DataAccountEnum.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   This file is intends for ¡K.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/

#ifndef _COOLSAND_DATA_ACCOUNT_ENUM_H
#define _COOLSAND_DATA_ACCOUNT_ENUM_H

typedef enum
{
    DIAL_TYPE_ANALOGUE,
    DIAL_TYPE_ISDN
} DATA_ACCOUNT_DIAL_TYPE_ENUM;

typedef enum
{
    DATA_RATE_FOUR_EIGHT,
    DATA_RATE_NINE_SIX,
    DATA_RATE_FOURTEEN_FOUR
} DATA_ACCOUNT_DATA_RATE_ENUM;

typedef enum
{
    DATA_ACCOUNT_NAME_STR = 0,
    DATA_ACCOUNT_NAME,
    DATA_ACCOUNT_DIAL_NUMBER_STR,
    DATA_ACCOUNT_DIAL_NUMBER,
    DATA_ACCOUNT_USER_NAME_STR,
    DATA_ACCOUNT_USER_NAME,
    DATA_ACCOUNT_PASSWD_STR,
    DATA_ACCOUNT_PASSWD,
    DATA_ACCOUNT_DIAL_TYPE_STR,
    DATA_ACCOUNT_DIAL_TYPE,
    DATA_ACCOUNT_DATA_RATE_STR,
    DATA_ACCOUNT_DATA_RATE,
    DATA_ACCOUNT_DNS_ADDRESS_STR,
    DATA_ACCOUNT_DNS_ADDRESS
} DATA_ACCOUNT_INLINE;

typedef enum
{
    GPRS_DATA_ACCOUNT_NAME_STR = 0,
    GPRS_DATA_ACCOUNT_NAME,
    GPRS_DATA_ACCOUNT_APN_STR,
    GPRS_DATA_ACCOUNT_APN,
    GPRS_DATA_ACCOUNT_USER_NAME_STR,
    GPRS_DATA_ACCOUNT_USER_NAME,
    GPRS_DATA_ACCOUNT_PASSWD_STR,
    GPRS_DATA_ACCOUNT_PASSWD,
    GPRS_DATA_ACCOUNT_AUTH_TYPE_STR,
    GPRS_DATA_ACCOUNT_AUTH_TYPE,
    GPRS_DATA_ACCOUNT_DNS_ADDRESS_STR,
    GPRS_DATA_ACCOUNT_DNS_ADDRESS
} GPRS_DATA_ACCOUNT_INLINE;

#endif /* _COOLSAND_DATA_ACCOUNT_ENUM_H */ 

