/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2006
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/**************************************************************

	FILENAME	: Res_SWFlash.c

  	PURPOSE		: Populate Resource for 

 

 

	DATE		: April-10-2006

**************************************************************/
#include "stdc.h"
#include "mmi_features.h"


#include "customcfg.h"


#ifdef FIRST_PASS
#include "buildcfg.h"
#endif

#if defined(__MMI_SWFLASH__)

#include "swflashdef.h"
#include "swflashgprot.h"
#include "swflashprot.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"

/**************************************************************

	FUNCTION NAME		: PopulateSWFlashMenuList()

  	PURPOSE				: Populate the SWFlash Menu List

	INPUT PARAMETERS	: void

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

 

**************************************************************/


void PopulateSWFlashRes(void)
{
	ADD_APPLICATION_MENUITEM((SERVICES_SWFLASH_MENU_ID,MAIN_MENU_SERVICES_MENUID,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_APP,IMG_SWFLASH_APP1));

    /* Level 1 */
	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_APP,SERVICES_SWFLASH_MENU_ID,3,
		MENU_ID_SWFLASH_MONTERNET,
		MENU_ID_SWFLASH_LIST,
		MENU_ID_SWFLASH_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_APP,IMG_SWFLASH_APP2));

    /* Level 2 */
	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_MONTERNET,MENU_ID_SWFLASH_APP,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_MONTERNET,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_LIST,MENU_ID_SWFLASH_APP,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_LIST,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_SETTING,MENU_ID_SWFLASH_APP,2,
        MENU_ID_SWFLASH_SETTING_STORAGE,
        MENU_ID_SWFLASH_SETTING_DATACNT,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_SETTING,0));

    /* Level 3 */
	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_SETTING_STORAGE,MENU_ID_SWFLASH_SETTING,2,
        MENU_ID_SWFLASH_STORAGE_PHONE,
        MENU_ID_SWFLASH_STORAGE_CARD,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_SETTING_STORAGE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_SETTING_DATACNT,MENU_ID_SWFLASH_SETTING,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_SETTING_DATACNT,0));

    /* Level 4 */
	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_STORAGE_PHONE,MENU_ID_SWFLASH_SETTING_STORAGE,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_STORAGE_PHONE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_STORAGE_CARD,MENU_ID_SWFLASH_SETTING_STORAGE,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_SWFLASH_STORAGE_CARD,0));

    /* Level for FileMgr */
	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_OPTION1, 0,5,
	    MENU_ID_SWFLASH_OPTION_PLAY,
	    MENU_ID_SWFLASH_OPTION_INFO,
        MENU_FMGR_GEN_OPTION_RENAME,
        MENU_FMGR_GEN_OPTION_DELETE,
        MENU_FMGR_GEN_OPTION_FORWARD,
		SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION, 0 ));

	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_OPTION2, 0,4,
	    MENU_ID_SWFLASH_OPTION_DOWNLOAD,
	    MENU_ID_SWFLASH_OPTION_INFO,
        MENU_FMGR_GEN_OPTION_RENAME,
        MENU_FMGR_GEN_OPTION_DELETE,
		SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION, 0 ));

	ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_OPTION3, 0,3,
	    MENU_ID_SWFLASH_OPTION_PLAY,
	    MENU_ID_SWFLASH_OPTION_INFO,
        MENU_FMGR_GEN_OPTION_FORWARD,
		SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION, 0 ));

    ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_OPTION_PLAY, 0,0,
        SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION_PLAY, 0 ));

    ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_OPTION_INFO, 0,0,
        SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION_INFO, 0 ));

    ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_OPTION_DOWNLOAD, 0,0,
        SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION_DOWNLOAD, 0 ));

    ADD_APPLICATION_MENUITEM((MENU_ID_SWFLASH_EMPTY_FOLDER_OPTION, 0,0,
        SHOW, NONMOVEABLE, 0, STR_SWFLASH_OPTION, 0 ));

    /* String */
	ADD_APPLICATION_STRING2(STR_SWFLASH_APP ,"Mobile Flash","Title String for SWFlash main screen");

	ADD_APPLICATION_STRING2(STR_SWFLASH_MONTERNET ,"Monternet","Title String for Monternet");
	ADD_APPLICATION_STRING2(STR_SWFLASH_LIST ,"Flash Manager","Title String for SWFlash List");
	ADD_APPLICATION_STRING2(STR_SWFLASH_SETTING ,"Flash Setting","Title String for SWFlash Setting");
	ADD_APPLICATION_STRING2(STR_SWFLASH_PLAYBACK ,"Flash Playback","Title String for SWFlash Playback");

	ADD_APPLICATION_STRING2(STR_SWFLASH_PLAY ,"Play","String for SWFlash Play");
	ADD_APPLICATION_STRING2(STR_SWFLASH_PAUSE ,"Pause","String for SWFlash Pause");
	ADD_APPLICATION_STRING2(STR_SWFLASH_RESUME ,"Resume","String for SWFlash Resume");
	ADD_APPLICATION_STRING2(STR_SWFLASH_STOP ,"Stop","String for SWFlash Stop");

	ADD_APPLICATION_STRING2(STR_SWFLASH_SETTING_STORAGE ,"Storage","Title String for SWFlash storage");
	ADD_APPLICATION_STRING2(STR_SWFLASH_SETTING_DATACNT ,"Data Account","Title String for SWFlash data account");
	ADD_APPLICATION_STRING2(STR_SWFLASH_STORAGE_PHONE ,"Phone","Title String for Phone storage");
	ADD_APPLICATION_STRING2(STR_SWFLASH_STORAGE_CARD ,"Memory Card","Title String for Card storage");

	ADD_APPLICATION_STRING2(STR_SWFLASH_OPTION ,"Option","Title String for SWFlash Option screen");
	ADD_APPLICATION_STRING2(STR_SWFLASH_OPTION_PLAY ,"Play","Title String for SWFlash Playback screen");
	ADD_APPLICATION_STRING2(STR_SWFLASH_OPTION_INFO ,"Info","Title String for SWFlash Information screen");
	ADD_APPLICATION_STRING2(STR_SWFLASH_OPTION_DOWNLOAD ,"Download","Title String for SWFlash Download screen");

	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_TITLE ,"Title","String for SWFlash title");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY ,"Category","String for SWFlash category");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_SIZE ,"Size","String for SWFlash size");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_BYTE ,"Byte","String for SWFlash byte");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_DATE ,"Date","String for SWFlash date");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_TIME ,"Time","String for SWFlash time");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_AUTHOR ,"Author","String for SWFlash author");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_COMPANY ,"Company","String for SWFlash company");

	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_SCRSAVER ,"Screen Saver","String for SWFlash screen saver");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_ANIMATION ,"Animation","String for SWFlash animation");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_CRAZYGAME ,"Game","String for SWFlash game");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_CARDSHOW ,"Card","String for SWFlash card");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_KARAOK ,"KaraOK","String for SWFlash karaok");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_HOTMV ,"MV","String for SWFlash MV");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_MOVIECLIP ,"Scene","String for SWFlash scene");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_MOBILEINFO ,"Infomation","String for SWFlash information");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_RECREATION ,"Recreation","String for SWFlash recreation");
	ADD_APPLICATION_STRING2(STR_SWFLASH_INFO_CATEGORY_UNKNOWN ,"Unknown","String for SWFlash unknown");

	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_NO_MEMORY_CARD ,"No Memory Card",	"[Notify-No Memory Card]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_FILE_ERROR ,"File Error",	"[Notify-File Error]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_NETWORK_ERROR ,"Network Error",	"[Notify-Network Error]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_DISK_FULL ,"Disk Full",	"[Notify-Disk full]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_DISK_WRITE_PROTECT ,"Disk Write Protect",	"[Notify-Disk Write Protect]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_SOCKET_ERROR ,"Socket Error",	"[Notify-Socket Error]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_SERVER_ERROR ,"Server Error",	"[Notify-Server Error]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_HTTP_FAILED ,"HTTP Error",	"[Notify-HTTP Error]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_NOTIFY_UNKNOWN ,"Unknown Error",	"[Notify-Unknown Error]");

	ADD_APPLICATION_STRING2(STR_SWFLASH_ASK_PLAYBACK ,"Playback?",	"[Ask-Playback?]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_ASK_DOWNLOAD ,"Download?",	"[Ask-Download?]");
	ADD_APPLICATION_STRING2(STR_SWFLASH_ASK_DOWNLOAD2 ,"Download incomplete, continue?",	"[Ask-Download2?]");

    /* Image */
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_APP1,CUST_IMG_PATH"/MainLCD/SWFlash/SB_ML.bmp","IMG_SWFLASH submenu");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_APP2,CUST_IMG_PATH"/MainLCD/SWFlash/TB_ML.bmp","IMG_SWFLASH title bar");

	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CMP1,CUST_IMG_PATH"/MainLCD/SWFlash/IC_M01.CMP","Built-in SWFlash file 1");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CMP2,CUST_IMG_PATH"/MainLCD/SWFlash/IC_M02.CMP","Built-in SWFlash file 2");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CMP3,CUST_IMG_PATH"/MainLCD/SWFlash/IC_M03.CMP","Built-in SWFlash file 3");

	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT1_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_01_SCRSAVER_FULL.bmp","SWFlash category 1 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT2_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_02_ANIMATION_FULL.bmp","SWFlash category 2 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT3_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_03_CRAZYGAME_FULL.bmp","SWFlash category 3 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT4_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_04_CARDSHOW_FULL.bmp","SWFlash category 4 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT5_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_05_KARAOK_FULL.bmp","SWFlash category 5 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT6_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_06_HOTMV_FULL.bmp","SWFlash category 6 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT7_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_07_MOVIECLIP_FULL.bmp","SWFlash category 7 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT8_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_08_MOBILEINFO_FULL.bmp","SWFlash category 8 - play ok");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT9_PL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_09_RECREATION_FULL.bmp","SWFlash category 9 - play ok");

	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT1_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_01_SCRSAVER_DL.bmp","SWFlash category 1 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT2_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_02_ANIMATION_DL.bmp","SWFlash category 2 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT3_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_03_CRAZYGAME_DL.bmp","SWFlash category 3 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT4_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_04_CARDSHOW_DL.bmp","SWFlash category 4 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT5_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_05_KARAOK_DL.bmp","SWFlash category 5 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT6_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_06_HOTMV_DL.bmp","SWFlash category 6 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT7_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_07_MOVIECLIP_DL.bmp","SWFlash category 7 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT8_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_08_MOBILEINFO_DL.bmp","SWFlash category 8 - need dl");
	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_CAT9_DL,CUST_IMG_PATH"/MainLCD/SWFlash/ML_09_RECREATION_DL.bmp","SWFlash category 9 - need dl");

	ADD_APPLICATION_IMAGE2(IMG_SWFLASH_INCOMING,CUST_IMG_PATH"/MainLCD/SWFlash/ML_INCOMINGCALL.bmp","SWFlash category 9 - need dl");
}

#endif
#endif

