/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/**************************************************************

	FILENAME	: Res_.c

  	PURPOSE		: Populate Resource for 

 

 

	DATE		: August-11-2003

**************************************************************/
#include "stdc.h"
#include "customcfg.h"

#ifdef FIRST_PASS
#include "buildcfg.h"
#endif

//#include "wgui_categories.h"
#include "organizerdef.h"

#include "mmi_features.h"

#include "worldclock.h"

#include "todolistenum.h"
#include "alarmdef.h"
#include "calculator.h"
#include "unitconvertor.h"
#include "currencyconvertor.h"
#include "stopwatchdef.h"
#include "bmi.h"
#include "healthmenstural.h"
#include "profilesenum.h"
#include "servicedefs.h"
#include "phoedtstrenum.h"
#include "phoedtimgenum.h"
#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"
#include "custresdef.h"
#include "calendardef.h"
#include "todolistenum.h"
#include "alarmdef.h"

//////////////////////////////////////////////////////////////////////////////////
void PopulateOrganizerMenu(void)
{

#ifndef __MMI_STYLE_E71_QCIF_S__
ADD_APPLICATION_MENUITEM((ORGANIZER_ALARM_MENU,MAIN_MENU_ORGANIZER_MENUID,0,
				SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,ORGANIZER_MENU_ALARMS_STRINGID,ORGANIZER_MENU_ALARMS_IMAGEID));
#endif

#if defined (__MMI_MAINLCD_240X320__) 
ADD_APPLICATION_MENUITEM((ORGANIZER_CALCULATOR_MENU,MAIN_MENU_EXTRA_MENUID,0,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
				STR_ID_CALC_MENU,IMG_ID_CALC_MENU_ICON));
#else
ADD_APPLICATION_MENUITEM((ORGANIZER_CALCULATOR_MENU,MAIN_MENU_ORGANIZER_MENUID,0,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
				STR_ID_CALC_MENU,IMG_ID_CALC_MENU_ICON));
#endif
// Beginning--added by kecx for flashlight function on 20081110
#ifdef __MMI_FLASHLIGHT__
ADD_APPLICATION_MENUITEM((ORGANIZER_FLASHLIGHT_MENUID,MAIN_MENU_ORGANIZER_MENUID,2,
				ORGANIZER_FLASHLIGHT_OPEN_MENUID,
				ORGANIZER_FLASHLIGHT_CLOSE_MENUID,
				SHOW,MOVEABLEWITHINPARENT|SHORTCUTABLE, DISP_LIST,ORGANIZER_MENU_FLASHLIGHT_STRID,IMG_PROFILES_OUTDOOR));
ADD_APPLICATION_MENUITEM((ORGANIZER_FLASHLIGHT_OPEN_MENUID,ORGANIZER_FLASHLIGHT_MENUID,0,
				SHOW,MOVEABLEWITHINPARENT, DISP_LIST,ORGANIZER_FLASHLIGHT_OPEN_STRID,0));
ADD_APPLICATION_MENUITEM((ORGANIZER_FLASHLIGHT_CLOSE_MENUID,ORGANIZER_FLASHLIGHT_MENUID,0,
				SHOW,MOVEABLEWITHINPARENT, DISP_LIST,ORGANIZER_FLASHLIGHT_CLOSE_STRID,0));
#endif
// end--added by kecx for flashlight function on 20081110
ADD_APPLICATION_MENUITEM((ORGANIZER_CALENDER_MENU,MAIN_MENU_ORGANIZER_MENUID,3,
				MENU_GOTO_TASK_CAL,
				MENU_ID_CLNDR_JUMP_TO_DATE,
				MENU_CAL_TYPE,
				SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,ORGANIZER_MENU_CALENDER_STRINGID,ORGANIZER_MENU_CALENDER_IMAGEID));
#if defined(__MMI_UNIT_CONVERTER__)
ADD_APPLICATION_MENUITEM((ORGANIZER_UNITCONVERTOR_MENU,MAIN_MENU_ORGANIZER_MENUID,2,		
				ORGANIZER_UNITCONVERTOR_WEIGHT,
				ORGANIZER_UNITCONVERTOR_LENGTH,
				SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,ORGANIZER_MENU_UNITSCONVERTOR_STRINGID,ORGANIZER_MENU_UNITSCONVERTOR_IMAGEID));
#endif
#if defined(__MMI_CURRENCY_CONVERTER__)
ADD_APPLICATION_MENUITEM((ORGANIZER_CURRENCYCONVERTOR_MENU,MAIN_MENU_ORGANIZER_MENUID, 0,
				SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,ORGANIZER_MENU_CURRENCYCONVERTOR_STRINGID,ORGANIZER_MENU_CURRENCYCONVERTOR_IMAGEID));
#endif
#if defined(__MMI_BMI__)
#if defined (__MMI_MAINLCD_240X320__) 
ADD_APPLICATION_MENUITEM((ORGANIZER_HEALTH_MENU,MAIN_MENU_EXTRA_MENUID,2,
				ORGANIZER_HEALTH_MENU_BMI,
				ORGANIZER_HEALTH_MENU_MENSTRUAL,
				SHOW,MOVEABLEACROSSPARENT,DISP_LIST,STR_SCR_HEALTH_CAPTION,ORGANIZER_MENU_HEALTH_IMAGEID));
#else
ADD_APPLICATION_MENUITEM((ORGANIZER_HEALTH_MENU,MAIN_MENU_ORGANIZER_MENUID,2,
				ORGANIZER_HEALTH_MENU_BMI,
				ORGANIZER_HEALTH_MENU_MENSTRUAL,
				SHOW,MOVEABLEACROSSPARENT,DISP_LIST,STR_SCR_HEALTH_CAPTION,ORGANIZER_MENU_HEALTH_IMAGEID));
#endif
	    
ADD_APPLICATION_MENUITEM((ORGANIZER_HEALTH_MENU_BMI,ORGANIZER_HEALTH_MENU,0,
				SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,EXTRA_HEALTH_MENU_BMI_STRINGID,0));
ADD_APPLICATION_MENUITEM((ORGANIZER_HEALTH_MENU_MENSTRUAL,ORGANIZER_HEALTH_MENU,0,
				SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,EXTRA_HEALTH_MENU_MENSTRUAL_STRINGID,0));
#endif
	
#ifdef __MMI_WORLDCLOCK_DST__
ADD_APPLICATION_MENUITEM((MENU_ID_WC_DST_OPT, 0,1,
                MENU_ID_WC_DST_SETTING,
                SHOW, NONMOVEABLE, DISP_LIST,STR_WORLD_CLOCK_DST_FOREIGN, 0));
ADD_APPLICATION_MENUITEM((MENU_ID_WC_DST_SETTING, MENU_ID_WC_DST_OPT,0,
                SHOW, NONMOVEABLE, DISP_LIST,STR_WORLD_CLOCK_DST_FOREIGN, 0));
#endif
#if defined(__MMI_UNIT_CONVERTER__)
ADD_APPLICATION_MENUITEM((ORGANIZER_UNITCONVERTOR_WEIGHT,ORGANIZER_UNITCONVERTOR_MENU,0,
				SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_UNITCONVERTOR_WEIGHT,0));
ADD_APPLICATION_MENUITEM((ORGANIZER_UNITCONVERTOR_LENGTH,ORGANIZER_UNITCONVERTOR_MENU,0,
				SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_UNITCONVERTOR_LENGTH,0));
#endif
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_APP,MAIN_MENU_ORGANIZER_MENUID, 0,
				SHOW, MOVEABLEACROSSPARENT|SHORTCUTABLE, 1, STR_ID_PHOART_APP, IMG_ID_PHOART_APP_ICON));	



ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_CLIP, 
										0,
										#ifdef __MMI_SUBLCD__
											3,
										#else
											2,
										#endif /* __MMI_SUBLCD__ */
										
										MENU_ID_PHOART_AUTO_RESIZE,
										MENU_ID_PHOART_MAINLCD_CLIP,

										#ifdef __MMI_SUBLCD__
											MENU_ID_PHOART_SUBLCD_CLIP,
										#endif /* __MMI_SUBLCD__ */	
																				
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_ID_PHOART_CLIP,
										0));		


ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_AUTO_RESIZE, MENU_ID_PHOART_CLIP, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_AUTO_RESIZE, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_MAINLCD_CLIP, MENU_ID_PHOART_CLIP, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_MAINLCD_CLIP, 0));	
	
	#ifdef __MMI_SUBLCD__
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_SUBLCD_CLIP, MENU_ID_PHOART_CLIP, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_SUBLCD_CLIP, 0));	
	#endif /* __MMI_SUBLCD__ */	



ADD_APPLICATION_MENUITEM((	MENU_ID_PHOART_OPTION, 
										0,
									#ifndef __MMI_TOUCH_SCREEN__										
										7, //9
									#else
										6, //8
									#endif
										MENU_ID_PHOART_SAVE_AS,
/*Guojian Del Start For no this feature Ver: GreenStone  on 2008-8-30 17:10 */
										#if 0
										MENU_ID_PHOART_ADD_EFFECT,
										#endif
/*Guojian Del End  For no this feature Ver: GreenStone  on 2008-8-30 17:10 */
										MENU_ID_PHOART_ADD_FRAME,
										MENU_ID_PHOART_ADD_ICON,
										MENU_ID_PHOART_ADD_TEXT,
/*Guojian Del Start For no this feature Ver: GreenStone  on 2008-9-3 16:23 */
										#if 0
										MENU_ID_PHOART_ADJUST_OPTION,
										#endif
/*Guojian Del End  For no this feature Ver: GreenStone  on 2008-9-3 16:23 */
										MENU_ID_PHOART_FLIP,
										MENU_ID_PHOART_EXPAND_CANVAS,
									#ifndef __MMI_TOUCH_SCREEN__
										MENU_ID_PHOART_HELP,
									#endif
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_ID_PHOART_CLIP,
										0));	
	
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_SAVE_AS, MENU_ID_PHOART_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_SAVE_AS, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_ADD_ICON, MENU_ID_PHOART_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_ADD_ICON, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_ADD_TEXT, MENU_ID_PHOART_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_ADD_TEXT, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EXPAND_CANVAS, MENU_ID_PHOART_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EXPAND_CANVAS, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_HELP, MENU_ID_PHOART_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_HELP, 0));


	/* editor option screen */
ADD_APPLICATION_MENUITEM((	MENU_ID_PHOART_EDITOR_OPTION, 
										0,
										3,
										MENU_ID_PHOART_EDITOR_DONE,
										MENU_ID_PHOART_EDITOR_CANCEL,
										MENU_ID_PHOART_EDITOR_INPUT,
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_GLOBAL_OPTIONS,
										0));	


ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EDITOR_DONE, MENU_ID_PHOART_EDITOR_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_GLOBAL_DONE, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EDITOR_CANCEL, MENU_ID_PHOART_EDITOR_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_GLOBAL_CANCEL, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EDITOR_INPUT, MENU_ID_PHOART_EDITOR_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_GLOBAL_INPUT_METHOD, 0));

	/* add effect */
ADD_APPLICATION_MENUITEM((	MENU_ID_PHOART_ADD_EFFECT, 
										MENU_ID_PHOART_OPTION,
										PHOART_EFFECT_COUNT,
										
										#ifdef PHOART_FEATURE_EFFECT_GRAYSCALE
											MENU_ID_PHOART_EFFECT_GRAYSCALE,
										#endif
										
										#ifdef PHOART_FEATURE_EFFECT_SEPIA
											MENU_ID_PHOART_EFFECT_SEPIA,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_SEPIA_GREEN
											MENU_ID_PHOART_EFFECT_SEPIA_GREEN,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_SEPIA_BLUE
											MENU_ID_PHOART_EFFECT_SEPIA_BLUE,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_COLOR_INVERT
											MENU_ID_PHOART_EFFECT_COLOR_INVERT,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_GRAY_INVERT
											MENU_ID_PHOART_EFFECT_GRAY_INVERT,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_WATER_COLOR
											MENU_ID_PHOART_EFFECT_WATER_COLOR,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_LIGHT_BLUR
											MENU_ID_PHOART_EFFECT_LIGHT_BLUR,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_BLUR
											MENU_ID_PHOART_EFFECT_BLUR,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_STRONG_BLUR
											MENU_ID_PHOART_EFFECT_STRONG_BLUR,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_UNSHARP
											MENU_ID_PHOART_EFFECT_UNSHARP,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_SHARPEN
											MENU_ID_PHOART_EFFECT_SHARPEN,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_MORE_SHARPEN
											MENU_ID_PHOART_EFFECT_MORE_SHARPEN,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_MEDIAN
											MENU_ID_PHOART_EFFECT_MEDIAN,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_DILATION
											MENU_ID_PHOART_EFFECT_DILATION,
										#endif

										#ifdef PHOART_FEATURE_EFFECT_EROSION
											MENU_ID_PHOART_EFFECT_EROSION,
										#endif
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_ID_PHOART_ADD_EFFECT,
										0));	

	#ifdef PHOART_FEATURE_EFFECT_GRAYSCALE
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_GRAYSCALE, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_GRAYSCALE, 0));
	#endif /* PHOART_FEATURE_EFFECT_GRAYSCALE */

	#ifdef PHOART_FEATURE_EFFECT_SEPIA
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_SEPIA, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_SEPIA, 0));
	#endif /* PHOART_FEATURE_EFFECT_SEPIA */

	#ifdef PHOART_FEATURE_EFFECT_SEPIA_GREEN
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_SEPIA_GREEN, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_SEPIA_GREEN, 0));
	#endif /* PHOART_FEATURE_EFFECT_SEPIA_GREEN */

	#ifdef PHOART_FEATURE_EFFECT_SEPIA_BLUE
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_SEPIA_BLUE, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_SEPIA_BLUE, 0));
	#endif /* PHOART_FEATURE_EFFECT_SEPIA_BLUE */

	#ifdef PHOART_FEATURE_EFFECT_COLOR_INVERT
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_COLOR_INVERT, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_COLOR_INVERT, 0));
	#endif /* PHOART_FEATURE_EFFECT_COLOR_INVERT */

	#ifdef PHOART_FEATURE_EFFECT_GRAY_INVERT
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_GRAY_INVERT, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_GRAY_INVERT, 0));
	#endif /* PHOART_FEATURE_EFFECT_GRAY_INVERT */

	#ifdef PHOART_FEATURE_EFFECT_WATER_COLOR
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_WATER_COLOR, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_WATER_COLOR, 0));
	#endif /* PHOART_FEATURE_EFFECT_WATER_COLOR */
	
	#ifdef  PHOART_FEATURE_EFFECT_LIGHT_BLUR 
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_LIGHT_BLUR, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_LIGHT_BLUR, 0));
	#endif /* PHOART_FEATURE_EFFECT_LIGHT_BLUR */

	#ifdef PHOART_FEATURE_EFFECT_BLUR
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_BLUR, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_BLUR, 0));
	#endif /* PHOART_FEATURE_EFFECT_BLUR */
	
	#ifdef PHOART_FEATURE_EFFECT_STRONG_BLUR
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_STRONG_BLUR, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_STRONG_BLUR, 0));
	#endif /* PHOART_FEATURE_EFFECT_STRONG_BLUR */

	#ifdef PHOART_FEATURE_EFFECT_UNSHARP
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_UNSHARP, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_UNSHARP, 0));
	#endif /* PHOART_FEATURE_EFFECT_UNSHARP */

	#ifdef PHOART_FEATURE_EFFECT_SHARPEN
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_SHARPEN, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_SHARPEN, 0));
	#endif /* PHOART_FEATURE_EFFECT_SHARPEN */
	
	#ifdef PHOART_FEATURE_EFFECT_MORE_SHARPEN
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_MORE_SHARPEN, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_MORE_SHARPEN, 0));
	#endif /* PHOART_FEATURE_EFFECT_MORE_SHARPEN */

	#ifdef PHOART_FEATURE_EFFECT_MEDIAN
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_MEDIAN, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_MEDIAN, 0));
	#endif /* PHOART_FEATURE_EFFECT_MEDIAN */

	#ifdef PHOART_FEATURE_EFFECT_DILATION
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_DILATION, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_DILATION, 0));	
	#endif /* PHOART_FEATURE_EFFECT_DILATION */

	#ifdef  PHOART_FEATURE_EFFECT_EROSION 
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_EFFECT_EROSION, MENU_ID_PHOART_ADD_EFFECT, 0,
						SHOW, NONMOVEABLE, 1, STR_ID_PHOART_EFFECT_EROSION, 0));			
	#endif /* PHOART_FEATURE_EFFECT_EROSION */


	/* add frame */
ADD_APPLICATION_MENUITEM((	MENU_ID_PHOART_ADD_FRAME, 
										MENU_ID_PHOART_OPTION,
										/*Guojian Modify Start For don't support so many menus Ver: GreenStone  on 2008-8-30 11:28 */
										2, //10
										/*Guojian Modify End  For don't support so many menus Ver: GreenStone  on 2008-8-30 11:28 */
										MENU_ID_PHOART_FRAME_1,
										MENU_ID_PHOART_FRAME_2,
/*Guojian Del Start For don't support so many menus  Ver: GreenStone  on 2008-8-30 11:26 */
										#if 0
										MENU_ID_PHOART_FRAME_3,
										MENU_ID_PHOART_FRAME_4,
										MENU_ID_PHOART_FRAME_5,
										MENU_ID_PHOART_FRAME_6,
										MENU_ID_PHOART_FRAME_7,
										MENU_ID_PHOART_FRAME_8,
										MENU_ID_PHOART_FRAME_9,
										MENU_ID_PHOART_FRAME_10,
										#endif
/*Guojian Del End  For don't support so many menus Ver: GreenStone  on 2008-8-30 11:26 */
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_ID_PHOART_ADD_FRAME,
										0));	


ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_1, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_1, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_2, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_2, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_3, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_3, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_4, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_4, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_5, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_5, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_6, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_6, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_7, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_7, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_8, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_8, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_9, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_9, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FRAME_10, MENU_ID_PHOART_ADD_FRAME, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FRAME_10, 0));




	/* text editor option */
ADD_APPLICATION_MENUITEM((	MENU_ID_PHOART_TEXT_EDITOR_OPTION, 
										0,
										3,
										MENU_ID_PHOART_TEXT_EDITOR_DONE,
										MENU_ID_PHOART_TEXT_EDITOR_CANCEL,
										MENU_ID_PHOART_TEXT_EDITOR_INPUT,
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_GLOBAL_OPTIONS,
										0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_TEXT_EDITOR_DONE, MENU_ID_PHOART_TEXT_EDITOR_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_GLOBAL_DONE, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_TEXT_EDITOR_CANCEL, MENU_ID_PHOART_TEXT_EDITOR_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_GLOBAL_CANCEL, 0));	

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_TEXT_EDITOR_INPUT, MENU_ID_PHOART_TEXT_EDITOR_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_GLOBAL_INPUT_METHOD, 0));
	

	/* adjust */
ADD_APPLICATION_MENUITEM((	MENU_ID_PHOART_ADJUST_OPTION, 
										MENU_ID_PHOART_OPTION,
										2,
										MENU_ID_PHOART_ADJUST_IMAGE_ADJUST,
										MENU_ID_PHOART_ADJUST_COLOR_ADJUST,										
										SHOW,
										NONMOVEABLE,
										DISP_LIST,
										STR_ID_PHOART_ADJUST,
										0));	
	
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_ADJUST_IMAGE_ADJUST, MENU_ID_PHOART_ADJUST_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_ADJUST_IMAGE, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_ADJUST_COLOR_ADJUST, MENU_ID_PHOART_ADJUST_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_ADJUST_COLOR, 0));


	/* flip */
ADD_APPLICATION_MENUITEM((MENU_ID_PHOART_FLIP, MENU_ID_PHOART_OPTION, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_PHOART_FLIP, 0));	

	
	/************* Scene Master **************/
ADD_APPLICATION_MENUITEM((MENU_ID_SCENMAST_APP, MENU_ID_PHOEDT_APP, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_SCENMAST_APP, 0));
	
	
	/************* Image Tile **************/
ADD_APPLICATION_MENUITEM((MENU_ID_IMGTILE_APP, MENU_ID_PHOEDT_APP, 0,
					SHOW, NONMOVEABLE, DISP_LIST, STR_ID_IMGTILE_APP, IMG_ID_IMGTILE_APP));	


	
	/************* Slide Show **************/
ADD_APPLICATION_MENUITEM((MENU_ID_SLIDSHOW_APP, MENU_ID_PHOEDT_APP, 0,
					SHOW, NONMOVEABLE, 1, STR_ID_SLIDSHOW_APP, IMG_ID_SLIDSHOW_APP));	

}


void PopulateOrganizerRes(void)
{
	PopulateOrganizerMenu();
	ADD_APPLICATION_IMAGE2(ORGANIZER_TITLE_IMAGEID,CUST_IMG_PATH"/MainLCD/Titlebar/TB_OR.png","Icon for Title of Organizer Screen.");
#ifdef __MMI_CALENDAR__
	ADD_APPLICATION_IMAGE2(ORGANIZER_MENU_CALENDER_IMAGEID,CUST_IMG_PATH"/MainLCD/Calendar/SB_OCDAR.gif","Icon for  Calender Menu.");
#endif
#ifdef __MMI_TODOLIST__
	ADD_APPLICATION_IMAGE2(ORGANIZER_MENU_TODOLIST_IMAGEID,CUST_IMG_PATH"/MainLCD/ToDoList/SB_OLIST.gif","Icon for To Do List Menu.");
#endif
	ADD_APPLICATION_IMAGE2(ORGANIZER_MENU_ALARMS_IMAGEID,CUST_IMG_PATH"/MainLCD/Alarm/SB_OAM.gif","Icon for Alams Options Menu.");

#if defined (__MMI_WORLD_CLOCK__)
	ADD_APPLICATION_IMAGE2(ORGANIZER_MENU_WORLDCLOCK_IMAGEID,CUST_IMG_PATH"/MainLCD/Worldclock/SB_WORLD.gif","Icon for World Clock  Menu.");
#endif

	ADD_APPLICATION_STRING2(ORGANIZER_TITLE_STRINGID,"Organizer","Title of Organizer Screen.");

#ifdef __MMI_CALENDAR__
 	ADD_APPLICATION_STRING2(ORGANIZER_MENU_CALENDER_STRINGID,"Calendar","To Go to Calendar Screen.");
#endif
	
#ifdef __MMI_TODOLIST__
	ADD_APPLICATION_STRING2(ORGANIZER_MENU_TODOLIST_STRINGID,"To Do List","To Go to  To Do List Screen.");
#endif	
 	ADD_APPLICATION_STRING2(ORGANIZER_MENU_ALARMS_STRINGID,"Alarms","To Go to Alarms Screen.");

#if defined (__MMI_WORLD_CLOCK__)
	ADD_APPLICATION_STRING2(ORGANIZER_MENU_WORLDCLOCK_STRINGID,"World Clock","To Go to World Clock Screen.");
#endif

#ifdef __MMI_FLASHLIGHT__
      ADD_APPLICATION_STRING2(ORGANIZER_MENU_FLASHLIGHT_STRID, "Flashlight", "Flashlight");
      ADD_APPLICATION_STRING2(ORGANIZER_FLASHLIGHT_OPEN_STRID, "Open", "Open");
      ADD_APPLICATION_STRING2(ORGANIZER_FLASHLIGHT_CLOSE_STRID, "Close", "Close");
#endif

#if 0
#ifdef __MMI_CALENDAR_V2__

    ADD_APPLICATION_MENUITEM((ORGANIZER_CALENDER_MENU,MAIN_MENU_ORGANIZER_MENUID, 
                                                    #ifdef __MMI_CLNDR_WEEKLY_VIEW_SUPPORT__
                                                        2,
                                                    #else
                                                        1,
                                                    #endif
                                                        ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,
                                                    #ifdef __MMI_CLNDR_WEEKLY_VIEW_SUPPORT__
                                                        ORGANIZER_CALENDER_WEEKLY_OPTIONS_MENU,
                                                    #endif
                                                        SHOW,
                                                        MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
                                                        ORGANIZER_MENU_CALENDER_STRINGID,ORGANIZER_MENU_CALENDER_IMAGEID));    

                                                    
    /* monthly options */
    ADD_APPLICATION_MENUITEM((ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,ORGANIZER_CALENDER_MENU,
                                                    CLNDR_OPTIONS_TOTAL,
                                               #ifdef __MMI_TODOLIST__ 
                                                    MENU_GOTO_TASK_CAL,
                                                    MENU_ID_CLNDR_ADD_TASK,
                                                #endif
                                                    MENU_ID_CLNDR_JUMP_TO_DATE,
                                                #ifdef __MMI_CLNDR_WEEKLY_VIEW_SUPPORT__    
                                                    MENU_ID_CLNDR_WEEKLY_VIEW,
                                                #endif
                                                    MENU_CAL_TYPE,
                                                    SHOW,
                                                    MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
                                                    ORGANIZER_MENU_CALENDER_STRINGID,ORGANIZER_MENU_CALENDER_IMAGEID));    

#ifdef __MMI_CLNDR_WEEKLY_VIEW_SUPPORT__
    /* weeksly options */                                                            
    ADD_APPLICATION_MENUITEM((ORGANIZER_CALENDER_WEEKLY_OPTIONS_MENU,ORGANIZER_CALENDER_MENU,
                                                    CLNDR_OPTIONS_TOTAL,
                                               #ifdef __MMI_TODOLIST__ 
                                                    MENU_GOTO_TASK_CAL,
                                                    MENU_ID_CLNDR_ADD_TASK,
                                                #endif
                                                    MENU_ID_CLNDR_JUMP_TO_DATE,
                                                    MENU_ID_CLNDR_MONTHLY_VIEW,
                                                    MENU_CAL_TYPE,
                                                    SHOW,
                                                    MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
                                                    ORGANIZER_MENU_CALENDER_STRINGID,ORGANIZER_MENU_CALENDER_IMAGEID));                                                    
#endif                                                
#else
#ifdef __MMI_TODOLIST__
	ADD_APPLICATION_MENUITEM((ORGANIZER_CALENDER_MENU,MAIN_MENU_ORGANIZER_MENUID,
	3,
	MENU_GOTO_TASK_CAL,
	MENU_ID_CLNDR_JUMP_TO_DATE,
	MENU_CAL_TYPE,
	SHOW,
	MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
		ORGANIZER_MENU_CALENDER_STRINGID,ORGANIZER_MENU_CALENDER_IMAGEID));
#else
	ADD_APPLICATION_MENUITEM((ORGANIZER_CALENDER_MENU,MAIN_MENU_ORGANIZER_MENUID,
	2,
	MENU_ID_CLNDR_JUMP_TO_DATE,
	MENU_CAL_TYPE,
	SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
		ORGANIZER_MENU_CALENDER_STRINGID,ORGANIZER_MENU_CALENDER_IMAGEID));

#endif

#endif
#endif

#ifdef __MMI_TODOLIST__
	ADD_APPLICATION_MENUITEM((ORGANIZER_TODOLIST_MENU,MAIN_MENU_ORGANIZER_MENUID,0,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
		ORGANIZER_MENU_TODOLIST_STRINGID,ORGANIZER_MENU_TODOLIST_IMAGEID));
#endif


#if defined (__MMI_WORLD_CLOCK__)
#if defined(__MMI_WORLD_CLOCK_SUBLCD_SETTING__)
	ADD_APPLICATION_MENUITEM((ORGANIZER_WORLDCLOCK_MENU,MAIN_MENU_ORGANIZER_MENUID,2,MITEM_WORLDCLOCK_BROWSECITY,MITEM_WORLDCLOCK_SUBLCDDISPLAY,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
		ORGANIZER_MENU_WORLDCLOCK_STRINGID,ORGANIZER_MENU_WORLDCLOCK_IMAGEID));
#else
	ADD_APPLICATION_MENUITEM((ORGANIZER_WORLDCLOCK_MENU,MAIN_MENU_ORGANIZER_MENUID,1,MITEM_WORLDCLOCK_BROWSECITY,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,
		ORGANIZER_MENU_WORLDCLOCK_STRINGID,ORGANIZER_MENU_WORLDCLOCK_IMAGEID));
#endif
#endif

#if defined (__MMI_WORLD_CLOCK__)
	mod_mmiPopulateWClockData();
#endif
}


#if defined (__MMI_WORLD_CLOCK__)
void mod_mmiPopulateWClockData(void)
{		
#if defined(__MMI_WCLOCK_CITY_LIST_2__)
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_NONE,"None","No City");	
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY1,"Abu Dhabi","Abu Dhabi");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY2,"Amsterdam","Amsterdam");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY3,"Anchorage","Anchorage");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY4,"Athens","Athens");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY5,"Bangkok","Bangkok");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY6,"Beijing","Beijing");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY7,"Berlin","Berlin");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY8,"Cairo","Cairo");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY9,"Cape Town","Cape Town");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY10,"Chicago","Chicago");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY11,"Dublin","Dublin");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY12,"Ho Chi Minh City","Ho Chi Minh City");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY13,"Hong Kong","Hong Kong");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY14,"Honolulu","Honolulu");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY15,"Jakata","Jakata");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY16,"Jerusalem","Jerusalem");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY17,"Kuala Lumpur","Kuala Lumpur");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY18,"Las Vegas","Las Vegas");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY19,"London","London");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY20,"Los Angeles","Los Angeles");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY21,"Madrid","Madrid");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY22,"Manila","Manila");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY23,"Mexico City","Mexico City");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY24,"Miami","Miami");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY25,"Montreal","Montreal");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY26,"Moscow","Moscow");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY27,"New Delhi","New Delhi");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY28,"New York","New York");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY29,"Paris","Paris");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY30,"Rio","Rio");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY31,"Rome","Rome");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY32,"San Fran.","San Fran.");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY33,"Singapore","Singapore");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY34,"Sydney","Sydney");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY35,"Taipei","Taipei");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY36,"Toronto","Toronto");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY37,"Vancouver","Vancouver");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY38,"Washington","Washington");
#elif defined(__MMI_WCLOCK_CITY_LIST_1__) || defined(__MMI_WCLOCK_CITY_LIST_3__) || defined(__MMI_WCLOCK_CITY_LIST_4__)
	/* populate city name */
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_NONE,"None","No City");	
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY1, "AbuDhabi", "AbuDhabi");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY2, "Amsterdam", "Amsterdam");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY3, "Apia", "Apia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY4, "Athens", "Athens");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY5, "Auckland", "Auckland");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY6, "Anchorage", "Anchorage");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY7, "Bangkok", "Bangkok");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY8, "Beijing", "Beijing");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY9, "Berlin", "Berlin");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY10, "Bogota", "Bogota");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY11, "Brasilia", "Brasilia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY12, "Brisbane", "Brisbane");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY13, "Brussels", "Brussels");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY14, "Bucharest", "Bucharest");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY15, "Budapest", "Budapest");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY16, "BuenosAires", "BuenosAires");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY17, "Cairo", "Cairo");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY18, "Canberra", "Canberra");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY19, "CapeTown", "CapeTown");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY20, "Casablanca", "Casablanca");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY21, "Central Atlantic", "Central Atlantic");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY22, "Chicago", "Chicago");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY23, "Copenhagen", "Copenhagen");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY24, "Dhaka", "Dhaka");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY25, "EasterIsland", "EasterIsland");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY26, "Geneva", "Geneva");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY27, "Guam", "Guam");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY28, "HongKong", "HongKong");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY29, "Honolulu", "Honolulu");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY30, "Islamabad", "Islamabad");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY31, "Istanbul", "Istanbul");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY32, "Jakarta", "Jakarta");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY33, "Johannesburg", "Johannesburg");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY34, "Kabul", "Kabul");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY35, "Kathmandu", "Kathmandu");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY36, "Kiev", "Kiev");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY37, "KualaLumpur", "KualaLumpur");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY38, "Kwajalein", "Kwajalein");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY39, "LaPaz", "LaPaz");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY40, "Lisbon", "Lisbon");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY41, "London", "London");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY42, "LosAngeles", "LosAngeles");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY43, "Luxembourg", "Luxembourg");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY44, "Madrid", "Madrid");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY45, "Manila", "Manila");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY46, "Melbourne", "Melbourne");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY47, "MexicoCity", "MexicoCity");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY48, "Montreal", "Montreal");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY49, "Moscow", "Moscow");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY50, "NewDelhi", "NewDelhi");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY51, "NewYork", "NewYork");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY52, "Norfolklsland", "Norfolklsland");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY53, "Paris", "Paris");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY54, "Phoenix", "Phoenix");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY55, "Polynesia", "Polynesia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY56, "Prague", "Prague");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY57, "Praia", "Praia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY58, "Rabat", "Rabat");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY59, "Rome", "Rome");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY60, "SanFrancisco", "SanFrancisco");
	#if 0
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY61, "Santiago", "Santiago");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY62, "Singapore", "Singapore");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY63, "Sofia", "Sofia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY64, "Solomon", "Solomon");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY65, "Stockholm", "Stockholm");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY66, "Sydney", "Sydney");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY67, "Taipei", "Taipei");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY68, "Tehran", "Tehran");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY69, "Tokyo", "Tokyo");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY70, "Tonga", "Tonga");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY71, "Vancouver", "Vancouver");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY72, "Vienna", "Vienna");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY73, "Vladivostok", "Vladivostok");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY74, "Warsaw", "Warsaw");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY75, "Wellington", "Wellington");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY76, "Yan-Gon", "Yan-Gon");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY77, "Zurich", "Zurich");
	#endif

#endif

	/* populate abbreviation of city name */	
#if defined(__MMI_WCLOCK_CITY_LIST_2__)
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE_NONE,"None","No City");	
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE1,"AUH","Abu Dhabi");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE2,"AMS","Amsterdam");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE3,"ATH","Athens");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE4,"AKL","Auckland");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE5,"BKK","Bangkok");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE6,"BEJ","Beijing");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE7,"BER","Berlin");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE8,"BOG","Bogota");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE9,"BSB","Brasilia");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE10,"BRU","Brussels");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE11,"BUH","Bucharest");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE12,"BUD","Budapest");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE13,"CAI","Cairo");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE14,"CBR","Canberra");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE15,"CPT","Cape Town");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE16,"CAS","Casablanca");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE17,"CGX","Chicago");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE18,"CPH","Copenhagen");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE19,"GVA","Geneva");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE20,"GUM","Guam");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE21,"HKG","Hong Kong");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE22,"HNL","Honolulu");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE23,"IST","Istanbul");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE24,"JKT","Jakarta");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE25,"JNB","Johannesburg");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE26,"KIE","Kiev");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE27,"KUL","Kuala Lumpur");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE28,"LIS","Lisbon");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE29,"LON","London");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE30,"LAX","Los Angeles");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE31,"LUX","Luxembourg");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE32,"MAD","Madrid");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE33,"MNL","Manila");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE34,"MEX","MexicoCity");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE35,"MON","Montreal");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE36,"MOW","Moscow");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE37,"DEL","New Delhi");
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE38,"NYC","New York");
#elif defined(__MMI_WCLOCK_CITY_LIST_1__) || defined(__MMI_WCLOCK_CITY_LIST_3__) || defined(__MMI_WCLOCK_CITY_LIST_4__)
	ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE_NONE,"None","No City");	
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE1, "AUH", "AbuDhabi");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE2, "AMS", "Amsterdam");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE3, "APW", "Apia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE4, "ATH", "Athens");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE5, "AKL", "Auckland");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE6, "MRI", "Anchorage");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE7, "BKK", "Bangkok");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE8, "BEJ", "Beijing");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE9, "BER", "Berlin");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE10, "BOG", "Bogota");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE11, "BSB", "Brasilia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE12, "Brisbane", "Brisbane");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE13, "BRU", "Brussels");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE14, "BUH", "Bucharest");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE15, "BUD", "Budapest");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE16, "BuenosAires", "BuenosAires");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE17, "CAI", "Cairo");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE18, "CBR", "Canberra");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE19, "CPT", "CapeTown");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE20, "CAS", "Casablanca");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE21, "Central Atlantic", "Central Atlantic");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE22, "CGX", "Chicago");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE23, "CPH", "Copenhagen");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE24, "DAC", "Dhaka");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE25, "EasterIsland", "EasterIsland");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE26, "GVA", "Geneva");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE27, "GUM", "Guam");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE28, "HKG", "HongKong");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE29, "HNL", "Honolulu");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE30, "Islamabad", "Islamabad");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE31, "IST", "Istanbul");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE32, "JKT", "Jakarta");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE33, "JNB", "Johannesburg");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE34, "Kabul", "Kabul");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE35, "Kathmandu", "Kathmandu");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE36, "KIE", "Kiev");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE37, "KUL", "KualaLumpur");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE38, "KWA", "Kwajalein");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE39, "LaPaz", "LaPaz");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE40, "LIS", "Lisbon");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE41, "LON", "London");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE42, "LAX", "LosAngeles");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE43, "LUX", "Luxembourg");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE44, "MAD", "Madrid");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE45, "MNL", "Manila");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE46, "Melbourne", "Melbourne");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE47, "MEX", "MexicoCity");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE48, "MON", "Montreal");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE49, "MOW", "Moscow");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE50, "DEL", "NewDelhi");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE51, "NYC", "NewYork");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE52, "Norfolklsland", "Norfolklsland");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE53, "PAR", "Paris");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE54, "PHX", "Phoenix");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE55, "Polynesia", "Polynesia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE56, "PRG", "Prague");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE57, "RAI", "Praia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE58, "RBA", "Rabat");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE59, "ROM", "Rome");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE60, "SFO", "SanFrancisco");
	#if 0
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE61, "SCL", "Santiago");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE62, "SIN", "Singapore");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE63, "SOF", "Sofia");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE64, "Sol", "Solomon");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE65, "STH", "Stockholm");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE66, "SYD", "Sydney");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE67, "TPE", "Taipei");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE68, "THR", "Tehran");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE69, "TKY", "Tokyo");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE70, "Tonga", "Tonga");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE71, "VAC", "Vancouver");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE72, "VIE", "Vienna");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE73, "VVO", "Vladivostok");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE74, "WAW", "Warsaw");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE75, "WLG", "Wellington");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE76, "Yan-Gon", "Yan-Gon");
    ADD_APPLICATION_STRING2(STR_WCLOCK_CITY_ABBRE77, "ZRH", "Zurich");
	#endif

#endif
#ifdef __MMI_WORLD_CLOCK__	
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_TITLE,"World Clock","World Clock");
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_MENU1,"Browse City","Browse City");
#endif

#ifdef __MMI_WORLD_CLOCK__	
#if defined(__MMI_WORLD_CLOCK_SUBLCD_SETTING__)
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_MENU2,"Sub LCD Display","sublcd display");
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_CITY1,"City 1","first city on sublcd");
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_CITY2,"City 2","second city on sublcd");
	ADD_APPLICATION_STRING2(STR_WORLD_SELECT_CITY,"Select City","select city frm list");
#endif	

	ADD_APPLICATION_IMAGE2(SUN_ICON,CUST_IMG_PATH"/MainLCD/WorldClock/DAY.gif","Sun Image");
	ADD_APPLICATION_IMAGE2(MOON_ICON,CUST_IMG_PATH"/MainLCD/WorldClock/NIGHT.gif","Moon Image");

#ifdef __MMI_TOUCH_SCREEN__  
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_IMAGE1,CUST_IMG_PATH"/MainLCD/WorldClock/map01.jpg","Worldmap Image");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_IMAGE2,CUST_IMG_PATH"/MainLCD/WorldClock/map01.jpg","Worldmap Image");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_IMAGE3,CUST_IMG_PATH"/MainLCD/WorldClock/map01.jpg","Worldmap Image");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_LEFT_ARROW_UP,CUST_IMG_PATH"/MAINLCD/WorldClock/TH_WUpL.bmp","WorldClock left arrow up");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_LEFT_ARROW_DOWN,CUST_IMG_PATH"/MAINLCD/WorldClock/TH_WDownL.bmp","WorldClock left arrow down");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_RIGHT_ARROW_UP,CUST_IMG_PATH"/MAINLCD/WorldClock/TH_WDUpR.bmp","WorldClock right arrow up");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_RIGHT_ARROW_DOWN,CUST_IMG_PATH"/MAINLCD/WorldClock/TH_WDownR.bmp","WorldClock right arrow down");
#else
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_IMAGE1,CUST_IMG_PATH"/MainLCD/WorldClock/map01.jpg","Worldmap Image");
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_IMAGE2,CUST_IMG_PATH"/MainLCD/WorldClock/map02.jpg","Worldmap Image");	
	ADD_APPLICATION_IMAGE2(WORLD_CLOCK_IMAGE3,CUST_IMG_PATH"/MainLCD/WorldClock/map03.jpg","Worldmap Image");
#endif
#if defined(__MMI_WORLD_CLOCK_SUBLCD_SETTING__)
	ADD_APPLICATION_MENUITEM((MITEM_WORLDCLOCK_BROWSECITY,ORGANIZER_WORLDCLOCK_MENU,0,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,STR_WORLD_CLOCK_MENU1,0));
#else
	ADD_APPLICATION_MENUITEM((MITEM_WORLDCLOCK_BROWSECITY,ORGANIZER_WORLDCLOCK_MENU,0,SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,DISP_LIST,STR_WORLD_CLOCK_TITLE,0));
#endif
#endif


#if defined(__MMI_WORLD_CLOCK_SUBLCD_SETTING__)
	ADD_APPLICATION_MENUITEM((MITEM_WORLDCLOCK_SUBLCDDISPLAY,ORGANIZER_WORLDCLOCK_MENU,2,MITEM_WORLDCLOCK_SUBLCDDISPLAY_CITY1,MITEM_WORLDCLOCK_SUBLCDDISPLAY_CITY2,SHOW,NONMOVEABLE,DISP_LIST,STR_WORLD_CLOCK_MENU2,0));
	ADD_APPLICATION_MENUITEM((MITEM_WORLDCLOCK_SUBLCDDISPLAY_CITY1,MITEM_WORLDCLOCK_SUBLCDDISPLAY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_WORLD_CLOCK_CITY1,0));
	ADD_APPLICATION_MENUITEM((MITEM_WORLDCLOCK_SUBLCDDISPLAY_CITY2,MITEM_WORLDCLOCK_SUBLCDDISPLAY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_WORLD_CLOCK_CITY2,0));
#endif

#ifdef __MMI_WORLDCLOCK_DST__
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_DST_FOREIGN,"Daylight Saving Time for Foreign City", "World Clock DST Setting String");
	ADD_APPLICATION_STRING2(STR_WORLD_CLOCL_DST_TITLE,"Daylight Saving Time", "World Clock DST Setting Title");

   ADD_APPLICATION_MENUITEM ((MENU_ID_WC_DST_OPT, 0,
                                    1,
                                    MENU_ID_WC_DST_SETTING,
                                    SHOW, NONMOVEABLE, DISP_LIST,
                                    STR_WORLD_CLOCK_DST_FOREIGN, 0));

   ADD_APPLICATION_MENUITEM ((MENU_ID_WC_DST_SETTING, MENU_ID_WC_DST_OPT,
                                    0,
                                    SHOW, NONMOVEABLE, DISP_LIST,
                                    STR_WORLD_CLOCK_DST_FOREIGN, 0));
#endif
#ifdef __MMI_WC_TZ_SUPPORT__
    ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_LOCAL,"Local  ", "local city");
    ADD_APPLICATION_STRING2(STR_WORLD_CLOCK_GMT,"GMT", "GMT");
#endif

}
#endif //__MMI_WORLD_CLOCK__

#endif


