/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	  PhoEdtMenuEnum.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   Photo Editor Menu Enum 
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

	/******** Start of ID ********/
	
	/* Photo Editor */
	MENU_ID_PHOEDT_APP,  //1738

	/* Photo Art */
	MENU_ID_PHOART_APP,  //1739
	MENU_ID_PHOART_CLIP,//1740
	MENU_ID_PHOART_AUTO_RESIZE,	//1741
	MENU_ID_PHOART_VIEW,	//1742
	MENU_ID_PHOART_MAINLCD_CLIP,	//1743
	MENU_ID_PHOART_SUBLCD_CLIP,	//1744
	MENU_ID_PHOART_OPTION,	//1745
	MENU_ID_PHOART_SAVE_AS,	//1746
	MENU_ID_PHOART_ADD_EFFECT,	//1747
	MENU_ID_PHOART_ADD_FRAME,	//1748
	MENU_ID_PHOART_ADD_ICON,	//1749
	MENU_ID_PHOART_ADD_TEXT,	//1750
	MENU_ID_PHOART_ADJUST_OPTION,	//1751
	MENU_ID_PHOART_FLIP,	//1752
	MENU_ID_PHOART_EXPAND_CANVAS,	//1753 
	MENU_ID_PHOART_HELP,	//1754

	MENU_ID_PHOART_EDITOR_OPTION,
	MENU_ID_PHOART_EDITOR_DONE,
	MENU_ID_PHOART_EDITOR_CANCEL,
	MENU_ID_PHOART_EDITOR_INPUT,

	MENU_ID_PHOART_EFFECT_GRAYSCALE,
	MENU_ID_PHOART_EFFECT_SEPIA,
	MENU_ID_PHOART_EFFECT_SEPIA_GREEN,
	MENU_ID_PHOART_EFFECT_SEPIA_BLUE,
	MENU_ID_PHOART_EFFECT_COLOR_INVERT,
	MENU_ID_PHOART_EFFECT_GRAY_INVERT,
	MENU_ID_PHOART_EFFECT_WATER_COLOR,
	MENU_ID_PHOART_EFFECT_LIGHT_BLUR,
	MENU_ID_PHOART_EFFECT_BLUR,
	MENU_ID_PHOART_EFFECT_STRONG_BLUR,
	MENU_ID_PHOART_EFFECT_UNSHARP,
	MENU_ID_PHOART_EFFECT_SHARPEN,
	MENU_ID_PHOART_EFFECT_MORE_SHARPEN,
	MENU_ID_PHOART_EFFECT_MEDIAN,
	MENU_ID_PHOART_EFFECT_DILATION,
	MENU_ID_PHOART_EFFECT_EROSION,
 
	MENU_ID_PHOART_FRAME_1,
	MENU_ID_PHOART_FRAME_2,
	MENU_ID_PHOART_FRAME_3,
	MENU_ID_PHOART_FRAME_4,
	MENU_ID_PHOART_FRAME_5,
	MENU_ID_PHOART_FRAME_6,
	MENU_ID_PHOART_FRAME_7,
	MENU_ID_PHOART_FRAME_8,
	MENU_ID_PHOART_FRAME_9,
	MENU_ID_PHOART_FRAME_10,

	MENU_ID_PHOART_TEXT_EDITOR_OPTION,
	MENU_ID_PHOART_TEXT_EDITOR_DONE,
	MENU_ID_PHOART_TEXT_EDITOR_CANCEL,
	MENU_ID_PHOART_TEXT_EDITOR_INPUT,

	MENU_ID_PHOART_ADJUST_IMAGE_ADJUST,
	MENU_ID_PHOART_ADJUST_COLOR_ADJUST,
	
 	
	/* Scene Master */
	MENU_ID_SCENMAST_APP,

	
	/* Image Tile */	
	MENU_ID_IMGTILE_APP,

	
	/* Slide Show */	
	MENU_ID_SLIDSHOW_APP,


	
	/******** End of ID ********/


