/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *	vObjectsMenuItems.h
 *
 * Project:
 * --------
 * 
 *
 * Description:
 * ------------
 *    This file is for vObjects related Menu IDs
 *
 * Author:
 * -------
 * -------
*****************************************************************************/
MENU_ID_VCARD_FORWARD_OPTION,// 1798
MENU_ID_VCARD_FORWARD_SMS,// 1799通过短信Send By SMS
MENU_ID_VCARD_FORWARD_MMS,
MENU_ID_VCARD_FORWARD_IRDA,
MENU_ID_VCARD_FORWARD_BT,		//Renwy add for BT 2008/09/11
MENU_ID_VCARD_FORWARD_EMAIL,
MENU_ID_VCARD_FORWARD_FMGR,// 1803存到文件Send To File
MENU_ID_VCARD_ENTER_FILENAME_OPT,
MENU_ID_VCARD_ENTER_FILENAME_OPT_DONE,
MENU_ID_VCARD_ENTER_FILENAME_OPT_INPUT_METHOD,
MENU_ID_VCARD_RECV_OPTION,
MENU_ID_VCARD_RECV_OPTION_TO_SIM,
MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM,
MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM3,
MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM4,
MENU_ID_VCARD_RECV_OPTION_TO_PHONE,
MENU_ID_VCARD_RECV_OPTION_FMGR,
MENU_VCLNDR_FORWARD,
MENU_VCLNDR_FORWARE_NO_SIM,
MENU_VCLNDR_SEND_BY_SMS,
MENU_VCLNDR_SEND_BY_MMS,
MENU_VCLNDR_SEND_BY_IRDA,
MENU_VCLNDR_SEND_BY_BT,	//Renwy add for bt 2008/09/11
MENU_VCLNDR_SEND_BY_EMAIL,
MENU_VCLNDR_SEND_BY_FILEMGR,
MENU_VCLNDR_FILENAME_OPT,
MENU_VCLNDR_OPT_DONE,
MENU_VCLNDR_OPT_INPUT_METHOD,
MENU_VCLNDR_RECV_OPTION,
MENU_VCLNDR_RECV_OPT_TDL,
MENU_VCLNDR_RECV_OPT_FMGR,

