/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  OutgoingCmStrIDDef.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

#ifndef OUTGOINGCMSTRIDDEF_H
#define OUTGOINGCMSTRIDDEF_H

STR_SCR1001_RUNNING	,
STR_SCR1001_IP_CALLING,
STR_SCR1002_RSK		,
STR_SCR1002_2RSK	,
STR_SCR1004_CAPTION	,
STR_SCR1004_RUNNING	,
STR_SCR1005_CAPTION	,
STR_SCR1005_RUNNING	,
STR_SCR1006_CAPTION	,
STR_SCR1006_RUNNING	,
STR_SCR1007_CAPTION	,
STR_SCR1007_RUNNING	,
STR_SCR1008_CAPTION	,
STR_SCR1008_RUNNING	,
STR_SCR1009_CAPTION	,
STR_SCR1010_CAPTION	,
STR_SCR1010_RUNNING	,
STR_MITEM2010_CM_ACTIVE_HOLD	,
STR_MITEM2011_CM_S_ACTIVE_END	,
STR_MITEM2030_CM_NEWCALL		,
STR_MITEM2031_CM_PBOOK			,
STR_MITEM2032_CM_SMS			,
STR_MITEM2012_CM_HELD_RETRIEVE	,
STR_MITEM2013_CM_S_HELD_END		,
STR_MITEM2014_CM_CALL_SWAP		,
STR_MITEM2015_CM_CALL_CONFER	,
STR_MITEM2016_CM_ALL_CALL_END	,
STR_MITEM2017_CM_CALL_TRANSFER	,
STR_MITEM2018_CM_CALL_SPLIT		,
STR_MITEM2019_CM_ALL_ACTIVE_END	,
STR_MITEM2020_CM_ALL_HELD_END	,
STR_MITEM2020_CM_MUTE			,
STR_MITEM2021_CM_NEWCALL		,
STR_MITEM2022_CM_VOICE_MEMO		,
STR_MITEM2026_CM_SOUND_RECORDER,
STR_MITEM2023_CM_LOUDSP			,
STR_MITEM2024_CM_DTMF			,
STR_MITEM2025_CM_AUDIO_PLAYER			,
STR_SCR1002_LOUDSP_H_FREE_RSK	,
STR_SCR1002_LOUDSP_H_HELD_RSK	,
STR_SCR1002_CAPTION				,
OUT_SCR_NFY_STR					,
STR_MITEM2041_CM_DROP 			,
STR_SCR1002_RETRIEVE_RSK		,
STR_SCR1002_HOLD_RSK			,
STR_SCR1002_SWAP_RSK			,
STR_MITEM2011_CM_S_ACTIVE_END_RETRIEVE 	,
DTMF_RSK_STR					,
STR_ECT_NFY_CAPTION				,
STR_ECT_NFY_LSK					,
STR_ECT_NFY_RUNNING				,
STR_DTMF_SCR_DISPLAY_ID			,
STR_MITEM2011_CM_S_END			,
STR_MITEM2050_CM_END_HELD_ENDALL_HELD,
STR_MITEM2011_CM_END,
STR_MITEM2010_CM_M_ACTIVE_HOLD,
STR_MITEM2012_CM_M_HELD_RETRIEVE,
STR_MITEM2011_CM_END_ALL,
STR_MITEM2011_CM_END_SINGLE,
STR_NFY_LOUDSPEAKER_ON ,
STR_NFY_LOUDSPEAKER_OFF,
STR_ACTION_DONE,
STR_REJECT
#endif


