/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2001
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   IMEres.c.c
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *   This file implements IME Resource for multi-load.
 *
 * Author:
 * -------
 *   Terry Yang  (CSD00866)
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Log:   O:/PSI_MMI/archives/2___work/Soft_11.13/soft/mmi_customer/CustResource/src/IMERes.c-arc  $
 * 
 *    Rev 1.4   Mar 02 2007 13:06:36   lin
 * 由于我们现在项目上没有智能英文输入法,所以我们需要进行添加
 * 
 *    Rev 1.3   Nov 30 2006 11:04:16   lin
 * 恢复CSW更新前的版本
 * 
 *    Rev 1.1   Nov 24 2006 18:44:32   lin
 * No change.
 * 
 *    Rev 1.0   Nov 13 2006 15:29:22   zhangxb
 * Initial revision.
 * Revision 1.1.1.1  2006/08/02 02:23:24  sushipeng
 * del .h in the include
 *
 * Revision 1.1.1.1  2006/07/22 08:00:46  sushipeng
 * second change new platform 
 * ssp 20060722
 *
 * Revision 1.1.1.1  2006/07/19 03:49:10  sushipeng
 * change coolsand platform
 * ssp 20060719
 *
 * Revision 1.2  2006/06/21 07:12:20  wangbei
 * Update Resource
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#include "mmi_features.h"
#include "imeres.h"

// __CUSTPACK_MULTIBIN     Terry   BEGIN

#if defined(__MMI_T9__)
#include "imerest9.h"
#elif defined(__MMI_ZI__)
#include "imereszi.h"
#else
const sIMELDBDetails CSD_gIMELDBArray[]={0};
#endif

const sIMEModeDetails CSD_gIMEModeArray[] =
{
	/*Multitap ABC*/
	{
		INPUT_MODE_MULTITAP_UPPERCASE_ABC,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE,
		STR_INPUT_METHOD_MENU_MULTITAP_ABC,
		STR_INPUT_METHOD_MULTITAP_U_ABC,
		1
	},

	/*Multitap abc*/
	{
		INPUT_MODE_MULTITAP_LOWERCASE_ABC,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE,
		STR_INPUT_METHOD_MENU_MULTITAP_abc,
		STR_INPUT_METHOD_MULTITAP_L_ABC,
		1
	},

	/*INPUT_MODE_123*/
	{
		INPUT_MODE_123,
		INPUT_TYPE_NUMERIC_CHANGEABLE,
		STR_INPUT_METHOD_MENU_NUMERIC,
		STR_INPUT_METHOD_NUMERIC,
		1
	},
	
//french set english flag --qiff bug 12987
	#if defined(__MMI_MULTITAP_FRENCH__)
	{
		INPUT_MODE_MULTITAP_UPPERCASE_FRENCH,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_MULTITAP_U_FRENCH,
		STR_INPUT_METHOD_MULTITAP_U_FRENCH,
		1
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_FRENCH,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_FRENCH,
		STR_INPUT_METHOD_MULTITAP_L_FRENCH,
		1
	},
	#endif

	#if defined(__MMI_MULTITAP_MYANMAR__)
	{
		INPUT_MODE_MULTITAP_MYANMAR,
		INPUT_TYPE_MMI_MULTITAP_MYANMAR,
		STR_INPUT_METHOD_MENU_MULTITAP_MYANMAR,
		STR_INPUT_METHOD_MULTITAP_MYANMAR,
		0
		
	},
	#endif

	#if defined(__MMI_MULTITAP_RUSSIAN__)
//russian set english flag --qiff bug 12987
	{
		INPUT_MODE_MULTITAP_UPPERCASE_RUSSIAN,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_U_RUSSIAN,
		STR_INPUT_METHOD_MULTITAP_U_RUSSIAN,
		1
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_RUSSIAN,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_RUSSIAN,
		STR_INPUT_METHOD_MULTITAP_L_RUSSIAN,
		1
	},
	#endif
	#if defined (__MMI_MULTITAP_THAI__)
//thai set english flag --qiff bug 12987
	{
		INPUT_MODE_MULTITAP_THAI,
		INPUT_TYPE_ALPHANUMERIC_MULTITAP_THAI,
		STR_INPUT_METHOD_MENU_MULTITAP_THAI,
		STR_INPUT_METHOD_MULTITAP_THAI,
		1
	},
	#endif
	#if defined(__MMI_MULTITAP_VIETNAMESE__)
//vientnamese set english flag --qiff bug 12987
	{
		INPUT_MODE_MULTITAP_UPPERCASE_VIETNAMESE,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_MULTITAP_U_VIETNAMESE,
		STR_INPUT_METHOD_MULTITAP_U_VIETNAMESE,
		0
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_VIETNAMESE,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_MULTITAP_L_VIETNAMESE,
		STR_INPUT_METHOD_MULTITAP_L_VIETNAMESE,
		0
	},
#endif

#if defined(__MMI_GB__)
#if defined(__MMI_GB_SMART_PORTUGUESE__)
//portuguese set english flag --qiff bug 12987
	{
		INPUT_MODE_SMART_UPPERCASE_PORTUGUESE,
		INPUT_TYPE_SMART_UPPERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_SMART_U_PORTUGUESE,
		STR_INPUT_METHOD_SMART_U_PORTUGUESE,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_PORTUGUESE,
		INPUT_TYPE_SMART_LOWERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_SMART_L_PORTUGUESE,
		STR_INPUT_METHOD_SMART_L_PORTUGUESE,
		0
	},
#endif
#ifdef __MMI_SMART_ENGLISH__
	/*Smart Upper ABC*/
	{
		INPUT_MODE_SMART_UPPERCASE_ABC,
		INPUT_TYPE_SMART_UPPERCASE_ABC,  
		STR_INPUT_METHOD_MENU_SMART_ABC,
		STR_INPUT_METHOD_SMART_U_ABC,
		1 //modified by zhoumn@2007/07/31 0->1
	},
	/*Smart Lower ABC*/
	{
		INPUT_MODE_SMART_LOWERCASE_ABC,
		INPUT_TYPE_SMART_LOWERCASE_ABC,  
		STR_INPUT_METHOD_MENU_SMART_abc,
		STR_INPUT_METHOD_SMART_L_ABC,
		1 //modified by zhoumn@2007/07/31 0->1
	},
#endif
	#if defined(__MMI_SMART_FRENCH__)
//french set english flag --qiff bug 12987
	{
		INPUT_MODE_SMART_UPPERCASE_FRENCH,
		INPUT_TYPE_SMART_UPPERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_SMART_U_FRENCH,
		STR_INPUT_METHOD_SMART_U_FRENCH,
		1
	},
	{
		INPUT_MODE_SMART_LOWERCASE_FRENCH,
		INPUT_TYPE_SMART_LOWERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_SMART_L_FRENCH,
		STR_INPUT_METHOD_SMART_L_FRENCH,
		1
	},
	#endif
// beginning--added by kecx for adding italian on 20081223
	#if defined(__MMI_SMART_ITALIAN__)
//italian set english flag --qiff bug 12987
	{
		INPUT_MODE_SMART_UPPERCASE_ITALIAN,
		INPUT_TYPE_SMART_UPPERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_SMART_U_ITALIAN,
		STR_INPUT_METHOD_SMART_U_ITALIAN,
		1
	},
	{
		INPUT_MODE_SMART_LOWERCASE_ITALIAN,
		INPUT_TYPE_SMART_LOWERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_SMART_L_ITALIAN,
		STR_INPUT_METHOD_SMART_L_ITALIAN,
		1
	},
	#endif
// end--added by kecx for adding italian on 20081223
	#if defined(__MMI_SMART_RUSSIAN__)
//russian set english flag --qiff bug 12987
	{
		INPUT_MODE_SMART_UPPERCASE_RUSSIAN,
		INPUT_TYPE_SMART_UPPERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_SMART_U_RUSSIAN,
		STR_INPUT_METHOD_SMART_U_RUSSIAN,
		1
	},
	{
		INPUT_MODE_SMART_LOWERCASE_RUSSIAN,
		INPUT_TYPE_SMART_LOWERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_SMART_L_RUSSIAN,
		STR_INPUT_METHOD_SMART_L_RUSSIAN,
		1
	},
	#endif


	#if defined(__MMI_SMART_THAI__)
//thai set english flag --qiff bug 12987
	{
		INPUT_MODE_SMART_THAI,
		INPUT_TYPE_SMART_THAI,
		STR_INPUT_METHOD_MENU_SMART_THAI,
		STR_INPUT_METHOD_SMART_THAI,
		1
	},
	#endif
	#if defined(__MMI_SMART_VIETNAMESE__)
//vietnamese set english flag --qiff bug 12987
	{
		INPUT_MODE_SMART_UPPERCASE_VIETNAMESE,
		INPUT_TYPE_SMART_UPPERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_SMART_U_VIETNAMESE,
		STR_INPUT_METHOD_SMART_U_VIETNAMESE,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_VIETNAMESE,
		INPUT_TYPE_SMART_LOWERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_SMART_L_VIETNAMESE,
		STR_INPUT_METHOD_SMART_L_VIETNAMESE,
		0
	},
	#endif
	#if defined(__MMI_SMART_ARABIC__)
	{
		INPUT_MODE_SMART_ARABIC,
		INPUT_TYPE_SMART_ARABIC,
		STR_INPUT_METHOD_MENU_SMART_ARABIC,
		STR_INPUT_METHOD_SMART_ARABIC,
		0
	},
	#endif
	#if defined(__MMI_SMART_PERSIAN__)
	{
		INPUT_MODE_SMART_PERSIAN,
		INPUT_TYPE_SMART_PERSIAN,
		STR_INPUT_METHOD_MENU_SMART_PERSIAN,
		STR_INPUT_METHOD_SMART_PERSIAN,
		0
	},
	#endif
	#if defined(__MMI_SMART_BENGALI__)
	{
		INPUT_MODE_SMART_BENGALI,
		INPUT_TYPE_SMART_BENGALI,
		STR_INPUT_METHOD_MENU_SMART_BENGALI,
		STR_INPUT_METHOD_SMART_BENGALI,
		0
	},
	#endif
	#if defined(__MMI_SMART_URDU__)
	{
		INPUT_MODE_SMART_URDU,
		INPUT_TYPE_SMART_URDU,
		STR_INPUT_METHOD_MENU_SMART_URDU,
		STR_INPUT_METHOD_SMART_URDU,
		0
	},
	#endif
	#if defined(__MMI_SMART_PUNJABI__)
	{
		INPUT_MODE_SMART_PUNJABI,
		INPUT_TYPE_SMART_PUNJABI,
		STR_INPUT_METHOD_MENU_SMART_PUNJABI,
		STR_INPUT_METHOD_SMART_PUNJABI,
		0
	},
	#endif
	#if defined(__MMI_SMART_TELUGU__)
	{
		INPUT_MODE_SMART_TELUGU,
		INPUT_TYPE_SMART_TELUGU,
		STR_INPUT_METHOD_MENU_SMART_TELUGU,
		STR_INPUT_METHOD_SMART_TELUGU,
		0
	},
	#endif
	#if defined(__MMI_SMART_TAMIL__)
	{
		INPUT_MODE_SMART_TAMIL,
		INPUT_TYPE_SMART_TAMIL,
		STR_INPUT_METHOD_MENU_SMART_TAMIL,
		STR_INPUT_METHOD_SMART_TAMIL,
		0,
	},
	#endif
	#if defined(__MMI_SMART_HINDI__)			//guoyt added for adding smart hindi ime
	{
		INPUT_MODE_SMART_HINDI,
		INPUT_TYPE_SMART_HINDI,
		STR_INPUT_METHOD_MENU_SMART_HINDI,
		STR_INPUT_METHOD_SMART_HINDI,
		0
	},
	
	#endif
	#if defined(__MMI_LANG_SM_CHINESE__)
		/*Smart Pinyin*/
	{
		INPUT_MODE_SM_PINYIN,
		INPUT_TYPE_SM_PINYIN,
		STR_INPUT_METHOD_MENU_PINYIN,
		STR_INPUT_METHOD_PINYIN,
		0
	},
#ifndef __MMI_FULL_KEYPAD__
	/*Simplified Chinese Stroke*/
	{
		INPUT_MODE_SM_STROKE,
		INPUT_TYPE_SM_STROKE,
		STR_INPUT_METHOD_MENU_SIMPLIFIED_CHINESE_STROKE,
		STR_INPUT_METHOD_SM_STROKE,
		0
	},
#endif	
	#endif
#if defined(__MMI_LANG_TR_CHINESE__)
	/*Smart Pinyin*/
	{
		INPUT_MODE_TR_BOPOMO,
		INPUT_TYPE_TR_BOPOMO,
		STR_INPUT_METHOD_MENU_BOPOMO,
		STR_INPUT_METHOD_BPMF,
		0
	},
#endif


#endif

#if defined(__MMI_MULTITAP_TAMIL__)
	{
		INPUT_MODE_MMI_MULTITAP_TAMIL,
		INPUT_TYPE_MMI_MULTITAP_TAMIL,
		STR_INPUT_METHOD_MENU_MULTITAP_TAMIL,
		STR_INPUT_METHOD_MULTITAP_TAMIL,
		0
	},
#endif

#if defined(__MMI_MULTITAP_SPANISH__)
//portuguese set english flag --qiff bug 12987
	/*Multitap SPANISH*/
	{
		INPUT_MODE_MULTITAP_UPPERCASE_SPANISH,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_MULTITAP_U_SPANISH,
		STR_INPUT_METHOD_MULTITAP_U_SPANISH,
		1
	},

	/*Multitap spanish*/
	{
		INPUT_MODE_MULTITAP_LOWERCASE_SPANISH,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_SPANISH,
		STR_INPUT_METHOD_MULTITAP_L_SPANISH,
		1
	},
#endif
//PMT VIKASG START 20050729
#if defined(__MMI_MULTITAP_DANISH__)
	/*Multitap DANISH*/         //Danish-Vikas
	{
		INPUT_MODE_MULTITAP_UPPERCASE_DANISH,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_DANISH,
		STR_INPUT_METHOD_MENU_MULTITAP_U_DANISH,
		STR_INPUT_METHOD_MULTITAP_U_DANISH,
		0
	},

	/*Multitap danish*/
	{
		INPUT_MODE_MULTITAP_LOWERCASE_DANISH,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_DANISH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_DANISH,
		STR_INPUT_METHOD_MULTITAP_L_DANISH,
		0
	},
#endif
//PMT VIKASG END 20050729


#if defined(__MMI_MULTITAP_GERMAN__)
//portuguese set english flag --qiff bug 12987

	{
		INPUT_MODE_MULTITAP_UPPERCASE_GERMAN,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_MULTITAP_U_GERMAN,
		STR_INPUT_METHOD_MULTITAP_U_GERMAN,
		1
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_GERMAN,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_GERMAN,
		STR_INPUT_METHOD_MULTITAP_L_GERMAN,
		1
	},
#endif

#if defined(__MMI_MULTITAP_ITALIAN__)
//portuguese set english flag --qiff bug 12987

	{
		INPUT_MODE_MULTITAP_UPPERCASE_ITALIAN,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_U_ITALIAN,
		STR_INPUT_METHOD_MULTITAP_U_ITALIAN,
		1
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_ITALIAN,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_ITALIAN,
		STR_INPUT_METHOD_MULTITAP_L_ITALIAN,
		1
	},
#endif



#if defined(__MMI_MULTITAP_TURKISH__)
	{
		INPUT_MODE_MULTITAP_UPPERCASE_TURKISH,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_MULTITAP_U_TURKISH,
		STR_INPUT_METHOD_MULTITAP_U_TURKISH,
		0
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_TURKISH,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_TURKISH,
		STR_INPUT_METHOD_MULTITAP_L_TURKISH,
		0
	},
#endif


#if defined(__MMI_MULTITAP_URDU__)
	{
		INPUT_MODE_MMI_MULTITAP_URDU,
		INPUT_TYPE_MMI_MULTITAP_URDU,
		STR_INPUT_METHOD_MENU_MULTITAP_URDU,
		STR_INPUT_METHOD_MULTITAP_URDU,
		0
	},
#endif


#if defined(__MMI_SMART_TURKISH__)
	{
		INPUT_MODE_SMART_UPPERCASE_TURKISH,
		INPUT_TYPE_SMART_UPPERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_SMART_U_TURKISH,
		STR_INPUT_METHOD_SMART_U_TURKISH,
		1
	},
	{
		INPUT_MODE_SMART_LOWERCASE_TURKISH,
		INPUT_TYPE_SMART_LOWERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_SMART_L_TURKISH,
		STR_INPUT_METHOD_SMART_L_TURKISH,
		1
	},
#endif

#if defined(__MMI_MULTITAP_PORTUGUESE__)
//portuguese set english flag --qiff bug 12987

	{
		INPUT_MODE_MULTITAP_UPPERCASE_PORTUGUESE,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_MULTITAP_U_PORTUGUESE,
		STR_INPUT_METHOD_MULTITAP_U_PORTUGUESE,
		1
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_PORTUGUESE,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_MULTITAP_L_PORTUGUESE,
		STR_INPUT_METHOD_MULTITAP_L_PORTUGUESE,
		1
	},
#endif

#if defined(__MMI_MULTITAP_INDONESIAN__)
	{
		INPUT_MODE_MULTITAP_UPPERCASE_INDONESIAN,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_U_INDONESIAN,
		STR_INPUT_METHOD_MULTITAP_U_INDONESIAN,
		0
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_INDONESIAN,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_INDONESIAN,
		STR_INPUT_METHOD_MULTITAP_L_INDONESIAN,
		0
	},
#endif
#if defined(__MMI_SMART_INDONESIAN__)
	{
		INPUT_MODE_SMART_UPPERCASE_INDONESIAN,
		INPUT_TYPE_SMART_UPPERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_SMART_U_INDONESIAN,
		STR_INPUT_METHOD_SMART_U_INDONESIAN,
		1
	},
	{
		INPUT_MODE_SMART_LOWERCASE_INDONESIAN,
		INPUT_TYPE_SMART_LOWERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_SMART_L_INDONESIAN,
		STR_INPUT_METHOD_SMART_L_INDONESIAN,
		1
	},
#endif

#if defined(__MMI_MULTITAP_MALAY__)
	{
		INPUT_MODE_MULTITAP_UPPERCASE_MALAY,
		INPUT_TYPE_ALPHANUMERIC_UPPERCASE_MALAY,
		STR_INPUT_METHOD_MENU_MULTITAP_U_MALAY,
		STR_INPUT_METHOD_MULTITAP_U_MALAY,
		0
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_MALAY,
		INPUT_TYPE_ALPHANUMERIC_LOWERCASE_MALAY,
		STR_INPUT_METHOD_MENU_MULTITAP_L_MALAY,
		STR_INPUT_METHOD_MULTITAP_L_MALAY,
		0
	},
#endif
#if defined(__MMI_SMART_MALAY__)
	{
		INPUT_MODE_SMART_UPPERCASE_MALAY,
		INPUT_TYPE_SMART_UPPERCASE_MALAY,
		STR_INPUT_METHOD_MENU_SMART_U_MALAY,
		STR_INPUT_METHOD_SMART_U_MALAY,
		1
	},
	{
		INPUT_MODE_SMART_LOWERCASE_MALAY,
		INPUT_TYPE_SMART_LOWERCASE_MALAY,
		STR_INPUT_METHOD_MENU_SMART_L_MALAY,
		STR_INPUT_METHOD_SMART_L_MALAY,
		1
	},
#endif


#if defined(__MMI_T9_ENGLISH__)||defined(__MMI_ZI_PRC_ENGLISH__)||defined(__MMI_ZI_UK_ENGLISH__)||defined(__MMI_ITAP_ENGLISH__)
	/*Smart ABC*/
	{
		INPUT_MODE_SMART_UPPERCASE_ABC,
		INPUT_TYPE_SMART_UPPERCASE_ABC,
		STR_INPUT_METHOD_MENU_SMART_ABC,
		STR_INPUT_METHOD_SMART_U_ABC,
		1
	},

	/*Smart abc*/
	{
		INPUT_MODE_SMART_LOWERCASE_ABC,
		INPUT_TYPE_SMART_LOWERCASE_ABC,
		STR_INPUT_METHOD_MENU_SMART_abc,
		STR_INPUT_METHOD_SMART_L_ABC,
		1
	},
#endif

#if defined(__MMI_T9_TR_CHINESE__)||defined(__MMI_ZI_TR_CHINESE__)||defined(__MMI_ITAP_TR_CHINESE__)
#if defined(__MMI_T9_MULTITAP_PHONETIC_INPUT__)||defined(__MMI_ZI_MULTITAP_PHONETIC_INPUT__)||defined(__MMI_ITAP_MULTITAP_PHONETIC_INPUT__)
	/*Multitap Bopomofo*/
	{
		INPUT_MODE_TR_MULTITAP_BOPOMO,
		INPUT_TYPE_TR_MULTITAP_BOPOMO,
		STR_INPUT_METHOD_MENU_MULTITAP_BOPOMO,
		STR_INPUT_METHOD_MULTITAP_BPMF,
		0
	},
#endif
#if !defined(__MMI_TOUCH_SCREEN__)
	/*Traditional Chinese Stroke*/
	{
		INPUT_MODE_TR_STROKE,
		INPUT_TYPE_TR_STROKE,
		STR_INPUT_METHOD_MENU_TRADITIONAL_CHINESE_STROKE,
		STR_INPUT_METHOD_TR_STROKE,
		0
	},
#endif
#if (defined(__MMI_T9_SMART_PHONETIC_INPUT__) && defined(__MMI_T9_AMB_BPMF_INPUT__))||defined(__MMI_ZI_SMART_PHONETIC_INPUT__)||defined(__MMI_ITAP_SMART_PHONETIC_INPUT__)
	/*Smart Bopomofo*/
	{
		INPUT_MODE_TR_BOPOMO,
		INPUT_TYPE_TR_BOPOMO,
		STR_INPUT_METHOD_MENU_BOPOMO,
		STR_INPUT_METHOD_BPMF,
		0
	},
#endif
#endif

#if defined(__MMI_T9_SM_CHINESE__)||defined(__MMI_ZI_SM_CHINESE__)||defined(__MMI_ITAP_SM_CHINESE__)
#if defined(__MMI_T9_MULTITAP_PHONETIC_INPUT__)||defined(__MMI_ZI_MULTITAP_PHONETIC_INPUT__)||defined(__MMI_ITAP_MULTITAP_PHONETIC_INPUT__)
	/*Multitap Pinyin*/
	{
		INPUT_MODE_SM_MULTITAP_PINYIN,
		INPUT_TYPE_SM_MULTITAP_PINYIN,
		STR_INPUT_METHOD_MENU_MULTITAP_PINYIN,
		STR_INPUT_METHOD_MULTITAP_PINYIN,
		0
	},
#endif
#if !defined(__MMI_TOUCH_SCREEN__)
	/*Simplified Chinese Stroke*/
	{
		INPUT_MODE_SM_STROKE,
		INPUT_TYPE_SM_STROKE,
		STR_INPUT_METHOD_MENU_SIMPLIFIED_CHINESE_STROKE,
		STR_INPUT_METHOD_SM_STROKE,
		0
	},
#endif
#if defined(__MMI_T9_SMART_PHONETIC_INPUT__)||defined(__MMI_ZI_SMART_PHONETIC_INPUT__)||defined(__MMI_ITAP_SMART_PHONETIC_INPUT__)
	/*Smart Pinyin*/
	{
		INPUT_MODE_SM_PINYIN,
		INPUT_TYPE_SM_PINYIN,
		STR_INPUT_METHOD_MENU_PINYIN,
		STR_INPUT_METHOD_PINYIN,
		0
	},
#endif
#endif
#if defined(__MMI_KA__)
	/*Simplified Chinese Stroke*/
	{
		INPUT_MODE_SM_STROKE,
		INPUT_TYPE_SM_STROKE,
		STR_INPUT_METHOD_MENU_SIMPLIFIED_CHINESE_STROKE,
		STR_INPUT_METHOD_SM_STROKE,
		0
	},
	/*Smart Pinyin*/
	{
		INPUT_MODE_SM_PINYIN,
		INPUT_TYPE_SM_PINYIN,
		STR_INPUT_METHOD_MENU_PINYIN,
		STR_INPUT_METHOD_PINYIN,
		0
	},
#endif

//zhanggh0
//zhanggh0 end

#if defined(__MMI_ZI_THAI__)	||	defined (__MMI_T9_THAI__)
	{
		INPUT_MODE_SMART_THAI,
		INPUT_TYPE_SMART_THAI,
		STR_INPUT_METHOD_MENU_SMART_THAI,
		STR_INPUT_METHOD_SMART_THAI,
		0
	},
#endif

#if defined(__MMI_T9_SPANISH__)||defined(__MMI_ZI_EU_SPANISH__)||defined(__MMI_ZI_SA_SPANISH__)
	{
		INPUT_MODE_SMART_UPPERCASE_SPANISH,
		INPUT_TYPE_SMART_UPPERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_SMART_U_SPANISH,
		STR_INPUT_METHOD_SMART_U_SPANISH,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_SPANISH,
		INPUT_TYPE_SMART_LOWERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_SMART_L_SPANISH,
		STR_INPUT_METHOD_SMART_L_SPANISH,
		0
	},
#endif
//PMT VIKASG START 20050729

#if defined(__MMI_SMART_SPANISH__)
	{
		INPUT_MODE_SMART_UPPERCASE_SPANISH,
		INPUT_TYPE_SMART_UPPERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_SMART_U_SPANISH,
		STR_INPUT_METHOD_SMART_U_SPANISH,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_SPANISH,
		INPUT_TYPE_SMART_LOWERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_SMART_L_SPANISH,
		STR_INPUT_METHOD_SMART_L_SPANISH,
		0
	},
#endif


#if defined(__MMI_T9_DANISH__)||defined(__MMI_ZI_DANISH__)
	{
		INPUT_MODE_SMART_UPPERCASE_DANISH,
		INPUT_TYPE_SMART_UPPERCASE_DANISH,
		STR_INPUT_METHOD_MENU_SMART_U_DANISH,
		STR_INPUT_METHOD_SMART_U_DANISH,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_DANISH,//Danish-Vikas
		INPUT_TYPE_SMART_UPPERCASE_DANISH,
		STR_INPUT_METHOD_MENU_SMART_L_DANISH,
		STR_INPUT_METHOD_SMART_L_DANISH,
		0
	},
#endif
//PMT VIKASG END 20050729
#if defined(__MMI_T9_FRENCH__)||defined(__MMI_ZI_CA_FRENCH__)||defined(__MMI_ZI_EU_FRENCH__)
	{
		INPUT_MODE_SMART_UPPERCASE_FRENCH,
		INPUT_TYPE_SMART_UPPERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_SMART_U_FRENCH,
		STR_INPUT_METHOD_SMART_U_FRENCH,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_FRENCH,
		INPUT_TYPE_SMART_LOWERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_SMART_L_FRENCH,
		STR_INPUT_METHOD_SMART_L_FRENCH,
		0
	},
#endif

#if defined(__MMI_T9_GERMAN__)||defined(__MMI_ZI_GERMAN__)
	{
		INPUT_MODE_SMART_UPPERCASE_GERMAN,
		INPUT_TYPE_SMART_UPPERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_SMART_U_GERMAN,
		STR_INPUT_METHOD_SMART_U_GERMAN,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_GERMAN,
		INPUT_TYPE_SMART_LOWERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_SMART_L_GERMAN,
		STR_INPUT_METHOD_SMART_L_GERMAN,
		0
	},
#endif

#if defined(__MMI_SMART_GERMAN__)		//guoyt added for adding smart german ime
	{
		INPUT_MODE_SMART_UPPERCASE_GERMAN,
		INPUT_TYPE_SMART_UPPERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_SMART_U_GERMAN,
		STR_INPUT_METHOD_SMART_U_GERMAN,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_GERMAN,
		INPUT_TYPE_SMART_LOWERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_SMART_L_GERMAN,
		STR_INPUT_METHOD_SMART_L_GERMAN,
		0
	},

#endif

#if defined(__MMI_T9_ITALIAN__)||defined(__MMI_ZI_ITALIAN__)
	{
		INPUT_MODE_SMART_UPPERCASE_ITALIAN,
		INPUT_TYPE_SMART_UPPERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_SMART_U_ITALIAN,
		STR_INPUT_METHOD_SMART_U_ITALIAN,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_ITALIAN,
		INPUT_TYPE_SMART_LOWERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_SMART_L_ITALIAN,
		STR_INPUT_METHOD_SMART_L_ITALIAN,
		0
	},
#endif
//START PMT VANDANA 20051506
#if defined(__MMI_T9_RUSSIAN__)||defined(__MMI_ZI_RUSSIAN__)||defined(__MMI_ZI_RECOMMENDED_SIZE_RUSSIAN__)
//END PMT
	{
		INPUT_MODE_SMART_UPPERCASE_RUSSIAN,
		INPUT_TYPE_SMART_UPPERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_SMART_U_RUSSIAN,
		STR_INPUT_METHOD_SMART_U_RUSSIAN,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_RUSSIAN,
		INPUT_TYPE_SMART_LOWERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_SMART_L_RUSSIAN,
		STR_INPUT_METHOD_SMART_L_RUSSIAN,
		0
	},
#endif

#if defined(__MMI_ZI_TURKISH__)
	{
		INPUT_MODE_SMART_UPPERCASE_TURKISH,
		INPUT_TYPE_SMART_UPPERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_SMART_U_TURKISH,
		STR_INPUT_METHOD_SMART_U_TURKISH,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_TURKISH,
		INPUT_TYPE_SMART_LOWERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_SMART_L_TURKISH,
		STR_INPUT_METHOD_SMART_L_TURKISH,
		0
	},
#endif

//PMT SHARIQ START 20050729
#if defined(__MMI_T9_PORTUGUESE__)||defined(__MMI_ZI_EU_PORTUGUESE__)||defined(__MMI_ZI_SA_PORTUGUESE__)||defined(__MMI_ZI_BZ_PORTUGUESE__)
//PMT SHARIQ END 20050729
	{
		INPUT_MODE_SMART_UPPERCASE_PORTUGUESE,
		INPUT_TYPE_SMART_UPPERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_SMART_U_PORTUGUESE,
		STR_INPUT_METHOD_SMART_U_PORTUGUESE,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_PORTUGUESE,
		INPUT_TYPE_SMART_LOWERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_SMART_L_PORTUGUESE,
		STR_INPUT_METHOD_SMART_L_PORTUGUESE,
		0
	},
#endif
//PMT Gurdev Start 20050729
#if defined(__MMI_ZI_INDONESIAN__)||defined(__MMI_T9_INDONESIAN__) 
	{
		INPUT_MODE_SMART_UPPERCASE_INDONESIAN,
		INPUT_TYPE_SMART_UPPERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_SMART_U_INDONESIAN,
		STR_INPUT_METHOD_SMART_U_INDONESIAN,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_INDONESIAN,
		INPUT_TYPE_SMART_LOWERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_SMART_L_INDONESIAN,
		STR_INPUT_METHOD_SMART_L_INDONESIAN,
		0
	},
#endif
//PMT Gurdev End 20050729
#if defined(__MMI_ZI_MALAY__)
	{
		INPUT_MODE_SMART_UPPERCASE_MALAY,
		INPUT_TYPE_SMART_UPPERCASE_MALAY,
		STR_INPUT_METHOD_MENU_SMART_U_MALAY,
		STR_INPUT_METHOD_SMART_U_MALAY,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_MALAY,
		INPUT_TYPE_SMART_LOWERCASE_MALAY,
		STR_INPUT_METHOD_MENU_SMART_L_MALAY,
		STR_INPUT_METHOD_SMART_L_MALAY,
		0
	},
#endif
// PMT BHASKAR START 20052907
#if defined(__MMI_ZI_VIETNAMESE__)||defined(__MMI_T9_VIETNAMESE__) 
// PMT BHASKAR END 20052907	
	{
		INPUT_MODE_SMART_UPPERCASE_VIETNAMESE,
		INPUT_TYPE_SMART_UPPERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_SMART_U_VIETNAMESE,
		STR_INPUT_METHOD_SMART_U_VIETNAMESE,
		0
	},
	{
		INPUT_MODE_SMART_LOWERCASE_VIETNAMESE,
		INPUT_TYPE_SMART_LOWERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_SMART_L_VIETNAMESE,
		STR_INPUT_METHOD_SMART_L_VIETNAMESE,
		0
	},
#endif

#ifdef __MMI_MULTITAP_HINDI__
	{
		INPUT_MODE_MULTITAP_HINDI,
		INPUT_TYPE_MULTITAP_HINDI,
		STR_INPUT_METHOD_MENU_MULTITAP_HINDI,
		STR_INPUT_METHOD_MULTITAP_HINDI,
		0
	},
#endif
#if defined(__MMI_WCSS_INPUT_FORMAT_SUPPORT__)
	{
		INPUT_MODE_MULTITAP_UPPERCASE_ABC_NO_NUMERIC,
		0,
		0,
		0,
		0
	},
	{
		INPUT_MODE_MULTITAP_LOWERCASE_ABC_NO_NUMERIC,
		0,
		0,
		0,
		0
	},
	{
		INPUT_MODE_123_SYMBOLS,
		0,
		0,
		0,
		0
	},
#endif
	/*End of Array*/
	{
		(0xff),
		(0xff),
		(0xff),
		(0xff),
		(0xff)
	},
};

const sIMEModeDetails CSD_gIMEQSearchModeArray[] =
{
	/*Quick Search abc*/
	{
		INPUT_MODE_MMI_LOWERCASE_ABC,
		INPUT_TYPE_MMI_LOWERCASE_ABC,
		STR_INPUT_METHOD_MENU_MULTITAP_abc,
		0,
		0,
	},

#if defined(__MMI_MULTITAP_SPANISH__)
	/*Quick Search Spanish*/
	{
		INPUT_MODE_MMI_LOWERCASE_SPANISH,
		INPUT_TYPE_MMI_LOWERCASE_SPANISH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_SPANISH,
		0,
		0,
	},
#endif
//PMT VIKASG START 20050729
#if defined(__MMI_MULTITAP_DANISH__)
	/*Quick Search Danish*///Danish-Vikas
	{
		INPUT_MODE_MMI_LOWERCASE_DANISH,
		INPUT_TYPE_MMI_LOWERCASE_DANISH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_DANISH,
		0,
		0,
	},
#endif
//PMT VIKASG END 20050729
#if defined(__MMI_MULTITAP_FRENCH__)
	/*Quick Search French*/
	{
		INPUT_MODE_MMI_LOWERCASE_FRENCH,
		INPUT_TYPE_MMI_LOWERCASE_FRENCH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_FRENCH,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_MYANMAR__)
	{
		INPUT_MODE_MULTITAP_MYANMAR,
		INPUT_TYPE_MMI_MULTITAP_MYANMAR,
		STR_INPUT_METHOD_MENU_MULTITAP_MALAYALAM,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_GERMAN__)
	/*Quick Search German*/
	{
		INPUT_MODE_MMI_LOWERCASE_GERMAN,
		INPUT_TYPE_MMI_LOWERCASE_GERMAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_GERMAN,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_ITALIAN__)
	/*Quick Search Italian*/
	{
		INPUT_MODE_MMI_LOWERCASE_ITALIAN,
		INPUT_TYPE_MMI_LOWERCASE_ITALIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_ITALIAN,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_RUSSIAN__)
	/*Quick Search Turkish*/
	{
		INPUT_MODE_MMI_LOWERCASE_RUSSIAN,
		INPUT_TYPE_MMI_LOWERCASE_RUSSIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_RUSSIAN,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_TURKISH__)
	/*Quick Search Turkish*/
	{
		INPUT_MODE_MMI_LOWERCASE_TURKISH,
		INPUT_TYPE_MMI_LOWERCASE_TURKISH,
		STR_INPUT_METHOD_MENU_MULTITAP_L_TURKISH,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_URDU__)
	{
		INPUT_MODE_MMI_MULTITAP_URDU,
		INPUT_TYPE_MMI_MULTITAP_URDU,
		STR_INPUT_METHOD_MENU_MULTITAP_URDU,
		0,
		0
	},
#endif

#if defined(__MMI_MULTITAP_TAMIL__)
	{
		INPUT_MODE_MMI_MULTITAP_TAMIL,
		INPUT_TYPE_MMI_MULTITAP_TAMIL,
		STR_INPUT_METHOD_MENU_MULTITAP_TAMIL,
		STR_INPUT_METHOD_MULTITAP_TAMIL,
		0
	},
#endif

#if defined(__MMI_MULTITAP_PORTUGUESE__)
	/*Quick Search Portuguese*/
	{
		INPUT_MODE_MMI_LOWERCASE_PORTUGUESE,
		INPUT_TYPE_MMI_LOWERCASE_PORTUGUESE,
		STR_INPUT_METHOD_MENU_MULTITAP_L_PORTUGUESE,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_INDONESIAN__)
	/*Quick Search Indonesian*/
	{
		INPUT_MODE_MMI_LOWERCASE_INDONESIAN,
		INPUT_TYPE_MMI_LOWERCASE_INDONESIAN,
		STR_INPUT_METHOD_MENU_MULTITAP_L_INDONESIAN,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_MALAY__)
	/*Quick Search Malay*/
	{
		INPUT_MODE_MMI_LOWERCASE_MALAY,
		INPUT_TYPE_MMI_LOWERCASE_MALAY,
		STR_INPUT_METHOD_MENU_MULTITAP_L_MALAY,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_VIETNAMESE__)
	/*Quick Search Vietnamese*/
	{
		INPUT_MODE_MMI_LOWERCASE_VIETNAMESE,
		INPUT_TYPE_MMI_LOWERCASE_VIETNAMESE,
		STR_INPUT_METHOD_MENU_MULTITAP_L_VIETNAMESE,
		0,
		0,
	},
#endif

	/*Quick Search numeric*/
	{
		INPUT_MODE_MMI_NUMERIC,
		INPUT_TYPE_MMI_NUMERIC,
		STR_INPUT_METHOD_MENU_NUMERIC,
		0,
		0,
	},

#if defined(__MMI_T9_TR_CHINESE__)||defined(__MMI_ZI_TR_CHINESE__)||defined(__MMI_ITAP_TR_CHINESE__)
	/*Quick Search TR Bopomofo*/
	{
		INPUT_MODE_MMI_MULTITAP_BPMF,
		INPUT_TYPE_MMI_MULTITAP_BPMF,
		STR_INPUT_METHOD_MENU_MULTITAP_BOPOMO,
		0,
		0,
	},
#if !defined(__MMI_TOUCH_SCREEN__)
	/*Quick Search Stroke*/
	{
		INPUT_MODE_MMI_TR_STROKE,
		INPUT_TYPE_MMI_TR_STROKE,
		STR_INPUT_METHOD_MENU_TRADITIONAL_CHINESE_STROKE,
		0,
		0,
	},
#endif
#endif

#if defined(__MMI_T9_SM_CHINESE__)||defined(__MMI_ZI_SM_CHINESE__)||defined(__MMI_ITAP_SM_CHINESE__)
	/*Quick Search PinYin*/
	{
		INPUT_MODE_MMI_MULTITAP_PINYIN,
		INPUT_TYPE_MMI_MULTITAP_PINYIN,
		STR_INPUT_METHOD_MENU_MULTITAP_PINYIN,
		0,
		0,
	},

#if !defined(__MMI_TOUCH_SCREEN__)
	/*Quick Search SM Stroke*/
	{
		INPUT_MODE_MMI_SM_STROKE,
		INPUT_TYPE_MMI_SM_STROKE,
		STR_INPUT_METHOD_MENU_SIMPLIFIED_CHINESE_STROKE,
		0,
		0,
	},
#endif
#endif

#if defined(__MMI_MULTITAP_HINDI__)
	/*Quick Search Hindi*/
	{
		INPUT_MODE_MULTITAP_HINDI,
		INPUT_TYPE_MULTITAP_HINDI,
		STR_INPUT_METHOD_MENU_MULTITAP_HINDI,
		0,
		0,
	},
#endif

#if defined(__MMI_MULTITAP_THAI__)
	/*Quick Search THAI*/
	{
		INPUT_MODE_MMI_MULTITAP_THAI,
		INPUT_TYPE_MMI_MULTITAP_THAI,
		STR_INPUT_METHOD_MENU_MULTITAP_THAI,
		0,
		0,
	},
#endif

	/*End of Array*/
	{
		(0xff),
		(0xff),
		(0xff),
		(0xff),
		(0xff),
	},
};

#if defined(__MMI_T9__)

#if defined(__MMI_T9_V7__)
	sIMEModuleDetails CSD_gIMEModule = T9V7;
#else
	sIMEModuleDetails CSD_gIMEModule = T9V6;
#endif

#elif defined(__MMI_ZI__)
	sIMEModuleDetails CSD_gIMEModule = ZiV6;
#else
	sIMEModuleDetails CSD_gIMEModule = IME_OTHERS;
#endif

// __CUSTPACK_MULTIBIN     Terry   END
