// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "coolrgbquad.h"


/////////////////////////////////////////////////////////////////////////////
// CCoolRGBQuad properties

short CCoolRGBQuad::GetRgbBlue()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CCoolRGBQuad::SetRgbBlue(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

short CCoolRGBQuad::GetRgbGreen()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CCoolRGBQuad::SetRgbGreen(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

short CCoolRGBQuad::GetRgbRed()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CCoolRGBQuad::SetRgbRed(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

short CCoolRGBQuad::GetRgbReserved()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CCoolRGBQuad::SetRgbReserved(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCoolRGBQuad operations
