// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCoolBitmapInfoHeader wrapper class

class CCoolBitmapInfoHeader : public COleDispatchDriver
{
public:
	CCoolBitmapInfoHeader() {}		// Calls COleDispatchDriver default constructor
	CCoolBitmapInfoHeader(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCoolBitmapInfoHeader(const CCoolBitmapInfoHeader& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetBiWidth();
	void SetBiWidth(long);
	long GetBiHeight();
	void SetBiHeight(long);
	short GetBiPlanes();
	void SetBiPlanes(short);
	short GetBiBitCount();
	void SetBiBitCount(short);
	long GetBiCompression();
	void SetBiCompression(long);
	long GetBiSizeImage();
	void SetBiSizeImage(long);
	long GetBiXPelsPerMeter();
	void SetBiXPelsPerMeter(long);
	long GetBiYPelsPerMeter();
	void SetBiYPelsPerMeter(long);
	long GetBiClrUsed();
	void SetBiClrUsed(long);
	long GetBiClrImportant();
	void SetBiClrImportant(long);

// Operations
public:
};
