// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCoolBitmapInfoHeader;
class CCoolRGBQuad;

/////////////////////////////////////////////////////////////////////////////
// CCoolBitmapInfo wrapper class

class CCoolBitmapInfo : public COleDispatchDriver
{
public:
	CCoolBitmapInfo() {}		// Calls COleDispatchDriver default constructor
	CCoolBitmapInfo(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCoolBitmapInfo(const CCoolBitmapInfo& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CCoolBitmapInfoHeader GetBmiHeader();
	void SetBmiHeader(LPDISPATCH);
	CCoolRGBQuad GetBmiColors();
	void SetBmiColors(LPDISPATCH);

// Operations
public:
};
