// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCoolRGBQuad wrapper class

class CCoolRGBQuad : public COleDispatchDriver
{
public:
	CCoolRGBQuad() {}		// Calls COleDispatchDriver default constructor
	CCoolRGBQuad(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCoolRGBQuad(const CCoolRGBQuad& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetRgbBlue();
	void SetRgbBlue(short);
	short GetRgbGreen();
	void SetRgbGreen(short);
	short GetRgbRed();
	void SetRgbRed(short);
	short GetRgbReserved();
	void SetRgbReserved(short);

// Operations
public:
};
