// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKeypad wrapper class

class CKeypad : public COleDispatchDriver
{
public:
	CKeypad() {}		// Calls COleDispatchDriver default constructor
	CKeypad(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CKeypad(const CKeypad& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetKeySize();
	long AddItem(LPCTSTR lpszName, long nKeyCode, long nLeft, long nTop, long nWidth, long nHeight, LPCTSTR lpszImageUp, LPCTSTR lpszImageDown);
	void RemoveAll();
};
