/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#include "cs_types.h"
#include "custdatares.h"
#include "mmi_features.h" 

#include "stdc.h"
#include "customcfg.h"


#ifdef FIRST_PASS
#include "buildcfg.h"
#endif

//#include "dlagentresdef.h"
#include "imageviewerresdefs.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"

#ifdef __MMI_DOWNLOAD_AGENT__

void PopulateDownloadAgentImgRes(void)
{
    
}


void PopulateDownloadAgentStrRes(void)
{
	ADD_APPLICATION_STRING2(STR_DA_TEXT_FILE,   "Text file!"   ,"STR_DA_TEXT_FILE"    );
	ADD_APPLICATION_STRING2(STR_DA_IMAGE_FILE,  "Image file!"  ,"STR_DA_IMAGE_FILE"   );
	ADD_APPLICATION_STRING2(STR_DA_AUDIO_FILE,  "Audio file!"  ,"STR_DA_AUDIO_FILE"   );
	ADD_APPLICATION_STRING2(STR_DA_VIDEO_FILE,  "Video file!"  ,"STR_DA_VIDEO_FILE"   );
	ADD_APPLICATION_STRING2(STR_DA_APP_FILE,    "APP file!"    ,"STR_DA_APP_FILE"     );
	ADD_APPLICATION_STRING2(STR_DA_MSG_FILE,    "MSG file!"    ,"STR_DA_MSG_FILE"     );
	ADD_APPLICATION_STRING2(STR_DA_MULTI_FILE,  "MUITI file!"  ,"STR_DA_MULTI_FILE"   );
	ADD_APPLICATION_STRING2(STR_DA_UNKNOWN_FILE,"Unknown file!","STR_DA_UNKNOWN_FILE" );
	ADD_APPLICATION_STRING2(STR_DA_SAVE_TO,     "Save To"                          ,"STR_DA_SAVE_TO"      );
	ADD_APPLICATION_STRING2(STR_DA_NEW_PUSH,    "You got a file from Internet"     ,"STR_DA_NEW_PUSH"     );
	ADD_APPLICATION_STRING2(STR_DA_REPLACE_FILE,    "File exists. Replace it?"     ,"STR_DA_REPLACE_FILE"     );
	ADD_APPLICATION_STRING2(STR_DA_FILENAME_EDITOR,    "Edit Filename"     ,"STR_DA_FILENAME_EDITOR"     );
	ADD_APPLICATION_STRING2(STR_DA_VCARD_FILE,    "Vcard file"     ,"STR_DA_VCARD_FILE"     );
	ADD_APPLICATION_STRING2(STR_DA_VCALENDAR_FILE,    "Vcalendar file"     ,"STR_DA_VCALENDAR_FILE"     );
	ADD_APPLICATION_STRING2(STR_DA_EBOOK_FILE,    "EBook file"     ,"STR_DA_EBook_FILE"     );
	ADD_APPLICATION_STRING2(STR_DA_EMPTY_USERNAME,    "Empty Username"     ,"STR_DA_EMPTY_USERNAME"     );
	ADD_APPLICATION_STRING2(STR_DA_CALLBACK_NOW,    "File Saved. Use Now?"     ,"STR_DA_CALLBACK_NOW"     );

#if defined (__MMI_OMA_DD_DOWNLOAD__)
    ADD_APPLICATION_STRING2(STR_DA_OMA_INSUFFICIENT_MEM_MSG      ,"Insufficient Memory",    "STR_DA_OMA_INSUFFICIENT_MEM_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_USER_CANCELLED_MSG        ,"User Cancelled",         "STR_DA_OMA_USER_CANCELLED_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_LOSS_OF_SERVICE_MSG       ,"Download URL or Server Error",        "STR_DA_OMA_LOSS_OF_SERVICE_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_ATTRIBUTE_MISMATCH_MSG    ,"Attribute Mismatch",     "STR_DA_OMA_JAR_SIZE_MISMATCH_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_INVALID_DESCRIPTOR_MSG    ,"Invalid descriptor",     "STR_DA_OMA_ATTRIBUTE_MISMATCH_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_INVALID_DDVSERSION_MSG    ,"Invalid DDVersion",      "STR_DA_OMA_INVALID_DDVSERSION_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_DEVICE_ABORTED_MSG        ,"Device Aborted",         "STR_DA_OMA_DEVICE_ABORTED_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_NON_ACCEPTABLE_CONTENT_MSG,"Non-Acceptable Content", "STR_DA_OMA_NON_ACCEPTABLE_CONTENT_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_LOADER_ERROR_MSG          ,"Download URL or Server Error",           "STR_DA_OMA_LOADER_LOADER_ERROR_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_INSUFFICIENT_STORAGE_MSG,"More free space is needed for installation","STR_DA_OMA_INSUFFICIENT_STORAGE_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_AUTHORIZATION_FAILURE_MSG,"Does not have permission it requires","STR_DA_OMA_AUTHORIZATION_FAILURE_MSG");
    ADD_APPLICATION_STRING2(STR_DA_OMA_SEND_REPORT,           "Send Report","STR_DA_OMA_SEND_REPORT");


    ADD_APPLICATION_STRING2(STR_DA_ERROR_FULL,"Disk space is not enough","STR_DA_ERROR_FULL");
    ADD_APPLICATION_STRING2(STR_DA_ERROR_SIZE,"File size exceeds maximum value","STR_DA_ERROR_SIZE");

#endif
}


void PopulateDownloadAgentMenuItemRes(void)
{

/* level 1 */

	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OPTION,MENU_ID_DA,2,
		MENU_ID_DA_OPTION_SAVE,
		MENU_ID_DA_OPTION_INPUT_METHOD,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS,0));

/* level 2 */

	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OPTION_SAVE,MENU_ID_DA_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_SAVE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OPTION_INPUT_METHOD,MENU_ID_DA_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_INPUT_METHOD,0));


/* level 1 */

	ADD_APPLICATION_MENUITEM((MENU_ID_DA_SAVE_TO,MENU_ID_DA,2,
		MENU_ID_DA_SAVE_TO_PHONE,
		MENU_ID_DA_SAVE_TO_CARD,
		SHOW, NONMOVEABLE, DISP_LIST, STR_DA_SAVE_TO ,0));

/* level 2 */

	ADD_APPLICATION_MENUITEM((MENU_ID_DA_SAVE_TO_PHONE,MENU_ID_DA_SAVE_TO,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_IMGVIEW_STORAGE_PHONE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_SAVE_TO_CARD,MENU_ID_DA_SAVE_TO,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_IMGVIEW_STORAGE_MEMORY_CARD,0));

    
    
}


void PopulateDownloadAgentRes(void)
{
    
    PopulateDownloadAgentImgRes();
    PopulateDownloadAgentStrRes();
    PopulateDownloadAgentMenuItemRes();
}
#endif //__MMI_DOWNLOAD_AGENT__
#endif //DEVELOPER_BUILD_FIRST_PASS
