/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/**************************************************************

	FILENAME	: Res_.c

  	PURPOSE		: Populate Resource for 

 

 

	DATE		: August-11-2003

**************************************************************/
#include "cs_types.h"
#include "custdatares.h"
#include "stdc.h"
#include "customcfg.h"
#include "custresdef.h"

#ifdef FIRST_PASS
#include "buildcfg.h"
#endif

#include "alarmdef.h"
#include "mmi_features.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"
/**************************************************************

	FUNCTION NAME		: PopulateAlarmsRes

  	PURPOSE				: Populates the resources for Alarm

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: nil

 

**************************************************************/

void PopulateAlarmRes(void)
{
//	ADD_APPLICATION_STRING2(ALARMS_MAIN_TITLE_STRINGID,"Alarm","Title of Alarms Screen.");
	ADD_APPLICATION_STRING2(ALARMS_EDIT_SOFTKEY_STRINGID,"Edit","Edit.");

	/*Alarm Indication Screen*/
	ADD_APPLICATION_STRING2(ALARMS_STOP_STRINGID,"Stop","Stop alarm button.");
	ADD_APPLICATION_STRING2(ALARMS_SNOOZE_STRINGID,"Snooze","Snooze alarm button.");
	
	ADD_APPLICATION_STRING2(ALARM_REPEAT_STRING,"Repeat","Repeat");
	ADD_APPLICATION_STRING2(ALARM_ONCE_STRING,"Once","Once");
	ADD_APPLICATION_STRING2(ALARM_EVREYDAY_STRING,"EveryDay","EveryDay");
	//ADD_APPLICATION_STRING2(ALARM_HOURLY_STRING,"Hourly","DHourlyays");
	ADD_APPLICATION_STRING2(ALARM_DAYS_STRING,"Days","Days");
	//ADD_APPLICATION_STRING2(ALARM_WEEKLY_STRING,"Weekly","Weekly");
	//ADD_APPLICATION_STRING2(ALARM_MONTHLY_STRING,"Monthly","Monthly");
	//ADD_APPLICATION_STRING2(ALARM_SEASONLY_STRING,"Seasonally","Seasonally");
	//ADD_APPLICATION_STRING2(ALARM_YEARLY_STRING,"Yearly","Yearly");

	ADD_APPLICATION_STRING2(ALARM_EDIT_TITLE_STRINGID,"Edit Alarm","Edit alarm title.");
	ADD_APPLICATION_STRING2(ALARM_STR_DONE,"Done","Str Done Button");
	ADD_APPLICATION_STRING2(ALARMS_POWER_ON,"Power On","Power On string");
	ADD_APPLICATION_STRING2(ALARM_OFF_STRING,"Off","Off");
	ADD_APPLICATION_STRING2(ALARM_ON_STRING,"On","On");
#ifdef __MMI_ALM_CUST_VOLUME__
	ADD_APPLICATION_STRING2(ALARMS_VOLUME,"Volume","Volume string");
#endif

#ifdef __MMI_ALM_AUDIO_OPTIONS__
	ADD_APPLICATION_MENUITEM((MENU_ID_ALM_AUDIO_OPT_FMRADIO,0,2,MENU_ID_ALM_FMRADIO_CHANNEL_LIST, 
		MENU_ID_ALM_FMRADIO_MANUAL_INPUT,SHOW,NONMOVEABLE,DISP_LIST,STR_GLOBAL_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ALM_FMRADIO_CHANNEL_LIST,MENU_ID_ALM_AUDIO_OPT_FMRADIO,9,
		MENU_ID_ALM_FMRADIO_CH1,
		MENU_ID_ALM_FMRADIO_CH2,
		MENU_ID_ALM_FMRADIO_CH3,
		MENU_ID_ALM_FMRADIO_CH4,
		MENU_ID_ALM_FMRADIO_CH5,
		MENU_ID_ALM_FMRADIO_CH6,
		MENU_ID_ALM_FMRADIO_CH7,
		MENU_ID_ALM_FMRADIO_CH8,
		MENU_ID_ALM_FMRADIO_CH9,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_ALM_AUDIO_OPTIONS_FMRADIO_CHANNELLIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ALM_FMRADIO_MANUAL_INPUT,MENU_ID_ALM_AUDIO_OPT_FMRADIO,0,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_ALM_AUDIO_OPTIONS_FMRADIO_MAN_INPUT,0));
	
	#ifdef __MMI_ALM_CUSTOMIZE_TONE__
	ADD_APPLICATION_MENUITEM((MENU_ID_ALM_TONE_SETUP,0,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_ALM_AUDIO_OPTIONS_TONE,0));
	#endif

	ADD_APPLICATION_STRING2(STR_ID_ALM_AUDIO_OPTIONS,"Audio Options","Audio Options String");
	ADD_APPLICATION_STRING2(STR_ID_ALM_AUDIO_OPTIONS_TONE,"Tone","Tone");
	ADD_APPLICATION_STRING2(STR_ID_ALM_AUDIO_OPTIONS_FMRADIO,"FM Radio","FM Radio");
	ADD_APPLICATION_STRING2(STR_ID_ALM_AUDIO_OPTIONS_FMRADIO_CHANNELLIST,"Channel List","Channel List String");
	ADD_APPLICATION_STRING2(STR_ID_ALM_AUDIO_OPTIONS_FMRADIO_MAN_INPUT,"Manual Input","Manual Input STring");
	ADD_APPLICATION_STRING2(STR_ID_ALM_AUDIO_OPT_FMRDO_OPT_PREV, "Preview", "Preview String");
	ADD_APPLICATION_STRING2(STR_ID_ALM_FMRDO_VALID_FM_BANDWIDTH,"Frequency 87.5 - 108","Frequency range warning string");
	ADD_APPLICATION_STRING2(STR_ID_ALM_FMRDO_HEADFONE_REMINDER,"HeadFones Should Be Plugged In When The Alarm Expires", "HeadFone Reminder String");
	ADD_APPLICATION_STRING2(STR_ID_ALM_FMRDO_AUD_OPT_INCOMPLETE_NOTIFY, "Please Select The Newly Selected Audio Option Completely","Incomplete Info Notification String");
	ADD_APPLICATION_STRING2(STR_ID_ALM_FMRDO_PLEASE_PLUG_IN_EARPHONE, "Please Plug In Earphone","Earphone notification string");
	ADD_APPLICATION_STRING2(STR_ID_ALM_FMRDO_INCOMPLETE_CHANNEL_INFO, "Please Select Some FM Channel/Frequency", "Incomplete FM Information string");	
#endif

#ifdef __MMI_ALM_SNOOZE_SETTING__
	ADD_APPLICATION_STRING2(ALARMS_SETTING_SNOOZE_INTERVAL,"Snooze(Mins)","Snooze Interval");
	ADD_APPLICATION_STRING2(STR_ID_ALM_DEFAULT, "Default", "Default snooze interval");
	ADD_APPLICATION_STRING2(STR_ID_ALM_1, "1", "1");
	ADD_APPLICATION_STRING2(STR_ID_ALM_2, "2", "2");
	ADD_APPLICATION_STRING2(STR_ID_ALM_3, "3", "3");
	ADD_APPLICATION_STRING2(STR_ID_ALM_4, "4", "4");
	ADD_APPLICATION_STRING2(STR_ID_ALM_5, "5", "5");
	ADD_APPLICATION_STRING2(STR_ID_ALM_6, "6", "6");
	ADD_APPLICATION_STRING2(STR_ID_ALM_7, "7", "7");
	ADD_APPLICATION_STRING2(STR_ID_ALM_8, "8", "8");
	ADD_APPLICATION_STRING2(STR_ID_ALM_9, "9", "9");
	ADD_APPLICATION_STRING2(STR_ID_ALM_10, "10", "10");
#endif

	ADD_APPLICATION_IMAGE2(ALARMS_MAIN_TITLE_IMAGEID,CUST_IMG_BASE_PATH"/EmptyImage.bmp","Title of power on confirmation screen.");
	ADD_APPLICATION_IMAGE2(ALARMS_EDIT_SOFTKEY_IMAGEID,CUST_IMG_BASE_PATH"/EmptyImage.bmp","Icon for Edit  Button.");

	ADD_APPLICATION_IMAGE2(ALARMS_STOP_IMAGEID,CUST_IMG_BASE_PATH"/EmptyImage.bmp","Icon for Alarm stop.");
	ADD_APPLICATION_IMAGE2(ALARMS_SNOOZE_IMAGEID,CUST_IMG_BASE_PATH"/EmptyImage.bmp","Icon for Alarm snooze.");
	
	ADD_APPLICATION_IMAGE2(ALARM_ANIMATION_INDICATION_IMAGEID,CUST_IMG_PATH"/MAINLCD/Alarm/ALARM.gif","Icon for Alarm indication :- Main screen");
	ADD_APPLICATION_IMAGE2(ALARM_ANIMATION_INDICATION_SUBLCD_IMAGEID,CUST_IMG_PATH"/SUBLCD/Active/SB_alarm.gif","Icon for Alarm Indication:- sub lcd .");
	
#ifdef __MMI_ALM_CUST_VOLUME__
	ADD_APPLICATION_IMAGE2(ALARM_VOLUME_IMAGEID, CUST_IMG_PATH"/MainLCD/Alarm/OA_VOLUME.PBM","Status Image");
#endif

#ifdef __MMI_ALM_AUDIO_OPTIONS__
	ADD_APPLICATION_IMAGE2(IMG_ALM_AUD_OPT,CUST_IMG_PATH"/MainLCD/Alarm/OA_AUDIO.pbm","Status Image");
#endif

#ifdef __MMI_ALM_SNOOZE_SETTING__
	ADD_APPLICATION_IMAGE2(ALARMS_SET_SNOOZE_PERIOD_IMAGEID,CUST_IMG_PATH"/MainLCD/Alarm/SB_snooz.gif","Status Image");
#endif

#ifdef __MMI_ALM_ALERT_TYPE__
	ADD_APPLICATION_IMAGE2(ALARMS_SET_ALERT_TYPE_IMAGEID,CUST_IMG_PATH"/MainLCD/Alarm/SB_alert.pbm","Status Image");
#endif
}


#endif


