/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is __SUPPORT_INFUSIO__. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/**************************************************************

	FILENAME	: Res_MainMenu.c

  	PURPOSE		: Populate Resource for MainMenu

 

 

	DATE		: August-19-2003

**************************************************************/
#include "stdc.h"


#ifdef DEVELOPER_BUILD_FIRST_PASS //for resource generator ,defined in resgenerator/makefile
#include "populateres.h"
#include "mmi_features.h"
#include "gui_config.h"//082806 240x320 matrix
#include "globalmenuitems.h"
#include "organizerdef.h"
//#include "extradef.h"
#include "phonebookdef.h"
#include "funandgamesdefs.h"
#include "settingdefs.h"
#if 1
#include "messagesresourcedata.h"
#endif
#include "mmi_features_camera.h"
#include "cameraresdefs.h"

#include "alarmdef.h"
#include "soundrecorderdef.h"
#include "imageviewerresdefs.h"
#include "filemanagerdef.h"
#include "extdevicedefs.h"
#include "vdoplystrenum.h"
#include "vdoplyimgenum.h"
#if defined( __MMI_IRDA_SUPPORT__ )
#include "extdevicedefs.h"
#endif

#if 1
#if defined(__MMI_AUDIO_PLAYER__)
#include "audioplayerdef.h"
#endif

#if defined(__MMI_FM_RADIO__)
#include "fmradiodef.h"
#endif
#endif/*__MMI_SUBLCD_MASTER_MODE__*/

#ifdef __J2ME__
#include "j2me_custom.h"
#endif

#ifdef __MMI_9_Matrix__
#include "filemanagerdef.h"
#endif

#ifdef __MMI_MULTI_SIM__
#include "mtpnp_ad_resdef.h"
#endif

#define TYPE(A)	TYPE_(A)
#define TYPE_(A) A##_MENU
#define  IMG_DIR(B)   IMG_DIR_(B)
#define  IMG_DIR_(B)  # B

/**************************************************************

	FUNCTION NAME		: PopulateMainMenuRes()

  	PURPOSE				: To Initialize the resources for the
						  Mainmenu

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

 

**************************************************************/
//Organizer

//////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////

void PopulateMMMenu(void)
{
#ifdef FM_RADIO_ENABLE
#ifdef PRODUCT_QPAD
	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_MAIN,IDLE_SCREEN_MENU_ID,0,SHOW, 
	                      MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,MAIN_MENU_FM_RADIO_TEXT,MAIN_MENU_FM_RADIO_ICON));
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_MAIN,MAIN_MENU_MULTIMEDIA_MENUID,0,SHOW, 
	                      MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_FMRDO_TITLE,IMG_ID_FMRDO_APP));
#endif

	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_MAIN_OPTION,0,4,
				MENU_ID_FMRDO_CHANNEL_LIST,
				MENU_ID_FMRDO_MANUAL_INPUT,
				MENU_ID_FMRDO_PRESET_AUTO_SEARCH,
				MENU_ID_FMRDO_SETTINGS,
			SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_FMRDO_TITLE,IMG_ID_FMRDO_APP));

	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_CHANNEL_LIST,MENU_ID_FMRDO_MAIN_OPTION,0,SHOW, 
                   	MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_FMRDO_CHANNEL_LIST, IMG_GLOBAL_L1));

	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_MANUAL_INPUT,MENU_ID_FMRDO_MAIN_OPTION,0,SHOW, 
                  	MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_FMRDO_MANUAL_INPUT, IMG_GLOBAL_L2));

	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_PRESET_AUTO_SEARCH,MENU_ID_FMRDO_MAIN_OPTION,0,SHOW, 
              		MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_FMRDO_PRESET_AUTO_SEARCH, IMG_GLOBAL_L3));

	ADD_APPLICATION_MENUITEM((MENU_ID_FMRDO_SETTINGS,MENU_ID_FMRDO_MAIN_OPTION,0,SHOW, 
          		MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_FMRDO_SETTINGS, IMG_GLOBAL_L4));


#endif	
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_MAIN, MAIN_MENU_MULTIMEDIA_MENUID, 0,
				SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_SNDREC_MAIN,IMG_ID_SNDREC_MAIN));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION, 0,8,
                MENU_ID_SNDREC_RECORD,
                MENU_ID_SNDREC_PLAY,
                MENU_ID_SNDREC_APPEND,
                MENU_ID_SNDREC_RENAME,
                MENU_ID_SNDREC_DELETE,
                MENU_ID_SNDREC_DELETE_ALL,
                MENU_ID_SNDREC_SETTINGS,
                MENU_FMGR_GEN_OPTION_FORWARD,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_1, 0,8,
                MENU_ID_SNDREC_RECORD,
                MENU_ID_SNDREC_PLAY,
                MENU_ID_SNDREC_APPEND,
                MENU_ID_SNDREC_RENAME,
                MENU_ID_SNDREC_DELETE,
                MENU_ID_SNDREC_DELETE_ALL,
                MENU_ID_SNDREC_SETTINGS,
                MENU_FMGR_GEN_OPTION_FORWARD,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_2, 0,8,
                MENU_ID_SNDREC_RECORD,
                MENU_ID_SNDREC_PLAY,
                MENU_ID_SNDREC_APPEND,
                MENU_ID_SNDREC_RENAME,
                MENU_ID_SNDREC_DELETE,
                MENU_ID_SNDREC_DELETE_ALL,
                MENU_ID_SNDREC_SETTINGS,
                MENU_FMGR_GEN_OPTION_FORWARD,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_3, 0,8,
                MENU_ID_SNDREC_RECORD,
                MENU_ID_SNDREC_PLAY,
                MENU_ID_SNDREC_APPEND,
                MENU_ID_SNDREC_RENAME,
                MENU_ID_SNDREC_DELETE,
                MENU_ID_SNDREC_DELETE_ALL,
                MENU_ID_SNDREC_SETTINGS,
                MENU_FMGR_GEN_OPTION_FORWARD,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_4, 0, 2,
                MENU_ID_SNDREC_RECORD,
                //MENU_ID_SNDREC_PLAY,
                //MENU_ID_SNDREC_APPEND,
                //MENU_ID_SNDREC_RENAME,
                //MENU_ID_SNDREC_DELETE,
                //MENU_ID_SNDREC_DELETE_ALL,
                MENU_ID_SNDREC_SETTINGS,
                //MENU_FMGR_GEN_OPTION_FORWARD,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_5, 0,8,
                MENU_ID_SNDREC_RECORD,
                MENU_ID_SNDREC_PLAY,
                MENU_ID_SNDREC_APPEND,
                MENU_ID_SNDREC_RENAME,
                MENU_ID_SNDREC_DELETE,
                MENU_ID_SNDREC_DELETE_ALL,
                MENU_ID_SNDREC_SETTINGS,
                MENU_FMGR_GEN_OPTION_FORWARD,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_RECORD, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_RECORD, IMG_ID_SNDREC_RECORD));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_PLAY, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_PLAY, IMG_ID_SNDREC_PLAY));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_APPEND, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_APPEND, IMG_ID_SNDREC_APPEND));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_RENAME, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_RENAME, IMG_ID_SNDREC_RENAME));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_DELETE, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE, IMG_ID_SNDREC_DELETE));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_DELETE_ALL, MENU_ID_SNDREC_OPTION, 2, 
                MENU_ID_SNDREC_DELETE_ALL_PHONE,
                MENU_ID_SNDREC_DELETE_ALL_CARD,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL, IMG_ID_SNDREC_DELETE_ALL));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_SETTINGS, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_SETTINGS, IMG_ID_SNDREC_SETTINGS));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_ADD_TO_RINGS, MENU_ID_SNDREC_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_ADD_TO_RING, IMG_ID_SNDREC_ADD_TO_RING));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_RENAME_OPTION,	0, 	2,  
				MENU_ID_SNDREC_OPTION_SAVE,
				MENU_ID_SNDREC_OPTION_INPUT_METHOD,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_SNDREC_RENAME_OPTION, IMG_ID_SNDREC_RENAME_OPTION));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_SAVE,	MENU_ID_SNDREC_RENAME_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_SNDREC_OPTION_SAVE, IMG_ID_SNDREC_OPTION_SAVE));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_OPTION_INPUT_METHOD,	MENU_ID_SNDREC_RENAME_OPTION, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_SNDREC_OPTION_INPUT_METHOD, IMG_ID_SNDREC_OPTION_INPUT_METHOD));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_DELETE_ALL_PHONE, MENU_ID_SNDREC_DELETE_ALL, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL_PHONE, IMG_ID_SNDREC_DELETE_ALL_PHONE));
	ADD_APPLICATION_MENUITEM((MENU_ID_SNDREC_DELETE_ALL_CARD, MENU_ID_SNDREC_DELETE_ALL, 0, 
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL_CARD, IMG_ID_SNDREC_DELETE_ALL_CARD));
	
	ADD_APPLICATION_MENUITEM((AUDIO_PLAYER_MAIN_MENUID,MAIN_MENU_MULTIMEDIA_MENUID,0,
				SHOW,NONMOVEABLE,1,MAIN_MENU_AUDPLY_TEXT,IMG_ID_AUDPLY_ICON));

	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DRIVE_OPTIONS,0,4,
   				MENU_FMGR_DRIVE_OPEN, 
   				MENU_FMGR_FOLDER_CREATE, 
				MENU_FMGR_DRIVE_FORMAT, 
				MENU_FMGR_DRIVE_UNMOUNT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_DRIVE_OPTION,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_DRIVE_OPEN,MITEM_FMGR_DRIVE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_DRIVE_FORMAT,MITEM_FMGR_DRIVE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_FORMAT,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_DRIVE_CHECK,MITEM_FMGR_DRIVE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_CHECK_DRIVE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_DRIVE_UNMOUNT,MITEM_FMGR_DRIVE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_UNMOUNT,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_SELECT_DONE,MITEM_FMGR_APP_DRIVE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_SELECT,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_FOLDER_OPTIONS,0,5,
   				MENU_FMGR_GEN_OPTION_OPEN, 
   				MENU_FMGR_FOLDER_CREATE, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_SORT, 
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_FOLDER_OPTION,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FOLDER_CREATE,MITEM_FMGR_FOLDER_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_FOLDER_CREATE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_TREE_OPEN,MITEM_FMGR_TREE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_TREE_SELECT,MITEM_FMGR_TREE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_TREE_SELECT,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_IMG_TYPE_OPTIONS,0,8,
				MENU_FMGR_IMG_OPTION_VIEW,
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_COPY, 
				MENU_FMGR_GEN_OPTION_DELETE_ALL, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DETAIL, 
				MENU_FMGR_GEN_OPTION_SORT,	
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_AUD_TYPE_OPTIONS,0,9,
				MENU_FMGR_AUD_OPTION_PLAY, 
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_MOVE, 
				MENU_FMGR_GEN_OPTION_DELETE_ALL, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_VID_TYPE_OPTIONS,0,9,
				MENU_FMGR_VID_OPTION_PLAY,
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_MOVE,
				MENU_FMGR_GEN_OPTION_DELETE_ALL, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,		
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_EXE_TYPE_OPTIONS,0,8,
				MENU_FMGR_EXE_OPTION_EXECUTE, 
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_DELETE_ALL, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_GEN_TYPE_OPTIONS,0,8,
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_MOVE,
				MENU_FMGR_GEN_OPTION_DELETE_ALL, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,		
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_IMG_TYPE_OPTIONS,0,6,
				MENU_FMGR_IMG_OPTION_VIEW,
	//			MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_AUD_TYPE_OPTIONS,0,6,
				MENU_FMGR_AUD_OPTION_PLAY,
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_VID_TYPE_OPTIONS,0,6,
				MENU_FMGR_VID_OPTION_PLAY,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_EXE_TYPE_OPTIONS,0,6,
				MENU_FMGR_EXE_OPTION_EXECUTE,
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_TYPE_OPTIONS,0,5,
//				MENU_FMGR_FWD_OPTION_GEN,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_JPG_IMG_TYPE_OPTIONS,0,9,
				MENU_FMGR_IMG_OPTION_VIEW, 
				MENU_FMGR_GEN_OPTION_FORWARD, 
				MENU_FMGR_GEN_OPTION_DETAIL, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_COPY, 
				MENU_FMGR_GEN_OPTION_MOVE, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DELETE_ALL, 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DRM_IMG_TYPE_OPTIONS,0,6,
				MENU_FMGR_IMG_OPTION_VIEW, 
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DRM_AUD_TYPE_OPTIONS,0,6,
				MENU_FMGR_AUD_OPTION_PLAY, 
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DRM_EXE_TYPE_OPTIONS,0,6,
				MENU_FMGR_EXE_OPTION_EXECUTE, 
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,	
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DRM_GEN_TYPE_OPTIONS,0,5,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL , 
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_IMG_TYPE_NO_SIM_OPTIONS,0,8,
				MENU_FMGR_IMG_OPTION_VIEW, 
				MENU_FMGR_GEN_OPTION_FORWARD, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_AUD_TYPE_NO_FWD_OPTIONS,0,8,
				MENU_FMGR_AUD_OPTION_PLAY, 
				MENU_FMGR_GEN_OPTION_FORWARD, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,	
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_VID_TYPE_NO_SIM_OPTIONS,0,8,
				MENU_FMGR_VID_OPTION_PLAY, 
				MENU_FMGR_GEN_OPTION_FORWARD, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,	
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_EXE_TYPE_NO_SIM_OPTIONS,0,6,
				MENU_FMGR_EXE_OPTION_EXECUTE, 
				MENU_FMGR_GEN_OPTION_FORWARD, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_COPY,
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DETAIL,
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_GEN_TYPE_NO_SIM_OPTIONS,0,7,
				MENU_FMGR_GEN_OPTION_DETAIL, 
				MENU_FMGR_GEN_OPTION_RENAME, 
				MENU_FMGR_GEN_OPTION_COPY, 
				MENU_FMGR_GEN_OPTION_MOVE, 
				MENU_FMGR_GEN_OPTION_DELETE, 
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_SORT,
				SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_IMG_OPTION_VIEW,MITEM_FMGR_IMG_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_VIEW_IMG,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_IMG_OPTION_EDIT,MITEM_FMGR_JPG_IMG_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_EDIT,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_AUD_OPTION_PLAY,MITEM_FMGR_AUD_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_PLAY_AUDIO,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_VID_OPTION_PLAY,MITEM_FMGR_VID_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_PLAY_VIDEO,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_EXE_OPTION_EXECUTE,MITEM_FMGR_EXE_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_EXECUTE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_OPEN,MITEM_FMGR_FOLDER_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_SORT,MITEM_FMGR_GEN_TYPE_OPTIONS,5,
				MENU_FMGR_SORT_BY_NAME, 
				MENU_FMGR_SORT_BY_TYPE, 
				MENU_FMGR_SORT_BY_TIME, 
				MENU_FMGR_SORT_BY_SIZE,
				MENU_FMGR_SORT_NONE,
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_SORT,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_IMG,MITEM_FMGR_GEN_TYPE_OPTIONS,
				4
#ifdef __MMI_OPP_SUPPORT__
				+1
#endif
				,
				MENU_FMGR_FWD_WALLPAPER,
				MENU_FMGR_FWD_POWER_ON,
				MENU_FMGR_FWD_SCREENSAVER,
				MENU_FMGR_FWD_POWER_OFF,		
#ifdef __MMI_OPP_SUPPORT__
				MENU_FMGR_FWD_BT,
#endif
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_IMG_DRM,MITEM_FMGR_GEN_TYPE_OPTIONS,5,
				MENU_FMGR_FWD_WALLPAPER, 
				MENU_FMGR_FWD_SCREENSAVER,
				MENU_FMGR_FWD_POWER_ON, 
				MENU_FMGR_FWD_POWER_OFF,
				MENU_FMGR_FWD_PHB,	
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_AUD,MITEM_FMGR_GEN_TYPE_OPTIONS,
				1
#ifdef __MMI_OPP_SUPPORT__
				+1
#endif
				,
				
				MENU_FMGR_FWD_PROFILE,	
#ifdef __MMI_OPP_SUPPORT__
				MENU_FMGR_FWD_BT,
#endif
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_AUD_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,	
				1
#ifdef __MMI_OPP_SUPPORT__
				+1
#endif
				,
				MENU_FMGR_FWD_PROFILE,	
#ifdef __MMI_OPP_SUPPORT__
				MENU_FMGR_FWD_BT,
#endif
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VID,MITEM_FMGR_GEN_TYPE_OPTIONS,0
#ifdef __MMI_INCOMING_CALL_VIDEO__         
				+1
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
				+1
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
				+2
#endif
#ifdef __MMI_OPP_SUPPORT__
				+1
#endif

				,
#ifdef __MMI_INCOMING_CALL_VIDEO__         
				MENU_FMGR_FWD_PHB,
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
				MENU_FMGR_FWD_SCREENSAVER,
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
				MENU_FMGR_FWD_POWER_ON,
				MENU_FMGR_FWD_POWER_OFF,
#endif
#ifdef __MMI_OPP_SUPPORT__
				MENU_FMGR_FWD_BT,
#endif

				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VID_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,0
#ifdef __MMI_INCOMING_CALL_VIDEO__         
				+1
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
//				+1
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
				+2
#endif
#ifdef __MMI_OPP_SUPPORT__
				+1
#endif

				,

#ifdef __MMI_INCOMING_CALL_VIDEO__         
				MENU_FMGR_FWD_PHB,
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
//				MENU_FMGR_FWD_SCREENSAVER,
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
				MENU_FMGR_FWD_POWER_ON,
				MENU_FMGR_FWD_POWER_OFF,
#endif
#ifdef __MMI_OPP_SUPPORT__
				MENU_FMGR_FWD_BT,
#endif

				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VCARD,MITEM_FMGR_GEN_TYPE_OPTIONS,
				1
#ifdef __MMI_OPP_SUPPORT__
				+1
#endif
				,
				MENU_FMGR_FWD_POWER_ON,	
#ifdef __MMI_OPP_SUPPORT__
				MENU_FMGR_FWD_BT,
#endif
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VCARD_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,
				2
#ifdef __MMI_VCARD__
				+1
#endif
				,
				MENU_FMGR_FWD_POWER_OFF,
				MENU_FMGR_FWD_PHB,
#ifdef __MMI_VCARD__
				MENU_FMGR_FWD_BT,
#endif
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VCAL,MITEM_FMGR_GEN_TYPE_OPTIONS,
				1
#ifdef __MMI_VCALENDAR__
				+1
#endif
				,
				MENU_FMGR_FWD_POWER_OFF,
#ifdef __MMI_VCALENDAR__
				MENU_FMGR_FWD_BT,
#endif
				
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VCAL_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,
				0
#ifdef __MMI_VCALENDAR__
				+1
#endif
				,
#ifdef __MMI_VCALENDAR__
				MENU_FMGR_FWD_BT,
#endif
				
				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
//	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_GEN,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
//				SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_FORWARD,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_RENAME,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_RENAME,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_JPG_DETAIL,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_DETAIL,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_DETAIL,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_COPY,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_COPY,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_DELETE_ALL,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_DELETE_ALL,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_DELETE,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_MOVE,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_MOVE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_WALLPAPER,MENU_FMGR_FWD_OPTION_IMG,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_WALLPAPER,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_SUB_WALLPAPER,MENU_FMGR_FWD_OPTION_IMG,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SUB_WALLPAPER,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_SCREENSAVER,MENU_FMGR_FWD_OPTION_IMG,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SCREENSAVER,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_POWER_ON,MENU_FMGR_FWD_OPTION_IMG,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_POWER_ON,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_POWER_OFF,MENU_FMGR_FWD_OPTION_IMG,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_POWER_OFF,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_PHB,MENU_FMGR_FWD_OPTION_IMG,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_PHB,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_SMS,MENU_FMGR_FWD_OPTION_VCAL_NO_SIM,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SMS,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_EMAIL,MENU_FMGR_FWD_OPTION_GEN,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_EMAIL,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_IRDA,MENU_FMGR_FWD_OPTION_GEN,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_IRDA,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_BT,MENU_FMGR_FWD_OPTION_GEN,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_BT,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_PROFILE,MENU_FMGR_FWD_OPTION_AUD,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_PROFILE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_BGSOUND,MENU_FMGR_FWD_OPTION_AUD,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_PROFILE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_SORT_BY_NAME,MENU_FMGR_GEN_OPTION_SORT,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SORT_BY_NAME,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_SORT_BY_TYPE,MENU_FMGR_GEN_OPTION_SORT,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SORT_BY_TYPE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_SORT_BY_TIME,MENU_FMGR_GEN_OPTION_SORT,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SORT_BY_TIME,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_SORT_BY_SIZE,MENU_FMGR_GEN_OPTION_SORT,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SORT_BY_SIZE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_SORT_NONE,MENU_FMGR_GEN_OPTION_SORT,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SORT_NONE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_EDITOR_DONE,MITEM_FMGR_EDITOR_OPTION,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DONE,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_INPUT_METHOD,MITEM_FMGR_EDITOR_OPTION,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_INPUT_METHOD,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_APP, MAIN_MENU_MULTIMEDIA_MENUID,0,
				SHOW,MOVEABLEACROSSPARENT|SHORTCUTABLE,1,STR_ID_VDOPLY_APP_NAME,IMG_ID_VDOPLY_APP_ICON));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_FILE_OPTION,	0,6,
				MENU_ID_VDOPLY_PLAY,
				MENU_FMGR_GEN_OPTION_FORWARD,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_SORT,			
				0, 0, 1,STR_GLOBAL_OPTIONS,IMG_ID_VDOPLY_APP_ICON));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_FILE_OPTION_NO_SIM,0,5,
				MENU_ID_VDOPLY_PLAY,
				MENU_FMGR_GEN_OPTION_RENAME,
				MENU_FMGR_GEN_OPTION_DELETE,
				MENU_FMGR_GEN_OPTION_DELETE_ALL,
				MENU_FMGR_GEN_OPTION_SORT,
				0,0,1,STR_GLOBAL_OPTIONS,IMG_ID_VDOPLY_APP_ICON));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_EMPTY_FOLDER_OPTION,0,1,
				MENU_ID_VDOPLY_STORAGE,
				0,0,1,STR_GLOBAL_OPTIONS,IMG_ID_VDOPLY_APP_ICON));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_PLAY, MENU_ID_VDOPLY_FILE_OPTION,0,
				SHOW,NONMOVEABLE,1,STR_ID_VDOPLY_PLAY,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_STORAGE,MENU_ID_VDOPLY_FILE_OPTION,2,
				MENU_ID_VDOPLY_STORAGE_PHONE,
				MENU_ID_VDOPLY_STORAGE_MEMORY_CARD,
				0,0, 1,STR_ID_VDOPLY_STORAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_STORAGE_PHONE, MENU_ID_VDOPLY_STORAGE,0,
				SHOW,NONMOVEABLE,1,STR_ID_VDOPLY_STORAGE_PHONE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_VDOPLY_STORAGE_MEMORY_CARD, MENU_ID_VDOPLY_STORAGE,0,
				SHOW,NONMOVEABLE,1,STR_ID_VDOPLY_STORAGE_MEMORY_CARD,0));

}


#if defined(__PROJECT_F26__)
#include "gamedefs.h"
#endif

//////////////////////////////////////////////////////////////////////////////////

void PopulateMainMenu(void)
{
	U8 i;
	/*Main Menu*/
	ADD_APPLICATION_MENUITEM((IDLE_SCREEN_MENU_ID,0,9,	        
	        MAIN_MENU_PHONEBOOK_MENUID,
	        MAIN_MENU_MESSAGES_MENUID,	        
			#ifndef __MMI_MULTI_SIM__ 
				MAIN_MENU_CALL_HISTORY,
			#else 
				MENU_MTPNP_DM_CALL_HISTORY,
			#endif /* __MMI_DUAL_SIM__  */
                MAIN_MENU_FUNANDGAMES_MENUID,
				MAIN_MENU_MULTIMEDIA_MENUID,
				MAIN_MENU_SETTINGS_MENUID,
				MAIN_MENU_EXTRA_MENUID,
				MAIN_MENU_ORGANIZER_MENUID,				 
				MAIN_MENU_SERVICES_MENUID,
				0,INSERTABLE,PAGE_MENU,MAIN_MENU_MENU_TEXT,MAIN_MENU_PHONEBOOK_ICON));

/*common menu among lcd size*/
	/*Phone Book*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_PHONEBOOK_MENUID,IDLE_SCREEN_MENU_ID,MMI_PHB_MAIN_ENUM_TOTAL,
	#if defined(__MMI_PHB_QUICK_SEARCH__)
		MENU_ID_PHB_QUICK_SEARCH,		
	#endif
		MITEM101_PBOOK_SEARCH_ENTRY,
		MITEM102_PBOOK_NEW_ENTRY,
		MITEM104_PBOOK_COPY_ALL,
		MITEM103_PBOOK_DELETE_ALL,
		MITEM109_PBOOK_CALLER_GROUPS,
		MENU_ID_PHB_EXTRA_NUMBER,
		MITEM110_PBOOK_SETTINGS,
	#if defined(__MMI_PHB_CALLER_RES_SETTING__)
		MENU_ID_PHB_CALLER_PIC,
		MENU_ID_PHB_CALLER_RING,
	#if defined(__MMI_INCOMING_CALL_VIDEO__)
		MENU_ID_PHB_CALLER_VIDEO,
	#endif
    #if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_EXPORT,
		MENU_ID_PHB_VCARD_IMPORT,
    #endif
	#endif
		SHOW, MOVEABLEACROSSPARENT|INSERTABLE, DISP_LIST, MAIN_MENU_PHONEBOOK_TEXT,MAIN_MENU_PHONEBOOK_ICON));


	/* phonebook for No SIM inserted mode-*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,MENU_SIM_OPTION_ID, MMI_PHB_MAIN_NO_SIM_ENUM_TOTAL,
	#if defined(__MMI_PHB_QUICK_SEARCH__)	
		MENU_ID_PHB_QUICK_SEARCH,		
	#endif
		MITEM101_PBOOK_SEARCH_ENTRY,
		MITEM102_PBOOK_NEW_ENTRY,
		MITEM103_PBOOK_DELETE_ALL,
		MITEM109_PBOOK_CALLER_GROUPS,
		MITEM110_PBOOK_SETTINGS_NO_SIM,
		SHOW, MOVEABLEACROSSPARENT|INSERTABLE, DISP_LIST, MAIN_MENU_PHONEBOOK_TEXT,MAIN_MENU_PHONEBOOK_ICON));


	/* Message main menu */
	ADD_APPLICATION_MENUITEM((MAIN_MENU_MESSAGES_MENUID,
									IDLE_SCREEN_MENU_ID,	NUM_MESSAGES_MAIN_MENU,
#ifdef JATAAYU_SUPPORT
									MMS_MAIN_SCREEN_MENUID, /* Jataayu MMS */
#endif
									MESSAGES_MENU_WMESSAGE_MENU_ID,
									MESSAGES_MENU_INBOX_MENUID,
									MESSAGES_MENU_OUTBOX_MENUID,
								#ifdef __MMI_MESSAGES_DRAFT_BOX__
									MESSAGES_MENU_DRAFTBOX_MENUID,
								#endif

								#if defined(__MMI_MESSAGES_DELETE_ALL_MENU__)
									MESSAGES_MENU_DELETE_MENUID,
								#endif
								#if defined(__MMI_MESSAGES_TEMPLATE__)
									MESSAGES_MENU_TEMPLATES_MENUID,
								#endif
								#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
									MENU_MTPNP_DM_MSG_SETTINGS,
								#else
									MESSAGES_MENU_MSG_SETTINGS_MENUID,
								#endif
								#ifdef __MMI_MULTI_SIM__
									MENU_MTPNP_DM_VMAIL,
								#else  /* No Defined __MMI_MULTI_SIM__ */
									MESSAGES_MENU_VMAIL_MENUID,
								#endif /* __MMI_MULTI_SIM__ */
									SHOW,	MOVEABLEWITHINPARENT|INSERTABLE,	DISP_LIST,								
									MAIN_MENU_MESSAGES_TEXT,	MAIN_MENU_MESSAGES_ICON));

	/*Call History*/
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		ADD_APPLICATION_MENUITEM((MAIN_MENU_CALL_HISTORY + i,
						#ifndef __MMI_MULTI_SIM__
							IDLE_SCREEN_MENU_ID,
						#else 
							MENU_MTPNP_DM_CALL_HISTORY,
						#endif /* __MMI_MULTI_SIM__  */
							8,
							MENU8103_MISSED_CALLS,
							MENU8102_DIALED_CALLS,	
							MENU8101_RECEIVED_CALLS,
							MENU8104_REJECTED_CALLS,
							MENU8113_CALLHISTORY_RESETCALL,
							MENU_CALL_TIME_SETUP,
							MENU_CALL_HISTORY_CALLCOST,
							MENU_CALL_HISTORY_SMSCOUNTER,
							SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,
						#ifndef __MMI_MULTI_SIM__ 
							#ifdef PRODUCT_QPAD
							MAIN_MENU_CALLS_TEXT, 
							#else
							MAIN_MENU_CALL_HISTORY_TEXT, 
							#endif		
						#else 
							#ifdef __MMI_DUAL_SIM_SINGLE_OPENED_
							MAIN_MENU_CALL_HISTORY_TEXT, 
							#else/* __MMI_DUAL_SIM_SINGLE_OPENED_*/
							STRING_MTPNP_CARD1_CALL_HISTORY + i,
							#endif /* __MMI_DUAL_SIM_SINGLE_OPENED_ */
						#endif /* __MMI_MULTI_SIM__  */
						#ifdef PRODUCT_QPAD  
							MAIN_MENU_CALLS_ICON));
						#else
							MAIN_MENU_CALL_HISTORY_ICON));
						#endif
	}


#ifdef PRODUCT_QPAD  
	/*Multi Media*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_MULTIMEDIA_MENUID,MAIN_MENU_ORGANIZER_MENUID,
		6,
		MENU_ID_CAMERA_APP,
		AUDIO_PLAYER_MAIN_MENUID,
		MENU_ID_VDOPLY_APP,
		MENU_ID_VDOREC_APP,
		MENU_ID_IMGVIEW_APP,
		MENU_ID_SNDREC_MAIN,
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,MAIN_MENU_MMEDIA_TEXT,NULL ));
#else

	/*Multi Media*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_MULTIMEDIA_MENUID,IDLE_SCREEN_MENU_ID,
	#ifdef FM_RADIO_ENABLE
		1+
#if  defined(__MMI_MAINLCD_240X320__)||defined(__MMI_MAINLCD_128X128__)	||defined(__MMI_MAINLCD_128X160__)				
		1+
	#endif
	#endif
	#if defined(__MMI_FM_RADIO_SCHEDULE_REC__)
		1+
	#endif
#if defined(__MMI_ANALOGTV__)
              1+
#endif
#ifndef MEM_ULC_3216
		1+
#endif
#ifdef __MMI_VIDEO_RECORDER__
		1+
#endif
		3,
#if defined(__MMI_ANALOGTV__)
            MENU_ID_ANALOGTV_MAIN,
#endif
		MENU_ID_IMGVIEW_APP,
#if  defined(__MMI_MAINLCD_240X320__)||defined(__MMI_MAINLCD_128X128__)	||defined(__MMI_MAINLCD_128X160__)				
		MENU_ID_CAMERA_APP,
	#endif
		AUDIO_PLAYER_MAIN_MENUID,
		MENU_ID_VDOPLY_APP,
#ifdef __MMI_VIDEO_RECORDER__
		MENU_ID_VDOREC_APP,
#endif		
#ifndef MEM_ULC_3216		
		MENU_ID_SNDREC_MAIN,
#endif
	#ifdef FM_RADIO_ENABLE
		MENU_ID_FMRDO_MAIN,
	#endif
	#if defined(__MMI_FM_RADIO_SCHEDULE_REC__)
		MENU_ID_FMSR_MAIN,
	#endif
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,MAIN_MENU_MMEDIA_TEXT,MAIN_MENU_MULTIMEDIA_ICON));
#endif


	/*Origanizer*/
#if defined __MMI_MAINLCD_240X320__
//Modified by Kenneth 2008-12-11
	/*Profile*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_MENUID,IDLE_SCREEN_MENU_ID,
	#ifdef __MMI_BT_PROFILE__
        6,
#else
        5,
#endif
    MAIN_MENU_PROFILES_GENERAL,
        MAIN_MENU_PROFILES_MEETING,
        MAIN_MENU_PROFILES_OUTDOOR,
        MAIN_MENU_PROFILES_INDOOR,
        MAIN_MENU_PROFILES_HEADSET,
#ifdef __MMI_BT_PROFILE__
        MAIN_MENU_PROFILES_BT,
#endif
		0,MOVEABLEACROSSPARENT | SHORTCUTABLE,1,MAIN_MENU_PROFILES_TEXT,MAIN_MENU_PROFILES_ICON));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_ORGANIZER_MENUID,IDLE_SCREEN_MENU_ID,
	#ifdef __MMI_FLASHLIGHT__                                 // flashlight--modified by kecx for flashlight function on 20081110
		1+
	#endif
		6
	#ifdef __MMI_NOTEPAD__
		+1
	#endif
		,
		ORGANIZER_CALENDER_MENU,
		ORGANIZER_ALARM_MENU,
	#ifdef __MMI_FLASHLIGHT__                                 // flashlight--added by kecx for flashlight function on 20081110
		ORGANIZER_FLASHLIGHT_MENUID,       
	#endif
		ORGANIZER_TODOLIST_MENU,
		ORGANIZER_CURRENCYCONVERTOR_MENU,
		ORGANIZER_UNITCONVERTOR_MENU, 
		MENU_STOPWATCH,
		#ifdef __MMI_NOTEPAD__
		ORGANIZER_NOTEPAD_MENU,
		#endif
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,MAIN_MENU_ORGANIZER_TEXT,MAIN_MENU_ORGANIZER_ICON));
			
//Modified by Kenneth 2008-12-11
/*for 240x320 lcd size*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_SERVICES_MENUID,IDLE_SCREEN_MENU_ID,
		//		SERVICES_WAP_MENU_ID,
		////	SERVICES_DATA_CONNECT_MENU_ID,
		//		SERVICES_INFO_NUM_MENU_ID,
			#ifdef JATAAYU_SUPPORT
			2+
			#endif
			0,
			#ifdef JATAAYU_SUPPORT
				WAP_MAIN_SCREEN_MENUID,
				SERVICES_DATA_CONNECT_MAIN_MENU_ID,
			#endif	
				SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,MAIN_MENU_SERVICES_TEXT,MAIN_MENU_SERVICES_ICON));
	ADD_APPLICATION_MENUITEM((MAIN_MENU_SHORTCUTS_MENUID,IDLE_SCREEN_MENU_ID,0,
				SHOW,MOVEABLEWITHINPARENT,1,MAIN_MENU_SHORTCUTS_TEXT,MAIN_MENU_SHORTCUTS_ICON));
				
	ADD_APPLICATION_MENUITEM((MAIN_MENU_EXTRA_MENUID, IDLE_SCREEN_MENU_ID,
			#if defined( __MMI_SUPPORT_BLUETOOTH__) 
				1+
			#endif
			#if defined(__MMI_EBOOK_READER__)
				1 +
			#endif
				3,
			#if defined( __MMI_SUPPORT_BLUETOOTH__) 
				MENU_CONN_BT_MAIN,
			#endif
			#if defined(__MMI_EBOOK_READER__)
				MAIN_MENU_EBOOK_MENUID,
			#endif
				ORGANIZER_CALCULATOR_MENU,
				ORGANIZER_HEALTH_MENU,
				ORGANIZER_WORLDCLOCK_MENU,
				SHOW,MOVEABLEWITHINPARENT,1,MAIN_MENU_EXTRA_TEXT ,MAIN_MENU_EXTRA_ICON));			
#elif defined (PRODUCT_QPAD)
	ADD_APPLICATION_MENUITEM((MAIN_MENU_STK_MENUID,IDLE_SCREEN_MENU_ID,
		1,
		MAIN_MENU_SERVICES_MENUID, 
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,MAIN_MENU_STK_TEXT,MAIN_MENU_STK_ICON));
#elif defined(__MMI_MAINLCD_176X220__) 	||defined(__MMI_MAINLCD_128X160__)||defined(__MMI_MAINLCD_128X128__)
	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_MENUID,
	                            #if defined(__MMI_MAINLCD_128X128__)
                                    MAIN_MENU_SETTINGS_MENUID,
                                #else
                                    IDLE_SCREEN_MENU_ID,
                                #endif
								#ifdef __MMI_BT_PROFILE__
								6,
								#else
								5,
								#endif
								MAIN_MENU_PROFILES_GENERAL,
								MAIN_MENU_PROFILES_MEETING,
								MAIN_MENU_PROFILES_OUTDOOR,
								MAIN_MENU_PROFILES_INDOOR,
								MAIN_MENU_PROFILES_HEADSET,
								#ifdef __MMI_BT_PROFILE__
								MAIN_MENU_PROFILES_BT,
								#endif
								0,MOVEABLEACROSSPARENT | SHORTCUTABLE,1,MAIN_MENU_PROFILES_TEXT,MAIN_MENU_PROFILES_ICON));

    ADD_APPLICATION_MENUITEM((MAIN_MENU_FILE_MNGR_MENUID,MAIN_MENU_ORGANIZER_MENUID,0,
				SHOW,MOVEABLEWITHINPARENT,1,MAIN_MENU_FILE_MNGR_TEXT,NULL));
    
	ADD_APPLICATION_MENUITEM((MAIN_MENU_ORGANIZER_MENUID,IDLE_SCREEN_MENU_ID,
								#if defined(__MMI_EBOOK_READER__)
								1 +
								#endif							
                                #ifdef __MMI_NOTEPAD__
								1+
								#endif  
								4,
								ORGANIZER_CALENDER_MENU,
								ORGANIZER_ALARM_MENU,
								ORGANIZER_TODOLIST_MENU,								
                                MAIN_MENU_FILE_MNGR_MENUID,
								#ifdef __MMI_NOTEPAD__
								ORGANIZER_NOTEPAD_MENU,
								#endif
								#if defined(__MMI_EBOOK_READER__)
								MAIN_MENU_EBOOK_MENUID,
								#endif      
								SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,MAIN_MENU_ORGANIZER_TEXT,MAIN_MENU_ORGANIZER_ICON));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_SERVICES_MENUID,IDLE_SCREEN_MENU_ID,
								#ifdef JATAAYU_SUPPORT
								2+
								#endif
								0,
								#ifdef JATAAYU_SUPPORT
								WAP_MAIN_SCREEN_MENUID,
								SERVICES_DATA_CONNECT_MAIN_MENU_ID,
								#endif	
								SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,MAIN_MENU_SERVICES_TEXT,MAIN_MENU_SERVICES_ICON));
	ADD_APPLICATION_MENUITEM((MAIN_MENU_SHORTCUTS_MENUID,IDLE_SCREEN_MENU_ID,0,
								SHOW,MOVEABLEWITHINPARENT,1,MAIN_MENU_SHORTCUTS_TEXT,MAIN_MENU_SHORTCUTS_ICON));
				
	ADD_APPLICATION_MENUITEM((MAIN_MENU_EXTRA_MENUID, IDLE_SCREEN_MENU_ID,
								#if defined( __MMI_SUPPORT_BLUETOOTH__) 
								1+
								#endif								
								#ifdef __MMI_WORLD_CLOCK__
								1 +
								#endif
								#ifdef __MMI_STOPWATCH__
								1 +
								#endif
                                #ifdef __MMI_CURRENCY_CONVERTER__
								1 +
								#endif
								#ifdef __MMI_UNIT_CONVERTER__
								1 +
								#endif
                                #ifdef __MMI_BMI__
                                1+
                                #endif
                                #ifdef __MMI_FLASHLIGHT__
								1+
								#endif
								1,
								#if defined( __MMI_SUPPORT_BLUETOOTH__) 
								MENU_CONN_BT_MAIN,
								#endif
								ORGANIZER_CALCULATOR_MENU,
								#ifdef __MMI_FLASHLIGHT__
								ORGANIZER_FLASHLIGHT_MENUID,       
								#endif
								#ifdef __MMI_CURRENCY_CONVERTER__
								ORGANIZER_CURRENCYCONVERTOR_MENU,
								#endif
								#ifdef __MMI_UNIT_CONVERTER__
								ORGANIZER_UNITCONVERTOR_MENU,
								#endif
								#ifdef __MMI_BMI__
								ORGANIZER_HEALTH_MENU,
								#endif
								#ifdef __MMI_STOPWATCH__
								MENU_STOPWATCH,
								#endif								
								#ifdef __MMI_WORLD_CLOCK__
								ORGANIZER_WORLDCLOCK_MENU,
								#endif								
								SHOW,MOVEABLEWITHINPARENT,1,MAIN_MENU_EXTRA_TEXT ,MAIN_MENU_EXTRA_ICON));		
#else

//Modified by Kenneth 2008-12-11
	/*Profile*/
	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_MENUID,MAIN_MENU_SETTINGS_MENUID,
	#ifdef __MMI_BT_PROFILE__
        6,
#else
        5,
#endif
    MAIN_MENU_PROFILES_GENERAL,
        MAIN_MENU_PROFILES_MEETING,
        MAIN_MENU_PROFILES_OUTDOOR,
        MAIN_MENU_PROFILES_INDOOR,
        MAIN_MENU_PROFILES_HEADSET,
#ifdef __MMI_BT_PROFILE__
        MAIN_MENU_PROFILES_BT,
#endif
		0,MOVEABLEACROSSPARENT | SHORTCUTABLE,1,MAIN_MENU_PROFILES_TEXT,MAIN_MENU_PROFILES_ICON));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_EXTRA_MENUID, IDLE_SCREEN_MENU_ID,
								#if defined( __MMI_SUPPORT_BLUETOOTH__) 
								1+
								#endif
								#if defined(__MMI_EBOOK_READER__)
								1 +
								#endif
								3,

								#if defined( __MMI_SUPPORT_BLUETOOTH__) 
								MENU_CONN_BT_MAIN,
								#endif
								ORGANIZER_CALCULATOR_MENU,
								MENU_STOPWATCH,
								ORGANIZER_WORLDCLOCK_MENU,
								#if defined(__MMI_EBOOK_READER__)
								MAIN_MENU_EBOOK_MENUID,
								#endif
								SHOW,MOVEABLEWITHINPARENT,1,MAIN_MENU_EXTRA_TEXT ,MAIN_MENU_EXTRA_ICON));	

	ADD_APPLICATION_MENUITEM((MAIN_MENU_ORGANIZER_MENUID,IDLE_SCREEN_MENU_ID,
		9
	#if defined(__MMI_EBOOK_READER__)
		+1 
	#endif
	#if defined( __MMI_SUPPORT_BLUETOOTH__) 
		+1
	#endif
	#ifdef __MMI_NOTEPAD__
		+1
	#endif
		,
		//MAIN_MENU_SERVICES_MENUID, //qiff the services menu in fun&games menu
	#if defined(__MMI_EBOOK_READER__)
		MAIN_MENU_EBOOK_MENUID,
	#endif
	#if defined( __MMI_SUPPORT_BLUETOOTH__) 
		MENU_CONN_BT_MAIN,
	#endif	
		ORGANIZER_CALENDER_MENU,
		ORGANIZER_ALARM_MENU,
		ORGANIZER_CALCULATOR_MENU,
		ORGANIZER_HEALTH_MENU,
		ORGANIZER_WORLDCLOCK_MENU,
		MENU_STOPWATCH,
		ORGANIZER_TODOLIST_MENU,
		ORGANIZER_CURRENCYCONVERTOR_MENU,
		ORGANIZER_UNITCONVERTOR_MENU, 
	#ifdef __MMI_NOTEPAD__
		ORGANIZER_NOTEPAD_MENU,
	#endif
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,MAIN_MENU_ORGANIZER_TEXT,MAIN_MENU_ORGANIZER_ICON));
#endif
#if defined(__PROJECT_F26__)
ADD_APPLICATION_MENUITEM((MENU3105_GAMES,MAIN_MENU_ORGANIZER_MENUID,
	0,	0,MOVEABLEACROSSPARENT|SHORTCUTABLE,1,STR_MENU3105_GAMES,0));
#endif
}


#if !defined (__MMI_BI_DEGREE_MAIN_MENU_STYLE__)
#if defined(__MMI_VERSION_2__)	 
void PopulateMainMenuRes(void)
{
	PopulateMainMenu();
	PopulateMMMenu();

	/*	string definitions */
	ADD_APPLICATION_STRING(MAIN_MENU_MENU_TEXT,"Menu");
	ADD_APPLICATION_STRING(MAIN_MENU_TITLE_TEXT,"Main Menu");

	ADD_APPLICATION_STRING(MAIN_MENU_PHONEBOOK_TEXT,"PhoneBook");
	ADD_APPLICATION_STRING(MAIN_MENU_MESSAGES_TEXT,"Messages");
	ADD_APPLICATION_STRING(MAIN_MENU_FUNANDGAMES_TEXT,"Fun & Games");
	ADD_APPLICATION_STRING(MAIN_MENU_ORGANIZER_TEXT,"Organizer");
	ADD_APPLICATION_STRING(MAIN_MENU_PROFILES_TEXT,"User Profiles");
	ADD_APPLICATION_STRING(MAIN_MENU_SETTINGS_TEXT,"Settings");
	ADD_APPLICATION_STRING(MAIN_MENU_SHORTCUTS_TEXT,"Shortcuts");
	ADD_APPLICATION_STRING(MAIN_MENU_SERVICES_TEXT,"Services");
	ADD_APPLICATION_STRING(MAIN_MENU_CALL_HISTORY_TEXT,"Call History");
	ADD_APPLICATION_STRING2(MAIN_MENU_FILE_MNGR_TEXT,"File Manager","File Manager menu title");
	ADD_APPLICATION_STRING2(MAIN_MENU_MMEDIA_TEXT,"Multimedia","Multimedia menu title");
	ADD_APPLICATION_STRING2(MAIN_MENU_EXTRA_TEXT,"Extra","Extra menu title");

	/* images */
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_ICON, CUST_IMG_BASE_PATH"/NoImage.bmp");

#ifdef __MMI_MAINMENU_STYLE_CHANGE_EN__
      /* Matrix */
 	#ifdef __MMI_MAINMENU_MATRIX_SUPPORT__
	#ifdef PRODUCT_QPAD                             			

		#ifndef __MMI_MATRIX_MAIN_MENU_FULL_BACKGROUND__
//del by reslim v0.1		  	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MESSAGE_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Message.gif"); 
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CONTACTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Contacts.gif");
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CALLS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Calls.gif");	
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_TOOLS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Tools.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Settings.bmp");
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FM_RADIO_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_FM_Radio.gif");
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_ALARM_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Alarm.gif");
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_STK_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_STK.gif");
//del by reslim v0.1			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_GAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Games.gif");
			
		#else
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PHONEBOOK_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
			ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		#endif

//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MESSAGE_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Message_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CONTACTS_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Contacts_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CALLS_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Calls_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_TOOLS_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Tools_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SETTINGS_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Settings_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FM_RADIO_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_FM_Radio_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_ALARM_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Alarm_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_STK_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_STK_Focus.gif");
//del by reslim v0.1		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_GAMES_FOCUS,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_Games_Focus.gif");
	#else /*!PRODUCT_QPAD*/
	#ifndef __MMI_MATRIX_MAIN_MENU_FULL_BACKGROUND__
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PHONEBOOK_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_PB.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_MG.gif");
//		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_FG.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_OR.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_ST.gif");
//		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_SC.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_SV.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_PR.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_CA.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_MM.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_FM.gif");
//		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EX.gif");

	#else
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PHONEBOOK_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EMPTY.gif");
	#endif
	
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PHONEBOOK_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_PB.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MESSAGES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_MG.gif");
//	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FUNANDGAMES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_FG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_ORGANIZER_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_OR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SETTINGS_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_ST.gif");
//	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SHORTCUTS_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_SC_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SERVICES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_PROFILES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_PR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_CALL_HISTORY_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_MULTIMEDIA_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_MM.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_FILEMNGR_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_FM.gif");
//	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_EXTRA_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_EX_ANI.gif");

	#endif
#ifdef __MMI_MATRIX_MAIN_MENU_FULL_BACKGROUND__
	ADD_APPLICATION_IMAGE(MAIN_MENU_MATRIX_SOFTKEY_BG,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/SK_BG.pbm");
#endif
	 
#endif //__MMI_MAINMENU_MATRIX_SUPPORT__

      /* Page */
 	#ifdef __MMI_MAINMENU_PAGE_SUPPORT__  
	#ifdef __MMI_UI_TECHNO_MAINMENU__
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_PB.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_MG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_FG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_OR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_ST.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_PR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_MM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_FM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Techno/MM_EX.png");
	 
	#elif defined (__MMI_UI_DALMATIAN_MAINMENU__)
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_PB.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_MG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_FG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_OR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_ST.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_PR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_MM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_FM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/Dalmatian/MM_EX.png");
	 
	#else
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_PB.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_MG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_FG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_OR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_ST.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_PR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_MM.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_FM.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_EX.gif");
	#endif

//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_PAGE_TITLE_BG,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/TB_BG.gif"); 
	#endif //__MMI_MAINMENU_PAGE_SUPPORT__

      /* List */
 	#ifdef __MMI_MAINMENU_LIST_SUPPORT__  
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_PB.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_MG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_FG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_OR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_ST.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_PR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_MM.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_FM.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/MM_EX.gif");

//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_LIST_TITLE_BG,CUST_IMG_PATH"/MainLCD/MainMenu/LIST/TB_BG.gif"); 
	#endif //__MMI_MAINMENU_LIST_SUPPORT__

      /* Circular */
	#ifdef __MMI_MAINMENU_CIRCULAR_SUPPORT__ 
	ADD_APPLICATION_IMAGE(IMG_MAIN_MENU_CIRCULAR_BG,	CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_BG.gif");  
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_PB.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_MG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_FG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_OR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_ST.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_PR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_MM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_FM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CIRCULAR_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_EX.png");
	#endif //__MMI_MAINMENU_CIRCULAR_SUPPORT__

	 /* Rotate */
	#ifdef __MMI_MAINMENU_ROTATE_SUPPORT__
	ADD_APPLICATION_IMAGE(IMG_MAIN_MENU_CIRCULAR_BG,	CUST_IMG_PATH"/MainLCD/MainMenu/CIRCULAR_3D/MM_BG.gif");  
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_PB.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_MG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_FG.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_OR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_ST.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_PR.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_MM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_FM.jpg");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ROTATE_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/ROTATE/MM_EX.png");
	#endif //__MMI_MAINMENU_ROTATE_SUPPORT__

	/* Tab */
	#ifdef __MMI_MAINMENU_TAB_SUPPORT__  
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_PHONEBOOK_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_PB.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_MG.JPG");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_FG.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_OR.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_ST.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_SC.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_SV.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_PR.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_CA.JPG");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_MM.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_FM.gif");
//del by reslim v0.1	ADD_APPLICATION_IMAGE(MAIN_MENU_TAB_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/TAB/TB_EX.gif");
	#endif //__MMI_MAINMENU_TAB_SUPPORT__


#else /* !__MMI_MAINMENU_STYLE_CHANGE_EN__ */
      /* Main menu is not able to change */
		ADD_APPLICATION_IMAGE(MAIN_MENU_PHONEBOOK_ICON,	CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_PB.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_MESSAGES_ICON,  CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_MG.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_FG.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_OR.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_ST.gif");
		//ADD_APPLICATION_IMAGE(MAIN_MENU_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_SC.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_SV.gif");
		//ADD_APPLICATION_IMAGE(MAIN_MENU_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_PR.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_CA.gif");

		ADD_APPLICATION_IMAGE(MAIN_MENU_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_MM.gif");
		//ADD_APPLICATION_IMAGE(MAIN_MENU_FILEMNGR_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_FM.gif");
		ADD_APPLICATION_IMAGE(MAIN_MENU_EXTRA_ICON,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_EX.gif");

	ADD_APPLICATION_IMAGE(MAIN_MENU_PHONEBOOK_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_PB_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MESSAGES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_MG_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_FUNANDGAMES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_FG_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_ORGANIZER_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_OR_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_SETTINGS_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_ST_ANI.gif");
	//ADD_APPLICATION_IMAGE(MAIN_MENU_SHORTCUTS_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_SC_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_SERVICES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_SV_ANI.gif");
	//ADD_APPLICATION_IMAGE(MAIN_MENU_PROFILES_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_PR_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_CALL_HISTORY_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_CA_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_MULTIMEDIA_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_MM_ANI.gif");
	//ADD_APPLICATION_IMAGE(MAIN_MENU_FILEMNGR_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_FM_ANI.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_EXTRA_ANIMATION,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_EX_ANI.gif");


#endif /* __MMI_MAINMENU_STYLE_CHANGE_EN__ */

#ifdef __MMI_WALLPAPER_ON_BOTTOM__ 
    /* Use 240x320 GIF because it is faster then BMP with hardware GIF decoder due to smaller data read from NOR Flash */
    //ADD_APPLICATION_IMAGE(IMG_MAIN_MENU_MATRIX_BG,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_BG.JPG"); ///WX changed here
    //ADD_APPLICATION_IMAGE(IMG_MAIN_MENU_PAGE_BG,CUST_IMG_PATH"/MainLCD/MainMenu/PAGE/MM_BG.GIF");
   // ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_EMPTY_ICON,CUST_IMG_PATH"/MainLCD/Titlebar/TB_transparent.pbm");
#endif
#if defined(__MMI_MAINLCD_128X128__)
	 
    ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_PHONEBOOK_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_PB.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_MESSAGES_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_MG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_FUNANDGAMES_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_FG.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_ORGANIZER_ICON,CUST_IMG_PATH"/MainLCD/Titlebar/TB_OR.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_SETTINGS_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_ST.gif");
	//ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_PROFILES_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_PR.gif");
	//ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_SHORTCUTS_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_SC.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_SERVICES_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_SV.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_CALL_HISTORY_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_CA.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_MULTIMEDIA_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_MM.gif");
	//ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_FILE_MNGR_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_FM.gif");
	ADD_APPLICATION_IMAGE(MAIN_MENU_TITLE_EXTRA_APP_ICON,CUST_IMG_PATH"/MainLCD/TitleBar/TB_EX.gif");
#endif 

	ADD_APPLICATION_STRING(STR_699_SYSTEM_SHUTDOWN,"ShutDown");
	ADD_APPLICATION_IMAGE2(IMG_MAIN_MENU_BG,CUST_IMG_PATH"/MainLCD/MainMenu/"IMG_DIR(__MMI_MAINMENU_TYPE__)"/MM_BG.gif","Background image in MainMenu");
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_MAIN_MENU_BG1,CUST_IMG_PATH"/MainLCD/MainMenu/MATRIX/MM_BG1.gif","Background image in MainMenu, related with theme");

}
#endif	// #if defined(__MMI_VERSION_2__)
#endif
#endif /* __MMI_BI_DEGREE_MAIN_MENU_STYLE__ */


