/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * Res_Jataayu.c
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   Populate Resource for Jataayu Browser/MMS.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/
#include "cs_types.h"
#include "custdatares.h"
#include "mmi_features.h" 

#include "stdc.h"
#include "customcfg.h"


#ifdef FIRST_PASS
#include "buildcfg.h"
#endif


#include "populateres.h"

//  JBRW Sandeep
#if defined (JATAAYU_SUPPORT)
#include "jwap_str_id.h"
#include "jmms_str_id.h"
#include "jprofilehandlerdefs.h"
#include "jprovdefs.h"
#include "messagesresourcedata.h"
#include "servicedefs.h"
#include "dataaccount.h"
#include "prv_str_id.h"
#ifdef __MMI_MULTI_SIM__
#include "mtpnp_ad_resdef.h"
#endif
//wap
void PopulateJaatayuBrowserRes(void)
{
//menu 
#ifdef JATAAYU_SUPPORT
#ifdef __PRODUCT_QPAD__                             		
	ADD_APPLICATION_MENUITEM((WAP_MAIN_SCREEN_MENUID, MAIN_MENU_FUNANDGAMES_MENUID, 6, \
		WAP_MAIN_HOMEPAGE_MENUID ,
		WAP_MAIN_FETCH_NEW_MENUID,
		WAP_MAIN_RECENT_MENUID,
		WAP_MAIN_BOOKMARKS_MENUID,
		WAP_MAIN_SETTINGS_MENUID,
		WAP_MAIN_ABOUT_US,
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_TEXT, MAIN_MENU_GAMES_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_HOMEPAGE_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_HOMEPAGE, MAIN_MENU_GAMES_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_FETCH_NEW_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_FETCH_URL, MAIN_MENU_GAMES_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_RECENT_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_RECENT, MAIN_MENU_GAMES_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_BOOKMARKS_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_BOOKMARKS, MAIN_MENU_GAMES_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_SETTINGS_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_SETTINGS, MAIN_MENU_GAMES_ICON));


	ADD_APPLICATION_MENUITEM((WAP_MAIN_ABOUT_US, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_ABOUT_US, MAIN_MENU_GAMES_ICON));
#else
	ADD_APPLICATION_MENUITEM((WAP_MAIN_SCREEN_MENUID, MAIN_MENU_FUNANDGAMES_MENUID, 6, \
		WAP_MAIN_HOMEPAGE_MENUID ,
		WAP_MAIN_FETCH_NEW_MENUID,
		WAP_MAIN_RECENT_MENUID,
		WAP_MAIN_BOOKMARKS_MENUID,
		WAP_MAIN_SETTINGS_MENUID,
		WAP_MAIN_ABOUT_US,
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_TEXT, IMG_ID_JATAAYU_WAP_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_HOMEPAGE_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_HOMEPAGE, IMG_ID_JATAAYU_WAP_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_FETCH_NEW_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_FETCH_URL, IMG_ID_JATAAYU_WAP_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_RECENT_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_RECENT, IMG_ID_JATAAYU_WAP_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_BOOKMARKS_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_BOOKMARKS, IMG_ID_JATAAYU_WAP_ICON));

	ADD_APPLICATION_MENUITEM((WAP_MAIN_SETTINGS_MENUID, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_SETTINGS, IMG_ID_JATAAYU_WAP_ICON));


	ADD_APPLICATION_MENUITEM((WAP_MAIN_ABOUT_US, WAP_MAIN_SCREEN_MENUID, 0, \
		SHOW,MOVEABLEWITHINPARENT|INSERTABLE,1,STR_ID_WAP_ABOUT_US, IMG_ID_JATAAYU_WAP_ICON));
#endif
/* Jataayu WAP Menu Insertion <end> */
	
	/* Jataayu MMS Menu Item <start> */

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_SCREEN_MENUID, MAIN_MENU_MESSAGES_MENUID, 7, \
		MMS_MAIN_NEW_MMS_MENUID,
		MMS_MAIN_INBOX_MENUID,
		MMS_MAIN_SENT_MENUID,
		MMS_MAIN_OUTBOX_MENUID,
		MMS_MAIN_DRAFT_MENUID,
		MMS_MAIN_SETTINGS_MENUID,
		MMS_MAIN_ABOUT_MENUID,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
#ifdef __PRODUCT_QPAD__                             		
		STR_ID_MMS_TEXT, MAIN_MENU_MESSAGE_ICON));
#else
		STR_ID_MMS_TEXT, IMG_MESSAGE_MMS_MENUENTRY));
#endif

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_NEW_MMS_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_NEW_MMS, NULL));

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_INBOX_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_INBOX, IMG_MESSAGE_SMS_MENUENTRY));

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_SENT_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_SENT, IMG_MESSAGE_SMS_MENUENTRY));

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_OUTBOX_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_OUTBOX, IMG_MESSAGE_SMS_MENUENTRY));

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_DRAFT_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_DRAFT, IMG_MESSAGE_SMS_MENUENTRY));

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_SETTINGS_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_SETTINGS, IMG_MESSAGE_SMS_MENUENTRY));

	ADD_APPLICATION_MENUITEM( (MMS_MAIN_ABOUT_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_ABOUT, IMG_MESSAGE_SMS_MENUENTRY));
	/* Jataayu MMS Menu Item <end> */
	//JIASHUO ADD FOR WAP/MMS,DATA ACCOUNT,START
    ADD_APPLICATION_MENUITEM((SERVICES_DATA_CONNECT_MAIN_MENU_ID,MAIN_MENU_SERVICES_MENUID,2,SERVICES_DATA_CONNECT_MENU_ID,SERVICES_DATA_CONNECT_GPRS_MENU_ID,
				SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,SERVICES_DATA_CONNECT_STRING_ID,IMG_ID_DATAACCOUNT_ICON));
	
    ADD_APPLICATION_MENUITEM((SERVICES_DATA_CONNECT_MENU_ID,SERVICES_DATA_CONNECT_MAIN_MENU_ID,0,
				SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,SERVICES_DATA_CONNECT_GSM_STRING_ID,IMG_ID_DATAACCOUNT_ICON));

	ADD_APPLICATION_MENUITEM((SERVICES_DATA_CONNECT_GPRS_MENU_ID,SERVICES_DATA_CONNECT_MAIN_MENU_ID,0,
				SHOW,MOVEABLEWITHINPARENT|INSERTABLE,DISP_LIST,SERVICES_DATA_CONNECT_GPRS_STRING_ID,IMG_ID_DATAACCOUNT_ICON));
	//JIASHUO ADD FOR WAP/MMS,DATA ACCOUNT,END
	ADD_APPLICATION_MENUITEM((MENU_ID_PH_CONNECTION_TYPE, 0, 2,
			MENU_ID_PH_CONN_TYPE_CONNECTION,
			MENU_ID_PH_CONN_TYPE_HTTP,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PROF_HDLR_CONN_TYPE, 0));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_PH_CONN_TYPE_CONNECTION,MENU_ID_PH_CONNECTION_TYPE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_CONN_TYPE_CONNECTION,0));	
	ADD_APPLICATION_MENUITEM((MENU_ID_PH_CONN_TYPE_HTTP,MENU_ID_PH_CONNECTION_TYPE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_CONN_TYPE_HTTP,0));	


	ADD_APPLICATION_MENUITEM((MENU_ID_PH_SELECT_PROFILE, 0, 2,
			MENU_ID_PH_SELECT_PROFILE_ACTIVATE,
			MENU_ID_PH_SELECT_PROFILE_EDIT,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_PH_SELECT_PROFILE_ACTIVATE,MENU_ID_PH_SELECT_PROFILE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_ACTIVATE_PROFILE,0));	
	ADD_APPLICATION_MENUITEM((MENU_ID_PH_SELECT_PROFILE_EDIT,MENU_ID_PH_SELECT_PROFILE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_EDIT_PROFILE,0));	
//string
//fengzb add begin
	ADD_APPLICATION_STRING2(STR_ID_PROV_INSTALL_SETTINGS_1 ,"Install New Settings ","Install New Settings");
	ADD_APPLICATION_STRING2(STR_ID_PROV_INVALID_BEARER,"Invalid Bearer","Invalid Bearer");
	ADD_APPLICATION_STRING2(STR_ID_PROV_MAX_QUE_SIZE ,"Settings List Full,Install Pending Settings" ,"Settings List Full,Install Pending Settings");
	ADD_APPLICATION_STRING2(STR_ID_PROV_INVALID_SETTINGS ,"Invalid Settings ","Invalid Settings");
	ADD_APPLICATION_STRING2(STR_ID_PROV_NEW_SETTINGS ,"New Settings","New Settings");	
	ADD_APPLICATION_STRING2(STR_ID_PROV_NEW_BOOKMARK ,"New Bookmark","New Bookmark");	
	ADD_APPLICATION_STRING2(STR_ID_PROV_ABORT_SETTINGS_SETUP,"Abort Setting Setup","Abort Setting Setup");
	ADD_APPLICATION_STRING2(STR_ID_PROV_DATAACCOUNT_CAPTION ,"Data Account","Data Account");	
	ADD_APPLICATION_STRING2(STR_ID_PROV_BOOKMARK_INVALID ,"Invalid  Bookmark","Invalid  Bookmark");
 
	ADD_APPLICATION_STRING2(STR_ID_PROV_BOOKMARK_STORED ,"Bookmark Saved","Bookmark Saved");	
	ADD_APPLICATION_STRING2(STR_ID_PROV_INSTALL_BOOKMARK ,"Install New Bookmark","Install New Bookmark");

    
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_SELECT_PROF_CAPTION ,"Select Profile","Select Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_ACTIVATE_PROFILE ,"Activate Profile","Activate Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_EDIT_PROFILE ,"Edit Profile","Edit Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_RENAME_PROFILE ,"Rename Profile","Rename Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_HOMEPAGE ,"Homepage","Homepage");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_MMSC_URL ,"MMSC URL","MMSC URL");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT ,"Data Account","Data Account");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE ,"Connection Type","Connection Type");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_USER_NAME ,"User Name","User Name");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PASSWORD ,"Password","Password");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_SAVED ,"Saved","Saved");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE_CONNECTION ,"Connection-Oriented","Connection-Oriented");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE_HTTP ,"HTTP","HTTP");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_IP_ADDRESS ,"IP Address","IP Address");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PROXY_ADDRESS ,"Proxy Address","Proxy Address");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_SECURITY ,"Security","Security");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PORT ,"Proxy Port","Proxy Port");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_OFF ,"Off","Off");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_ON ,"On","On");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PROFILE ,"Profile","Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_INVALID_INPUT ,"Invalid Input","Invalid Input");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_INVALID_IP ,"Invalid IP Address","Invalid IP Address");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DEFAULT_PROFILE_NAME ,"Profile","Profile");
//fengzb add end

	ADD_APPLICATION_STRING2(STR_ID_PROV_NEWPROV_ALERT	,"New SIM%d Settings","New SIM%d Settings");
	ADD_APPLICATION_STRING2(STR_ID_PROV_ENTER_PIN	,"Enter PIN","Enter PIN");
	ADD_APPLICATION_STRING2(STR_ID_PROV_DISCARD_CONFIRMATION	,"Discard?","Discard?");
	ADD_APPLICATION_STRING2(STR_ID_PROV_DISCARD_SUCC_MSG	,"Discarded","Discarded");
	ADD_APPLICATION_STRING2(STR_ID_PROV_SAVE_CONFIRMATION	,"Save and Activate?","Save and Activate?");
	ADD_APPLICATION_STRING2(STR_ID_PROV_SAVE_SUCC_MSG	,"Saved Successfully","Saved Successfully");
	ADD_APPLICATION_STRING2(STR_ID_PROV_FAIL_MSG	,"Provisioning Failed","Provisioning Failed");
	ADD_APPLICATION_STRING2(STR_ID_PROV_NET_ERROR	,"Network Error","Network Error");
	ADD_APPLICATION_STRING2(STR_ID_PROV_DOWNLOAD	,"Download","Download");
	ADD_APPLICATION_STRING2(STR_ID_PROV_TITLE	,"Provisioning","Provisioning");
	ADD_APPLICATION_STRING2(STR_ID_PROV_DISCARD	,"Discard","Discard");
	ADD_APPLICATION_STRING2(STR_ID_PROV_BROW_PROFILE	,"Browser Profile","Browser Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROV_MMS_PROFILE	,"MMS Profile","MMS Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROV_INAVLID_PIN_TRYAGAIN,"Invalid PIN . Please Try Again","Invalid PIN . Please Try Again");
	ADD_APPLICATION_STRING2(STR_ID_PROV_ERR_UNKNOWN,"Unknown Error","Unknown Error");
	ADD_APPLICATION_STRING2(STR_ID_PROV_USEPIN_AUTH_FAIL,"Authentication Failed","Authentication Failed");
	ADD_APPLICATION_STRING2(STR_ID_PROV_INSTALL,"Install","Install");
	ADD_APPLICATION_STRING2(STR_ID_PROV_INSTALL_SETTINGS,"Install Settings","Install Settings");
	ADD_APPLICATION_STRING2(STR_ID_PROV_NEW_SETTINGS,"New Setting","New Setting");
	ADD_APPLICATION_STRING2(STR_ID_PROV_SUMMARY_REPORT,"Summary Report","Summary Report");
	ADD_APPLICATION_STRING2(STR_ID_PROV_DATA_ACCOUNT,"Data Account","Data Account");
       ADD_APPLICATION_STRING2(STR_ID_PROV_INVALID_SETTING,"Invalid settings ","Invalid settings ");
       
       ADD_APPLICATION_STRING2(	STR_ID_PROV_REPLACE_PROFILE,"Replace Profile","Replace Profile");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_SETTINGSFOR,"Settings For","Settings For");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_DOWNLOAD_SETTINGS,"Download settings from","Download settings from");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_PROFILE_NAME,"Profile Name","Profile Name");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_PROFILE_ID,"Profile ID","Profile ID");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_USERNAME,"User Name","User Name");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_PASSWORD,"PassWord","PassWord");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_PROXYIP,"ProxyIP","ProxyIP");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_PORT,"Port","Port");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_NAP_ID,"NAP ID","NAP ID");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_HOMEPAGE,"Home Page","Home Page");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_MMSC_URL,"MMSC URL","MMSC URL");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_DNS1,"DNS1","DNS1");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_DNS2,"DNS2","DNS2");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_APN,"APN","APN");
       ADD_APPLICATION_STRING2(	STR_ID_PROV_REPLACE_CONFIRMATION,"Max profiles exceeded. Replace with existing profile?","Max profiles exceeded. Replace with existing profile?");

    	ADD_APPLICATION_STRING2(STR_ID_VIEW_URL,"View URL","View URL");
	ADD_APPLICATION_STRING2(STR_ID_SET_AS_HOMEPAGE_URL	,"Set As HomePage","Set As HomePage");
	ADD_APPLICATION_STRING2(STR_ID_MMS_SAVE_MEDIA	,"Save Media","Save Media");
    	ADD_APPLICATION_STRING2(STR_ID_MMS_INSERT_VIDEO	,"Insert Video","Insert Video");	
	ADD_APPLICATION_STRING2(STR_ID_MMS_DELETE_VIDEO	,"Delete Video","Delete Video");
	ADD_APPLICATION_STRING2(STR_ID_MMS_CNF_IMAGE_ADD,"Image already exists. Do you want to Replace?","Image already exists. Do you want to Replace?");
	ADD_APPLICATION_STRING2(STR_ID_MMS_CNF_AUDIO_ADD,"Audio already exists. Do you want to Replace?","Audio already exists. Do you want to Replace?");
    	ADD_APPLICATION_STRING2(STR_ID_MMS_CNF_VIDEO_ADD,"Video already exists. Do you want to Replace?","Video already exists. Do you want to Replace?");	
	ADD_APPLICATION_STRING2(STR_ID_MMS_CNF_IMAGE_AUDIO_ADD,"Image & Audio already exists. Do you want to Replace?","Image & Audio already exists. Do you want to Replace?");
	ADD_APPLICATION_STRING2(STR_ID_MMS_VIDEO_DELETED,"Video deleted","Video deleted");	
    
//jiashuo add for data account,start
ADD_APPLICATION_STRING2(SERVICES_DATA_CONNECT_STRING_ID,"Data Account","Data Account");
ADD_APPLICATION_STRING2(SERVICES_DATA_CONNECT_GSM_STRING_ID,"GSM Data","GSM Data account");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_CAPTION ,"Data Account","Title String for Data Acouunt main screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_RENAME,"Account Name"," Rename String for Data Account Screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_DIAL_NUMBER,"Number"," Dial Number String for Data Account Screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_USER_NAME,"User Name","User mane String for Data Account Screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_PASSWD,"Password"," Password String for Data Account Screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_DIAL_TYPE,"Line Type"," Dial Type String for Data Account Screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_DATA_RATE,"Speed"," Data Rate String for Data Account Screen");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_DNS_ADDRESS,"DNS"," DNS Address String for Data Account Screen");
//ADD_APPLICATION_STRING2(STR_ID_DTCNT_SAVE_QUERY ,"Save"," Querry to User");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_ANALOGUE_STR ,"Analogue"," String of Dial Type");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_ISDN_STR ,"ISDN"," String of Dial Type");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_RATE_STR_ONE ,"4.8 Kbps "," String of Dial Rate 1");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_RATE_STR_TWO ,"9.6 Kbps"," String of Dial Rate 2");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_RATE_STR_THREE ,"14.4 Kbps"," String of Dial Rate 3");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME ,"Account "," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_ONE ,"Account 1"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_TWO ,"Account 2"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_THREE ,"Account 3"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_FOUR ,"Account 4"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_FIVE ,"Account 5"," Default Account Name");
//micha1230
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_SIX ,"Account 6"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_SEVEN ,"Account 7"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_EIGHT ,"Account 8"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_NINE ,"Account 9"," Default Account Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_NAME_TEN ,"Account 10"," Default Account Name");
//micha0120
#ifdef __MMI_GPRS_FEATURES__
ADD_APPLICATION_STRING2(SERVICES_DATA_CONNECT_GPRS_STRING_ID,"GPRS","GPRS Data account");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_GPRS_PAP_AUTH ,"Normal"," GPRS PAP Auth.");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_GPRS_CHAP_AUTH ,"Secure"," GPRS CHAP Auth.");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_GPRS_APN ,"APN"," GPRS APN Name");
ADD_APPLICATION_STRING2(STR_ID_DTCNT_GPRS_AUTH_TYP ,"Auth. Type"," GPRS Authentication Type");
ADD_APPLICATION_STRING2(SERVICES_DATA_CONNECT_MAIN_STRING_ID,"Data Account","Data Connect Menu Item String");
#endif
//jiashuo add for data account,end
//jataayu add begin

ADD_APPLICATION_STRING(STR_ID_WAP_NON_AUTHORITATIVE,"Non Authoritative");
 ADD_APPLICATION_STRING(STR_ID_WAP_NO_CONTENT,"No Content");
ADD_APPLICATION_STRING( STR_ID_WAP_MOVED_PERMANENTLY,"Moved Permanently");
ADD_APPLICATION_STRING( STR_ID_WAP_MOVED_TEMPORARILY,"Moved Temporarily");
ADD_APPLICATION_STRING( STR_ID_WAP_BAD_REQUEST,"Bad Request");
ADD_APPLICATION_STRING( STR_ID_WAP_UNAUTHORIZED,"Unauthorized");
ADD_APPLICATION_STRING( STR_ID_WAP_PAYMENT,"Payment");
ADD_APPLICATION_STRING( STR_ID_WAP_FORBIDDEN,"Forbidden");
ADD_APPLICATION_STRING( STR_ID_WAP_NOT_FOUND,"Not Found");
ADD_APPLICATION_STRING( STR_ID_WAP_METHOD_NOT_ALLOWED,"Method not allowed");
ADD_APPLICATION_STRING( STR_ID_WAP_NOT_ACCEPTABLE,"Not Acceptable");
ADD_APPLICATION_STRING( STR_ID_WAP_REQUEST_TIMEOUT,"Request Timeout");
ADD_APPLICATION_STRING( STR_ID_WAP_CONFLICT,"Conflict");
ADD_APPLICATION_STRING( STR_ID_WAP_REQUEST_ENTITY_TOO_LARGE,"Request Entity Too Large");
ADD_APPLICATION_STRING( STR_ID_WAP_REQUEST_URI_TOO_LARGE,"Request URI Too Large");
ADD_APPLICATION_STRING( STR_ID_WAP_UNSUPPORTED_MEDIA_TYPE,"Unsupported media type");
ADD_APPLICATION_STRING( STR_ID_WAP_INTERNAL_SERVER_ERROR,"Internal Server Error");
ADD_APPLICATION_STRING( STR_ID_WAP_NOT_IMPLEMENTED,"Not implemented");
ADD_APPLICATION_STRING( STR_ID_WAP_BAD_GATEWAY,"Bad Gateway");
ADD_APPLICATION_STRING( STR_ID_WAP_SERVICE_UNAVAILABLE,"Service Unavailable");
ADD_APPLICATION_STRING( STR_ID_WAP_GATEWAY_TIMEOUT,"Gateway Timeout");
ADD_APPLICATION_STRING( STR_ID_WAP_BAD_VERSION,"Bad Version");
ADD_APPLICATION_STRING(STR_ID_WAP_NETWORK_ERROR,"Network Error");
ADD_APPLICATION_STRING( STR_ID_WAP_HTTP_UNKNOWN,"HTTP Error");
ADD_APPLICATION_STRING( STR_ID_WAP_UNKNOWN,"Unknown Error");
 
ADD_APPLICATION_STRING(STR_ID_WAP_TEXT,"WAP");
ADD_APPLICATION_STRING(STR_ID_WAP_HOMEPAGE,"Home Page");
ADD_APPLICATION_STRING(STR_ID_WAP_FETCH_URL,"Goto URL");
ADD_APPLICATION_STRING(STR_ID_WAP_RECENT,"Recent Visits");
ADD_APPLICATION_STRING(STR_ID_WAP_BOOKMARKS,"Favorites");
ADD_APPLICATION_STRING(STR_ID_WAP_HISTORY_GO,"Goto URL");
ADD_APPLICATION_STRING(STR_ID_WAP_HISTORY_CLEAR,"Clear");
ADD_APPLICATION_STRING(STR_ID_WAP_HISTORY_CLEARALL,"Clear all");
ADD_APPLICATION_STRING(STR_ID_WAP_NEW_URL,"New URL");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS,"Settings");
ADD_APPLICATION_STRING(STR_ID_WAP_ABOUT_US,"About Us");
ADD_APPLICATION_STRING(STR_ID_WAP_OPTIONS_REFRESH,"Refresh");
ADD_APPLICATION_STRING(STR_ID_WAP_OPTIONS_NEXT,"Next");
ADD_APPLICATION_STRING(STR_ID_WAP_OPTIONS_SAVEIMAGE,"Save Image");
ADD_APPLICATION_STRING(STR_ID_WAP_OPTIONS_SAVEPAGE,"Save Page");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_OPEN, "Open");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_EDIT, "Edit");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_ADD, "Add Bookmark");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_CLEAR, "Delete");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_CLEARALL, "Delete All");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_FAV, "Favourites");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_TITLE, "Title");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_URL, "URL");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_ALREADY_EXITS, "Favourite All Ready Exists");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_MAX_LIMIT, "Maxium Limit Reached");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_NO_FAV, "No Favourites");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_WRONG_URL, "Wrong URL");
ADD_APPLICATION_STRING(STR_ID_WAP_BM_NO_URL, "Please enter the URL");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_DATACONN, "Data Connection");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_CLEAR_CACHE, "Clear Cache");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_CLEAR_COOKIE, "Clear Cookie");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_OPTIONS, "Options");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_GRAPHICS, "Graphics");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_TIMEOUT, "Timeout");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_30S, "30 sec");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_60S, "60 sec");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_100S, "100s");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_CACHE, "Cache");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_COOKIE, "Cookie");
ADD_APPLICATION_STRING(STR_ERR_NET_INIT, "Net Init Error");
ADD_APPLICATION_STRING(STR_ERR_NET_CONNECT, "Net Connect Error");
ADD_APPLICATION_STRING(STR_ERR_NET_DNS_RESOLVE, "Net DNS Resolve Error");
ADD_APPLICATION_STRING(STR_ERR_NET_TIMEOUT, "Net Timeout Error");
ADD_APPLICATION_STRING(STR_ERR_NET_SEND, "Net Send Error");
ADD_APPLICATION_STRING(STR_ERR_NET_RECV, "Net Recv Error");
ADD_APPLICATION_STRING(STR_ERR_NET_SOCKET, "Net Socket Error");
ADD_APPLICATION_STRING(STR_ERR_NET_SOCKET_NOT_READY, "Socket Not Ready");
ADD_APPLICATION_STRING(STR_ERR_NET_SET_SOCKOPT, "Set Socket Opt Error");
ADD_APPLICATION_STRING(STR_ERR_NET_GET_SOCKOPT, "Get Socket Opt Error");
ADD_APPLICATION_STRING(STR_ERR_NET_WOULDBLOCK, "Wouldblock Error");
ADD_APPLICATION_STRING(STR_ERR_NET_ACCEPT, "Net Accept Error");
ADD_APPLICATION_STRING(STR_ERR_NET_LISTEN, "Net Listen Error");
ADD_APPLICATION_STRING(STR_ERR_NET_CONN_ABORT, "Net Connection Abort");
ADD_APPLICATION_STRING(STR_ERR_NET_DNS_WOULDBLOCK, "DNS Wouldblock Error");
ADD_APPLICATION_STRING(STR_ERR_NET_SOCKET_FULL, "Socket Full Error");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_CANCEL, "Data Connection Cancel");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_CONTINUER, "Data Connection Continue Error");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_LINE_BUSY, "Data Connetion Line Busy");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_INVALID_USERNAME, "Data Connection Invalid User Name");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_INVALID_PASSWORD, "Data Connection Invalid Password");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_NO_DIALTONE, "Data Connection No Dailtone");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_INVALID_APN, "Data Connection Invalid APNt");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_TIMEOUT, "Data Connection Timeout");
ADD_APPLICATION_STRING(STR_ERR_DATA_CONN_UNKNOWN, "Data Connection Unknown error");

ADD_APPLICATION_STRING(STR_ID_MMS_TEXT, "MMS");
ADD_APPLICATION_STRING(STR_ID_MMS_NEW_MMS, "New MMS");
ADD_APPLICATION_STRING(STR_ID_MMS_INBOX, "Inbox");
ADD_APPLICATION_STRING(STR_ID_MMS_SENT, "Sent");
ADD_APPLICATION_STRING(STR_ID_MMS_OUTBOX, "Outbox");
ADD_APPLICATION_STRING(STR_ID_MMS_DRAFT, "Draft");	
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE, "Template");
ADD_APPLICATION_STRING(STR_ID_MMS_SETTINGS, "Message Settings");
ADD_APPLICATION_STRING(STR_ID_MMS_ABOUT, "About Us");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_TO, "TO:");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_CC, "CC:");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_BCC, "BCC:");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_SUB, "Subject");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_INSERTCONTENT, "Insert Content");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_DELETECONTENT, "Delete Content");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_TO_ADDNUMBER,"Add Number");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_TO_ADDEMAIL, "Add Email");
ADD_APPLICATION_STRING(STR_ID_MMS_EDIT_DONE,"Done");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_TO_ADDNUMBER_PHONEBOOK,"Phone Book");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDR_TO_ADDEMAIL_PHONEBOOK,"Phone Book");
ADD_APPLICATION_STRING(STR_ID_MMS_ADDRESS,"Address");
ADD_APPLICATION_STRING(STR_ID_MMS_INSERT_IMAGE,"Add Image");
ADD_APPLICATION_STRING(STR_ID_MMS_INSERT_AUDIO,"Add Audio");
ADD_APPLICATION_STRING(STR_ID_MMS_EDIT_TEXT,"Edit Text");
ADD_APPLICATION_STRING(STR_ID_MMS_ADD_SLIDE,"Add Slide");
ADD_APPLICATION_STRING(STR_ID_MMS_SET_SLIDE_TIMER,"Set Slide Timer");
ADD_APPLICATION_STRING(STR_ID_MMS_PREVIEW,"Preview");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE1, "I'll be late");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE2, "I am busy now");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE3, "Take care");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE4, "Call me");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE5, "Happy birthday");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE6, "How about lunch?");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE7, "Be right back");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE8, "Sorry");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE9, "Thank you");
ADD_APPLICATION_STRING(STR_ID_MMS_TEMPLATE10, "How was the day?");
ADD_APPLICATION_STRING(STR_ID_MMS_SERVER_PROFILE, "Server Profile"); 
ADD_APPLICATION_STRING(STR_ID_MMS_COMPOSE,  "Compose");
ADD_APPLICATION_STRING(STR_ID_MMS_SEND, "Send");
ADD_APPLICATION_STRING(STR_ID_MMS_RETRIEVE, "Retrieve");
ADD_APPLICATION_STRING(STR_ID_MMS_CREATE_MODE, "Create mode");
ADD_APPLICATION_STRING(STR_ID_GLOBAL_ON, "On");
ADD_APPLICATION_STRING(STR_ID_GLOBAL_OFF, "Off");
ADD_APPLICATION_STRING(STR_ID_MMS_AUTO_SIGNATURE, "Auto signature");
ADD_APPLICATION_STRING(STR_ID_MMS_SIGNATURE, "Signature");
ADD_APPLICATION_STRING(STR_ID_MMS_VALIDITY_PERIOD, "Validity period");
ADD_APPLICATION_STRING(STR_ID_MMS_MAX, "Max");
ADD_APPLICATION_STRING(STR_ID_MMS_1HOUR, "1 Hour");
ADD_APPLICATION_STRING(STR_ID_MMS_12HOUR, "12 Hours");
ADD_APPLICATION_STRING(STR_ID_MMS_1DAY, "1 Day");
ADD_APPLICATION_STRING(STR_ID_MMS_1WEEK, "1 Week");
ADD_APPLICATION_STRING(STR_ID_MMS_DELIVERY_REPORT, "Delivery report");
ADD_APPLICATION_STRING(STR_ID_MMS_READ_REPORT, "Read report");
ADD_APPLICATION_STRING(STR_ID_MMS_PRIORITY, "Priority");
ADD_APPLICATION_STRING(STR_ID_MMS_HIGH, "High");
ADD_APPLICATION_STRING(STR_ID_MMS_LOW, "Low");
ADD_APPLICATION_STRING(STR_ID_MMS_NORMAL, "Normal");
ADD_APPLICATION_STRING(STR_ID_MMS_NONE, "None");
ADD_APPLICATION_STRING(STR_ID_MMS_SLIDE_TIMING, "Slide Timing");
ADD_APPLICATION_STRING(STR_ID_MMS_DELIVERY_TIME, "Delivery time");
ADD_APPLICATION_STRING(STR_ID_MMS_IMMEDIATE, "Immediate");
ADD_APPLICATION_STRING(STR_ID_MMS_IN1HOUR, "In 1 hour");
ADD_APPLICATION_STRING(STR_ID_MMS_IN12HOUR, "In 12 hours");
ADD_APPLICATION_STRING(STR_ID_MMS_IN24HOUR, "In 24 hours");
ADD_APPLICATION_STRING(STR_ID_MMS_HOME_NETWORK, "Home network");
ADD_APPLICATION_STRING(STR_ID_MMS_REJECTED, "Rejected");
ADD_APPLICATION_STRING(STR_ID_MMS_DELAYED, "Delayed");
ADD_APPLICATION_STRING(STR_ID_MMS_ON_REQUEST, "On request");
ADD_APPLICATION_STRING(STR_ID_MMS_NEVER_SEND, "Never send");
ADD_APPLICATION_STRING(STR_ID_MMS_CNF_SAVE, "Do you want to save?");
ADD_APPLICATION_STRING(STR_ID_MMS_INF_SUCCESS, "Success");
ADD_APPLICATION_STRING(STR_ID_MMS_INF_FAIL, "Fail");
ADD_APPLICATION_STRING(STR_ID_MMS_FREE, "Free");
ADD_APPLICATION_STRING(STR_ID_MMS_RESTRICTED, "Restricted");
ADD_APPLICATION_STRING(STR_ID_MMS_VIEW_MSG, "View");
ADD_APPLICATION_STRING(STR_ID_MMS_REPLY, "Reply");
ADD_APPLICATION_STRING(STR_ID_MMS_REPLY_BY_SMS, "Reply by sms");
ADD_APPLICATION_STRING(STR_ID_MMS_REPLY_ALL, "reply all");
ADD_APPLICATION_STRING(STR_ID_MMS_FORWARD, "forward");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETE, "Delete");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETE_ALL, "Delete all");
ADD_APPLICATION_STRING(STR_ID_WAP_HTTPDWN_DWNLOAD_CONFIRM, "Do you want to download?");
ADD_APPLICATION_STRING(STR_ID_WAP_HTTPDWN_DWNLOAD_SUCESS, "Download sucessfull");
ADD_APPLICATION_STRING(STR_ID_WAP_HTTPDWN_FILE_EXISTS, "File with name already exists");
ADD_APPLICATION_STRING(STR_ID_WAP_HTTPDWN_DWNLD_PROGRESS, "Downloading...");
ADD_APPLICATION_STRING(STR_ID_WAP_HTTPDWN_FILENAME, "File name");
ADD_APPLICATION_STRING(STR_ID_WAP_FILE_SYSTEM_FULL, "Not Enough Space");
ADD_APPLICATION_STRING(STR_ID_WAP_NO_MEMORY_CARD, "No Memory Card");
ADD_APPLICATION_STRING(STR_ID_MMS_SENDING, "Sending...");
ADD_APPLICATION_STRING(STR_ID_STOP, "Stop");
ADD_APPLICATION_STRING(STR_ID_MMS_RESEND, "ReSend");
ADD_APPLICATION_STRING(STR_ID_MMS_EDIT_MESSAGE, "Edit Message");
ADD_APPLICATION_STRING(STR_ID_MMS_PROPERTY, "Properties");
ADD_APPLICATION_STRING(STR_ID_WAP_NO_HISTORY,"No Recent Pages");
ADD_APPLICATION_STRING(STR_ID_WAP_AUTHORIZATION,"Authorization Required");
ADD_APPLICATION_STRING(STR_ID_WAP_USER_NAME,"User Name");
ADD_APPLICATION_STRING(STR_ID_WAP_PASSWORD,"Password");
ADD_APPLICATION_STRING(STR_ID_WAP_SETTING_PROFILES,"Active Profile");
ADD_APPLICATION_STRING(STR_ID_WAP_CLEAR_CONFIRMATION,"Do you want to clear");
ADD_APPLICATION_STRING(STR_ID_WAP_CLEAR_ALL_CONFIRMATION,"Do you want to clear all");
ADD_APPLICATION_STRING(STR_ID_WAP_ADD_TO_BM,"Add To Bookmark");
ADD_APPLICATION_STRING(STR_ID_MMS_WARNING,"Warning");
ADD_APPLICATION_STRING(STR_ID_MMS_LAST_PAGE,"Arrived Last Page");
ADD_APPLICATION_STRING(STR_ID_MMS_FIRST_PAGE,"Arrived First Page");
ADD_APPLICATION_STRING(STR_ID_WAP_CONNECTING,"Connecting");
ADD_APPLICATION_STRING(STR_ID_WAP_GO,"Go");
ADD_APPLICATION_STRING(STR_ID_WAP_NAVIGATION,"Navigation");
ADD_APPLICATION_STRING(STR_ID_WAP_NO_FILE_NAME,"Please enter the file name");
ADD_APPLICATION_STRING(STR_ID_MMS_SLIDE_ADD_FAIL,"Slide adding failed");
ADD_APPLICATION_STRING(STR_ID_MMS_MSG_SEND_SUCCESS,"Message send success");
ADD_APPLICATION_STRING(STR_ID_MMS_SLIDE_DELETED,"Slide deleted");
ADD_APPLICATION_STRING(STR_ID_MMS_IMAGE_DELETED,"Image deleted");
ADD_APPLICATION_STRING(STR_ID_MMS_NO_MEDIA_TO_DELETE,"No Media to Delete");
ADD_APPLICATION_STRING(STR_ID_MMS_ADD_ADDRESS,"Cannot send MMS. Please add address");
ADD_APPLICATION_STRING(STR_ID_MMS_FOLDER_EMPTY,"Folder empty");
ADD_APPLICATION_STRING(STR_ID_MMS_MESSAGE_DELETE_SUCCESS,"Message delete success");
ADD_APPLICATION_STRING(STR_ID_MMS_MESSAGE_RECIEVED,"Message Received");
//ADD_APPLICATION_STRING(STR_ID_MMS_CNF_MEDIA_ADD,"Media already exists Do you want to Add ?");
ADD_APPLICATION_STRING(STR_ID_MMS_ERR_CONTENT_CLASS,"Content class Error. Change to Free?");
ADD_APPLICATION_STRING(STR_ID_MMS_MEDIA_CONTENT_UNS,"Unsupported media content");
ADD_APPLICATION_STRING(STR_ID_MMS_MEDIA_CONTENT_CORRUPT,"Corrupted media content");
ADD_APPLICATION_STRING(STR_ID_MMS_DRM_UNS,"DRM Not Supported");
ADD_APPLICATION_STRING(STR_ID_MMS_MESSAGE_SIZE_EXCEED,"Message size exceeds");
ADD_APPLICATION_STRING(STR_ID_MMS_ENTER_WARNING,"Enter Between 1 and 60");
ADD_APPLICATION_STRING(STR_ID_MMS_MAX_LIMIT,"Maximum limit has reached");
ADD_APPLICATION_STRING(STR_ID_MMS_CNF_MEDIA_TYPE,"Media Type Exists");
ADD_APPLICATION_STRING(STR_ID_MMS_ADD_MEDIA_FAILED,"Failed to add Media");
ADD_APPLICATION_STRING(STR_ID_MMS_AUDIO_DELETED,"Audio deleted");
ADD_APPLICATION_STRING2(STR_ID_JMMS_MMS_DOWNLAOD_SUCCESS,"MMS Downloaded Successfully","MMS Downloaded Successfully");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_FROM,"From:","From:");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_DATE,"Date:","Date:");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_TIME,"Time:","Time:");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_STATUS,"Status:","Status:");
ADD_APPLICATION_STRING2(STR_ID_MMS_READREPORT_SENT_SUCCESS,"Read Report Sent Successfully","Read Report Sent Successfully");
ADD_APPLICATION_STRING2(STR_ID_MMS_READREPORT_SENT_FAIL,"Read Report Sent Fail","Read Report Sent Fail");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_VERSION,"Version:","Version:");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_DETAILS, "Details:", "Details:");
ADD_APPLICATION_STRING2(STR_ID_MMS_MSG_TYPE,"Type:","Type:");	

ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_EXPIRED,"Expired","Expired");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_RETRIEVED,"Retrieved","Retrieved");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_REJECTED,"Rejected","Rejected");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_DEFFERED," Deferred"," Deferred");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_UNRECOGNISED,"Unrecognized","Unrecognized");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_INDETERMINATE,"Indeterminate","Indeterminate");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_FORWARDED,"Forwarded","Forwarded");
ADD_APPLICATION_STRING2(STR_ID_JMMS_DELIVERY_STATUS_UNREACHABLE,"Unreachable","Unreachable");


//add by Renyh
ADD_APPLICATION_STRING(STR_ID_MMS_PREVIEW_LSK_BLANK," ");
ADD_APPLICATION_STRING(STR_ID_MMS_PREVIEW_PLAY,"Play");
ADD_APPLICATION_STRING(STR_ID_MMS_ADD_ATTACHMENT,"Add Attachment");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETE_IMAGE,"Delete Image");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETE_AUDIO,"Delete Audio");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETE_ATTACHMENT,"Delete Attachment");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETE_SLIDE,"Delete Slide");
ADD_APPLICATION_STRING(STR_ID_MMS_INFO_NEW_SLIDE,"New Slide Added");
ADD_APPLICATION_STRING(STR_ID_MMS_ATTACHMENT_DELETED,"Attachment deleted");
ADD_APPLICATION_STRING(STR_ID_MMS_INFO_IMAGE_DELETE,"No image to delete");
ADD_APPLICATION_STRING(STR_ID_MMS_INFO_AUDIO_DELETE,"No audio to delete");
ADD_APPLICATION_STRING(STR_ID_MMS_INFO_ATTACHMENT_DELETE,"No attachment to delete");
ADD_APPLICATION_STRING(STR_ID_MMS_CNF_DELETE,"Do you want to Delete");
ADD_APPLICATION_STRING(STR_ID_MMS_FEATURE_NOT_IMP,"Feature not Implmented");
ADD_APPLICATION_STRING(STR_ID_MMS_WARNING_CONTENT_CLASS,"Content Class Warning");

//add by Renyh
ADD_APPLICATION_STRING(STR_ID_WAP_HTTPDWN_DWNLOAD_CONFIRM, "Download?");
ADD_APPLICATION_STRING(STR_ID_WAP_DL_CONTENT_TYPE,"Type");
ADD_APPLICATION_STRING(STR_ID_WAP_DL_CONTENT_SIZE,"Size");
ADD_APPLICATION_STRING(STR_ID_MMS_SUBJECT,"Subject");
//ADD_APPLICATION_STRING(STR_ID_MMS_CNF_MEDIA_ADD,"Media already exists. Do you want to Replace?");
ADD_APPLICATION_STRING(STR_ID_MMS_MAX_RECIPIENT_ADDED,"Maximum recipient added");
ADD_APPLICATION_STRING(STR_ID_SEND_READ_REPORT,"Do You Want to send Read Report");
ADD_APPLICATION_STRING(STR_ID_MMS_MSG_RESTRICTED,"Restricted media. Do you want to add?");
ADD_APPLICATION_STRING(STR_ID_MMS_RECIPIENT_EXITS,"Recipient already exists");

//add by zhangm
#ifdef __MMI_MULTI_SIM__
ADD_APPLICATION_STRING2(STR_ID_MULTI_SIM_CARD_MENU ,"Select SIM Card","Select SIM Card");
ADD_APPLICATION_STRING2(STR_ID_WAP_SIMTYPE_ALWAYS_ASK ,"Always Ask","Always Ask");
#endif

ADD_APPLICATION_STRING(STR_ID_MMS_CNF_DELETE_ALL,"Do you want to delete all");
ADD_APPLICATION_STRING(STR_ID_MMS_CNF_RESTRICTED_MEDIA,"Restricted Media");
ADD_APPLICATION_STRING(STR_ID_MMS_CONTENT_CLASS, "Content Class") ;
ADD_APPLICATION_STRING(STR_ID_MMS_CONTENT_CLASS_TEXT, "Text Class") ;
ADD_APPLICATION_STRING(STR_ID_MMS_CONTENT_CLASS_IMAGE_BASIC, "Image Basic") ;
ADD_APPLICATION_STRING(STR_ID_MMS_CONTENT_CLASS_IMAGE_RICH, "Image Rich") ;
ADD_APPLICATION_STRING(STR_ID_MMS_CONTENT_CLASS_VIDEO_BASIC, "Video Basic") ;
ADD_APPLICATION_STRING(STR_ID_MMS_CONTENT_CLASS_VIDEO_RICH, "Video Rich") ;

ADD_APPLICATION_STRING(STR_ID_MMS_INF_SEND_FAIL,"MMS Send Fail");
ADD_APPLICATION_STRING(STR_ID_MMS_INF_VIEW_FAIL,"Failed to open");
ADD_APPLICATION_STRING(STR_ID_MMS_INF_TEXT_MISSING,"/*Some Text Missing*/");

ADD_APPLICATION_STRING(STR_ID_WAP_SETTINGS_NO_TIMEOUT,"No limit");
ADD_APPLICATION_STRING(STR_ID_MMS_DOWNLOAD,"Download");
ADD_APPLICATION_STRING(STR_ID_MMS_DOWNLOADING,"Message Downloading...");
ADD_APPLICATION_STRING(STR_ID_MMS_FILE_SYSTEM_FULL,"Not Enough Space");

ADD_APPLICATION_STRING(STR_ID_MMS_ENTER_VALID_INPUT,"Enter Valid Input");
ADD_APPLICATION_STRING(STR_ID_MMS_ENTER_VALID_PHONE_NUMBER,"Enter Valid phone number");
ADD_APPLICATION_STRING(STR_ID_MMS_ENTER_VALID_EMAIL_ID,"Enter Valid Email ID");
ADD_APPLICATION_STRING(STR_ID_MMS_MEMORY_STATUS, "Memory Status");
ADD_APPLICATION_STRING(STR_ID_MMS_SETTINGS_USAGE,"Usage");
ADD_APPLICATION_STRING(STR_ID_MMS_SETTINS_USED,"Used");
ADD_APPLICATION_STRING(STR_ID_MMS_SETTINGS_FREE, "Free");
ADD_APPLICATION_STRING(STR_ID_MMS_DELETING, "Deleting...");
ADD_APPLICATION_STRING(STR_ID_MMS_DRM_NOT_SUPPORTED, "DRM Not Supported");
ADD_APPLICATION_STRING(STR_ID_MMS_ABOUT_US_MMS_CLIENT, "MMS Client");
ADD_APPLICATION_STRING(STR_ID_MMS_ABOUT_US_VERSION, "Version: 1.0");
ADD_APPLICATION_STRING(STR_ID_MMS_ABOUT_US_BUILD, "Build: 5");
ADD_APPLICATION_STRING(STR_ID_WAP_ABOUT_US_JWAP_BROWSER, "jWAP Browser");
ADD_APPLICATION_STRING(STR_ID_WAP_ABOUT_US_VERSION, "Version: 1.0");
ADD_APPLICATION_STRING(STR_ID_WAP_ABOUT_US_BUILD, "Build: 5");
ADD_APPLICATION_STRING(STR_ID_MMS_MMS_NOTIFICATION, "MMS Notification");
ADD_APPLICATION_STRING(STR_ID_MMS_NO_SUBJECT, "No Subject");
ADD_APPLICATION_STRING(STR_ID_MMS_SLIDE, "Slide");
ADD_APPLICATION_STRING(STR_ID_MMS_READ_REPORT_SUBJECT, "[Read Report]");

ADD_APPLICATION_STRING(STR_ID_MMS_INBOX_FORWARD, "Fw:");
ADD_APPLICATION_STRING(STR_ID_MMS_INBOX_REPLY, "Re:");
ADD_APPLICATION_STRING(STR_ID_WAP_DELETE_SUCCESS, "Delete success");
ADD_APPLICATION_STRING(STR_ID_WAP_DELETING, "Delete...");
ADD_APPLICATION_STRING2(STR_ID_JMMS_SUBJECT,"Subject:","Subject:");
ADD_APPLICATION_STRING2(STR_ID_JMMS_TO,"To:","To:");
ADD_APPLICATION_STRING2(STR_ID_JMMS_BCC,"Bcc:","Bcc:");
ADD_APPLICATION_STRING2(STR_ID_JMMS_CC,"Cc:","Cc:");
ADD_APPLICATION_STRING2(STR_ID_JMMS_PRIORITY,"Priority:","Priority:");
ADD_APPLICATION_STRING2(STR_ID_JMMS_SIZE,"Size:","Size:");	
ADD_APPLICATION_STRING2(STR_ID_JMMS_KB,"KB","KB");
ADD_APPLICATION_STRING2(STR_ID_JMMS_MB,"MB","MB");
ADD_APPLICATION_STRING2(STR_ID_JMMS_BYTE,"byte","byte");
ADD_APPLICATION_STRING2(STR_ID_JMMS_BYTES,"bytes","bytes");
ADD_APPLICATION_STRING2(STR_ID_JMMS_MSG_CLASS,"Class:","Class:");	
ADD_APPLICATION_STRING2(STR_ID_JMMS_PERSONEL_MSG_CLASS,"Personal","Personal");	
ADD_APPLICATION_STRING2(STR_ID_JMMS_INFORMATIONAL_MSG_CLASS,"Informational","Informational");	
ADD_APPLICATION_STRING2(STR_ID_JMMS_ADVERTISEMENT_MSG_CLASS,"Advertisement","Advertisement");	
ADD_APPLICATION_STRING2(STR_ID_JMMS_AUTO_MSG_CLASS,"Auto","Auto");	
ADD_APPLICATION_STRING2(STR_ID_JMMS_READ_REPORT_READ,"Read","Read");
ADD_APPLICATION_STRING2(STR_ID_JMMS_READ_REPORT_DELETED,"Deleted","Deleted");
ADD_APPLICATION_STRING2(STR_ID_MMS_WAIT_AND_RETRY,"Another operate is running. Please wait and retry!","Another operate is running. Please wait and retry!");
ADD_APPLICATION_STRING2(STR_ID_WAP_UNSUPPORTED_CONTENT_TYPE,"Unsupported Content Type","Unsupported Content Type");
ADD_APPLICATION_STRING2(STR_ID_WAP_ACCESS_DENIED,"Acess Denied","Acess Denied");
ADD_APPLICATION_STRING2(STR_ID_WAP_PAGE_SIZE_EXCEEDS,"Page too large","Page too large");
ADD_APPLICATION_STRING2(STR_ID_WAP_INVALID_INPUT,"Invalid Input","Invalid Input");
ADD_APPLICATION_STRING2(STR_ID_WAP_MAX_REDIRECT,"Error maximum redirections","Error maximum redirections");
ADD_APPLICATION_STRING2(STR_ID_WAP_HISTORY_NOT_FOUND,"History not found","History not found");
ADD_APPLICATION_STRING2(STR_ID_WAP_HISTORY_FULL,"History Full","History Full");
ADD_APPLICATION_STRING2(STR_ID_WAP_EMPTY_PAGE,"Page Empty","Page Empty");
ADD_APPLICATION_STRING2(STR_ID_JMMS_NO_PRESENTATION_AVAILABLE,"Presentation unavailable","Presentation unavailable");
ADD_APPLICATION_STRING2(STR_ID_DELETE_FAIL_NODEBUSY,"MMS is transporting...","MMS is transporting...");
ADD_APPLICATION_STRING2(STR_ID_WAP_UNKNOWN_SIZE,"unknown","unknown");

ADD_APPLICATION_STRING2(STR_ID_WAP_SERVICE_INBOX,"Service Inbox","Service Inbox screen title");
ADD_APPLICATION_STRING2(STR_ID_WAP_SERVICE_MSG,"Service Messages","Service messages ");
ADD_APPLICATION_STRING2(STR_ID_WAP_SERVICE_MSG_RECEIVED,"Service Message Received","Service Message Received");
ADD_APPLICATION_STRING2(STR_ID_WAP_SERVICE_MSG_VIEW,"Service Messages View","Service messages View");
ADD_APPLICATION_STRING2(STR_ID_WAP_NO_SERVICE_MSGS,"No Service Message","No Service Message ");
ADD_APPLICATION_STRING2(STR_ID_WAP_VIEW,"View","View ");
ADD_APPLICATION_STRING2(STR_ID_WAP_SAVED_PAGES,"Saved Pages","Saved Pages");
ADD_APPLICATION_STRING2(STR_ID_WAP_DC_FILENAME,"FileName","FileName");
ADD_APPLICATION_STRING2(STR_ID_WAP_DC_FILE_DESCRIPTION,"Description","Description");
ADD_APPLICATION_STRING2(STR_ID_WAP_NO_OFFLINE_PAGES,"No Offline Pages","No Offline Pages");
ADD_APPLICATION_STRING2(STR_ID_WAP_FAIL_TO_OPEN,"File Open Error","File Open Error");

ADD_APPLICATION_STRING2(STR_ID_DC_UNSUPPORTED_TYPE,"Invalid or Unsupported Download File","Invalid or Unsupported Download File");
ADD_APPLICATION_STRING2(STR_ID_DC_LOW_MEMORY_TYPE,"No Memory Card or Low Memory","No Memory Card or Low Memory");



ADD_APPLICATION_STRING2(STR_ID_DC_FAILD_TO_DOWNLOAD," Fail to Download","Fail to Download");
ADD_APPLICATION_STRING2(STR_ID_DC_DOWNLOAD_CANCELLED,"Download cancelled","Download Cancelled");
ADD_APPLICATION_STRING2(STR_ID_WAP_SERVICE_EXIST,"Service Message already exist","Service Message already exist");
//add by Renyh
ADD_APPLICATION_IMAGE(IMG_JATAAYU_MAIN_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/WAP_MAIN_ICON.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_SELECTED_RADIOBUTTON_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/SELECTED_RADIOBUTTON.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_CHECKBOX_CHECKED_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/CHECKBOX_CHECKED.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_CHECKBOX_UNCHECKED_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/CHECKBOX_UNCHECKED.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_ALTERNATE_IMAGE_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/ALTERNATE.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_SMALL_ARROW_DOWN_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/SMALL_ARROW_DOWN.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_WAP_ANIMATION_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/WAP_ANI.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_WAP_END_ANIMATION_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/WAP_END_ANI.jpg");
ADD_APPLICATION_IMAGE(IMG_MMS_MAIN_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/WAP_ANI.gif");
ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_UNSELECTED_RADIOBUTTON_GIF, CUST_IMG_PATH "/MainLCD/Jataayu/UNSELECTED_RADIOBUTTON.gif");

ADD_APPLICATION_IMAGE(IMG_MMS_ALT_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_alternate_image.gif");

ADD_APPLICATION_IMAGE(IMG_MMS_AUDIO_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/AUDIO.gif");
ADD_APPLICATION_IMAGE(IMG_MMS_ATTACHMENT_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/ATTACHMENT.gif");
ADD_APPLICATION_IMAGE(IMG_MMS_ATTACHMENT_AUDIO_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/ATTACHMENT_AUDIO.gif");

ADD_APPLICATION_IMAGE(IMG_ID_JATAAYU_WAP_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/SB_WAP.gif");
ADD_APPLICATION_IMAGE(IMG_ID_DATAACCOUNT_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/SB_CM.gif");
ADD_APPLICATION_IMAGE(IMG_MMS_UP_ARROW, CUST_IMG_PATH "/MainLCD/Jataayu/JMMS_scoll_arrow_up.gif");
ADD_APPLICATION_IMAGE(IMG_MMS_DOWN_ARROW, CUST_IMG_PATH "/MainLCD/Jataayu/JMMS_scoll_arrow_down.gif");

#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM1_READ_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_read_sim1.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM2_READ_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_read_sim2.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM1_UNREAD_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_unread_sim1.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM2_UNREAD_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_unread_sim2.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_SENT_FOLDER_SIM1_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_sent_sim1.gif");
  	ADD_APPLICATION_IMAGE(IMG_MMS_SENT_FOLDER_SIM2_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_sent_sim2.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_OUTBOX_FOLDER_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_outbox.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_DRAFT_FOLDER_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_draft.gif");
	#if (MMI_SIM_NUMBER >= 3)
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM3_READ_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_read_sim3.bmp");
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM3_UNREAD_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_unread_sim3.bmp");
	ADD_APPLICATION_IMAGE(IMG_MMS_SENT_FOLDER_SIM3_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_sent_sim3.bmp");
	#endif
	#if (MMI_SIM_NUMBER >=4)
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM4_READ_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_read_sim4.bmp");
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_SIM4_UNREAD_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_inbox_unread_sim4.bmp");
	ADD_APPLICATION_IMAGE(IMG_MMS_SENT_FOLDER_SIM4_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/mms_message_sent_sim4.bmp");
	#endif
#else
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_READ_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/jmms_inbox_folder_read_icon.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_INBOX_FOLDER_UNREAD_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/jmms_inbox_folder_unread_icon.gif");
	ADD_APPLICATION_IMAGE(IMG_MMS_SENT_FOLDER_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/jmms_sent_folder_icon.GIF");
	ADD_APPLICATION_IMAGE(IMG_MMS_OUTBOX_FOLDER_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/jmms_outbox_folder_icon.GIF");
	ADD_APPLICATION_IMAGE(IMG_MMS_DRAFT_FOLDER_ICON, CUST_IMG_PATH "/MainLCD/Jataayu/jmms_draft_folder_icon.GIF");
#endif
	ADD_APPLICATION_IMAGE(IMG_ID_PROF_HDLR_SET_ACTIVATED_PROFILE,CUST_IMG_PATH"/MainLCD/UIElement/checkbox/CK_V.gif");

	ADD_APPLICATION_IMAGE(IMG_WAP_SERVICE_MSG_READ_ICON,CUST_IMG_PATH"/MainLCD/WAP/SW_READ.gif");
	ADD_APPLICATION_IMAGE(IMG_WAP_SERVICE_MSG_UNREAD_ICON,CUST_IMG_PATH"/MainLCD/WAP/SW_UNREAD.gif");
	
//jataayu add end
#endif 
}
//mms
void PopulateJaatayuMMSRes(void)
{
//menu 
	ADD_APPLICATION_MENUITEM( (MMS_MAIN_NEW_MMS_MENUID, MMS_MAIN_SCREEN_MENUID, 0, \
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,
		STR_ID_MMS_NEW_MMS, IMG_MESSAGE_SMS_MENUENTRY));
	ADD_APPLICATION_MENUITEM((MMS_COMPOSE_DONE_OPTION, 0, 4,
		MMS_SEND_ONLY,
		MMS_SEND_AND_SAVE,
		MMS_SAVE,
		MMS_EXIT_COMPOSE,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,0, 0));
	ADD_APPLICATION_MENUITEM((MMS_SEND_ONLY, MMS_COMPOSE_DONE_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_SEND, 0));
	ADD_APPLICATION_MENUITEM((MMS_SEND_AND_SAVE, MMS_COMPOSE_DONE_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_SEND_AND_SAVE, 0));
	ADD_APPLICATION_MENUITEM((MMS_SAVE, MMS_COMPOSE_DONE_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_SAVE, 0));
	ADD_APPLICATION_MENUITEM((MMS_EXIT_COMPOSE, MMS_COMPOSE_DONE_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_EXIT, 0));

	ADD_APPLICATION_MENUITEM((MMS_EDITCONTENT_OPTION, 0, 11,
		MMS_INSERT_IMAGE,
		MMS_DELETE_IMAGE,
		MMS_INSERT_AUDIO,
		MMS_DELETE_AUDIO,						 
		MMS_ADD_ATTACHMENT,
		MMS_EDIT_TEXT,
		MMS_ADD_SLIDE,
		MMS_SET_SLIDE_TIMER,
		MMS_DELETE_SLIDE,
		MMS_TEMPLATE,
		MMS_PREVIEW,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,0, 0));
	ADD_APPLICATION_MENUITEM((MMS_INSERT_IMAGE, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_INSERT_IMAGE, 0));
	ADD_APPLICATION_MENUITEM((MMS_INSERT_AUDIO, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_INSERT_AUDIO, 0));
	ADD_APPLICATION_MENUITEM((MMS_ADD_ATTACHMENT, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_ADD_ATTACHMENT, 0));
	ADD_APPLICATION_MENUITEM((MMS_EDIT_TEXT, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_EDIT_TEXT, 0));
	ADD_APPLICATION_MENUITEM((MMS_ADD_SLIDE, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_ADD_SLIDE, 0));
	ADD_APPLICATION_MENUITEM((MMS_DELETE_IMAGE, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_DELETE_IMAGE, 0));
	ADD_APPLICATION_MENUITEM((MMS_DELETE_AUDIO, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_DELETE_AUDIO, 0));
	ADD_APPLICATION_MENUITEM((MMS_SET_SLIDE_TIMER, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_SET_SLIDE_TIMER, 0));
	ADD_APPLICATION_MENUITEM((MMS_DELETE_SLIDE, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_DELETE_SLIDE, 0));
	ADD_APPLICATION_MENUITEM((MMS_TEMPLATE, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_TEMPLATE, 0));
	ADD_APPLICATION_MENUITEM((MMS_PREVIEW, MMS_EDITCONTENT_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_PREVIEW, 0));

	ADD_APPLICATION_MENUITEM((MMS_OUTBOX_RESEND_OPTION, 0, 2,
		MMS_RESEND_SEND_ONLY,
		MMS_RESEND_SEND_AND_SAVE,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,0, 0));
	ADD_APPLICATION_MENUITEM((MMS_RESEND_SEND_ONLY, MMS_OUTBOX_RESEND_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_SEND, 0));
	ADD_APPLICATION_MENUITEM((MMS_RESEND_SEND_AND_SAVE, MMS_OUTBOX_RESEND_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST,STR_ID_MMS_SEND_AND_SAVE, 0));

	ADD_APPLICATION_MENUITEM((MMS_ATTACHMENT_OPT, 0 ,3,
		MMS_ATTACHMENT_ADD,
		MMS_ATTACHMENT_DELETE,
		MMS_ATTACHMENT_DELETE_ALL,
		SHOW, MOVEABLEACROSSPARENT|INSERTABLE, DISP_LIST, 0,0));
	ADD_APPLICATION_MENUITEM((MMS_ATTACHMENT_ADD, MMS_ATTACHMENT_OPT, 0,
		SHOW, MOVEABLEACROSSPARENT|INSERTABLE, DISP_LIST, STR_GLOBAL_ADD,0));
	ADD_APPLICATION_MENUITEM((MMS_ATTACHMENT_DELETE, MMS_ATTACHMENT_OPT, 0,
		SHOW, MOVEABLEACROSSPARENT|INSERTABLE, DISP_LIST, STR_GLOBAL_DELETE,0));
	ADD_APPLICATION_MENUITEM((MMS_ATTACHMENT_DELETE_ALL, MMS_ATTACHMENT_OPT, 0,
		SHOW, MOVEABLEACROSSPARENT|INSERTABLE, DISP_LIST, STR_GLOBAL_DELETE_ALL,0));
	
//string
	ADD_APPLICATION_STRING(STR_ID_MMS_SEND_AND_SAVE, "Save and Send");
	ADD_APPLICATION_STRING(STR_ID_MMS_SAVE, "Save to drafts");
	ADD_APPLICATION_STRING(STR_ID_MMS_EXIT,"Exit");
	ADD_APPLICATION_STRING(STR_ID_MMS_EXIT_QUESTION, "Save to drafts?");
	ADD_APPLICATION_STRING(STR_ID_MMS_VIEW_ATTACHMENT, "View attachments");
	ADD_APPLICATION_STRING(STR_ID_MMS_INPUT_NAME, "Input name");
	ADD_APPLICATION_STRING(STR_ID_MMS_FILE_ALREADY_EXIST, "File alredy exist, input another name!");
	ADD_APPLICATION_STRING(STR_ID_MMS_FILE_EMPTY, "Failed to add empty file");
	ADD_APPLICATION_STRING(STR_ID_MMS_NO_TCARD, "Drive not found");
	ADD_APPLICATION_STRING(STR_ID_MMS_NO_SAPCE_FOR_SIGNATURE, "No sapce for signature, contiue send?");
	ADD_APPLICATION_STRING(STR_ID_MMS_FILE_NAME_EMPTY, "File name should not be empty");
	ADD_APPLICATION_STRING(STR_ID_MMS_FILE_OPEN_ERROR, "File open fail");
	ADD_APPLICATION_STRING(STR_ID_MMS_AUTO_RETRIVE_FAIL_MEMORY_FULL, "New MMS received, memory not enough");
	ADD_APPLICATION_STRING(STR_ID_MMS_AUTO_RETRIVE_FAIL, "New MMS received, auto receive failed");
	ADD_APPLICATION_STRING(STR_ID_MMS_FILE_NAME_INVALID, "File name invalid");

//img

}
void PopulateJaatayuRes(void)
{
	PopulateJaatayuBrowserRes();
	PopulateJaatayuMMSRes();
}
#endif

