/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
 /*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of COOLSAND Inc. (C) 2001
 *
 *******************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   wap_sap.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/
ADD_MAG(MSG_ID_WAP_STATUS_UPDATE_IND = MSG_ID_WAP_CODE_BEGIN),

ADD_MAG(MSG_ID_WAP_JAS_STARTUP_REQ),
ADD_MAG(MSG_ID_WAP_JAS_SHUTDOWN_REQ),
ADD_MAG(MSG_ID_WAP_JAS_GET_AND_SAVE_REQ),
ADD_MAG(MSG_ID_WAP_JAS_GET_AND_SAVE_RSP),
ADD_MAG(MSG_ID_WAP_JAS_POST_AND_SAVE_REQ),
ADD_MAG(MSG_ID_WAP_JAS_POST_AND_SAVE_RSP),
ADD_MAG(MSG_ID_WAP_JAS_DOWNLOAD_PROGRESS_IND),

ADD_MAG(MSG_ID_WAP_PROF_ACCESS_REQ),
ADD_MAG(MSG_ID_WAP_BROWSER_POWEROFF_REQ),
ADD_MAG(MSG_ID_WAP_BROWSER_POWEROFF_RSP),
ADD_MAG(MSG_ID_WAP_MMI_DELETE_DOWNLOAD_INDEX_REQ),
ADD_MAG(MSG_ID_WAP_MMI_ADD_DOWNLOAD_REQ),
ADD_MAG(MSG_ID_WAP_BROWSER_STARTUP_REQ),
ADD_MAG(MSG_ID_WAP_MMI_READY_IND),
ADD_MAG(MSG_ID_WAP_BROWSER_SHUTDOWN_REQ),
ADD_MAG(MSG_ID_WAP_RESTORE_FACTORY_SETTING_REQ),
ADD_MAG(MSG_ID_WAP_RESTORE_FACTORY_SETTING_CNF),
ADD_MAG(MSG_ID_MEA_STARTUP_REQ),
ADD_MAG(MSG_ID_MEA_STARTUP_NEW_MMS_REQ),
ADD_MAG(MSG_ID_MEA_PHB_ADDR_INPUT_IND),
ADD_MAG(MSG_ID_MEA_SHUTDOWN_REQ),
ADD_MAG(MSG_ID_WAP_MMI_KEY_INDICATION),
ADD_MAG(MSG_ID_WAP_MMI_LAUNCH_BROWSER_REQ),
ADD_MAG(MSG_ID_WAP_MMI_LAUNCH_BROWSER_RSP),
ADD_MAG(MSG_ID_WAP_MMI_BROWSER_TERMINATION_IND),
ADD_MAG(MSG_ID_WAP_MMI_JAVA_INTALL_REQ),
ADD_MAG(MSG_ID_WAP_GET_PROF_LIST_REQ),
ADD_MAG(MSG_ID_WAP_GET_PROF_LIST_RSP),
ADD_MAG(MSG_ID_WAP_GET_PROF_CONTENT_REQ),
ADD_MAG(MSG_ID_WAP_GET_PROF_CONTENT_RSP),
ADD_MAG(MSG_ID_WAP_GET_BRA_PROF_ID_REQ),
ADD_MAG(MSG_ID_WAP_GET_BRA_PROF_ID_RSP),
ADD_MAG(MSG_ID_WAP_READY_IND),

ADD_MAG(MSG_ID_WPS_SET_CHANNEL_REQ),
   ADD_MAG(MSG_ID_WPS_SET_CHANNEL_RSP),
   ADD_MAG(MSG_ID_WPS_UNSET_CHANNEL_REQ),
   ADD_MAG(MSG_ID_WPS_UNSET_CHANNEL_RSP),
   ADD_MAG(MSG_ID_WPS_HTTP_REQ),
   ADD_MAG(MSG_ID_WPS_HTTP_RSP),
   ADD_MAG(MSG_ID_WPS_READ_CONTENT_REQ),
   ADD_MAG(MSG_ID_WPS_READ_CONTENT_RSP),
   ADD_MAG(MSG_ID_WPS_POST_CONTENT_IND),
   ADD_MAG(MSG_ID_WPS_POST_CONTENT_RES),
   ADD_MAG(MSG_ID_WPS_DL_PROGRESS_IND),
   ADD_MAG(MSG_ID_WPS_CANCEL_REQ),
   ADD_MAG(MSG_ID_WPS_CANCEL_RSP),
   ADD_MAG(MSG_ID_WPS_PUSH_IND),
   ADD_MAG(MSG_ID_WPS_CLEAR_REQ),
   ADD_MAG(MSG_ID_WPS_CLEAR_RSP),
   ADD_MAG(MSG_ID_WPS_EXT_MSG_IND),
   ADD_MAG(MSG_ID_WPS_READY_IND),
   ADD_MAG(MSG_ID_WPS_SEC_GET_SESSION_INFO_REQ),
   ADD_MAG(MSG_ID_WPS_SEC_GET_SESSION_INFO_RSP),
   ADD_MAG(MSG_ID_WPS_SEC_GET_CURRENT_CERT_REQ),
   ADD_MAG(MSG_ID_WPS_SEC_GET_CURRENT_CERT_RSP),  
   ADD_MAG(MSG_ID_WPS_HTTP_AUTH_IND),
   ADD_MAG(MSG_ID_WPS_HTTP_AUTH_RES),
   ADD_MAG(MSG_ID_WPS_STATUS_QUERY_REQ),
   ADD_MAG(MSG_ID_WPS_STATUS_QUERY_RSP),          

ADD_MAG(MSG_ID_WAP_CODE_END),



