/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * power_on_off_display_defs.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   This file is intends for Resource IDs for the Power ON/Off Display
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/


#ifndef POWERONOFFDISPLAYDEFS_H
#define POWERONOFFDISPLAYDEFS_H


#include "mmi_data_types.h"

typedef enum{
/*Please Dont Change This Sequence*/
	STR_ID_PHNSET_ON_OFF_1 = PHNSET_ONOFF_BASE+1,
	STR_ID_PHNSET_ON_OFF_2,
	STR_ID_PHNSET_ON_OFF_3,
	STR_ID_PHNSET_ON_OFF_4,
	STR_ID_PHNSET_ON_OFF_5,
	STR_ID_PHNSET_ON_OFF_6,
	STR_ID_PHNSET_ON_OFF_7,
	STR_ID_PHNSET_ON_OFF_8,
	STR_ID_PHNSET_ON_OFF_9,
	
	STR_ID_PHNSET_ON_OFF_DEFAULT,//video1

 
	STR_ID_PHNSET_ON_OFF_ANIMATION,
 

	STR_ID_PHNSET_ON_OFF_CAPTION,
	STR_ID_PHNSET_ON_OFF_SYSTEM,
	STR_ID_PHNSET_ON_OFF_DOWNLOAD,
	STR_ID_PHNSET_ON_OFF_BAD_FILE,
	STR_ID_PHNSET_ON_OFF_SELECT_CAPTION


}PHNSET_STR_ONOFF;

typedef enum {
	SCR_ID_PHNSET_POWER_ON = 	PHNSET_ONOFF_BASE + 1,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_LIST,
	SCR_ID_PHNSET_POWER_ON_SYSTEM_VIEW,
	SCR_ID_PHNSET_POWER_ON_DOWNLOAD_LIST,
	SCR_ID_PHNSET_POWER_ON_USER_VIEW,
	SCR_ID_PHNSET_POWER_OFF,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_LIST,
	SCR_ID_PHNSET_POWER_OFF_SYSTEM_VIEW,
	SCR_ID_PHNSET_POWER_OFF_DOWNLOAD_LIST,
	SCR_ID_PHNSET_POWER_OFF_USER_VIEW,
	SCR_ID_PHNSET_POWER_ON_OFF_LAST
} 	SCR_ID_PHNSET_ONOFF;


typedef enum
{

/*Please Dont Change This Sequence*/	
	IMG_ID_PHNSET_ON_OFF_1 = 	PHNSET_ONOFF_BASE + 1,
	IMG_ID_PHNSET_ON_OFF_2,
#if defined(__PROJECT_GALLITE_C01__)
	IMG_ID_PHNSET_ON_OFF_3,
#endif	
#if !defined( __MMI_RESOURCE_SLIM_ON_128X160__)	    
	IMG_ID_PHNSET_ON_OFF_3,
	#if !defined( __MMI_RESOURCE_SLIM__	)	
	IMG_ID_PHNSET_ON_OFF_4,
	IMG_ID_PHNSET_ON_OFF_5,
	IMG_ID_PHNSET_ON_OFF_6,
	IMG_ID_PHNSET_ON_OFF_7,
	IMG_ID_PHNSET_ON_OFF_8,
	IMG_ID_PHNSET_ON_OFF_9,
	#endif
#endif	
       IMG_ID_PHNSET_ON_OFF_VIDEO_START,
	IMG_ID_PHNSET_ON_OFF_VIDEO_MAX,

	IMG_ID_PHNSET_ON_ANIMATION_DEFAULT1,
	IMG_ID_PHNSET_ON_ANIMATION_MAX,

	IMG_ID_PHNSET_OFF_ANIMATION_DEFAULT1,
	IMG_ID_PHNSET_OFF_ANIMATION_MAX,
	
	
	IMG_ID_PHNSET_ON_OFF_SYSTEM ,
	IMG_ID_PHNSET_ON_OFF_DOWNLAOD,
	IMG_ID_PHNSET_ON_OFF_CAPTION,
	IMG_ID_PHNSET_ON_OFF_MAX,
#ifdef  __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
	IMG_ID_PHNSET_ON_OFF_DEFAULT1,
#else
    IMG_ID_PHNSET_ON_OFF_DEFAULT1_dummy,
#endif  //modified by lin for poweronoff @20070628

} IMG_ID_PHNSET_ON_OFF ;
#if !defined( __MMI_RESOURCE_SLIM_ON_128X160__	)	
#if !defined( __MMI_RESOURCE_SLIM__	)
#define MAX_ONOFF_VIDEO (IMG_ID_PHNSET_ON_OFF_VIDEO_START-IMG_ID_PHNSET_ON_OFF_9-1)
#else
#define MAX_ONOFF_VIDEO (IMG_ID_PHNSET_ON_OFF_VIDEO_START-IMG_ID_PHNSET_ON_OFF_3-1)
#endif
#else
#if defined(__PROJECT_GALLITE_C01__)
#define MAX_ONOFF_VIDEO (IMG_ID_PHNSET_ON_OFF_VIDEO_START-IMG_ID_PHNSET_ON_OFF_3-1)
#else
#define MAX_ONOFF_VIDEO (IMG_ID_PHNSET_ON_OFF_VIDEO_START-IMG_ID_PHNSET_ON_OFF_2-1)
#endif
#endif
#endif /* POWERONOFFDISPLAYDEFS_H */

