/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	SettingDefs.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *============================================================================== 
 *******************************************************************************/

#ifndef _PIXCOM_SETTINGDEFS_H
#define _PIXCOM_SETTINGDEFS_H

#include "mmi_data_types.h"
#include "timerevents.h"
#include "l4dr.h"

#include "mmi_features.h"



#define ST_NOTIFYDURATION					UI_POPUP_NOTIFYDURATION_TIME

#define NUM_ITEMS_DATE_TIME_ENTRY_SCREEN	6
#define POPUP_TIME UI_POPUP_NOTIFYDURATION_TIME_2000

enum SCR_SETTING_LIST
{
	SCR9000_SETTINGS = SETTINGS_BASE+1,
	SCR_ID_SECSET_MAIN,
	SCR_ID_SECSET_PHONE_LOCK,
#ifdef __MMI_AUTO_KEYPAD_LOCK__
	SCR9022_AUTO_KEYPAD_LOCK,
#endif
	SCR_ID_SECSET_PIN2,
	SCR_ID_SECSET_BAR_DIAL,
	SCR_ID_SECSET_SIM_LOCK_PIN1,
	SCR_ID_SECSET_CHANGE_PASSWORD,
	SCR9027_PIN2,
	SCR9028_PIN1,
	SCR_ID_SECSET_CHANGEPW_OLD_PWD,
	SCR_ID_SECSET_CHANGEPW_NEW_PWD,
	SCR_ID_SECSET_CHANGEPW_CFM_PWD,
	SCR9032_SUCCESS,
	SCR9033_AUTO_REDIAL,
	SCR9027_PIN21,
#ifdef __MMI_AUTO_KEYPAD_LOCK__
	SCR_ID_SECSET_AKPL_TIME,
#endif
	SCR9028_PIN1_CAPTION,
	SCR_SETTING_CALL_TIME_DISPLAY,
	SCR_SETTING_MENU_TREE,
	SCR_ID_SECSET_FDN_LIST,
	SCR8055_SERVICE_OFF,
	SCR_ID_SECSET_FDN_OPTION,
	SCR8057_FDL_VIEW_DETAILS,
	SCR_ID_SECSET_FDN_DETAILS,
	SCR8059_FDL_ADD_NUMBER_DETAILS,
	SCR8060_FDL_NO_LIST,
	SCR8061_FDL_ENTRY_SAVE,
	SCR8062_FDL_ENTRY_NOT_SAVE,
	SCR8063_FDL_SCREEN_IN_PROGRESS,
	SCR8064_FDL_SCREEN_OVERWRITE,
	SCR8065_FDL_DELETE_CONFIRM,
	SCR8066_FDL_DELETE_NOTE,
	SCR8067_FDL_DELETE_ALL_NOTE,
	SCR_ID_SECSET_FDNBDN_SAVING,
	SCR_ID_SECSET_FDNBDN_DELETING,
	SCR_RESTORE,
	SCR_RESTORE_PROCESSING,
	SCR8077_BDL_SCREEN,
	SCR8078_BDL_SERVICE_OFF,
	SCR_ID_SECSET_BDN_LIST,
	SCR_ID_SECSET_BDN_OPTION,
	SCR_ID_SECSET_BDN_DETAILS,
	SCR8083_BDL_ADD_NUMBER,
	SCR8084_BDL_OVERWRITE,
	SCR8085_BDLFDL_DUPLICATE,
	SCR8086_BDL_ENTRY_SAVE,
	SCR8087_BDL_ENTRY_NOTSAVE,
	SCR8088_BDL_SCREEN_IN_PROGRESS,
	SCR8089_BDL_SCREEN_VIEW_DETAILS,
	SCR_ID_SECSET_BDN_DEL_CONFIRM,
	SCR8091_BDL_DELETED_ENTRY,
	SCR8092_BDL_FAILURE_DELETE,
	SCR_SETTING_RESTORE_CONFIRM,
	SCR_ID_SECSET_PUK1,
	SCR_ID_SECSET_PUK2,
	SCR_ID_SECSET_PUK_NEW_PIN1,
	SCR_ID_SECSET_PUK2_NEW_PIN2,
	SCR_ID_SECSET_PUK_CONFIRM_PIN1,
	SCR_ID_SECSET_PUK2_CONFIRM_PIN2,	
	SCR_ID_SECSET_FIX_DIAL,
	SCR_ID_CALLSET_CUG_OPTIONS,
	SCR_ID_CALLSET_CUG_MAIN,
	SCR_ID_CALLSET_CUG_ADD_LIST,
	SCR_ID_CALLSET_CUG_EDIT_LIST,
	SCR_ID_CALLSET_CUG_ADD_LIST_INDEX,
	SCR_ID_CALLSET_CUG_EDIT_LIST_INDEX,
	SCR_ID_CALLSET_CUG_DEL_LIST_CNRM,
	SCR_ID_CALLSET_CUG_EDIT_OPTIONS,
	SCR_POPUP_GROUPLIST,
	SCR_ID_CALLSET_CTR,
	SCR_ID_CALLSET_CTR_TIME,
	SCR_SETTING_CTR_TIME_DONE,
	SCR_SECSET_FDN_SAVE_CONFIRM,
	SCR_ID_SECSET_FDN_DEL_CONFIRM,
	SCR_SETTING_PIN2_BLOCKED,
	SCR_DATETIME_DUMMY,
#ifdef __MMI_SOUND_EFFECT__
	SCR_ID_SETTING_SOUND_EFFECT,
	SCR_ID_SETTING_AUDIO_EQUALIZER,
#endif
#if defined(__MMI_PREFER_INPUT_METHOD__)
    SCR_INPUT_METHOD_SELECTION,
#endif
#ifdef __MMI_MULTI_SIM__
    SCR_GSM_CHANGE_PIN1_SELECT_SIM,
    SCR_GSM_CHANGE_PIN2_SELECT_SIM, 
#endif
    SCR_SECSET_BDN_SAVE_CONFIRM,
#ifdef __MMI_VIP_FUNCTION__
	SCR_SETTING_VIP_FUNCTION,
	SCR_SETTING_VIP_PASSWORD,
	SCR_SETTING_VIP_PASSWORD_CONFIRM,
	SCR_SETTING_VIP_LIST,
	SCR_SETTING_VIP_LIST_OPTION,
	SCR_SETTING_VIP_NUMBER,
#endif

#ifdef __MMI_TTS_FEATURES__ 
	SCR_ID_SETTING_TTS_PLAYER,
	SCR_ID_TTS_READ_MSG,
	SCR_ID_TTS_READ_MENU,
	SCR_ID_TTS_READ_CALL,
	SCR_ID_TTS_ALARM_SETTING,
	SCR_ID_TTS_EFFECT_SETTING,
	SCR_ID_TTS_HELP,
	SCR_ID_TTS_ALARM_EVERY_HOUR,
	SCR_ID_TTS_ALARM_READ_DATE,
	SCR_ID_TTS_ALARM_READ_WEEK,
	SCR_ID_TTS_SETTING_VOLUME,
	SCR_ID_TTS_SETTING_SPEED,
	SCR_ID_TTS_SETTING_EFFECT,
	SCR_ID_TTS_SETTING_STYLE,
	SCR_ID_TTS_SETTING_TONE,//add by ejTTS

#endif

};

enum SCR_PHONESETUP
{
	SCR9003_INITIALSETUP = PHONE_SETUP_BASE+1,
	SCR_DISP_SETUP,
	SCR9146_WELCOME_TEXT,
	SCR9146_WELCOME_TEXT_ON,
	SCR9041_TIMEANDDATE,
	SCR9042_SETTIME,
	SCR9043_SETTIMEFORMAT,
	SCR9044_SETDATE,
	SCR9045_SETDATEFORMAT,
	SCR9051_24HOURS,
	SCR9052_AM_PM,
	SCR9061_DATE_MONTH,
	SCR9062_DATE_MONTH_YEAR,
	SCR9063_MONTH_DATE_YEAR,
	SCR9064_DATE_MONTH_YEAR2,
	SCR_SETTING_POWER_ON_WITH_ALARM,
	SCR_SETTING_SPEED_DIAL,
	SCR_SETTING_SPEED_DIAL_ENTER_NUM,
	SCR_SETTING_CONTRAST_LEVEL,
	SCR_SETTING_SCHEDULE_POWER,
	SCR_ID_PHNSET_SET_DT,
	SETTINGS_SET_TIME_FORMAT_SCREENID,
//__MMI_SEPARATE_DT_SETTING__
	SCR_ID_PHNSET_SET_DATEANDFORMAT,
	SCR_ID_PHNSET_SET_TIMEANDFORMAT,
//__MMI_SEPARATE_DT_SETTING__
	SETTINGS_SETHOMECITY_SCREENID,
    SCR_IDLE_SCR_DISP,
    SCR_IDLE_SCR_DISP_WP_PREVIEW,
    SCR_VDO_DISP_PHB_PREVIEW,   //guojian added for jaspmin video forward to phb
    SCR_MAINMENU_STYLE,
#if defined(__MMI_DEDICATED_KEY_SHORTCUTS__)
	SCR_DEDICATED_KEYS,
	SCR_EDIT_DEDICATED_KEYS,			
#endif
#if defined(__MMI_SET_DEF_ENCODING_TYPE__)
	SCR_DEF_ENCODING_TYPE,
#endif
#if defined(__MMI_TOUCH_SCREEN__)
	SCR_HANDWRITING_SETTING,
	SCR_CALIBRATION_SETTING,
#endif
#if defined(MMI_2D_SENSOR_SUPPORT)||defined(CAM_MD_SUPPORT)
	SCR_SETTING_2D_SENSOR,
#endif
#if defined(MOTION_SENSOR_SUPPORT)
	 SCR_SETTING_MOTION_SENSOR,
#endif
#if defined(__MMI_TVOUT__)
	SCR_ID_SETTING_TVOUT,
	SCR_ID_SETTING_TVOUT_FORMAT,
	SCR_ID_SETTING_TVOUT_STYLE,
#endif /* __MMI_TVOUT__ */
#ifdef __MMI_CHANGE_WIN_WITH_DYNAMIC__
	SCR_ID_SETTING_CHANGE_WIN_STYLE,
#endif
	SCR_SPEED_PHONELIST
};

enum SCR_SETTING_LANGUAGE_LIST
{
	SCR_LANGUAGE_SELECTION= LANG_SETTINGS_BASE+1
};

 
enum SCR_FLIGHT_MODE_LIST
{
	SCR_FLIGHT_MODE_SELECTION = FLIGHT_MODE_BASE+1,
	SCR_FLIGHT_MODE_CONFIRM,
	SCR_FLIGHT_MODE_QUERY,
	SCR_FLIGHT_MODE_IDLE,
	SCR_FLIGHT_MODE_PROGRESS
};
 

enum STR_SETTING_LIST
{
STR_MENU9100_CALL_SETTING = SETTINGS_BASE+1,
STR_SCR9000_SETTINGS_CAPTION,
STR_SCR9001_CALL_SETTING_CAPTION,
STR_SETTING_CALL_TIME_DISPLAY_CAPTION,
STR_POWER_SAVE_TIMER_CAPTION,
STR_SETTING_RESTORE_ERR1,
STR_SETTING_RESTORE_CONFIRM,
STR_SETTING_RESTORE_PROCESSING,
STR_SETTING_YES,
STR_SETTING_WRONG,
//micha0616
STR_SETTING_BLOCK,
STR_CTR_REM,
STR_SETTING_CR_RANGE1,
STR_SETTING_CR_RANGE2,
STR_SETTING_CR_RANGE3,
STR_ID_SETTING_SOUND_EFFECT,
STR_ID_SETTING_AUDIO_EQUALIZER,  //18567
STR_ID_SETTING_AUDIO_EQUALIZER_SET_1,  //18568
STR_ID_SETTING_AUDIO_EQUALIZER_SET_2,   //18569
STR_ID_SETTING_AUDIO_EQUALIZER_SET_3,  //18570
STR_ID_SETTING_AUDIO_EQUALIZER_SET_4,  //18571
STR_ID_SETTING_AUDIO_EQUALIZER_SET_5,
STR_ID_SETTING_AUDIO_EQUALIZER_SET_6,
STR_ID_SETTING_AUDIO_EQUALIZER_SET_7,
STR_ID_SETTING_AUDIO_EQUALIZER_SET_8,

STR_MENU_INPUT_METHOD,
STR_INPUT_METHOD_MULTITAP_U_ABC,
STR_INPUT_METHOD_MULTITAP_L_ABC,
STR_INPUT_METHOD_SMART_U_ABC,
STR_INPUT_METHOD_SMART_L_ABC,
STR_INPUT_METHOD_NUMERIC,
STR_INPUT_METHOD_MULTITAP_BPMF,
STR_INPUT_METHOD_BPMF,
STR_INPUT_METHOD_TR_STROKE,
STR_INPUT_METHOD_MULTITAP_PINYIN,
STR_INPUT_METHOD_PINYIN,
STR_INPUT_METHOD_SM_STROKE,
STR_INPUT_METHOD_MULTITAP_U_SPANISH,
STR_INPUT_METHOD_MULTITAP_L_SPANISH,
STR_INPUT_METHOD_SMART_U_SPANISH,
STR_INPUT_METHOD_SMART_L_SPANISH,
STR_INPUT_METHOD_MENU_SMART_U_SPANISH,
STR_INPUT_METHOD_MENU_SMART_L_SPANISH,
#if defined(__MMI_MULTITAP_MARATHI__)
STR_INPUT_METHOD_MENU_MULTITAP_MARATHI,
STR_INPUT_METHOD_MULTITAP_MARATHI,
#endif
#if defined(__MMI_MULTITAP_URDU__)
STR_INPUT_METHOD_MENU_MULTITAP_URDU,
STR_INPUT_METHOD_MULTITAP_URDU,
#endif
//qiff add multi-input method support
#if defined(__MMI_MULTITAP_TAMIL__)
		STR_INPUT_METHOD_MENU_MULTITAP_TAMIL,
		STR_INPUT_METHOD_MULTITAP_TAMIL,
#endif
#if defined(__MMI_MULTITAP_BENGALI__)
		STR_INPUT_METHOD_MENU_MULTITAP_BENGALI,
		STR_INPUT_METHOD_MULTITAP_BENGALI,
#endif
#if defined(__MMI_MULTITAP_PUNJABI__)
		STR_INPUT_METHOD_MENU_MULTITAP_PUNJABI,
		STR_INPUT_METHOD_MULTITAP_PUNJABI,
#endif
#if defined(__MMI_MULTITAP_TELUGU__)
		STR_INPUT_METHOD_MENU_MULTITAP_TELUGU,
		STR_INPUT_METHOD_MULTITAP_TELUGU,
#endif
#if defined(__MMI_SMART_TELUGU__)
		STR_INPUT_METHOD_MENU_SMART_TELUGU,
		STR_INPUT_METHOD_SMART_TELUGU,
#endif
#if defined(__MMI_MULTITAP_KANNADA__)
		STR_INPUT_METHOD_MENU_MULTITAP_KANNADA,
		STR_INPUT_METHOD_MULTITAP_KANNADA,
#endif		
#if defined(__MMI_MULTITAP_MALAYALAM__)
		STR_INPUT_METHOD_MENU_MULTITAP_MALAYALAM,
		STR_INPUT_METHOD_MULTITAP_MALAYALAM,
#endif
#if defined(__MMI_MULTITAP_ORIYA__)
		STR_INPUT_METHOD_MENU_MULTITAP_ORIYA,
		STR_INPUT_METHOD_MULTITAP_ORIYA,
#endif
//qiff add end
 
STR_INPUT_METHOD_MULTITAP_U_DANISH,
STR_INPUT_METHOD_MULTITAP_L_DANISH,
STR_INPUT_METHOD_SMART_U_DANISH,
STR_INPUT_METHOD_SMART_L_DANISH,
 
STR_INPUT_METHOD_MULTITAP_U_FRENCH,
STR_INPUT_METHOD_MULTITAP_L_FRENCH,
STR_INPUT_METHOD_SMART_U_FRENCH,
STR_INPUT_METHOD_SMART_L_FRENCH,
STR_INPUT_METHOD_MULTITAP_U_GERMAN,
STR_INPUT_METHOD_MULTITAP_L_GERMAN,
STR_INPUT_METHOD_MENU_SMART_U_GERMAN,
STR_INPUT_METHOD_MENU_SMART_L_GERMAN,

STR_INPUT_METHOD_SMART_U_GERMAN,
STR_INPUT_METHOD_SMART_L_GERMAN,
STR_INPUT_METHOD_MULTITAP_U_ITALIAN,
STR_INPUT_METHOD_MULTITAP_L_ITALIAN,
STR_INPUT_METHOD_SMART_U_ITALIAN,
STR_INPUT_METHOD_SMART_L_ITALIAN,
STR_INPUT_METHOD_MENU_MULTITAP_U_ITALIAN,
STR_INPUT_METHOD_MENU_MULTITAP_L_ITALIAN,
STR_INPUT_METHOD_MENU_SMART_U_ITALIAN,
STR_INPUT_METHOD_MENU_SMART_L_ITALIAN,
STR_INPUT_METHOD_MULTITAP_ARABIC,
STR_INPUT_METHOD_MULTITAP_PERSIAN,

STR_INPUT_METHOD_MULTITAP_U_RUSSIAN,
STR_INPUT_METHOD_MULTITAP_L_RUSSIAN,
STR_INPUT_METHOD_SMART_U_RUSSIAN,
STR_INPUT_METHOD_SMART_L_RUSSIAN,
STR_INPUT_METHOD_MULTITAP_U_TURKISH,
STR_INPUT_METHOD_MULTITAP_L_TURKISH,
STR_INPUT_METHOD_SMART_U_TURKISH,
STR_INPUT_METHOD_SMART_L_TURKISH,
STR_INPUT_METHOD_MULTITAP_U_PORTUGUESE,
STR_INPUT_METHOD_MULTITAP_L_PORTUGUESE,
STR_INPUT_METHOD_SMART_U_PORTUGUESE,
STR_INPUT_METHOD_SMART_L_PORTUGUESE,
STR_INPUT_METHOD_MULTITAP_U_INDONESIAN,
STR_INPUT_METHOD_MULTITAP_L_INDONESIAN,
STR_INPUT_METHOD_SMART_U_INDONESIAN,
STR_INPUT_METHOD_SMART_L_INDONESIAN,
STR_INPUT_METHOD_MULTITAP_U_MALAY,
STR_INPUT_METHOD_MULTITAP_L_MALAY,
STR_INPUT_METHOD_SMART_U_MALAY,
STR_INPUT_METHOD_SMART_L_MALAY,
STR_INPUT_METHOD_MULTITAP_U_VIETNAMESE,
STR_INPUT_METHOD_MULTITAP_L_VIETNAMESE,
STR_INPUT_METHOD_SMART_U_VIETNAMESE,
STR_INPUT_METHOD_SMART_L_VIETNAMESE,
STR_INPUT_METHOD_MULTITAP_THAI,
STR_INPUT_METHOD_SMART_THAI,
STR_INPUT_METHOD_SMART_ARABIC,
STR_INPUT_METHOD_SMART_PERSIAN,
STR_INPUT_METHOD_MULTITAP_HINDI,
STR_INPUT_METHOD_SMART_HINDI,
STR_INPUT_METHOD_SMART_URDU,
STR_INPUT_METHOD_MULTITAP_MYANMAR,
STR_INPUT_METHOD_SMART_TAMIL,
STR_INPUT_METHOD_SMART_BENGALI,
STR_INPUT_METHOD_SMART_PUNJABI,
#ifdef __FT_IDLE_SMART_DIAL__
STR_ID_PHNSET_SMART_DIAL_STYLE,
#endif

STR_SCR9033_AUTO_REDIAL_CAPTION,

#ifdef __MMI_TTS_FEATURES__ 
STR_ID_SETTING_TTS_PLAYER,//add by ejTTS
STR_ID_SETTING_TTS_READ_MSG,
STR_ID_SETTING_TTS_READ_MENU,
STR_ID_SETTING_TTS_READ_CALL,
STR_ID_SETTING_TTS_ALARM_SETTING,
STR_ID_SETTING_TTS_SETTING,
STR_ID_SETTING_TTS_HELP,
STR_ID_TTS_READ_MSG_AUTO,
STR_ID_TTS_READ_MSG_CONTROL,
STR_ID_TTS_READ_MENU_OPEN,
STR_ID_TTS_READ_MENU_CLOSE,
STR_ID_TTS_READ_CALL_OPEN,
STR_ID_TTS_READ_CALL_CLOSE,
STR_ID_TTS_AlARM_EVERY_HOUR,
STR_ID_TTS_ALARM_READ_DATE,
STR_ID_TTS_ALARM_READ_WEEK,
STR_ID_TTS_AlARM_OPEN,
STR_ID_TTS_AlARM_CLOSE,
STR_ID_TTS_SETTING_VOLUME,
STR_ID_TTS_SETTING_SPEED,
STR_ID_TTS_SETTING_EFFECT,
STR_ID_TTS_SETTING_STYLE,
STR_ID_TTS_SETTING_TUNE,
STR_ID_TTS_SETTING_VOLUME_1,
STR_ID_TTS_SETTING_VOLUME_2,
STR_ID_TTS_SETTING_VOLUME_3,
STR_ID_TTS_SETTING_VOLUME_4,
STR_ID_TTS_SETTING_VOLUME_5,
STR_ID_TTS_SETTING_EFFECT_BASE,
STR_ID_TTS_SETTING_EFFECT_REVERB,
STR_ID_TTS_SETTING_EFFECT_ECHO,
STR_ID_TTS_SETTING_EFFECT_CHORUS,
STR_ID_TTS_SETTING_EFFECT_NEARFAR,
STR_ID_TTS_SETTING_EFFECT_ROBOT,
STR_ID_TTS_SETTING_STYLE_CLEAR,
STR_ID_TTS_SETTING_STYLE_NORMAL,
STR_ID_TTS_SETTING_STYLE_PLAIN,
STR_ID_TTS_SETTING_STYLE_VIVID,
STR_ID_TTS_SETTING_TUNE_DEEP,
STR_ID_TTS_SETTING_TUNE_NORMAL,
STR_ID_TTS_SETTING_TUNE_STRIDENT,
STR_ID_TTS_SETTING_SPEED_NOR,
STR_ID_TTS_SETTING_SPEED_FAST,
STR_ID_TTS_SETTING_SPEED_SLOW,
STR_ID_TTS_AlARM_TODAY,
STR_ID_TTS_AlARM_NOW,
STR_ID_TTS_AlARM_AM,
STR_ID_TTS_AlARM_PM,
STR_ID_TTS_AlARM_HOUR,
STR_ID_TTS_AlARM_MINTUE,
STR_ID_TTS_AlARM_YEAR,
STR_ID_TTS_AlARM_MONTH,
STR_ID_TTS_AlARM_DAY,
STR_ID_TTS_AlARM_ZHENG,
STR_ID_TTS_AlARM_WEEK,
STR_ID_TTS_CALL_CONTENT,//end add by ejTTS
STR_ID_SETTING_TTS_HELP_DESCRIPTION,
       
#endif	

};
//xiaoke 08.12.31
#ifdef __DOUBLE_SIMCARD_211__      
enum STR_SWITCHSIMCARD
{
	STR_DOUBLE_SIMCARD_OPTION = SWITCH_SIMCARD_BASE+1,
	STR_DOUBLE_SIMCARD1_OPTION,
	STR_DOUBLE_SIMCARD2_OPTION

};
#endif
//xiaoke 08.12.31

enum STR_PHONESETUP
{
STR_MENU9102_INITIAL_SETUP = PHONE_SETUP_BASE+1,
STR_DISP_SETUP,	   
STR_MENU9141_TIME_AND_DATE,
STR_SETTIME_UNFINISHED,
STR_MENU9142_SETHOMECITY,
STR_ID_PHNSET_SET_DT,
//__MMI_SEPARATE_DT_SETTING__
STR_ID_PHNSET_SET_DATEANDFORMAT,
STR_ID_PHNSET_SET_TIMEANDFORMAT,
//__MMI_SEPARATE_DT_SETTING__
STR_ID_PHNSET_SET_DST,
STR_MENU9144_SETTIMEANDDATEFORMAT,
STR_ENTER_TIME_FORMAT_DISP_CAPTION,
STR_ENTER_DATE_FORMAT_DISP_CAPTION,
STR_TIME_FORMAT_CAPTION,
STR_DATE_FORMAT_CAPTION,
STR_DATE_TIME_SET_FORMAT_CAPTION,
STR_SCR_SPEED_DIAL_MAIN_CAPTION,
STR_SCR_SPEED_DIAL_LIST_CAPTION,
STR_SPEEDDIAL_NO_NUM_TODIAL_TEXT,
STR_DD_MM,
STR_MM_DD,
STR_DD_MMM_YYYY_H,
STR_DD_MM_YYYY_S,
STR_MM_DD_YYYY_S,
STR_YYYY_MM_DD_S,
STR_YYYY_MM_DD_H,
STR_MMM_DD_YYYY,
STR_MENU9146_WELCOME_TEXT,
STR_SCR9041_TIMEANDDATE_CAPTION,
STR_SCR9042_SETTIME_CAPTION,
STR_SCR9043_SETTIMEFORMAT_CAPTION,
STR_SCR9044_SETDATE_CAPTION,
STR_SCR9045_SETDATEFORMAT_CAPTION,
STR_SCR9051_24HOURS_CAPTION,
STR_SCR9051_24HOURS_MESSAGE,
STR_SCR_WELCOME_LSK,
STR_SCR_WELCOME_RSK,
STR_MENU_SETTING_AUTO_UPDATE_DT_TIME,
STR_MENU_SETTING_SPEED_DIAL,
STR_MENU_SETTING_CONTRAST_LEVEL,
STR_SETTING_CONTRAST_LEVEL_CAPTION,
//#if defined(__MMI_NITZ__)
	STR_MENU_SETTING_MENU_TREE,
//#endif
STR_MENU_SETTING_SCHEDULE_POWER,
STR_MENU_SETTING_SCHEDULE_POWER_SET1,
STR_MENU_SETTING_SCHEDULE_POWER_SET2,
STR_MENU_SETTING_SCH_POW_SET1_POW_ON,
STR_MENU_SETTING_SCH_POW_SET1_POW_OFF,
STR_OWN_NO,
//Lisen 0921-1
#if defined(__MMI_OPERATOR_NAME_MENU__)
STR_OPN,
#endif
STR_MAINMENU_STYLE,
STR_MAINMENU_STYLE_MATRIX,
STR_MAINMENU_STYLE_PAGE,
STR_MAINMENU_STYLE_CIRCULAR,
STR_MAINMENU_STYLE_ROTATE,
STR_MAINMENU_STYLE_LIST,
 
STR_MAINMENU_STYLE_TAB,
 
STR_IDLE_SCR_DISP,
STR_SPEED_DIAL_STATUS,
STR_SPEED_DIAL_LIST,
STR_EDIT,
STR_DONE,
STR_SETTING_WALLPAPER,
#ifdef __MMI_SUB_WALLPAPER__
STR_SETTING_WALLPAPER_SUB,
#endif
STR_MENU_SETTING_SCREEN_SVR,
#ifdef __MMI_POWER_ON_OFF_DISPLAY__			
STR_SETTING_POWER_ON_DISPLAY,	//"Power On Display"
STR_SETTING_POWER_OFF_DISPLAY,//"Power Off Display"
#endif
STR_SETTING_SHOW_DT_TIME,
STR_SETTING_SPEED_STATUS,
STR_SETTING_MAIN_LCD,
STR_SETTING_SUB_LCD,
STR_SETTING_WRONG_TIME,
STR_MENU9146_ON,
STR_MENU9146_OFF,
#if defined(__MMI_DEDICATED_KEY_SHORTCUTS__)
STR_DEDICATED_KEY,
STR_DEDICATED_UP_KEY,
STR_DEDICATED_DOWN,
STR_DEDICATED_LEFT,
STR_DEDICATED_RIGHT,
STR_DEDICATED_OK,
#endif
#if defined(__MMI_SET_DEF_ENCODING_TYPE__)
STR_DEF_ENCODING_TYPE_TITLE,
STR_DEF_ENCODING_TYPE_BIG5,
STR_DEF_ENCODING_TYPE_GB2312,
STR_DEF_ENCODING_TYPE_UCS2,
#endif
#ifdef __MMI_TOUCH_SCREEN__
STR_HANDWRITING_SETTING,
STR_CALIBRATION_SETTING,
STR_HANDWRITING_PEN_SPEED,
STR_HANDWRITING_PEN_COLOR,
STR_HANDWRITING_FAST,			/* Don't change the order of these three strings */
STR_HANDWRITING_MEDIUM,
STR_HANDWRITING_SLOW,
STR_CALIBRATION_WELCOME_TEXT,
STR_CALIBRATION_TOP_LEFT_TEXT,	/* Don't change the order of these three strings */
STR_CALIBRATION_BOTTOM_RIGHT_TEXT,
STR_CALIBRATION_CENTER_TEXT,
STR_CALIBRATION_ARROW_CENTER_TEXT,
#endif	/* __MMI_TOUCH_SCREEN__ */

	#ifdef __MMI_TVOUT__
		STR_ID_SETTING_TVOUT,
		STR_ID_SETTING_TVOUT_FORMAT,
		STR_ID_SETTING_TVOUT_FORMAT_PAL,
		STR_ID_SETTING_TVOUT_FORMAT_NTSC,	
		STR_ID_SETTING_TVOUT_FORMAT_PALM,
		STR_ID_SETTING_TVOUT_FORMAT_PALC,
		STR_ID_SETTING_TVOUT_MM_STYLE,
		STR_ID_SETTING_TVOUT_MM_STYLE_PHONE,
		STR_ID_SETTING_TVOUT_MM_STYLE_FULLSCR,	
		STR_ID_SETTING_TVOUT_PLUG_IN,
		STR_ID_SETTING_TVOUT_PLUG_OUT,	
	#endif /* __MMI_TVOUT__ */
	#if defined(MMI_2D_SENSOR_SUPPORT)||defined(CAM_MD_SUPPORT)
		STR_SETTING_2D_SENSOR,
	#endif
	#if defined(MOTION_SENSOR_SUPPORT)
        STR_SETTING_MOTION_SENSOR,
	#endif
	
		STR_24,
		STR_12,
		STR_SIM_SWITCH_MAIN,  
		STR_SIM_1,
		STR_SIM_2,
		STR_SIM_SWITCH_ASK,
		STR_SIMSWITCHDONE,
		STR_SIMSWITCHORFAIL,
#if defined (__LED__) || defined (__MMI_RUNNING_LED__)	
		STR_MENU_SETTING_ENABLE_ROLL_LED,
#endif

#ifdef __T800_MAIN_MENU__
    STR_ID_CALL_CENTER,
#endif
#ifdef __MMI_CHANGE_WIN_WITH_DYNAMIC__
STR_ID_SETTING_CHANGE_WIN_STYLE,
STR_ID_SETTING_CHANGE_WIN_STYLE_MODE,
#endif
STR_ID_PHNSET_DISPCHAR_DIGITAL,

};
 
enum STR_SETTINGS_SECURITY_SETUP
{
STR_MENU9101_SECURITY	=	SECURITY_SETUP_BASE+1,		
STR_SCR8079_BDL_VIEW_LIST_CAPTION,
STR_MENU8236_BDL_VIEW_OPTIONS_MAIN,
STR_PASS_TRIALS_REMAIN,
STR_BDL_NOT_READY,
STR_FDL_IS_ON,
STR_FDL_IS_OFF,
STR_BDL_IS_ON,
STR_BDL_IS_OFF,
STR_SETTING_STORAGE_FULL,
STR_SETTING_CODE_VERIFIED,
STR_SETTING_PIN_BLK,
STR_SETTING_PIN2_BLK,
STR_SETTING_PIN2_BLK2,
STR_INVALID_PINPUKPLOCK_LENGTH,
STR_SETTING_SOS,
STR_SETTING_SIM_LOCK,
STR_SETTING_SIM_UNLOCK,
STR_SETTING_PHONE_LOCK,
STR_SETTING_PHONE_UNLOCK,
STR_SETTING_OLD_PIN,
STR_SETTING_NEW_PIN,
STR_SETTING_OLD_PIN2,
STR_SETTING_NEW_PIN2,
STR_DIFF_PIN,
STR_DIFF_PIN2,
STR_DIFF_PHONE,
STR_WRONG_PIN,
STR_PIN_CHANGE,
STR_WRONG_PIN2,
STR_PIN2_CHANGE,
STR_WRONG_PHONE,
STR_PHONE_CHANGE,
STR_SETTING_ENTER_PUK2,
STR_SETTING_ENTER_NEW_PIN2,
STR_SETTING_WRONG_PUK2,
STR_SETTING_WRONG_PUK,
STR_SETTING_PIN2_BLOCK_TITLE,
STR_SETTING_PIN2_BLOCK_MSG,
STR_NEW_PIN1,
STR_ENABLE_PIN,
STR_SETTING_PUK,
STR_SETTING_FDL_MODE,
STR_SETTING_FDL_LIST,
STR_NO_FDL,
STR_SETTING_BDL_MODE,
STR_SETTING_BDL_LIST,
STR_SETTING_FDL_NAME,
STR_SETTING_FDL_NUMBER,
STR_SETTING_FDL_EDIT_ENTRY,
STR_MENU_RESTORE,
STR_MENU8234_FDL_VIEW_OPTIONS_MAIN,
STR_SCR8054_CALL_FDL_CAPTION,
STR_MENU9165_PHONE_LOCK,
#ifdef __MMI_AUTO_KEYPAD_LOCK__
STR_MENU9166_AUTO_KEYPAD_LOCK,
#endif
STR_MENU9167_FIXED_DIAL,
STR_MENU9168_BARRED_DAIL,
STR_MENU9169_SIM_LOCK,
STR_MENU9170_CHANGE_PASSWORD,
STR_MENU9173_CP_PHONE_LOCK,
#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
STR_MENU9174_CP_SIM1_PIN1,
STR_MENU9175_CP_SIM1_PIN2,
#else
STR_MENU9174_CP_PIN1,
STR_MENU9175_CP_PIN2,
#endif
#ifdef __MMI_AUTO_KEYPAD_LOCK__
STR_MENU9177_AKPL_OFF,
STR9178_AKPL_TIME_5,
STR9178_AKPL_TIME_30,
STR9178_AKPL_TIME_60,
STR9178_AKPL_TIME_2,
#endif
STR_SCR9002_SECURITY_CAPTION,
#ifdef __MMI_AUTO_KEYPAD_LOCK__
STR_SCR9022_AUTO_KEYPAD_LOCK_CAPTION,
#endif
STR_SCR9023_FIXED_DAIL_CAPTION,
STR_SCR9024_BARRED_DIAL_CAPTION,
STR_SCR9025_SIM_LOCK_CAPTION,
STR_SCR9026_CHANGE_PASSWORD_CAPTION,
STR_SCR9027_PIN2_CAPTION,
STR_SCR9029_CURRENT_PW_CAPTION,
STR_SCR9030_NEW_PW_CAPTION,
STR_SCR9031_CONFIRM_PW_CAPTION,
STR_SCR9034_SECURITY_FAILURE_CAPTION,
STR_SCR9034_SECURITY_FAILURE_MESSAGE,
STR_SCR9028_PIN1_CAPTION,
STR_FDL_NOT_READY,
STR_ID_PIN_NOT_SUPPORT,
STR_ID_PIN2_NOT_SUPPORT,
#ifdef __MMI_MULTI_SIM__
STR_SIM1_FIXED_DAIL_CAPTION,
STR_SIM2_FIXED_DAIL_CAPTION,
STR_SIM3_FIXED_DAIL_CAPTION,
STR_SIM4_FIXED_DAIL_CAPTION,
STR_SIM1_BARRED_DIAL_CAPTION,
STR_SIM2_BARRED_DIAL_CAPTION,
STR_SIM3_BARRED_DIAL_CAPTION,
STR_SIM4_BARRED_DIAL_CAPTION,
#endif

#ifdef __MMI_VIP_FUNCTION__
STR_VIP_SETTING,
STR_VIP_STATUS,
STR_VIP_LIST,
STR_VIP_PASSWORD_ERROR,
STR_VIP_PASSWORD_NOT_ACCORDANT,
STR_VIP_NUMBER_ERASE_Q,
STR_VIP_INPUT_PASSWORD,
STR_VIP_CONFIRM_PASSWORD,
#endif
STR_QUIT_QQ_INFORM_STRING,
};

enum STR_SETTING_LANGUAGE_LIST
{
STR_MENU_LANGUAGE = LANG_SETTINGS_BASE+1,
STR_LANGUAGESCR_AUTO,
STR_LANGUAGESCR_AUTO_SEL,
STR_LANGUAGESCR_ENG,
STR_LANGUAGESCR_TRCH,
STR_LANGUAGESCR_SICH
};

 
enum STR_FLIGHT_MODE_LIST
{
	STR_MENU_FLIGHT_MODE = FLIGHT_MODE_BASE + 1,	/* menu text */
	STR_FLIGHT_MODE_NORMAL,				/* selection text */
	STR_FLIGHT_MODE_SILENT,				/* selection text */
	STR_FLIGHT_MODE_QUERY,				/* selection text */
	STR_FLIGHT_MODE_CONFIRM,			/* confirmation text */
	STR_FLIGHT_MODE_RSK,				/* right softkey text */
	STR_FLIGHT_MODE_PROGRESS			/* progressing text */
	#ifdef __FLIGHT_MODE_RENAME_TO_ANTENNA_MODE__
	,
	STR_FLIGHT_MODE_IDLE,				/* idle screen text */
	STR_FLIGHT_MODE_POWERON				/* power on query screen text */
	#endif
};
 

enum IMG_SETTING_LIST
{
IMG_MENU9140_AUTO_REDIAL = SETTINGS_BASE+1,
IMG_SCR9001_CALL_SETTING_CAPTION,
IMG_SCR9001_CALL_SETTING_LSK,
IMG_SCR9001_CALL_SETTING_RSK,
IMG_SCR9033_AUTO_REDIAL_CAPTION,
IMG_SCR9033_AUTO_REDIAL_LSK,
IMG_SCR9033_AUTO_REDIAL_RSK,
IMG104_SCR8054_LSK,
IMG_SCR8055_SERVICE_OFF	,
IMG_SETTING_CALL_SETUP,
IMG_SETTING_SECURITY,
IMG_SETTING_NETWORK,
IMG_SETTING_STORE,
IMG_SCR_SETTING_CAPTION,
IMG_SETTING_BARRED_DIAL,
IMG_SETTING_FIXED_DIAL,
#ifdef __MMI_SOUND_EFFECT__
IMG_ID_SETTING_SOUND_EFFECT,
IMG_ID_SETTING_AUDIO_EQUALIZER, //18568
#endif
#ifndef __MMI_SUBLCD__
IMG_CONTRAST_BACKGROUND,
#endif
IMG_GROUPLIST_NO_IMAGE,
IMG_SETTING_SHORTCUT
};
//xiaoke 08.12.31
#ifdef __DOUBLE_SIMCARD_211__      
enum IMG_SETTING_DOUBLE_SIMCARD
{
IMG_ID_DOUBLE_SIMCARD_ICON = SWITCH_SIMCARD_BASE+1,
SCR_ID_SIMSWITCH_MAIN
};
#endif
//xiaoke 08.12.31

enum IMG_PHONE_SETUP
{
IMG_MENU9102_INITIAL_SETUP = PHONE_SETUP_BASE+1,
IMG_SETTING_DISP,
IMG_MENU9141_TIME_AND_DATE,
IMG_MENU9141_SCHEDULE_POWER,
IMG_MENU9141_WELLCOME,
IMG_MENU9141_SPEED_DIAL,
IMG_MENU9141_HANDWRITING,
IMG_MENU9141_CHANGE_WIN_WITH_DYNAMIC,
IMG_MENU9141_SMART_DIAL_STYLE,
IMG_MENU9141_LCD_LEVEL,
IMG_MENU9141_LCD_TIME,
IMG_SETTING_DISP_SCREEN_SAVER,
IMG_SETTING_DISP_WALLPAPER,
IMG_SETTING_DISP_POWER_ON,
IMG_SETTING_DISP_POWER_OFF,
IMG_SETTING_DISP_OWN_NUM,

IMG_SETTING_CALL_SET_SIM1,
IMG_SETTING_CALL_SET_SIM2,
IMG_SETTING_CALL_REMIND,
IMG_SETTING_CALL_DISP_TIME,
IMG_SETTING_CALL_AUTO_DIAL,
IMG_SETTING_CALL_BLACK_LIST,
IMG_SETTING_CALL_IP_NUM,
IMG_SETTING_CALL_MISS,
IMG_SETTING_CALLL_ANSWER,

IMG_SETTING_CALL_SETUP_WAIT,
IMG_SETTING_CALL_SETUP_DIVERT,
IMG_SETTING_CALL_SETUP_BARRING,
IMG_SETTING_CALL_SETUP_SWITCH,

IMG_MENU9142_SETTIME,
IMG_MENU9143_SETTIMEFORMAT,
IMG_MENU9144_SETDATE,
IMG_MENU9145_SETDATEFORMAT,
IMG_MENU9151_24HOURS,
IMG_MENU9152_AM_PM,
IMG_MENU9161_DATE_MONTH,
IMG_MENU9162_DATE_MONTH_YEAR,
IMG_MENU9163_MONTH_DATE_YEAR,
IMG_MENU9164_DATE_MONTH_YEAR2,
IMG_SCR9003_INITIALSETUP_CAPTION,
IMG_SCR9003_INITIALSETUP_LSK,
IMG_SCR9003_INITIALSETUP_RSK,
IMG_SCR9041_TIMEANDDATE_CAPTION,
IMG_SCR9041_TIMEANDDATE_LSK,
IMG_SCR9041_TIMEANDDATE_RSK,
IMG_SCR9042_SETTIME_CAPTION,
IMG_SCR9042_SETTIME_LSK,
IMG_SCR9042_SETTIME_RSK,
IMG_SCR9043_SETTIMEFORMAT_CAPTION,
IMG_SCR9043_SETTIMEFORMAT_LSK,
IMG_SCR9043_SETTIMEFORMAT_RSK,
IMG_SCR9044_SETDATE_CAPTION,
IMG_SCR9044_SETDATE_LSK,
IMG_SCR9044_SETDATE_RSK,
IMG_SCR9045_SETDATEFORMAT_CAPTION,
IMG_SCR9045_SETDATEFORMAT_LSK,
IMG_SCR9045_SETDATEFORMAT_RSK,
IMG_SCR9051_24HOURS_CAPTION,
IMG_SCR9051_24HOURS_LSK,
IMG_SCR9051_24HOURS_RSK,
IMG_SCR9051_24HOURS_MESSAGE,
IMG_SCR9052_AM_PM_CAPTION,
IMG_SCR9052_AM_PM_LSK,
IMG_SCR9052_AM_PM_RSK,
IMG_SCR9052_AM_PM_MESSAGE,
IMG_SCR9061_DATE_MONTH_CAPTION,
IMG_SCR9061_DATE_MONTH_LSK,
IMG_SCR9061_DATE_MONTH_RSK,
IMG_SCR9061_DATE_MONTH_MESSAGE,
IMG_SCR9062_DATE_MONTH_YEAR_CAPTION,
IMG_SCR9062_DATE_MONTH_YEAR_LSK,
IMG_SCR9062_DATE_MONTH_YEAR_RSK,
IMG_SCR9062_DATE_MONTH_YEAR_MESSAGE,
IMG_SCR9063_MONTH_DATE_YEAR_CAPTION,
IMG_SCR9063_MONTH_DATE_YEAR_LSK,
IMG_SCR9063_MONTH_DATE_YEAR_RSK,
IMG_SCR9063_MONTH_DATE_YEAR_MESSAGE,
IMG_SCR9064_DATE_MONTH_YEAR2_CAPTION,
IMG_SCR9064_DATE_MONTH_YEAR2_LSK,
IMG_SCR9064_DATE_MONTH_YEAR2_RSK,
IMG_SCR9064_DATE_MONTH_YEAR2_MESSAGE,
IMG_SETTING_PHONE,
#ifdef __T800_MAIN_MENU__
IMG_ID_DM_SETTING,
#endif
IMG_TIME_AND_DATE_BLANK,
IMG_DATE_TIME_SET_FORMAT_CAPTION,
IMG_MENU9142_SETHOMECITY,
#ifdef __MMI_TOUCH_SCREEN__
IMG_CALIBRATION_MENU_ICON,
IMG_CALIBRATION_TOP_LEFT, /* Don't change the order of these three images */
IMG_CALIBRAION_BOTTOM_RIGHT,
IMG_CALIBRATION_CENTER,
#endif /* __MMI_TOUCH_SCREEN__ */
IMG_SETTING_GREET_TEXT,
IMG_SETTING_GREET_STATUS,

	#ifdef __MMI_TVOUT__
		IMG_ID_POPUP_TVOUT,
	#endif /* __MMI_TVOUT__ */
	
	END_OF_IMAGES
};

enum IMG_SETTING_LANGUAGE_LIST
{
IMG_MENU_LANGUAGE = LANG_SETTINGS_BASE+1
};

 
enum IMG_FLIGHT_MODE_LIST
{
	IMG_MENU_FLIGHT_MODE = FLIGHT_MODE_BASE+1,
	IMG_FLIGHT_MODE_PROGRESS
};
 

#define MAX_LENGTH_YEAR 5
#define MAX_SETTING_WELCOME_TEXT 30
#define NUM_ITEMS_DATE_TIME_FORMAT_ENTRY_SCREEN 4
#define NUM_TIME_FORMATS 2
#if defined(__PROJECT_GALLITE_C01__)
#define	NUM_DATE_FORMATS 2
#else
#if defined( __MMI_NOKIA_STYLE_N800__)||defined( __MMI_MAINLCD_220X176__  )
#define	NUM_DATE_FORMATS 5
#else
#define	NUM_DATE_FORMATS 6
#endif
#endif
#define MAX_LENGTH 3

//security definitions 
#define MIN_PASSWORD_LENGTH 4
#define MAX_SIM_SETTING_PASSWD_LEN  8
#define MAX_PASS_COUNTDOWN_DISP 60

#define 	FACTORY_RESTORE_DEFAULT_SPEED_DIAL						0
#define 	FACTORY_RESTORE_DEFAULT_CONTRAST_SUBLCD_LEVEL_VALUE		7
#define 	FACTORY_RESTORE_DEFAULT_CONTRAST_MAINLCD_LEVEL_VALUE	7
#define 	FACTORY_RESTORE_DEFAULT_WELCOME_TEXT_STATUS				0
#define		FACTORY_RESTORE_DEFAULT_APHORISM_TEXT_STATUS			1
#define 	FACTORY_RESTORE_DEFAULT_OWNER_NO_STATUS					0
#define 	FACTORY_RESTORE_DEFAULT_STATUS_SHOW_DT_TIME_STATUS		1
#define 	FACTORY_RESTORE_DEFAULT_AUTOUPDATE_TIME_VALUE			0
#define 	FACTORY_RESTORE_DEFAULT_SCREENSAVER_STATUS				0
#define 	FACTORY_RESTORE_DEFAULT_SCREENSAVER_WAITING_TIME		30
#define		FACTORY_RESTORE_DEFAULT_CURRENT_SCREENSVER_ID			(SCREENSAVER_BASE + 1)		
#define		FACTORY_RESTORE_DEFAULT_PROFILES_ACTIVATED_ID			0
#define		FACTORY_RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER_ID		(WALLPAPER_BASE + 1)	

#endif


