## --------------Don't change the line below------------------ ##
# For more information on the different variables, and others you
# may define, see ${SOFT_DIR}/Makefile.skel and/or read the doc
include ${SOFT_WORKDIR}/env/compilation/compilevars.mk

LOCAL_NAME := platform/edrv/camd/siv100b

LOCAL_API_DEPENDS ?= \
        target \
        platform \
        platform/stack \
        platform/base/common \
        platform/base/sx \
        platform/chip/hal \
        platform/chip/defs \
        platform/edrv/camd \
        platform/edrv/pmd \
        platform/edrv \



C_SRC := drv_camera.c
S_SRC :=


## --------------Don't change the line below------------------ ##
include ${SOFT_WORKDIR}/env/compilation/compilerules.mk
