////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//            Copyright (C) 2003-2007, Coolsand Technologies, Inc.            //
//                            All Rights Reserved                             //
//                                                                            //
//      This source code is the property of Coolsand Technologies and is      //
//      confidential.  Any  modification, distribution,  reproduction or      //
//      exploitation  of  any content of this file is totally forbidden,      //
//      except  with the  written permission  of  Coolsand Technologies.      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file                                                                     //
/// That file Implements the functions to register the module.
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "cs_types.h"

#include "hal_map_engine.h"

#include "calibp_calibration.h"

#include "calib_m.h"
#include "calib_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#define CALIB_VERSION_STRING "Calibration Daemon v" \
                             STRINGIFY_VALUE(CALIB_MAJ_VERSION) "." \
                             STRINGIFY_VALUE(CALIB_MIN_VERSION)
#include "calibp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_calibMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_calibMapVersion = CALIB_VERSION_STRUCT;



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// calib_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID calib_RegisterYourself(VOID)
{
    //  Init the pointer used by HST to say talk with the Platform's calibration code.
    //  This will allow HST to read the calib buffer. 
    hal_MapEngineRegisterModule(HAL_MAP_ID_CALIB, &g_calibMapVersion, &g_calibCalibration);
}
