#ifndef _PROTO_H_
#define _PROTO_H_
/* This file is automatically generated with "make proto". DO NOT EDIT */


/*The following definitions come from  conform_tests.c  */

u_int32 prh_test_rfcomm_iut_no_mmi(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_not_impl(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_01_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_02_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_03_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_06_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_07_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_08_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_09_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_10_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_11_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_12_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_13_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_15_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_17_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
u_int32 prh_test_rfcomm_iut_TP_RFC_BV_19_C(t_bdaddr remoteAddress, u_int32 groupParam, u_int32 testParam);
int rftest_data_buf_release_header(t_DataBuf *buf, u_int32 size);

int prh_rftest_cc_create_test(t_DataBuf *frame, u_int8 cresp);
int prh_rftest_cc_create_fcon(t_DataBuf *frame, u_int8 cresp);
int prh_rftest_cc_create_fcoff(t_DataBuf *frame, u_int8 cresp);
int prh_rftest_cc_create_nsc(t_DataBuf *frame, u_int8 cresp, u_int8 nscom, u_int8 nscomm_cr);
int prh_rftest_cc_create_rpn_req(t_DataBuf *frame, u_int8 cresp, prh_t_rfcomm_dlci dlci);
int prh_rftest_cc_create_rpn_comm(t_DataBuf *frame, u_int8 cresp, prh_t_rfcomm_dlci dlci ,prh_t_rfcomm_port_params *port_parameters);
int prh_rftest_cc_create_msc(t_DataBuf *frame, u_int8 cresp, prh_t_rfcomm_dlci dlci, prh_t_rfcomm_control_params *ctrl_params);
int prh_rftest_cc_create_rls(t_DataBuf *frame, u_int8 cresp, prh_t_rfcomm_dlci dlci, prh_t_rfcomm_line_stat_params line_stat_params);
int prh_rftest_cc_create_pn(t_DataBuf *frame, u_int8 cresp, prh_t_rfcomm_dlci dlci, prh_t_rfcomm_dlc_params *dlc_params);
int prh_rftest_cc_create_credit_pn(t_DataBuf *frame, u_int8 cresp, prh_t_rfcomm_dlci dlci, prh_t_rfcomm_dlc_params *dlc_params, u_int8 clbits, u_int8 kbits);

/*The following definitions come from  rftest_frames.c  */

int rftest_data_buf_reserve_header(t_DataBuf *buf, u_int32 size);
int rftest_data_buf_release_header(t_DataBuf *buf, u_int32 size);
int prh_rftest_create_sabm(t_DataBuf *frame, prh_t_rfcomm_dlci DLCI, u_int8 pbit, u_int32 cresp);
int prh_rftest_create_ua(t_DataBuf *frame, prh_t_rfcomm_dlci DLCI, u_int8 fbit, u_int32 cresp);
int prh_rftest_create_dm(t_DataBuf *frame, prh_t_rfcomm_dlci DLCI, u_int8 fbit, u_int32 cresp);
int prh_rftest_create_disc(t_DataBuf *frame, prh_t_rfcomm_dlci DLCI, u_int8 fbit, u_int32 cresp);
int prh_rftest_create_uih(t_DataBuf *frame, prh_t_rfcomm_dlci DLCI, u_int8 pbit, u_int32 cresp);
int prh_rftest_create_uih_credit(t_DataBuf *frame, prh_t_rfcomm_dlci DLCI, u_int8 pbit, u_int32 cresp, u_int8 num_credits);
int prh_rftest_destroy_uih(t_DataBuf *frame);
int prh_rftest_add_fcs(t_DataBuf *frame, int fcs_len);
int prh_rftest_rx_fcs(t_DataBuf *frame, int fcs_len);
int prh_rftest_dump_frame(t_DataBuf *frame, int tx);

/*The following definitions come from  rftest_handle_pdu.c  */

int rftest_init_events(void);
int rftest_free_events(void);
int rftest_dumpua(void);
int rftest_takeua(t_DataBuf **ua_buf);
int rftest_gotua(t_DataBuf *p_buf);

/*The following definitions come from  rftest_l2cap.c  */

void rftest_l2cap_connect_ind(u_int8 eventType, t_L2_ControlCallbackArgs *args);
void rftest_l2cap_config_ind_cb(u_int8 eventType, t_L2_ControlCallbackArgs *args);
void rftest_l2cap_config_cfm_cb(u_int8 eventType, t_L2_ControlCallbackArgs *args);
void rftest_l2cap_disc_ind_cb(u_int8 eventType, t_L2_ControlCallbackArgs *args);
void rftest_l2cap_disc_cfm_cb(u_int8 eventType, t_L2_ControlCallbackArgs *args);
void rftest_l2cap_connect_cfm_cb(u_int8 eventType, t_L2_ControlCallbackArgs *args);
void rftest_l2cap_connect(t_bdaddr remoteaddress);
int rftest_init(void);

/*The following definitions come from  rftest_pdu_gen.c  */

int rftest_sendua(prh_t_rfcomm_dlci dlci, u_int8 fbit, u_int8 cresp);
int rftest_sendsabm(prh_t_rfcomm_dlci dlci, u_int8 fbit, u_int8 cresp);
int rftest_senddisc(prh_t_rfcomm_dlci dlci, u_int8 fbit, u_int8 cresp);
int rftest_sendmsc_reply(prh_t_rfcomm_dlci dlci, u_int8 cresp, char *inframe);
int rftest_sendmsc(prh_t_rfcomm_dlci dlci, u_int8 cresp, prh_t_rfcomm_control_params *ctrl_params);
int rftest_sendtest(int cresp);
int rftest_sendrls(prh_t_rfcomm_dlci dlci, u_int8 cresp, prh_t_rfcomm_line_stat_params lsp);
int rftest_sendpn(prh_t_rfcomm_dlci dlci, u_int8 cresp, u_int16 max_frame_size);
int rftest_sendrpnc(prh_t_rfcomm_dlci dlci, u_int8 cresp, prh_t_rfcomm_port_params *port_params);
int rftest_sendrpnr(prh_t_rfcomm_dlci dlci, u_int8 cresp);
int rftest_send_fcon(int cresp);
int rftest_send_fcoff(int cresp);
void rftest_l2cap_data_ind_cb(u_int16 cid, t_DataBuf *p_buf);
int rftest_handle_uih(t_DataBuf *buffer, prh_t_rfcomm_dlci dlci);
int rftest_passed(void);
int rftest_failed(void);

/*The following definitions come from  test_run.c  */

int host_init(int mode);
void app_manager_inquiry_cb(t_MGR_DeviceEntry *deviceInfo, u_int8 status);
int main(int argc, char **argv);
void connect_Callback(int transid, int result);
int baseband_connect(void);
#endif /* _PROTO_H_ */
