
##############################################
# ÒÔÏÂÄÚÈÝÇë½÷É÷±à¼­
##############################################

##############################################
# make configuration option for the mmi code. 
# don't modify
##############################################
ifndef MMI_SUPPORT_SIM_NUMBER
$(error "MMI_SUPPORT_SIM_NUMBER not defined")
endif

ifneq "$(strip ${MMI_SUPPORT_SIM_NUMBER})" "1"
MMI_EXPORT_FLAG += __MMI_MULTI_SIM__
MMI_EXPORT_FLAG += __ADP_MULTI_SIM__
endif

MMI_EXPORT_FLAG += MMI_SIM_NUMBER=${MMI_SUPPORT_SIM_NUMBER}
MMI_EXPORT_FLAG += ADP_SIM_NUMBER=${MMI_SUPPORT_SIM_NUMBER}

ifndef MMI_SUPPORT_BLUETOOTH
$(error "MMI_SUPPORT_BLUETOOTH not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_BLUETOOTH})" "YES" 
MMI_EXPORT_FLAG += __MMI_SUPPORT_BLUETOOTH__
ifneq ($(findstring rda,${BT_MODEL}),) # rda BT
MMI_BT_MODEL := rda5868
endif # rda bt
endif # MMI_SUPPORT_BLUETOOTH

ifndef MMI_SUPPORT_WAPMMS
$(error "MMI_SUPPORT_WAPMMS not defined")
endif

ifeq "$(strip ${MMI_SUPPORT_GPRS})" "YES" 
MMI_EXPORT_FLAG += __GPRS_MODE__ 
MMI_EXPORT_FLAG += __TCPIP__ 
MMI_EXPORT_FLAG += __MOD_TCM__ 
MMI_EXPORT_FLAG += CFW_GPRS_SUPPORT
MMI_EXPORT_FLAG += CFW_TCPIP_SUPPORT
endif
ifeq "$(strip ${MMI_SUPPORT_WAPMMS})" "YES" 

MMI_EXPORT_FLAG += JATAAYU_SUPPORT
ifeq "$(strip ${MMI_SUPPORT_WAP})" "YES" 
MMI_EXPORT_FLAG +=  JATAAYU_SUPPORT_WAP
endif
ifeq "$(strip ${MMI_SUPPORT_MMS})" "YES"  
MMI_EXPORT_FLAG +=  JATAAYU_SUPPORT_MMS
endif
ifeq "$(strip ${MMI_SUPPORT_JAT_OTA})" "YES" 
MMI_EXPORT_FLAG += JATAAYU_SUPPORT_OTA
endif
ifeq "$(strip ${MMI_SUPPORT_JAT_OMA_DLD})" "YES" 
MMI_EXPORT_FLAG += JATAAYU_SUPPORT_OMA_DOWNLOAD
endif
ifeq "$(strip ${MMI_SUPPORT_JAT_SEC})" "YES" 
MMI_EXPORT_FLAG += JATAAYU_SUPPORT_SECURITY
endif
ifeq "$(strip ${MMI_SUPPORT_WAPPUSH})" "YES" 
MMI_EXPORT_FLAG += JWAP_PUSH_ENABLE
endif

endif

ifndef MMI_SUPPORT_USB
$(error "MMI_SUPPORT_USB not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_USB})" "YES" 
MMI_EXPORT_FLAG += __USB_ENABLE__
endif

ifndef MMI_SUPPORT_FM
$(error "MMI_SUPPORT_FM not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_FM})" "YES" 
MMI_EXPORT_FLAG += FM_RADIO_ENABLE
endif

ifeq "$(strip ${MMI_SUPPORT_FM_RECORD})" "YES" 
MMI_EXPORT_FLAG += FM_RADIO_RECORD
endif
ifndef MMI_SUPPORT_TOUCHPANEL
$(error "MMI_SUPPORT_TOUCHPANEL not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_TOUCHPANEL})" "YES" 
MMI_EXPORT_FLAG += TOUCH_PANEL_SUPPORT
endif


ifndef MMI_SUPPORT_LANG_FRENCH
$(error "MMI_SUPPORT_LANG_FRENCH not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_FRENCH})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_FRENCH__
endif

ifndef MMI_SUPPORT_LANG_ITALIAN
$(error "MMI_SUPPORT_LANG_ITALIAN not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_ITALIAN})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_ITALIAN__
endif

ifndef MMI_SUPPORT_LANG_VIETNAMESE
$(error "MMI_SUPPORT_LANG_VIETNAMESE not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_VIETNAMESE})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_VIETNAMESE__
endif

ifndef MMI_SUPPORT_LANG_RUSSIAN
$(error "MMI_SUPPORT_LANG_RUSSIAN not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_RUSSIAN})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_RUSSIAN__
endif

ifndef MMI_SUPPORT_LANG_ARABIC
$(error "MMI_SUPPORT_LANG_ARABIC not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_ARABIC})" "YES" 
MMI_EXPORT_FLAG += BIDI_SUPPORT
endif

ifndef MMI_SUPPORT_LANG_THAI
$(error "MMI_SUPPORT_LANG_THAI not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_THAI})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_THAI__
endif

ifndef MMI_SUPPORT_LANG_SM_CHINESE
$(error "MMI_SUPPORT_LANG_SM_CHINESE not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_SM_CHINESE})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_SM_CHINESE__
endif

ifndef MMI_SUPPORT_LANG_TR_CHINESE
$(error "MMI_SUPPORT_LANG_TR_CHINESE not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_TR_CHINESE})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_TR_CHINESE__
endif

ifndef MMI_SUPPORT_LANG_HINDI
$(error "MMI_SUPPORT_LANG_HINDI not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_HINDI})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_HINDI__
MMI_EXPORT_FLAG += __MMI_HINDI_ALG__
endif

ifndef MMI_SUPPORT_LANG_GERMAN
$(error "MMI_SUPPORT_LANG_GERMAN not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_GERMAN})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_GERMAN__
endif

ifndef MMI_SUPPORT_LANG_SPANISH
$(error "MMI_SUPPORT_LANG_SPANISH not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_SPANISH})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_SPANISH__
endif

ifndef MMI_SUPPORT_LANG_PORTUGUESE
$(error "MMI_SUPPORT_LANG_PORTUGUESE not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_PORTUGUESE})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_PORTUGUESE__
endif

ifndef MMI_SUPPORT_LANG_PERSIAN
$(error "MMI_SUPPORT_LANG_PERSIAN not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_PERSIAN})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_PERSIAN__
endif

ifndef MMI_SUPPORT_LANG_TURKISH
$(error "MMI_SUPPORT_LANG_TURKISH not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_TURKISH})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_TURKISH__
endif

ifndef MMI_SUPPORT_LANG_INDONESIAN
$(error "MMI_SUPPORT_LANG_INDONESIAN not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_INDONESIAN})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_INDONESIAN__
endif

ifndef MMI_SUPPORT_LANG_MALAY
$(error "MMI_SUPPORT_LANG_MALAY not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_MALAY})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_MALAY__
endif

ifndef MMI_SUPPORT_INDIC_LANGUAGES
$(error "MMI_SUPPORT_INDIC_LANGUAGES not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_INDIC_LANGUAGES})" "YES" 
MMI_EXPORT_FLAG += __MMI_HINDI_ALG__
endif
 
ifndef MMI_SUPPORT_LANG_HINDI
$(error "MMI_SUPPORT_LANG_HINDI not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_HINDI})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_HINDI__
MMI_EXPORT_FLAG += __MMI_MULTITAP_HINDI__

endif

ifndef MMI_SUPPORT_LANG_TELUGU
$(error "MMI_SUPPORT_LANG_TELUGU not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_TELUGU})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_TELUGU__
endif

ifndef MMI_SUPPORT_LANG_PUNJABI
$(error "MMI_SUPPORT_LANG_PUNJABI not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_PUNJABI})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_PUNJABI__
endif

ifndef MMI_SUPPORT_LANG_BENGALI
$(error "MMI_SUPPORT_LANG_BENGALI not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_BENGALI})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_BENGALI__
endif

ifndef MMI_SUPPORT_LANG_ORIYA
$(error "MMI_SUPPORT_LANG_ORIYA not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_ORIYA})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_ORIYA__
endif

ifndef MMI_SUPPORT_LANG_TAMIL
$(error "MMI_SUPPORT_LANG_TAMIL not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_TAMIL})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_TAMIL__
endif

ifndef MMI_SUPPORT_LANG_KANNADA
$(error "MMI_SUPPORT_LANG_KANNADA not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_KANNADA})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_KANNADA__
endif

ifndef MMI_SUPPORT_LANG_MALAYALAM
$(error "MMI_SUPPORT_LANG_MALAYALAM not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_MALAYALAM})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_MALAYALAM__
endif

ifndef MMI_SUPPORT_LANG_MARATHI
$(error "MMI_SUPPORT_LANG_MARATHI not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_LANG_MARATHI})" "YES" 
MMI_EXPORT_FLAG += __MMI_LANG_MARATHI__
endif
ifndef MMI_SUPPORT_SIDEKEY
$(error "MMI_SUPPORT_SIDEKEY not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_SIDEKEY})" "NO" 
MMI_EXPORT_FLAG += __MMI_NO_SIDEKEY__
endif

ifndef MMI_SUPPORT_SENDKEY2
$(error "MMI_SUPPORT_SENDKEY2 not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_SENDKEY2})" "YES" 
#ifeq "$(strip ${MMI_SUPPORT_SIM_NUMBER})" "2" 
MMI_EXPORT_FLAG += __SENDKEY2_SUPPORT__
#else
#$(error "__SENDKEY2_SUPPORT__ not defined")
#endif
else
endif

ifndef MMI_SUPPORT_CAMERAKEY
$(error "MMI_SUPPORT_CAMERAKEY not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_CAMERAKEY})" "YES" 
MMI_EXPORT_FLAG += __MMI_CAMERA_KEY__
endif

ifndef MMI_SUPPORT_GSENSOR
$(error "MMI_SUPPORT_GSENSOR not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_GSENSOR})" "YES" 
MMI_EXPORT_FLAG += MOTION_SENSOR_SUPPORT
endif

ifndef MMI_SUPPORT_WEBCAM
$(error "MMI_SUPPORT_WEBCAM not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_WEBCAM})" "YES" 
MMI_EXPORT_FLAG += WEBCAM_SUPPORT
endif

ifndef MMI_SUPPORT_MAGIC_SOUND
$(error "MMI_SUPPORT_MAGIC_SOUND not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_MAGIC_SOUND})" "YES" 
MMI_EXPORT_FLAG += MAGIC_AE_SUPPORT
else
MMI_EXPORT_FLAG += TARGET_MAGIC_SOUND_OFF
endif

MMI_EXPORT_FLAG += ${MMI_PARAM_LCDSIZE} 


ifndef MMI_SUPPORT_DUAL_SENSOR
$(error "MMI_SUPPORT_DUAL_SENSOR not defined")
endif
ifeq "$(strip ${MMI_SUPPORT_DUAL_SENSOR})" "NO" 
MMI_EXPORT_FLAG +=__MMI_DISABLE_DUAL_SENSOR__
endif

ifeq "${CAM_MD_SUPPORT}" "1"
MMI_EXPORT_FLAG += CAM_MD_SUPPORT
endif

ifeq "$(strip ${MMI_SUPPORT_MESSAGES_BLACK_LIST})" "YES"
MMI_EXPORT_FLAG += __MMI_MESSAGES_BLACK_LIST__
endif
MMI_EXPORT_FLAG += MAX_PHB_PHONE_ENTRY=${PHONE_PHB_ENTRY_COUNT}

MMI_EXPORT_FLAG += CM_SMS_MAX_MSG_NUM=${PHONE_SMS_ENTRY_COUNT}  
MMI_EXPORT_FLAG += MAX_INDEX_MAP_LENGTH=${PHONE_SMS_ENTRY_COUNT}


##############################################
# fixed option
# don't modify
##############################################

MMI_EXPORT_FLAG += __CB__ 	
MMI_EXPORT_FLAG += __DCS1800__ 	
#MMI_EXPORT_FLAG += __DOUBLE_SIMCARD_211__	
MMI_EXPORT_FLAG += __EGSM900__ 	
MMI_EXPORT_FLAG += __EM_MODE__	
MMI_EXPORT_FLAG += __FF_AUDIO_SET__	
MMI_EXPORT_FLAG += __GSM_MODE__ 	
MMI_EXPORT_FLAG += __MCD__ 	
MMI_EXPORT_FLAG += __MED_MJPG_AUDIO__ 	
MMI_EXPORT_FLAG += __MED_MMA_MOD__ 	
#MMI_EXPORT_FLAG += __MMI_EBOOK_READER__	
MMI_EXPORT_FLAG += __MMI_GB__ 	
MMI_EXPORT_FLAG += __MMI_SMART_ENGLISH__	
MMI_EXPORT_FLAG += __MMI_IMAGE_VIEWER__	
MMI_EXPORT_FLAG += __MMI_MERGE_SAT_TO_MAINMENU__	
MMI_EXPORT_FLAG += __MMI_VIDEO_RECORDER__	
MMI_EXPORT_FLAG += __MOD_CSM__ 	
#MMI_EXPORT_FLAG += __MOD_FLASHLIGHT__	
MMI_EXPORT_FLAG += __MOD_NVRAM__	
MMI_EXPORT_FLAG += __MOD_ORGANIZER__	
MMI_EXPORT_FLAG += __MOD_PHB__ 	
MMI_EXPORT_FLAG += __MOD_RAC__ 	
MMI_EXPORT_FLAG += __MOD_SIM__ 	
MMI_EXPORT_FLAG += __MOD_SMS__ 	
MMI_EXPORT_FLAG += __MOD_SMSAL__ 	
MMI_EXPORT_FLAG += __MOD_SMU__ 	
MMI_EXPORT_FLAG += __MOD_UEM__ 	
#MMI_EXPORT_FLAG += __NO_SIDE_VOLUME_KEY_STAR_POUND__	
MMI_EXPORT_FLAG += __SAT__ 	
#MMI_EXPORT_FLAG += __SP__	
MMI_EXPORT_FLAG += __UCS2_ENCODING 	
MMI_EXPORT_FLAG += __VIBRATOR__	
MMI_EXPORT_FLAG += APPMEM_SUPPORT 	
MMI_EXPORT_FLAG += CAMERA_MODULE 	
MMI_EXPORT_FLAG += CSD_NEW_API 	
MMI_EXPORT_FLAG += CSD_TARGET 	
MMI_EXPORT_FLAG += JPG_DECODE 	
MMI_EXPORT_FLAG += JPG_DECODE_USING_SOFTWARE	
MMI_EXPORT_FLAG += MESSAGES_APPLICATION 	
MMI_EXPORT_FLAG += MJPG_SUPPORT 	
MMI_EXPORT_FLAG += MMI_ON_HARDWARE_P 	
MMI_EXPORT_FLAG += MT6205B 	
MMI_EXPORT_FLAG += SHORTCUTS_APP 	
MMI_EXPORT_FLAG += SIM_APP_TOOLKIT 	
MMI_EXPORT_FLAG += VM_SUPPORT
MMI_EXPORT_FLAG += DAF_DECODE
MMI_EXPORT_FLAG += AAC_DECODE

MMI_EXPORT_FLAG +=__MMI_RESOURCE_SLIM__
MMI_EXPORT_FLAG += __GSM850__ 
MMI_EXPORT_FLAG += __PCS1900__ 
# Fine tune USB-Update
MMI_EXPORT_FLAG +=__MMI_USB_DOWNLOAD_FR__

ifeq "$(strip ${MMI_SUPPORT_JME})" "YES"
MMI_EXPORT_FLAG += __MMI_SUPPORT_JME__
MMI_EXPORT_FLAG += _MMI_SUPPORT_JME_QQ_
#MMI_EXPORT_FLAG += _MMI_SUPPORT_JME_MSN_
#MMI_EXPORT_FLAG += _MMI_SUPPORT_JME_GEO_
endif

# turn torch support on T800
#MMI_EXPORT_FLAG +=__MOD_FLASHLIGHT__

ifeq "$(strip ${ANALOG_TV_SUPPORT})" "1" 
MMI_EXPORT_FLAG += __MMI_ANALOGTV__
endif

MMI_EXPORT_FLAG += __MMI_NOKIA_STYLE_N800__
#MMI_EXPORT_FLAG += RESTOR_BY_CLEAR_USERDATA

ifeq "${CAM_MD_SUPPORT}" "1"
MMI_EXPORT_FLAG += CAM_MD_SUPPORT
endif

ifeq "$(strip ${MMI_SUPPORT_J2ME})" "YES" 
MMI_EXPORT_FLAG +=__J2ME__
endif

#define feature: LCD ROTATE 
#MMI_EXPORT_FLAG += __CSD_DRV_SUPPORT_LCM_ROTATE__

# From compile.rules
#MMI_EXPORT_FLAG += FPM_MIPS

MMI_EXPORT_FLAG += __PHB_CALLER_IMAGE_SAVE_PATH_ONLY__

MMI_EXPORT_FLAG += __MMI_USE_DM_VOLUME_LEVEL_DISPLAY__
#MMI_EXPORT_FLAG +=__MMI_LARGE_FONTS__
#MMI_EXPORT_FLAG +=__MMI_LARGE_EN_FONTS__
#MMI_EXPORT_FLAG +=__MMI_16X16_CHINESE_FONT__
# FIXED #
LOCAL_EXPORT_FLAG += ${MMI_EXPORT_FLAG}
