/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  NVRAMEnum.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

/**********************************************************************************
	Filename:		NVRMEnum.h
 
	Date Created:	
	Contains:		NVRAM declarations
**********************************************************************************/


#ifndef _NVRM_ENUM_H
#define _NVRM_ENUM_H

#ifdef MMI_ON_HARDWARE_P
	#include "nvram_user_defs.h"
#endif
#include "mmi_data_types.h"

#ifdef MMI_ON_WIN32
#include "cswtype.h"
#define NVRAM_COMPOSE_RINGTONE_SIZE   40*5
#define NVRAM_PICTURE_EDITOR_SIZE   40*5
#define NVRAM_EF_FM_RADIO_SIZE  396

#define NVRAM_EF_FMGR_FILEPATH_POOL_HEAD_TOTAL		4
#define NVRAM_EF_FMGR_FILEPATH_POOL_HEAD_SIZE  		510
#define NVRAM_EF_FMGR_FILEPATH_POOL_TAIL_TOTAL		4
#define NVRAM_EF_FMGR_FILEPATH_POOL_TAIL_SIZE  		10

#define NVRAM_EF_PHB_VIDEO_COUNT					500
#define NVRAM_EF_PHB_VIDEO_SIZE					1000

#define NVRAM_EF_CAMERA_SETTING_SIZE			84
#define NVRAM_EF_PHOTO_EDITOR_SETTING_SIZE	200
#define NVRAM_EF_VIDEO_SETTING_SIZE				51


#define NVRAM_CACHE_SIZE					256	/*For Cache file*/
#define NVRAM_CACHE_TOTAL					3	/*For Cache file*/

#define NVRAM_PHB_SETTINGS_SIZE			20
#define NVRAM_PHB_SETTINGS_TOTAL			1

#define NVRAM_EF_PHB_BIRTHDAY_COUNT		250
#define NVRAM_EF_PHB_BIRTHDAY_SIZE		1000
#define NVRAM_EF_PHB_BIRTHDAY_TOTAL		1


typedef enum 
{
    NVRAM_EF_SMS_LID = 33,
    NVRAM_EF_SMS_CB_CHNL_LID,
    NVRAM_EF_SMS_CB_SMS_LID,
    NVRAM_EF_SMS_CB_SMS_INFO_LID,
    NVRAM_EF_PHB_IDS_LID,
    NVRAM_EF_PHB_SETTINGS_LID,
    NVRAM_EF_PHB_CALLER_GROUPS_LID,
    NVRAM_EF_PROFILES_LID,
    NVRAM_EF_GROUPLIST_LID,
    NVRAM_EF_CALL_TIME_LID,
    NVRAM_EF_CALL_COST_GET_MAX_LID,
    NVRAM_EF_CALL_COST_GET_ALL_COST_LID,
    NVRAM_EF_CALL_COST_GET_LAST_COST_LID,
    NVRAM_EF_CALL_COST_GET_CURRENCY_LID,
    NVRAM_EF_CALL_COST_GET_PPU_LID,
    NVRAM_EF_BT_INFO_LID,
    NVRAM_EF_ALM_QUEUE_LID,
    NVRAM_EF_SYS_CACHE_OCTET_LID,
    NVRAM_EF_CAMERA_PARA_LID,
    NVRAM_EF_WPSS_FILENAME_LID,
    NVRAM_EF_AUTOTEST_LID,
    NVRAM_EF_FMGR_FILEPATH_POOL_HEAD_LID,
    NVRAM_EF_FMGR_FILEPATH_POOL_TAIL_LID,
    NVRAM_EF_ALM_SPOF_DATA_LID,
    NVRAM_EF_PHB_COMPARE_DIGIT_LID,
    NVRAM_EF_CAMERA_SETTING_LID,
    NVRAM_EF_VIDEO_SETTING_LID,
    NVRAM_EF_CUST_ACOUSTIC_DATA_LID,
    NVRAM_EF_AUDIO_PARAM_LID,
    NVRAM_EF_BARCODE_NUM_LID,
    
#ifdef __MMI_NOTEPAD__
    NVRAM_EF_NOTEPAD_LIST_LID,
    NVRAM_EF_NOTEPAD_RECORD_LID,
#endif

#ifdef __GPRS_MODE__
    NVRAM_EF_CSD_PROFILE_LID,
    NVRAM_EF_ABM_GPRS_PROFILE_LID,
#endif

#ifdef __IP_NUMBER__
    NVRAM_EF_IP_NUMBER_LID,
#endif

#ifdef __MMI_PROFILE_EXTMELODY_SUPPORT__
    NVRAM_EF_EXT_MELODY_INFO_LID,
#endif

#if defined(__MMI_VCARD__)
    NVRAM_EF_PHB_VCARD_LID,
#endif

#ifdef __MMI_STOPWATCH__
    NVRAM_EF_STOPWATCH_LID,
#endif

#ifdef __MMI_MESSAGES_CHAT__
    NVRAM_EF_CHAT_ROOM_INFO_LID,
#endif

#ifdef __MMI_MESSAGES_CLUB__
    NVRAM_EF_MSG_CLUB_NUM_LID,
#endif

#ifdef __MMI_CM_BLACK_LIST__
    NVRAM_EF_BLACK_LIST_LID,
#endif

#ifdef __MMI_SOUND_EFFECT__
    NVRAM_EF_AUDIO_EQUALIZER_LID,
#endif

#if defined(__MMI_PHB_BIRTHDAY_FIELD__)
    NVRAM_EF_PHB_BIRTHDAY_LID,
#endif

#ifdef __MMI_FM_RADIO__
    NVRAM_EF_FM_RADIO_LID,
#endif

#if defined(__MMI_FM_RADIO_SCHEDULE_REC__)
    NVRAM_EF_FMSR_SETTING_LID,
#endif

#ifdef __MMI_PHOTOEDITOR__
    NVRAM_EF_PHOTO_EDITOR_SETTING_LID,
#endif

#ifdef __MMI_INCOMING_CALL_VIDEO__
    NVRAM_EF_PHB_VIDEO_LID,
#endif

#ifdef JATAAYU_SUPPORT
    NVRAM_EF_WAP_PROFILE_CONTENT_LID,

#ifdef __MMI_MULTI_SIM__
    NVRAM_EF_WAP_PROFILE_CONTENT_SIM2_LID,
    NVRAM_EF_WAP_PROFILE_CONTENT_SIM3_LID,
    NVRAM_EF_WAP_PROFILE_CONTENT_SIM4_LID,
#endif

    NVRAM_EF_MMS_PROFILE_CONTENT_LID,

#ifdef __MMI_MULTI_SIM__
    NVRAM_EF_MMS_PROFILE_CONTENT_SIM2_LID,
    NVRAM_EF_MMS_PROFILE_CONTENT_SIM3_LID,
    NVRAM_EF_MMS_PROFILE_CONTENT_SIM4_LID,
#endif

    NVRAM_EF_WAP_PROFILE_NAMES_LID,

#ifdef __MMI_MULTI_SIM__
    NVRAM_EF_WAP_PROFILE_NAMES_SIM2_LID,
    NVRAM_EF_WAP_PROFILE_NAMES_SIM3_LID,
    NVRAM_EF_WAP_PROFILE_NAMES_SIM4_LID,
#endif

    NVRAM_EF_MMS_PROFILE_NAMES_LID,

#ifdef __MMI_MULTI_SIM__
    NVRAM_EF_MMS_PROFILE_NAMES_SIM2_LID,
    NVRAM_EF_MMS_PROFILE_NAMES_SIM3_LID,
    NVRAM_EF_MMS_PROFILE_NAMES_SIM4_LID,
#endif

#endif/*JATAAYU_SUPPORT*/

#ifdef __MMI_EBOOK_READER__ 
    NVRAM_EF_EBOOK_SETTINGS_LID,
#endif

#if defined( __MMI_ANALOGTV__)	
    NVRAM_EF_ATV_PLAYER_SETTINGS_LID,
    NVRAM_EF_ATV_PLAYER_CHANNEL_LID,
#endif

#ifdef __MMI_NITZ__
    NVRAM_EF_NITZ_NW_NAME_LID,
#endif

#if defined(CSD_HW_LEVEL_NVRAM)
    NVRAM_EF_CUST_HW_LEVEL_TBL_LID,
#endif

#if defined(CSD_PHB_EXT_NVRAM)
    NVRAM_EF_PHB_LID,
    NVRAM_EF_PHB_LN_ENTRY_LID,
#endif

#if defined(SHORTCUTS_APP)
    NVRAM_EF_SHORTCUTS_LID,
#endif

#if defined(__DOWNLOAD__)    
    NVRAM_EF_EMS_MY_PICTURE_NAME_LID,
#endif

#if defined(__MMI_IMELODY_SUPPORT__)
    NVRAM_EF_EMS_MY_ANIMATION_NAME_LID,
    NVRAM_EF_EMS_MY_MELODY_NAME_LID,
#endif

#ifdef __MMI_TODOLIST__
    NVRAM_EF_TODO_LIST_LID,
#endif

#ifndef __MMI_THEMES_V2_SUPPORT__     
    NVRAM_EF_THEMES_VALUES,
#endif    
#if defined(__PHB_CALLER_IMAGE_SAVE_PATH_ONLY__)	
	NVRAM_EF_PHB_PIC_LID,
#endif	   

#if defined(CSD_NO_SLIM_NVRAM)	
    NVRAM_EF_CALORIE_DATA_LID,
    NVRAM_EF_DOWNLOAD_IMAGE_LID,
    NVRAM_EF_COMPOSE_RINGTONE_LID,
    NVRAM_EF_DOWNLOAD_TONE_LID,
    NVRAM_EF_DOWNLOAD_MELODY_LID,
    NVRAM_EF_ROOT_CA_LID,
    NVRAM_EF_IMEI_IMEISV_LID,
    NVRAM_EF_CLASSMARK_RACAP_LID,
    NVRAM_EF_ADC_LID,
    NVRAM_EF_UEM_MANUFACTURE_DATA_LID,
    NVRAM_EF_UEM_RMI_DATA_LID,
    NVRAM_EF_SMSAL_MWIS_LID,
    NVRAM_EF_SMSAL_SMS_LID,
    NVRAM_EF_TCM_PDP_PROFILE_LID,
    NVRAM_EF_PORT_SETTING_LID,
    NVRAM_PICTURE_EDITOR_LID,
    NVRAM_EF_MSG_CLUB_LID,
    NVRAM_EF_IMPS_LID,
    NVRAM_EF_PHB_LN_TYPE_SEQ_LID,
    NVRAM_EF_EONS_INFO_LID,
#endif

    NVRAM_EF_LINESWITCH_LID,//man for lineswitch
    NVRAM_EF_LINEFORWARD_LID,//man for forward icon
    NVRAM_EF_PHB_BLACK_AND_RED_LIST,//chenhe for black and red list
    NVRAM_EF_BAND_SELECT_AUTO,
#ifdef __MMI_MULTI_SIM__
    NVRAM_EF_CARD2_BAND_SELECT_AUTO,
    NVRAM_EF_CARD3_BAND_SELECT_AUTO,
    NVRAM_EF_CARD4_BAND_SELECT_AUTO,
#endif
    NVRAM_EF_CALIBRATION_SET,
    NVRAM_EF_RDA_SETTING_LID,//licheng for rda bt
#ifdef __MMI_A2DP_SUPPORT__
    NVRAM_EF_AUDIO_PLAYER_BT_SETTINGS_LID,
#endif

#ifdef __MMI_VIP_FUNCTION__
	NVRAM_EF_VIP_FUNCTION_LID,
#endif

#if defined(__MMI_MESSAGES_BLACK_LIST__)
	NVRAM_EF_MESSAGES_BLACK_LIST_LID,
#endif
#if defined(__MMI_SAVE_CURRENT_TIME__)
	NVRAM_EF_SAVE_CURRENT_TIME_LID,
#endif
	
/*Don't remove this line: insert LID definition above*/
   /* DO NOT MODIFY THIS. */
   NVRAM_EF_LAST_LID_CUST
} nvram_LID_cust_enum;


 
 
#define NVRAM_EF_CUSTPACK_BASE 200
typedef enum{
    NVRAM_EF_SETTING_LID = NVRAM_EF_CUSTPACK_BASE,
    NVRAM_EF_CACHE_BYTE_LID,
    NVRAM_EF_CACHE_SHORT_LID,
    NVRAM_EF_CACHE_DOUBLE_LID,
    NVRAM_EF_PHONEBOOK_SOS_LID,
    NVRAM_EF_PHONEBOOK_SPEEDDIAL_LID,
    NVRAM_EF_CHIS_NUM_LID,
    NVRAM_EF_UNREAD_MISSED_NUM_LID,
#ifdef __MMI_MULTI_SIM__
    NVRAM_EF_PHONEBOOK_SIM2_SOS_LID,
    NVRAM_EF_PHONEBOOK_SIM3_SOS_LID,
    NVRAM_EF_PHONEBOOK_SIM4_SOS_LID,
#endif
#if defined(CSD_NO_SLIM_NVRAM)	 
    NVRAM_EF_CUSTPACK_VERNO_LID,
    NVRAM_EF_SMSAL_MAILBOX_ADDR_LID,
    NVRAM_EF_MS_SECURITY_LID,
    NVRAM_EF_ALS_LINE_ID_LID,
    NVRAM_EF_MSCAP_LID,
    NVRAM_EF_RAC_PREFERENCE_LID,
    NVRAM_EF_SMSAL_COMMON_PARAM_LID,
    NVRAM_EF_CB_DEFAULT_CH_LID,
#endif
    NVRAM_EF_LAST_LID_CUSTPACK
}NVRAM_LID_CUSTPACK_ENUM;








 
typedef struct{
	kal_uint8 const* version;
	kal_uint8 const*
	custpack_default[NVRAM_EF_LAST_LID_CUSTPACK-NVRAM_EF_CUSTPACK_BASE-1];
}custpack_nvram_header;

extern const custpack_nvram_header custpack_nvram_ptr;
//NVRAM for Notepad Application
#ifdef __MMI_NOTEPAD__

#define NVRAM_NOTEPAD_LIST_SIZE			220
#define NVRAM_NOTEPAD_LIST_TOTAL			1
#define NVRAM_NOTEPAD_RECORD_SIZE			500
#define NVRAM_NOTEPAD_RECORD_TOTAL			10
#endif



/*
 * Schedule FM Radio Settings  :jiashuo add for fm schedule record
 */
#define NVRAM_EF_FMSR_SETTING_SIZE		300
#define NVRAM_EF_FMSR_SETTING_TOTAL		4

#ifdef __MMI_VIP_FUNCTION__
#define MAX_NUMBER_VIP  10
#define MIN_VIP_SETTING_PASSWD_LEN 6
#define MAX_VIP_SETTING_PASSWD_LEN 8
#ifndef MAX_PB_NUMBER_LENGTH
#define MAX_PB_NUMBER_LENGTH 40
#endif

typedef struct
{
	BOOL status;
	U8 VIPNumber[MAX_NUMBER_VIP][(MAX_PB_NUMBER_LENGTH+1)*ENCODING_LENGTH];
	U8 Password[(MAX_VIP_SETTING_PASSWD_LEN+1) * ENCODING_LENGTH];
}vip_nvram_data_struct;

#define NVRAM_EF_VIP_FUNCTION_SIZE sizeof(vip_nvram_data_struct)
#define NVRAM_EF_VIP_FUNCTION_TOTAL 1
#endif

#define MAX_MESSAGES_BLACK_LIST_NUMBER	5
#define MAX_MESSAGES_BLACK_LIST_NUMBER_LEN	20

#endif /* #ifdef MMI_ON_WIN32 */
 

#define __MMI_SECTION__
#include "custom_mmi_default_value.h"

#undef __MMI_SECTION__
//Cache enums moved to custom_mmi_default_value.h
#endif 

