/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * SoundRecorderDef.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   This file is for sound recorder.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/
#ifndef SOUND_RECORDER_DEF_H
#define SOUND_RECORDER_DEF_H


#include "gui_data_types.h"


typedef enum {
	STR_ID_SNDREC_START_STRING_BASE=SOUND_RECORDER_BASE+1,
   STR_ID_SNDREC_MAIN,

   STR_ID_SNDREC_OPTION,
   STR_ID_SNDREC_RECORD,
   STR_ID_SNDREC_PLAY,
   STR_ID_SNDREC_APPEND,
   STR_ID_SNDREC_RENAME,
   STR_ID_SNDREC_DELETE,
   STR_ID_SNDREC_DELETE_ALL,
   STR_ID_SNDREC_DELETE_ALL_PHONE,
   STR_ID_SNDREC_DELETE_ALL_CARD,
   STR_ID_SNDREC_SETTINGS,
   STR_ID_SNDREC_ADD_TO_RING,

   STR_ID_SNDREC_RENAME_OPTION,
   STR_ID_SNDREC_OPTION_SAVE,
   STR_ID_SNDREC_OPTION_INPUT_METHOD,
   
   STR_ID_SNDREC_SETTINGS_STORAGE,
   STR_ID_SNDREC_SETTINGS_PHONE,
   STR_ID_SNDREC_SETTINGS_CARD,

   STR_ID_SNDREC_SETTINGS_FORMAT,
   STR_ID_SNDREC_SETTINGS_AMR,
   STR_ID_SNDREC_SETTINGS_WAV,
   STR_ID_SNDREC_SETTINGS_AMRWB,
   STR_ID_SNDREC_SETTINGS_VM,
   

   STR_ID_SNDREC_PAUSE,
   STR_ID_SNDREC_RESUME,
   STR_ID_SNDREC_STOP,

   STR_ID_SNDREC_QUERY_SAVE,
   STR_ID_SNDREC_QUERY_DELETE,
   STR_ID_SNDREC_QUERY_DELETE_ALL,
   STR_ID_SNDREC_QUERY_ABORT,

   STR_ID_SNDREC_LIST_EMPTY,
   STR_ID_SNDREC_LIST_FULL,
   STR_ID_SNDREC_OPEN_FILE_ERROR,
   STR_ID_SNDREC_LIST_ERROR,
   STR_ID_SNDREC_NO_CARD,
   STR_ID_SNDREC_COMMAND_ERROR,
   STR_ID_SNDREC_DEVICE_BUSY,
   STR_ID_SNDREC_WRITE_PROTECTION_ERROR,

   STR_ID_SNDREC_ERROR,
   STR_ID_SNDREC_WARNING,
   STR_ID_SNDREC_SUCCESS,
   STR_ID_SNDREC_DISC_FULL,
   STR_ID_SNDREC_NO_RECORD,
   STR_ID_SNDREC_RECORDING,
   STR_ID_SNDREC_PAUSED,
   STR_ID_SNDREC_PLAYING,
   STR_ID_SNDREC_AVAILABLE,
   
   STR_ID_SNDREC_BAD_FORMAT,
   STR_ID_SNDREC_INVALID_FORMAT,
   
   STR_ID_SNDREC_EMPTY_FILENAME,
   STR_ID_SNDREC_SETTINGS_MP3,

#ifdef __MMI_SOUND_RECORDER_STYLE_X__
   STR_ID_SNDREC_NEW_RECORD,
   STR_ID_SNDREC_LIST,
#endif
   STR_ID_SNDREC_WAV_NOT_ON_FLASH,
   /*+ zhouqin modify for dual t-flash card 20110503*/
    #if defined(DUAL_TFLASH_SUPPORT)
    STR_ID_SNDREC_SETTINGS_SEC_CARD,
    #endif
    /*- zhouqin modify for dual t-flash card 20110503*/
   NO_OF_STR_ID_SNDREC
   
}sndrec_str_ids_enum;

typedef enum {
	IMG_ID_SNDREC_START_IMAGE_BASE=SOUND_RECORDER_BASE+1,
   IMG_ID_SNDREC_MAIN,


   IMG_ID_SNDREC_OPTION,
   IMG_ID_SNDREC_RECORD,
   IMG_ID_SNDREC_PLAY,
   IMG_ID_SNDREC_APPEND,
   IMG_ID_SNDREC_RENAME,
   IMG_ID_SNDREC_DELETE,
   IMG_ID_SNDREC_DELETE_ALL,
   IMG_ID_SNDREC_DELETE_ALL_PHONE,
   IMG_ID_SNDREC_DELETE_ALL_CARD,
   IMG_ID_SNDREC_SETTINGS,
   IMG_ID_SNDREC_ADD_TO_RING,

   IMG_ID_SNDREC_RENAME_OPTION,
   IMG_ID_SNDREC_OPTION_SAVE,
   IMG_ID_SNDREC_OPTION_INPUT_METHOD,

   IMG_ID_SNDREC_SETTINGS_STORAGE,
   IMG_ID_SNDREC_SETTINGS_FORMAT,
   IMG_ID_SNDREC_SETTINGS_PHONE,
   IMG_ID_SNDREC_SETTINGS_CARD,
   IMG_ID_SNDREC_SETTINGS_AMR,
   IMG_ID_SNDREC_SETTINGS_WAV,

   IMG_ID_SNDREC_RECORDING,
   IMG_ID_SNDREC_RECORDING_PAUSED,
   IMG_ID_SNDREC_PLAYING,
   IMG_ID_SNDREC_PLAYING_PAUSED,

#ifdef __MMI_SOUND_RECORDER_STYLE_X__
   IMG_ID_SNDREC_NEW_RECORD,
   IMG_ID_SNDREC_LIST,
#endif
   NO_OF_IMG_ID_SNDREC

}sndrec_img_ids_enum;

typedef enum {
	SCR_ID_SNDREC_START_BASE=SOUND_RECORDER_BASE+1,
   SCR_ID_SNDREC_MAIN,

   SCR_ID_SNDREC_OPTION,
   SCR_ID_SNDREC_RECORD,
   SCR_ID_SNDREC_RECORD_PAUSED,
   SCR_ID_SNDREC_PLAY,
   SCR_ID_SNDREC_PLAY_PAUSED,
   SCR_ID_SNDREC_APPEND,
   SCR_ID_SNDREC_RENAME,
   SCR_ID_SNDREC_SETTINGS,

   SCR_ID_SNDREC_RENAME_OPTION,
   
   SCR_ID_SNDREC_SETTINGS_SAVE_QUERY,

   NO_OF_SCR_ID_SNDREC

}sndrec_scr_ids_enum;

//#define MAX_FILE_NAME_LEN 128
#define MAX_FILE_NAME_LEN ( (255+1)*2 )
//#define MAX_PATH_LEN 128
#define MAX_PATH_LEN 16 // because its path is fixed. i.e "c:\audio\"
#define MAX_FULL_NAME_LEN ( (260+1)*2 )
#define NO_OF_LIST_ENTRIES 60

#define MAX_INPUT_FILE_LEN  35  
#define MAX_FILE_EXT_LEN 5   


#define MAX_STORAGE_PATH_LEN  20
#define STORAGE_PATH_PHONE (L"Audio")
#define STORAGE_PATH_CARD (L"Audio")

#define FILE_EXT_AMR (".amr")
#define FILE_EXT_WAV (".wav")
#define FILE_EXT_AWB (".awb")
#define FILE_EXT_VM (".vm")
#define FILE_EXT_MP3 (".mp3")	// add for jasperII      chenxia  20071121

#define SNDREC_FILE_FILTER  FMGR_TYPE_WAV|FMGR_TYPE_AMR|FMGR_TYPE_VM

#ifndef MAX_VOL_LEVEL
#define MAX_VOL_LEVEL 7
#endif


#define RANDOM_POS   (8)

#endif /* SOUND_RECORDER_DEF_H */


