/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/**************************************************************

	FILENAME	: Res_PhoneBook.c

  	PURPOSE		: Populate Resource for

 

 

	DATE		: August-11-2003

**************************************************************/
#include "stdc.h"
#include "customcfg.h"

#ifdef FIRST_PASS
#include "buildcfg.h"
#endif
#include "mmi_features.h"
#include "phonebookdef.h"

//[221] Added by Ryh 2009/02/12								[BEGIN]
#ifdef __MMI_MULTI_SIM__
#include "mtpnp_ad_resdef.h"
#endif
//[221] Added by Ryh 2009/02/12								[END]

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"

typedef enum
{
	MMI_PHB_SETTING_BASE = 1, /* Memory Status and Fields */
#if defined(__MMI_VCARD__)
	MMI_PHB_SETTING_VCARD,
#endif
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	MMI_PHB_SETTING_SPEAK_NAME,
#endif
	MMI_PHB_SETTING_PREFER_STORAGE,
	MMI_PHB_SETTING_NO_SIM_ENUM_TOTAL = MMI_PHB_SETTING_PREFER_STORAGE,
#if defined(__MMI_PHB_NAME_LIST_FILTER__)
    MMI_PHB_SETTING_NAME_LIST_FILTER,
#endif
	MMI_PHB_SETTING_ENUM_TOTAL
}mmi_phb_setting_num_enum;

//////////////////////////////////////////////////////////////////////////////////
void PopulatePhoneBookMenu(void)
{
	U8 i;
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_VIEW_OPTIONS,0, 
				MMI_PHB_OPTION_MENU_ENUM_TOTAL
				#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)
				+ MMI_SIM_NUMBER -1
				#endif
				,
				#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)	
				MULTI_MENU(MENU_ID_PHB_OPTION_IP_DIAL),
				#endif
				MENU_ID_PHB_OPTION_DIAL,
				MENU_ID_PHB_OPTION_SEND_SMS,
		#if defined(__MMI_PHB_SEND_MMS_FROM_PHB__)
				MENU_ID_PHB_OPTION_SEND_MMS,
		#endif
				MITEM1010_PBOOK_VIEW,
			//	MITEM102_PBOOK_NEW_ENTRY,
				MITEM1011_PBOOK_EDIT,
				MITEM1012_PBOOK_DELETE,
				MITEM1013_PBOOK_COPY_ENTRY,
				MITEM1014_PBOOK_MOVE,
				#ifdef __MMI_VCARD__
				MENU_ID_PHB_VCARD_SEND_ENTRY,
				#endif
				SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_VIEW_OPTIONS_NO_SIM,0, 3,
				MITEM1010_PBOOK_VIEW,
				MITEM1011_PBOOK_EDIT,
				MITEM1012_PBOOK_DELETE,
				SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)	
		ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_IP_DIAL+i, MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT,DISP_LIST,
			#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
				STR_ID_PHB_OPTION_IP_DIAL1 + i,
			#else
				STR_ID_PHB_OPTION_IP_DIAL,
			#endif
				IMG_ID_PHB_NO_IMAGE));
		#endif
	}

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_DIAL,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DIAL,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_SEND_SMS,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_SEND_SMS,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MITEM1010_PBOOK_VIEW,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1010,IMG_MITEM1010));
	ADD_APPLICATION_MENUITEM((MITEM1011_PBOOK_EDIT,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_EDIT,IMG_MITEM1011));
	ADD_APPLICATION_MENUITEM((MITEM1012_PBOOK_DELETE,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_MITEM1012));
	ADD_APPLICATION_MENUITEM((MITEM1013_PBOOK_COPY_ENTRY,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1013,IMG_MITEM1013));
	ADD_APPLICATION_MENUITEM((MITEM1014_PBOOK_MOVE,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1014,IMG_MITEM1014));
	ADD_APPLICATION_MENUITEM((MITEM1015_PBOOK_DUPLICATE,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1015,IMG_MITEM1015));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_MYCARD,MITEM110_PBOOK_SETTINGS,1,
				MENU_ID_PHB_VCARD_EDIT_MYCARD,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_MYCARD_NO_SIM,MITEM110_PBOOK_SETTINGS,1,
				MENU_ID_PHB_VCARD_EDIT_MYCARD,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_EDIT_MYCARD,MENU_ID_PHB_VCARD_MYCARD,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_EDIT_MYCARD, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_SEND_MYCARD,MENU_ID_PHB_VCARD_MYCARD,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_SEND_MYCARD,IMG_ID_PHB_NO_IMAGE));
	#ifdef __MMI_VCARD__
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_SEND_ENTRY,MITEM101_PBOOK_VIEW_OPTIONS,0,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD_SEND_ENTRY, IMG_ID_PHB_NO_IMAGE));
	#endif

	ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY,MAIN_MENU_PHONEBOOK_MENUID,
				1 + MMI_SIM_NUMBER,
				MULTI_MENU(MITEM_ADD_ENTRY_TO_SIM),
				MITEM_ADD_ENTRY_TO_PHONE,
				SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));

#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_SIM+i, MITEM102_PBOOK_NEW_ENTRY,0,
					SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_LOCATION_SIM1 + i,IMG_STORAGE_SIM_1));
	}
#else
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_SIM,MITEM102_PBOOK_NEW_ENTRY,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_LOCATION_SIM,IMG_STORAGE_SIM));
#endif
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_PHONE,MITEM102_PBOOK_NEW_ENTRY,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_LOCATION_PHONE,IMG_STORAGE_HANDSET));
	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL,MAIN_MENU_PHONEBOOK_MENUID,
				2+MMI_SIM_NUMBER,
				MULTI_MENU(MITEM_PBOOK_DELETE_ALL_SIM),
				MITEM_PBOOK_DELETE_ALL_PHONE,
				MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));

#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_SIM + i,MITEM103_PBOOK_DELETE_ALL,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_DELETE_ALL_SIM1 + i,IMG_STORAGE_SIM));
	}
#else
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_SIM,MITEM103_PBOOK_DELETE_ALL,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_DELETE_ALL_SIM,IMG_STORAGE_SIM));
#endif

	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_PHONE,MITEM103_PBOOK_DELETE_ALL,0,
				SHOW, NONMOVEABLE, DISP_LIST, STR_DELETE_ALL_PHONE, IMG_STORAGE_HANDSET));

#ifdef __MMI_MULTI_SIM__
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL,MAIN_MENU_PHONEBOOK_MENUID,6,
				MENU_ID_PHB_COPY_ALL_SIM1_TO_PHONE,
				MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM1,
				MENU_ID_PHB_COPY_ALL_SIM2_TO_PHONE,
				MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM2,
				MENU_ID_PHB_COPY_ALL_SIM1_TO_SIM2,
				MENU_ID_PHB_COPY_ALL_SIM2_TO_SIM1,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL_NO_SIM1,MAIN_MENU_PHONEBOOK_MENUID,2,
				MENU_ID_PHB_COPY_ALL_SIM2_TO_PHONE,
				MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM2,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL_NO_SIM2,MAIN_MENU_PHONEBOOK_MENUID,2,
				MENU_ID_PHB_COPY_ALL_SIM1_TO_PHONE,
				MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM1,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));	
#else	
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL,MAIN_MENU_PHONEBOOK_MENUID,2,
				MITEM_PBOOK_COPY_ALL_SIM,
				MITEM_PBOOK_COPY_ALL_PHONE,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));
#endif
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_COPY_ALL_SIM,MITEM104_PBOOK_COPY_ALL,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_COPY_ALL_SIM,IMG_STORAGE_SIM));
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_COPY_ALL_PHONE,MITEM104_PBOOK_COPY_ALL,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_COPY_ALL_PHONE,IMG_STORAGE_HANDSET));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXTRA_NUMBER,MAIN_MENU_PHONEBOOK_MENUID,
				#if !defined( __MMI_MAINLCD_128X160__)
				3*MMI_SIM_NUMBER
				#else
				2*MMI_SIM_NUMBER
				#endif
				,
			#if!defined( __MMI_MAINLCD_128X160__)
				MULTI_MENU(MITEM105_PBOOK_OWNER_NUMBER),
			#endif
				MULTI_MENU(MENU_PHONEBOOK_SERVICENUMBER),
				MULTI_MENU(MITEM116_PBOOK_SOS_NUMBER),
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EXTRA_NUMBER,IMG_PHB_OWNER_NUMBER));

#ifdef __MMI_MULTI_SIM__
	#ifdef __MMI_DUAL_SIM_SINGLE_OPENED_
	#if !defined( __MMI_MAINLCD_128X160__)
	ADD_APPLICATION_MENUITEM((MITEM105_PBOOK_OWNER_NUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
				SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM105,IMG_PHB_OWNER_NUMBER));
	#endif
	ADD_APPLICATION_MENUITEM((MENU_PHONEBOOK_SERVICENUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
				SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_SDL_MAIN_MENU,IMG_PHB_OWNER_NUMBER));
	ADD_APPLICATION_MENUITEM((MITEM116_PBOOK_SOS_NUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
				SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_SOS_MENU_ITEM,IMG_PHB_OWNER_NUMBER));

	#else/* __MMI_DUAL_SIM_SINGLE_OPENED_*/
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		#if !defined( __MMI_MAINLCD_128X160__)
		ADD_APPLICATION_MENUITEM((MITEM105_PBOOK_OWNER_NUMBER + i, MENU_ID_PHB_EXTRA_NUMBER,0,
					SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STRING_MTPNP_SIM1_OWNER_NUMBER + i,IMG_PHB_OWNER_NUMBER));
		#endif
		ADD_APPLICATION_MENUITEM((MENU_PHONEBOOK_SERVICENUMBER + i, MENU_ID_PHB_EXTRA_NUMBER,0,
					SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STRING_MTPNP_SIM1_SDL_NUMBER + i,IMG_PHB_OWNER_NUMBER));
		ADD_APPLICATION_MENUITEM((MITEM116_PBOOK_SOS_NUMBER + i,MENU_ID_PHB_EXTRA_NUMBER,0,
					SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STRING_MTPNP_SIM1_SOS_NUMBER + i,IMG_PHB_OWNER_NUMBER));
	}
	#endif /* __MMI_DUAL_SIM_SINGLE_OPENED_ */
#else
	ADD_APPLICATION_MENUITEM((MITEM105_PBOOK_OWNER_NUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
				SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM105,IMG_PHB_OWNER_NUMBER));
	ADD_APPLICATION_MENUITEM((MENU_PHONEBOOK_SERVICENUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
				SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_SDL_MAIN_MENU,IMG_PHB_OWNER_NUMBER));
	ADD_APPLICATION_MENUITEM((MITEM116_PBOOK_SOS_NUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
				SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_SOS_MENU_ITEM,IMG_PHB_OWNER_NUMBER));
#endif
	ADD_APPLICATION_MENUITEM((MITEM110_PBOOK_SETTINGS,MAIN_MENU_PHONEBOOK_MENUID, 2,
				MITEM1101_PBOOK_MEMORY_STATUS,
				MITEM1102_PBOOK_STORAGE_LOCATION,
				SHOW, INSERTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM110,IMG_PHB_SETTINGS));
	ADD_APPLICATION_MENUITEM((MITEM110_PBOOK_SETTINGS_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID, 1,
				MITEM1101_PBOOK_MEMORY_STATUS,
				SHOW, INSERTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM110,IMG_PHB_SETTINGS));
	ADD_APPLICATION_MENUITEM((MITEM1101_PBOOK_MEMORY_STATUS, MITEM110_PBOOK_SETTINGS,0,
				SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_MITEM1101,IMG_MITEM1101));
	ADD_APPLICATION_MENUITEM((MITEM1102_PBOOK_STORAGE_LOCATION,MITEM110_PBOOK_SETTINGS,
				MMI_SIM_NUMBER + 1,
				MULTI_MENU(MITEM_STORAGE_LOCATION_SIM),
				MITEM_STORAGE_LOCATION_PHONE,
				SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_MITEM1102,IMG_MITEM1102));
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
	#if defined( __MMI_MULTI_SIM__) && !defined(__MMI_DUAL_SIM_SINGLE_OPENED_)
		ADD_APPLICATION_MENUITEM((MITEM_STORAGE_LOCATION_SIM + i,MITEM1102_PBOOK_STORAGE_LOCATION,0,
					SHOW, NONMOVEABLE, DISP_LIST,STRING_MTPNP_SIM1 + i,IMG_STORAGE_SIM));
	#else
		ADD_APPLICATION_MENUITEM((MITEM_STORAGE_LOCATION_SIM,MITEM1102_PBOOK_STORAGE_LOCATION,0,
					SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_SIM,IMG_STORAGE_SIM));
	#endif
	}

	ADD_APPLICATION_MENUITEM((MITEM_STORAGE_LOCATION_PHONE,MITEM1102_PBOOK_STORAGE_LOCATION,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_PHONE,IMG_STORAGE_HANDSET));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO,MAIN_MENU_PHONEBOOK_MENUID,0,
				SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO, IMG_ID_PHB_CALLER_VIDEO_1));
#ifdef __MMI_VCARD__
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_EXPORT,MAIN_MENU_PHONEBOOK_MENUID,
				MMI_SIM_NUMBER + 1,
				MULTI_MENU(MENU_ID_PHB_EXPORT_FROM_SIM1),
				MENU_ID_PHB_EXPORT_FROM_PHONE,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EXPORT, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXPORT_FROM_PHONE,MENU_ID_PHB_VCARD_EXPORT,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_EXPORT_FROM_PHONE,IMG_STORAGE_HANDSET));

#ifdef __MMI_MULTI_SIM__
	#ifdef __MMI_DUAL_SIM_SINGLE_OPENED_
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXPORT_FROM_SIM1,MENU_ID_PHB_VCARD_EXPORT,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_EXPORT_FROM_SIM,IMG_STORAGE_HANDSET));
	#else
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXPORT_FROM_SIM1 + i, MENU_ID_PHB_VCARD_EXPORT,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_EXPORT_FROM_SIM1 + i,IMG_STORAGE_HANDSET));
	}
	#endif /* __MMI_DUAL_SIM_SINGLE_OPENED_ */
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXPORT_FROM_SIM1,MENU_ID_PHB_VCARD_EXPORT,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_EXPORT_FROM_SIM,IMG_STORAGE_HANDSET));
#endif

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_IMPORT,MAIN_MENU_PHONEBOOK_MENUID,
				2,
				MENU_ID_PHB_IMPORT_FROM_VCF,
				MENU_ID_PHB_IMPORT_FROM_OUTLOOK,
				SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_IMPORT, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMPORT_FROM_VCF, MENU_ID_PHB_VCARD_IMPORT,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_IMPORT_FROM_VCF,IMG_STORAGE_HANDSET));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMPORT_FROM_OUTLOOK, MENU_ID_PHB_VCARD_IMPORT,0,
				SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_IMPORT_FROM_OUTLOOK,IMG_STORAGE_HANDSET));

#endif

#if defined(__MMI_INCOMING_CALL_VIDEO__)
	/*Option for video in file*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_OPTION,0,3,
		MENU_ID_PHB_VIDEO_FILE_VIEW,
		MENU_ID_PHB_VIDEO_FILE_SELECT,
		MENU_ID_PHB_VIDEO_FILE_DELETE,
//		MENU_ID_PHB_VIDEO_FILE_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_VIDEO, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_VIEW,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_VIDEO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_SELECT,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_DELETE,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_SETTING,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VIDEO_AUDIO_ONOFF, 0));
#endif

#ifdef __MMI_MULTI_SIM__
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM1_COPY_CHOOSE,0,2,
		MENU_ID_PHB_COPY_SIM1_TO_SIM2,
		MENU_ID_PHB_COPY_SIM1_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM1_COPY_CHOOSE_NO_SIM2,0,1,
		MENU_ID_PHB_COPY_SIM1_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_SIM1_TO_SIM2,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM1_TO_SIM2, 0));
	#ifdef __MMI_DUAL_SIM_SINGLE_OPENED_
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_SIM1_TO_PHONE,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM104,0));	
	#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_SIM1_TO_PHONE,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM1_TO_PHONE,0));	
	#endif /* __MMI_DUAL_SIM_SINGLE_OPENED_ */

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM2_COPY_CHOOSE,0,2,
		MENU_ID_PHB_COPY_SIM2_TO_SIM1,
		MENU_ID_PHB_COPY_SIM2_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM2_COPY_CHOOSE_NO_SIM1,0,1,
		MENU_ID_PHB_COPY_SIM2_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_SIM2_TO_SIM1,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM2_TO_SIM1, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_SIM2_TO_PHONE,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM2_TO_PHONE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_PHONE_COPY_CHOOSE,0,2,
		MENU_ID_PHB_COPY_PHONE_TO_SIM1,
		MENU_ID_PHB_COPY_PHONE_TO_SIM2,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_PHONE_TO_SIM1,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_PHONE_TO_SIM1, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_PHONE_TO_SIM2,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_PHONE_TO_SIM2,0));		
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_PHONE_TO_SIM1_NOSIM2,0,1,
		MENU_ID_PHB_COPY_PHONE_TO_SIM1,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_PHONE_TO_SIM2_NOSIM1,0,1,
		MENU_ID_PHB_COPY_PHONE_TO_SIM2,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015, IMG_ID_PHB_NO_IMAGE));	
	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM1_MOVE_CHOOSE,0,2,
		MENU_ID_PHB_MOVE_SIM1_TO_SIM2,
		MENU_ID_PHB_MOVE_SIM1_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM1_MOVE_CHOOSE_NO_SIM2,0,1,
		MENU_ID_PHB_MOVE_SIM1_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_SIM1_TO_SIM2,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MOVE_FROM_SIM1_TO_SIM2, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_SIM1_TO_PHONE,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MOVE_FROM_SIM1_TO_PHONE,0));	

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM2_MOVE_CHOOSE,0,2,
		MENU_ID_PHB_MOVE_SIM2_TO_SIM1,
		MENU_ID_PHB_MOVE_SIM2_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SIM2_MOVE_CHOOSE_NO_SIM1,0,1,
		MENU_ID_PHB_MOVE_SIM2_TO_PHONE,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));		
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_SIM2_TO_SIM1,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MOVE_FROM_SIM2_TO_SIM1, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_SIM2_TO_PHONE,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MOVE_FROM_SIM2_TO_PHONE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_PHONE_MOVE_CHOOSE,0,2,
		MENU_ID_PHB_MOVE_PHONE_TO_SIM1,
		MENU_ID_PHB_MOVE_PHONE_TO_SIM2,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_PHONE_TO_SIM1,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MOVE_FROM_PHONE_TO_SIM1, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_PHONE_TO_SIM2,MENU_ID_PHB_DAIL_CHOOSE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MOVE_FROM_PHONE_TO_SIM2,0));	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_PHONE_TO_SIM1_NOSIM2,0,1,
		MENU_ID_PHB_MOVE_PHONE_TO_SIM1,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MOVE_PHONE_TO_SIM2_NOSIM1,0,1,
		MENU_ID_PHB_MOVE_PHONE_TO_SIM2,	
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1014, IMG_ID_PHB_NO_IMAGE));	
	

#ifdef __MMI_DUAL_SIM_SINGLE_OPENED_
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_SIM1_TO_PHONE,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_COPY_ALL_SIM, 0));
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_SIM1_TO_PHONE,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM1_TO_PHONE, 0));
#endif /* __MMI_DUAL_SIM_SINGLE_OPENED_ */

#ifdef __MMI_DUAL_SIM_SINGLE_OPENED_
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM1,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_COPY_ALL_PHONE, 0));
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM1,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_PHONE_TO_SIM1, 0));
#endif /* __MMI_DUAL_SIM_SINGLE_OPENED_ */
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_SIM2_TO_PHONE,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM2_TO_PHONE, 0));	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_PHONE_TO_SIM2,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_PHONE_TO_SIM2, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_SIM1_TO_SIM2,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM1_TO_SIM2, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_COPY_ALL_SIM2_TO_SIM1,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_COPY_FROM_SIM2_TO_SIM1, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_MTPNP_SELECT_SIM_MENU,0,MMI_SIM_NUMBER,
				MULTI_MENU(MENU_ID_MTPNP_SELECT_SIM_SIM1),
				SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS, IMG_ID_PHB_NO_IMAGE));
	for(i = 0; i < MMI_SIM_NUMBER; i++)
	{
		ADD_APPLICATION_MENUITEM((MENU_ID_MTPNP_SELECT_SIM_SIM1 + i,MENU_ID_MTPNP_SELECT_SIM_MENU,0,
					SHOW, NONMOVEABLE, DISP_LIST,STRING_MTPNP_SIM1 + i, IMG_GLOBAL_L1 + i));
	}

#endif

}

/**************************************************************

	FUNCTION NAME		: PopulatePbResData()

  	PURPOSE				: Populate phone book resource data

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

 

**************************************************************/
void PopulatePbResData()
{
	PRINT_INFORMATION(("File: [%s]  Line: [%d] <<PopulatePbResData.>\n",__FILE__,__LINE__));
	PopulatePhoneBookMenu();
	/*Quick Seach*/
#if defined(__MMI_PHB_QUICK_SEARCH__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_QUICK_SEARCH,IMG_ID_PHB_QUICK_SEARCH));

#if defined(__MMI_MULTITAP_FOR_STAR_AND_POUND__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH_OPTION,0,2,
		MENU_ID_PHB_QUICK_SEARCH_INPUT_METHOD,
		MENU_ID_PHB_QUICK_SEARCH_OP_OPTION,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH_INPUT_METHOD,MENU_ID_PHB_QUICK_SEARCH_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_INPUT_METHOD,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH_OP_OPTION,MENU_ID_PHB_QUICK_SEARCH_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION,0));
		
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SMS_QUICK_SEARCH_OPTION,0,2,
		MENU_ID_PHB_SMS_QUICK_SEARCH_DONE,
		MENU_ID_PHB_SMS_QUICK_SEARCH_INPUT_METHOD,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SMS_QUICK_SEARCH_DONE,MENU_ID_PHB_SMS_QUICK_SEARCH_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DONE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SMS_QUICK_SEARCH_INPUT_METHOD,MENU_ID_PHB_SMS_QUICK_SEARCH_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_INPUT_METHOD,0));
#endif

#endif

	/*Search*/
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_SEARCH_ENTRY,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM101,IMG_PHB_SEARCH_ENTRY));

	ADD_APPLICATION_MENUITEM((MITEM101_SEARCH_OPTIONS,0,2,
		MITEM1010_SEARCH,
		MITEM1011_INPUT_MEHTHOD,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MITEM1010_SEARCH,MITEM101_SEARCH_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1010_SEARCH,IMG_MITEM1010_SEARCH));
	ADD_APPLICATION_MENUITEM((MITEM1011_INPUT_MEHTHOD,MITEM101_SEARCH_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_INPUT_METHOD,IMG_MITEM1011_INPUT_METHOD));

	/*Add New Entry*/
#ifdef __DOUBLE_PHONE__
	ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY,MAIN_MENU_PHONEBOOK_MENUID,3,
		MITEM_ADD_ENTRY_TO_SIM,
		MITEM_ADD_ENTRY_TO_PHONE,
		MITEM_ADD_ENTRY_TO_SIM2,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_SIM2,MITEM102_PBOOK_NEW_ENTRY,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_TWIN_A_STORAGE_LOCATION_SIM2,IMG_STORAGE_SIM02));
#else
	ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY,MAIN_MENU_PHONEBOOK_MENUID,2,
		MITEM_ADD_ENTRY_TO_SIM,
		MITEM_ADD_ENTRY_TO_PHONE,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));
#endif
#if 0
        ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,1,
		MITEM_ADD_ENTRY_TO_PHONE,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));
#endif

#ifdef __UNI_TWIN_A_DUAL_ACTIVE__
        ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY_NO_SIM1_EXIST_SIM2,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,2,
		MITEM_ADD_ENTRY_TO_PHONE,
		MITEM_ADD_ENTRY_TO_SIM2,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));
#endif
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_SIM,MITEM102_PBOOK_NEW_ENTRY,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_LOCATION_SIM,IMG_STORAGE_SIM));

	/* Delete All Phonebook Entry*/
#ifdef __DOUBLE_PHONE__
	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL,MAIN_MENU_PHONEBOOK_MENUID,4,
		MITEM_PBOOK_DELETE_ALL_SIM,
		MITEM_PBOOK_DELETE_ALL_SIM2,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#else
	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL,MAIN_MENU_PHONEBOOK_MENUID,3,
		MITEM_PBOOK_DELETE_ALL_SIM,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#endif
#if 0

	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,2,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#endif
#ifdef __UNI_TWIN_A_DUAL_ACTIVE__
	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL_NO_SIM1_EXIST_SIM2,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,3,
	       MITEM_PBOOK_DELETE_ALL_SIM2,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#endif
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_SIM,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_DELETE_ALL_SIM,IMG_STORAGE_SIM));
#ifdef __DOUBLE_PHONE__
		ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_SIM2,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_TWIN_A_DELETE_ALL_SIM2,IMG_STORAGE_SIM02));
#endif
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_DELETE_ALL_ONE_BY_ONE,IMG_PHB_DELETE_ALL_ONE));

	/* Phonebook Entry Option for No SIM inserted mode */
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_VIEW_OPTIONS_NO_SIM,0, MMI_PHB_OPTION_NO_SIM_TOTAL,
		MITEM1010_PBOOK_VIEW,
		MITEM1011_PBOOK_EDIT,
#if defined(__MMI_PHB_INFO_FIELD__)
		MENU_ID_PHB_OPTION_EDIT_DETAIL,
#endif
#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
		MENU_ID_PHB_OPTION_EDIT_SERVICE_FIELD,
#endif
		MITEM1012_PBOOK_DELETE,
#if !defined(__MMI_PHB_COMBINE_COPY_DUPLICATE__)
		MITEM1015_PBOOK_DUPLICATE,
#endif
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_SEND_ENTRY,
#endif
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));

	ADD_APPLICATION_MENUITEM((MITEM1011_PBOOK_EDIT,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_EDIT,IMG_MITEM1011));
#if defined(__MMI_PHB_INFO_FIELD__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_EDIT_DETAIL,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EDIT_DETAIL,IMG_MITEM1011));
#endif
#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_EDIT_SERVICE_FIELD,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EDIT_SERVICE_FIELD, IMG_MITEM1011));
#endif

	/*IP Dial from phonebook entry option menu.*/
#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_IP_DIAL,	"IP Dial"	,"Menu item string for View options->IP Dial");
#endif
	/*Send SMS from phonebook entry option menu.*/
#if defined(__MMI_PHB_SEND_SMS_FROM_PHB__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_SEND_SMS	,"Send SMS"	,"Menu item string for View options->Send SMS");
#endif
#if defined(__MMI_PHB_SEND_MMS_FROM_PHB__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_SEND_MMS, MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_SEND_MMS,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_SEND_MMS	,"Send MMS"	,"Menu item string for Send Message of View options->Send MMS");
#endif

	/*Combine copy and duplicate into one option.*/
#if defined(__MMI_PHB_COMBINE_COPY_DUPLICATE__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_COPY_DUPLICATE,MITEM101_PBOOK_VIEW_OPTIONS,2,
		MITEM1013_PBOOK_COPY_ENTRY,
		MITEM1015_PBOOK_DUPLICATE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_COPY_DUPLICATE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MITEM1013_PBOOK_COPY_ENTRY,MENU_ID_PHB_OPTION_COPY_DUPLICATE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1013,IMG_MITEM1013));
	ADD_APPLICATION_MENUITEM((MITEM1015_PBOOK_DUPLICATE,MENU_ID_PHB_OPTION_COPY_DUPLICATE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015,IMG_MITEM1015));

	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_COPY_DUPLICATE,	"Copy"	,"Menu item string for View options->Copy Entry");
#endif

	/*vCard Menu*/
	/*vCard - SubMenu of PhoneBook Entry Options*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_SEND_ENTRY,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD_SEND_ENTRY, IMG_ID_PHB_NO_IMAGE));

	/*vCard - SubMenu of PhoneBook Setting*/
	#if 0
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_MYCARD,MITEM110_PBOOK_SETTINGS,2,
		MENU_ID_PHB_VCARD_EDIT_MYCARD,
		MENU_ID_PHB_VCARD_SEND_MYCARD,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD, IMG_ID_PHB_NO_IMAGE));
	#endif
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_SEND_MYCARD,MENU_ID_PHB_VCARD_MYCARD,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_SEND_MYCARD,IMG_ID_PHB_NO_IMAGE));

#if defined(__MMI_FILE_MANAGER__) && !defined(__MMI_FILE_MANAGER_HIDE_MENU__)
	/*Associate Image - Option Menu For Associate Image Handling*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION,0,3,
		MENU_ID_PHB_IMAGE_OPTION_VIEW,
		MENU_ID_PHB_IMAGE_OPTION_SELECT,
		MENU_ID_PHB_IMAGE_OPTION_DELETE,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION_VIEW,MENU_ID_PHB_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_VIEW_PICTURE_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION_SELECT,MENU_ID_PHB_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION_DELETE,MENU_ID_PHB_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, IMG_ID_PHB_NO_IMAGE));

	/*Save image to Phb from File Mgr*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_OPTION,0,3,
		MENU_ID_PHB_FMGR_SAVE_NEW,
		MENU_ID_PHB_FMGR_SAVE_LIST,
		MENU_ID_PHB_FMGR_SAVE_CALLGRP,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_NEW,MENU_ID_PHB_FMGR_SAVE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_TO_NEW_ENTRY, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_LIST,MENU_ID_PHB_FMGR_SAVE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_TO_SELECT_ENTRY,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_CALLGRP,MENU_ID_PHB_FMGR_SAVE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_TO_CALLER_GROUP, IMG_ID_PHB_NO_IMAGE));

	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_SELECT_FILE	,"Select From File"	,"Select Image From File Manager");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_DELETE_REF	,"Delete Reference"	,"Delete image reference from File Manager");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_NO_SELECT	,"No Image Selected"	,"Pop up string for No Image Select when view image");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_TO_NEW_ENTRY	,"To New Entry"	,"Forward image to a new entry");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_TO_SELECT_ENTRY	,"To Selected Entry"	,"Forward image to a selected entry");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_TO_CALLER_GROUP	,"To Caller Group"	,"Forward image to caller group");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_NOT_SUPPORT	,"Format not support"	,"Error Message for file mgr");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_INCORRECT_FILE	,"Incorrect File Content"	,"Error Message for file mgr");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_DISC_FULL,	"Free space is not enough for image."	,"Error Message for file mgre");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_SELECTED	,"Select From File"	,"Selected Image From File Manager");
#endif	/*END of #if defined(__MMI_FILE_MANAGER__)*/


	ADD_APPLICATION_STRING2(STR_SCR_PBOOK_CAPTION	,"Phone Book"	,"Title String for PhoneBook main screen");

	ADD_APPLICATION_STRING2(STR_MITEM101			,"Search Entry"	,"Menu item string for Search Entry");
	ADD_APPLICATION_STRING2(STR_MITEM102			,"Add New Entry","Menu item string for New Entry");
	//ADD_APPLICATION_STRING2(STR_MITEM103			,"Delete All"	,"Menu item string for Delete All entries");
	ADD_APPLICATION_STRING2(STR_MITEM1010			,"View"		,"Menu item string for View options->view");
	//ADD_APPLICATION_STRING2(STR_MITEM1011			,"Edit"		,"Menu item string for View options->Edit");
	//ADD_APPLICATION_STRING2(STR_MITEM1012			,"Delete"	,"Menu item string for View options->Delete");
	ADD_APPLICATION_STRING2(STR_MITEM1013			,"Copy"		,"Menu item string for View options->Copy Entry");
	ADD_APPLICATION_STRING2(STR_MITEM1014			,"Move"		,"Menu item string for View options->Move");
	ADD_APPLICATION_STRING2(STR_MITEM1015			,"Duplicate"	,"Menu item string for View options->Duplicate");
	ADD_APPLICATION_STRING2(STR_MITEM1010_SEARCH	,"Search", "Search options->search");
	//ADD_APPLICATION_STRING2(STR_MITEM1011_INPUT_METHOD,"Input Method","Search options->input method");

	ADD_APPLICATION_IMAGE2(IMG_MITEM1010,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Menu item image for View options->View");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1011,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Menu item image for View options->Edit");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1012,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Menu item image for View options->Delete");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1013,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Menu item image for View options->Copy Entry");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1014,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Menu item image for View options->Move");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1015,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Menu item image for View options->Duplicate");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1010_SEARCH	,CUST_IMG_BASE_PATH"/NoImage.bmp", "Search options->search");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1011_INPUT_METHOD,CUST_IMG_BASE_PATH"/NoImage.bmp","Search options->input method");
	ADD_APPLICATION_STRING2(STR_NO_ENTRIES_MESSAGE, "Phone Book Empty!", "No entries message");
	//Fix Bug#12144 for M301WapMMS by cong.li on 2009.05.13.
	ADD_APPLICATION_STRING2(STR_NO_THIS_ENTRIE_MESSAGE, "No Record!", "No finding any entry");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME_NUM_REQUIRE	,"Enter either name or number","Error message");
#if defined(__MMI_PHB_NAME_AND_NUM_REQUIRE__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME_REQUIRE	,"Please enter name","Error message");
#endif
	ADD_APPLICATION_STRING2(STR_ID_PHB_NUM_REQUIRE	,"Please enter number","Error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NUM_INVALID	,"Invalid Number Format","Error message");
	ADD_APPLICATION_STRING2(STR_DELETE_QUERY_MSG			,"Delete"		,"Delete query message");
	ADD_APPLICATION_STRING2(STR_COPY_QUERY_MSG				,"Copy"		,"Copy query message");
	ADD_APPLICATION_STRING2(STR_MOVE_QUERY_MSG				,"Move"		,"Move query message");
	ADD_APPLICATION_STRING2(STR_DUPLICATE_QUERY_MSG			,"Duplicate"	,"Duplicate query message");
	ADD_APPLICATION_STRING2(STR_DELETEALL_QUERY_SIM_MSG		,"Delete SIM"	,"Delete All SIM message");
	ADD_APPLICATION_STRING2(STR_DELETEALL_QUERY_PHONE_MSG	,"Delete Phone","Delete All Phone message");
	//ADD_APPLICATION_STRING2(STR_SAVE_QUERY					,"Save"		,"Save entry query");
	ADD_APPLICATION_STRING2(STR_NOENTRY_FOUND_MSG	,"No Entries Found!"	,"No Entries Found message");
	ADD_APPLICATION_STRING2(STR_PBOOK_FULL_MSG	,"Phonebook Full!"	,"Phonebook full message");
	ADD_APPLICATION_STRING2(STR_SIM_FULL_MSG	,"SIM Storage Full!"	,"SIM full message");
	ADD_APPLICATION_STRING2(STR_PHONE_FULL_MSG	,"Phone Storage Full!"	,"Phone full message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NO_ENTRY_TO_SELECT	,"No Entry To Select!"	,"No entry can be selected message");
#if !defined(MEM_ULC_3216)
	ADD_APPLICATION_IMAGE2(IMG_COPIED, CUST_IMG_PATH"/MainLCD/Warningpage/PopUpPage/PP_COP.gif", "Copied image");
	ADD_APPLICATION_IMAGE2(IMG_ENTRY_MOVED_MSG			,CUST_IMG_PATH"/MainLCD/Warningpage/PopUpPage/PP_MOV.gif","Entry Moved message icon");
	ADD_APPLICATION_IMAGE2(IMG_ENTRY_DUPLICATED_MSG		,CUST_IMG_PATH"/MainLCD/Warningpage/PopUpPage/PP_DUP.gif","Entry Duplicated message icon");
#endif
	ADD_APPLICATION_STRING2(STR_SCR_PBOOK_VIEW_CAPTION	,"Phone Book List"	,"Title string for entry list screen");
	ADD_APPLICATION_STRING2(STR_SCR_VIEW_OPTIONS_CAPTION	,"Entry Option"	,"Title string for view options screen");
	ADD_APPLICATION_STRING2(STR_SCR_INLINE_EDIT_CAPTION		,"Edit Entry"	,"Title string for Inline Edit screen");
	ADD_APPLICATION_STRING2(STR_SCR_ENTRY_VIEW_CAPTION,		"Phone Book View"	,"Title string for Entry View screen");
	ADD_APPLICATION_STRING2(STR_SCR_SEARCH_NAME_CAPTION	,"Name"			,"Title string for search name entry screen");
	ADD_APPLICATION_STRING2(STR_PROCESSING_PHONEBOOK	,"Processing Phone Book"	, "Processing Phonebook message");
	ADD_APPLICATION_IMAGE2(IMG_PROCESSING_PHONEBOOK	,CUST_IMG_PATH"/MainLCD/UIElement/Progress/PROGRESS.gif","Processing Phonebook message icon");
	//ADD_APPLICATION_STRING2(STR_SCR_DELETE_ALL_MENU_CAPTION	,"Delete All", "Delete all menu caption string");
	ADD_APPLICATION_STRING2(STR_CHOOSE_STORAGE_CAPTION	,"Choose Storage"	,"Storage menu caption string");
	ADD_APPLICATION_STRING2(STR_STORAGE_LOCATION_SIM, "To SIM", "Storage location To SIM");
#ifdef __DOUBLE_PHONE__
	ADD_APPLICATION_STRING2(STR_TWIN_A_STORAGE_LOCATION_SIM2, "To SIM2", "Storage location To SIM");
#endif
	ADD_APPLICATION_STRING2(STR_STORAGE_LOCATION_PHONE, "To Phone","Strorage location To Phone");
	ADD_APPLICATION_STRING2(STR_SCR_ADD_NEW_ENTRY_CAPTION, "New Entry", "New Entry screen caption");
	ADD_APPLICATION_STRING2(STR_EMERGENCY_NUMBER,"Emergency Number", "Emergency Number");
#ifdef __DOUBLE_PHONE__
#ifdef __UNI_TWIN_C_PHONEBOOK__
       ADD_APPLICATION_IMAGE2(IMG_STORAGE_SIM02			,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_INSIM_C.PBM","SIM Card image");
#else
	ADD_APPLICATION_IMAGE2(IMG_STORAGE_SIM02			,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_INSIM02.PBM","SIM Card image");
#endif
#endif
#if !defined(MEM_ULC_3216)
	ADD_APPLICATION_IMAGE2(IMG_SCR_PBOOK_CAPTION	,CUST_IMG_PATH"/MainLCD/TitleBar/TB_PB.gif","Title image for PhoneBook main screen");
#endif
	ADD_APPLICATION_IMAGE2(IMG_PHB_SEARCH_ENTRY,CUST_IMG_PATH"/MainLCD/Phonebook/SB_ENTRY.gif","PHB Submenu image for Search Entry");
	ADD_APPLICATION_IMAGE2(IMG_PHB_ADD_ENTRY,CUST_IMG_PATH"/MainLCD/Phonebook/SB_ADD.gif","PHB Submenu image for Add New Entry");
	ADD_APPLICATION_IMAGE2(IMG_PHB_DELETE_ALL,CUST_IMG_PATH"/MainLCD/Phonebook/SB_DELE.gif","PHB Submenu image for Delete All");
	ADD_APPLICATION_IMAGE2(IMG_PHB_DELETE_ALL_ONE,CUST_IMG_PATH"/MainLCD/Phonebook/SB_DELEO.gif","PHB Submenu image for Delete All");
	ADD_APPLICATION_IMAGE2(IMG_PHB_COPY_ALL,CUST_IMG_PATH"/MainLCD/Phonebook/SB_COPY.gif","PHB Submenu image for Copy All");
	ADD_APPLICATION_IMAGE2(IMG_PHB_OWNER_NUMBER,CUST_IMG_PATH"/MainLCD/Phonebook/SB_OWNER.gif","PHB Submenu image for Owner Number");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_SDN,CUST_IMG_PATH"/MainLCD/Phonebook/SB_EDN.PBM","PHB Submenu image for SDN");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_SOS_NUMBER,CUST_IMG_PATH"/MainLCD/Phonebook/SB_SOS.PBM","PHB Submenu image for SOS Number");
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_PHB_SPEED_DIAL,CUST_IMG_PATH"/MainLCD/Phonebook/SB_SPEED.JPG","PHB Submenu image for Speed Dial");
	ADD_APPLICATION_IMAGE2(IMG_PHB_CALLER_GROUP,CUST_IMG_PATH"/MainLCD/Phonebook/SB_GROUP.gif","PHB Submenu image for Caller Group");
	ADD_APPLICATION_IMAGE2(IMG_PHB_SETTINGS,CUST_IMG_PATH"/MainLCD/Phonebook/SB_SET.gif","PHB Submenu image for Phonebook Settings");
#if !defined(MMI_ULC)
	ADD_APPLICATION_IMAGE2(IMG_NAME			,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_NAME.gif"		,"name image");
	ADD_APPLICATION_IMAGE2(IMG_MOBILE_NUMBER,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_PHONE.gif"	,"mobile number image");
	ADD_APPLICATION_IMAGE2(IMG_HOME_NUMBER	,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_home.gif"	,"home number image");
	ADD_APPLICATION_IMAGE2(IMG_COMPANY_NAME	,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_CP.gif"		,"company image");
	ADD_APPLICATION_IMAGE2(IMG_EMAIL_ADDRESS,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_EM.gif"		,"email image");
	ADD_APPLICATION_IMAGE2(IMG_OFFICE_NUMBER,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_OFCNB.gif"	,"office number image");
	ADD_APPLICATION_IMAGE2(IMG_FAX_NUMBER	,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_FAX.gif"		,"fax number image");
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_PICTURE		,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_PIC.JPG"		,"picture tag image");
	ADD_APPLICATION_IMAGE2(IMG_RING_TONE	,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_RING.gif"	,"ring tone image");
	ADD_APPLICATION_IMAGE2(IMG_CALLER_GROUP	,CUST_IMG_PATH"/MainLCD/Phonebook/Callergroup/CG_GROUP.gif","caller group image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLERGRP_MEMBER	,CUST_IMG_PATH"/MainLCD/Phonebook/Callergroup/CG_MEMBER.gif","caller group image");
#endif
#ifdef __UNI_TWIN_A_PHONEBOOK__
#ifdef __UNI_TWIN_C_PHONEBOOK__
       ADD_APPLICATION_IMAGE2(IMG_STORAGE_SIM			,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_INSIM_G.PBM","SIM Card image");
#else
	ADD_APPLICATION_IMAGE2(IMG_STORAGE_SIM			,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_INSIM01.PBM","SIM Card image");
#endif
#else
	ADD_APPLICATION_IMAGE2(IMG_STORAGE_SIM			,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_INSIM.gif","SIM Card image");
#endif
	ADD_APPLICATION_IMAGE2(IMG_STORAGE_HANDSET		,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_INPH.gif","Handset image");
#if defined(__MMI_PHB_BIRTHDAY_FIELD__)
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_BIRTHDAY,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_BDAY.gif"		,"birthday image");
#endif
#if defined(__MMI_PHB_INFO_FIELD__)
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_TITLE,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_TITLE.PBM"		,"title image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_URL,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_URL.PBM"		,"url image");
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_ADDRESS,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_ADDR.gif"		,"address image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_NOTE,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_NOTE.PBM"		,"note image");
#endif

#if defined(__MMI_PHB_USIM_FIELD__)
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_ANR,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_ANR.gif"		,"anr image");
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_SNE,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_SNE.gif"		,"sne image");
#endif

#ifdef __MMI_VOIP__
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_VOIP,CUST_IMG_PATH"/MainLCD/VOIP/Call/Phonebook/PV_VoIP.gif"		,"VoIP image");
#endif

	//ADD_APPLICATION_STRING2(STR_SCR_SEARCH_OPTIONS_CAPTION, "Option", "Title string for Search options screen");
	ADD_APPLICATION_STRING2(STR_NO_NUMBER_TO_DIAL,"No Number to Dial!","No Number to Dial");
	ADD_APPLICATION_STRING2(STR_CHOOSE_NUMBER_CAPTION,"Choose Number", "Choose Number Title");
	ADD_APPLICATION_STRING2(STR_COMPANY_CAPTION, "Company", "Company");
	ADD_APPLICATION_STRING2(STR_VIEW_PICTURE_CAPTION, "View Picture", "View Picture caption");
	//ADD_APPLICATION_STRING2(STR_PHB_OPTIONS, "Option", "Phonebook Options");

	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME		,"Name"	, "Name String");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOBILE_NUMBER	,"Mobile Number"	, "Mobile Number String");
	//ADD_APPLICATION_STRING2(STR_ID_PHB_ADD, "Add", "General string for add a record");

	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD						,"My vCard"			,"Menu item string for vCard");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_EDIT_MYCARD			,"Edit My Card"	,"Sub Menu item string for vCard -> Edit My Card");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_SEND_MYCARD			,"Send My Card"	,"Sub Menu item string for vCard -> Send My Card");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_SEND_ENTRY			,"Send This Entry"	,"Sub Menu item string for vCard -> Send This Card");

	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_NO_IMAGE,CUST_IMG_BASE_PATH"/NoImage.bmp"	,"Common no image for submenu item.");
	ADD_APPLICATION_STRING2(STR_ID_PHB_AUDIO_ID_NOT_EXIST	,"Audio File Does Not Exist"	,"Audio File Does Not Exist");

#if defined(__MMI_DOWNLOADABLE_THEMES_SUPPORT__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_THEME_TONE_NOT_FOUND	,"Theme Tone Not Found"	,"Theme Tone not found");
#endif	

#if defined(__MMI_PHB_QUICK_SEARCH__)		/*Quick Search*/
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_QUICK_SEARCH		,CUST_IMG_PATH"/MainLCD/Phonebook/SB_QSERH.gif","Quick Search image");
#if !defined(MEM_ULC_3216)
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_QUICK_SEARCH_FIND		,CUST_IMG_PATH"/MainLCD/Phonebook/SB_Search.gif","Quick Search image");
#endif
	ADD_APPLICATION_STRING2(STR_ID_PHB_QUICK_SEARCH	,"Quick Search"	,"Quick Search string");
#endif

	ADD_APPLICATION_STRING2(STR_ID_PHB_OP_IMAGE_FAIL	,"Image"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_OP_VIDEO_FAIL	,"Video"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ADD_FAIL			," Add Fail!"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_EDIT_FAIL			," Edit Fail!"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_DUPLICATE_FAIL			," Duplicate Fail!"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_OP_COMMA		,", "	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SYSTEM_FULL		,"Not Enough Space"	,"Not Enough Space");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME_NUM_INVALID_ALL,"Invalid name and number","Error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME_NUM_INVALID,"Invalid either name or number","Error message");

#if defined(__MMI_PHB_CALLERGROUP_IN_SIM__) /* Associate caller group in SIM card entry*/
	ADD_APPLICATION_STRING2(STR_ID_PHB_REFRESH_SIM	,"SIM changed, Delete all caller group in SIM?"	,"SIM change prompt message.");
#endif
	/*For image list default icon*/
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_LIST_ICON1		,CUST_IMG_PATH"/MainLCD/Phonebook/SB_Default.jpg","Picture List Default Icon");

//[221] Added by Ryh 2009/02/12								[BEGIN]
#ifdef __MMI_MULTI_SIM__
	ADD_APPLICATION_STRING2(STR_STORAGE_LOCATION_SIM1, "To SIM1", "Storage location To SIM1");
	ADD_APPLICATION_STRING2(STR_STORAGE_LOCATION_SIM2, "To SIM2", "Storage location To SIM2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_IP_DIAL1,"SIM1 IP Dial","Menu item string for View options->IP Dial");	
	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_IP_DIAL2,"SIM2 IP Dial","Menu item string for View options->IP Dial");
	ADD_APPLICATION_STRING2(STR_ID_PHB_DAIL_FROM_SIM1, "SIM1 voice call", "Dial from sim1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_DAIL_FROM_SIM2, "SIM2 voice call","Dial from sim2");

	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_FROM_SIM1_TO_SIM2, "Copy from SIM1 to SIM2","PHB copy from sim1 to sim2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_FROM_SIM1_TO_PHONE, "Copy from SIM1 to phone","PHB copy from sim1 to phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_FROM_SIM2_TO_SIM1, "Copy from SIM2 to SIM1","PHB copy from sim2 to sim1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_FROM_SIM2_TO_PHONE, "Copy from SIM2 to phone","PHB copy from sim2 to phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_FROM_PHONE_TO_SIM1, "Copy from phone to SIM1","PHB copy from phone to sim1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_FROM_PHONE_TO_SIM2, "Copy from phone to SIM2","PHB copy from phone to sim2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOVE_FROM_SIM1_TO_SIM2, "Move from SIM1 to SIM2","PHB move from sim1 to sim2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOVE_FROM_SIM1_TO_PHONE, "Move from SIM1 to phone","PHB move from sim1 to phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOVE_FROM_SIM2_TO_SIM1, "Move from SIM2 to SIM1","PHB move from sim2 to sim1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOVE_FROM_SIM2_TO_PHONE, "Move from SIM2 to phone","PHB move from sim2 to phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOVE_FROM_PHONE_TO_SIM1, "Move from phone to SIM1","PHB move from phone to sim1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOVE_FROM_PHONE_TO_SIM2, "Move from phone to SIM2","PHB move from phone to sim2");

//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_ALL_FROM_SIM1_TO_SIM2, "From SIM1 to SIM2","PHB copy all from sim1 to sim2");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_ALL_FROM_SIM1_TO_PHONE, "From SIM1 to phone","PHB copy all from sim1 to phone");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_ALL_FROM_SIM2_TO_SIM1, "From SIM2 to SIM1","PHB copy all from sim2 to sim1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_ALL_FROM_SIM2_TO_PHONE, "From SIM2 to phone","PHB copy all from sim2 to phone");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_ALL_FROM_PHONE_TO_SIM1, "From phone to SIM1","PHB copy all from phone to sim1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_COPY_ALL_FROM_PHONE_TO_SIM2, "From phone to SIM2","PHB copy all from phone to sim2");

	ADD_APPLICATION_STRING2(STR_DELETE_ALL_SIM1 ,"From SIM1" ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_DELETE_ALL_SIM2 ,"From SIM2" ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_SIM1 ,"From SIM1" ,"Menu item string for Add All->SIM");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_SIM2 ,"From SIM2" ,"Menu item string for Add All->SIM");	
	ADD_APPLICATION_STRING2(STR_COPY_ALL_SIM3 ,"From SIM3" ,"Menu item string for Add All->SIM");	    
	ADD_APPLICATION_STRING2(STR_SIM1_FULL_MSG,"SIM1 Storage Full!","SIM1 full message");
	ADD_APPLICATION_STRING2(STR_SIM2_FULL_MSG,"SIM2 Storage Full!","SIM2 full message");
	ADD_APPLICATION_STRING2(STR_COPIED_TO_SIM1_DONE,"Copied to SIM1","Copied to SIM1");
	ADD_APPLICATION_STRING2(STR_COPIED_TO_SIM2_DONE,"Copied to SIM2","Copied to SIM2");
	ADD_APPLICATION_STRING2(STR_MOVED_TO_SIM1_DONE,"Moved to SIM1!","Moved to SIM1");
	ADD_APPLICATION_STRING2(STR_MOVED_TO_SIM2_DONE,"Moved to SIM2!","Moved to SIM2");

	ADD_APPLICATION_STRING2(STRING_MTPNP_SIM1_OWNER_NUMBER,"SIM1 Owner Number","Menu item string for SIM1 Owner Number");
	ADD_APPLICATION_STRING2(STRING_MTPNP_OWNER_NUMBER,"SIM2 Owner Number","Menu item string for SIM2 Owner Number");
	ADD_APPLICATION_STRING2(STRING_MTPNP_SIM1_SDL_NUMBER,"SIM1 Service Dial Number","SIM1 SDL NO LIST CAPTION ");
	ADD_APPLICATION_STRING2(STRING_MTPNP_SDL_NUMBER,"SIM2 Service Dial Number","SIM2 SDL NO LIST CAPTION ");
	ADD_APPLICATION_STRING2(STRING_MTPNP_SIM1_SOS_NUMBER, "SIM1 SOS Number","SIM1 STR_DISPLAY_SOS_CAPTION");
	ADD_APPLICATION_STRING2(STRING_MTPNP_SOS_NUMBER, "SIM2 SOS Number","SIM2 STR_DISPLAY_SOS_CAPTION");
#endif
//[221] Added by Ryh 2009/02/12								[END]


#if defined(__MMI_VCARD__)
#if defined(__MMI_VCARD_V30__)		/* vCard Version 2.1 or 3.0 */
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_VERSION ,"Vcard Version" ,"Menu item string for vcard version");
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_VERSION_21 ,"Vcard Version 2.1" ,"Menu item string for vcard verson 21");
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_VERSION_30 ,"Vcard Version 3.0"   ,"Menu item string for vcard version 30"); 
#endif  /* defined(__MMI_VCARD_V30__) */
    ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT, "Export Phonebook", "Export Phonebook");
    ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT_FROM_PHONE, "Export Phonebook From Phone", "Export Phonebook From Phone");
    ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT_FROM_SIM, "Export Phonebook From Sim", "Export Phonebook From Sim");
#ifdef __MMI_MULTI_SIM__
	ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT_FROM_SIM1, "Export Phonebook From Sim1", "Export Phonebook From Sim1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT_FROM_SIM2, "Export Phonebook From Sim2", "Export Phonebook From Sim2");
	#if(MMI_SIM_NUMBER >= 3)
	ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT_FROM_SIM3, "Export Phonebook From Sim3", "Export Phonebook From Sim2");
	#endif
	#if(MMI_SIM_NUMBER >= 4)
	ADD_APPLICATION_STRING2(STR_ID_PHB_EXPORT_FROM_SIM4, "Export Phonebook From Sim4", "Export Phonebook From Sim2");
	#endif
#endif    
    ADD_APPLICATION_STRING2(STR_ID_PHB_IMPORT, "Import Phonebook", "Import Phonebook");
    ADD_APPLICATION_STRING2(STR_ID_PHB_IMPORT_FROM_VCF, "Vcf Style", "VcfStyle");
    ADD_APPLICATION_STRING2(STR_ID_PHB_IMPORT_FROM_OUTLOOK, "Outlook Style", "Outlook Style");    
#endif 	/* defined(__MMI_VCARD__)  */

	PopulateAdvancedPbResData();
	PopulateInlineEditRes();
	PopulateCopyAllResData();
	PopulateExtraNumberRes();
	PopulatePbookSettingsData();
	PopulatePhbExtraMainMenuRes();
}


void PopulateAdvancedPbResData(void)
{

	PRINT_INFORMATION(("File: [%s]  Line: [%d] <<PopulateAdvancedPbResData.>\n",__FILE__,__LINE__));

	/*Caller Group*/
	ADD_APPLICATION_MENUITEM((MITEM109_PBOOK_CALLER_GROUPS, MAIN_MENU_PHONEBOOK_MENUID, 0,
		SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM109,IMG_PHB_CALLER_GROUP));

	/*Caller Group Member List*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLERGROUP_MEMBER_VIEW_OPTION,0,2,
		MENU_ID_PHB_CALLERGROUP_MEMBER_ADD_MEMBER,
		MENU_ID_PHB_CALLERGROUP_MEMBER_DELETE_MEMBER,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLERGROUP_MEMBER_ADD_MEMBER,MENU_ID_PHB_CALLERGROUP_MEMBER_VIEW_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_ADD,IMG_PHB_ADD_ENTRY));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLERGROUP_MEMBER_DELETE_MEMBER,MENU_ID_PHB_CALLERGROUP_MEMBER_VIEW_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_DELETE,IMG_MITEM1012));

	ADD_APPLICATION_IMAGE2(IMG_PHB_DEFAULT  ,CUST_IMG_PATH"/MainLCD/Call/Incoming/CL_INCOM00.gif", "Deafult picture of every entry");
#if !defined(MMI_ULC)
	ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE1 ,CUST_IMG_PATH"/MainLCD/Call/Incoming/CL_incom01.gif", "Picture 1");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE2 ,CUST_IMG_PATH"/MainLCD/Call/Incoming/CL_incom02.gif", "Picture 2");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE3 ,CUST_IMG_PATH"/MainLCD/Call/Incoming/CL_incom03.gif", "Picture 3");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE4 ,CUST_IMG_PATH"/MainLCD/Call/Incoming/CL_incom04.gif", "Picture 4");
#endif
	ADD_APPLICATION_IMAGE2(IMG_CG_NAME,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_GROUP.gif","Caller Grp name image");
#if !defined(MMI_ULC)
	ADD_APPLICATION_IMAGE2(IMG_CG_ALERT_TYPE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_ALERT.gif","Caller Grp alert type image");
	ADD_APPLICATION_IMAGE2(IMG_CG_RING_TONE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_RING.gif","Caller Grp ring tone image");
	ADD_APPLICATION_IMAGE2(IMG_CG_PICTURE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_PIC.gif","Caller Grp picture image");
	ADD_APPLICATION_IMAGE2(IMG_CG_INDICATOR_LITE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_PATT.gif","Caller Grp indicator lite image");
#endif
	ADD_APPLICATION_STRING2(STR_MITEM109	,"Caller Group"	,"Menu item string for Caller Groups option");
	ADD_APPLICATION_STRING2(STR_SCR_CALLER_GROUP_CAPTION, "Caller Group", "Title string for Caller Groups screen");
	ADD_APPLICATION_STRING2(STR_SCR_CG_DETAILS_CAPTION, "Caller Group Details", "Title string for Caller Groups Details screen");
#if !defined(MMI_ULC)
	ADD_APPLICATION_IMAGE2(IMG_CG_ALERT_TYPE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_ALERT.gif","Caller Grp alert type image");
	ADD_APPLICATION_IMAGE2(IMG_CG_RING_TONE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_RING.gif","Caller Grp ring tone image");
	ADD_APPLICATION_IMAGE2(IMG_CG_PICTURE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_PIC.gif","Caller Grp picture image");
	ADD_APPLICATION_IMAGE2(IMG_CG_INDICATOR_LITE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_PATT.gif","Caller Grp indicator lite image");
	//begin:guoyt added for C128
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_PICTURE,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_PIC.gif","Caller Grp picture image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLERGROUP_BLACKLIST,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_ALERT.gif","Caller Grp black list");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLERGROUP_REDLIST,CUST_IMG_PATH"/MainLCD/Phonebook/CallerGroup/CG_PATT.gif","Caller Grp red list");
	//end:guoyt added for C128
#endif
	ADD_APPLICATION_STRING2(STR_GRP_NAME_CAPTION, "Group Name", "Group Name Caption");
	ADD_APPLICATION_STRING2(STR_CG_RENAME_FAIL_MSG, "Cannot rename as other groups", "CG rename fail msg");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_1, "Friends"	, "Caller Group 1");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_2, "Family"	, "Caller Group 2");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_3, "VIP"		, "Caller Group 3");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_4, "Business"	, "Caller Group 4");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_5, "Others"	, "Caller Group 5");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLERGROUP_MEMBER_LIST, "Member List"	, "Caller Group Member List");
	ADD_APPLICATION_STRING2(STR_PICTURE_1, "Picture 1", "Picture Tag 1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_PICTURE_2, "Picture 2", "Picture Tag 2");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_PICTURE_3, "Picture 3", "Picture Tag 3");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_PICTURE_4, "Picture 4", "Picture Tag 4");
	ADD_APPLICATION_STRING2(STR_PHB_COPYING,"Copying" , "Copying");
	ADD_APPLICATION_STRING2(STR_PHB_DUPLICATING,"Duplicating", "Duplicating");
	ADD_APPLICATION_STRING2(STR_PHB_DELETING,"Deleting", "Deleting");
	//ADD_APPLICATION_STRING2(STR_PHB_SAVING, "Saving", "Saving");
	ADD_APPLICATION_STRING2(STR_PHB_ERASING, "Erasing", "Erasing");
	ADD_APPLICATION_STRING2(STR_PHB_MOVING, "Moving", "Moving");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SORTING_EMAIL, "Sorting Email", "Processing String");
	ADD_APPLICATION_STRING2(STR_NUMBER_TOO_LONG, "Number Too Long! Maximum = 40", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_SAVED_NUMBER_TOO_LONG, "Not Saved, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_MOVED_NUMBER_TOO_LONG, "Not Moved, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_COPIED_NUMBER_TOO_LONG, "Not Copied, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_DUPLICATED_NUMBER_TOO_LONG, "Not Duplicated, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_COPIED_NAME_MODIFIED, "Copied, Name Modified!", "Copied, Name Modified!");
	ADD_APPLICATION_STRING2(STR_COPIED_TO_PHONE_DONE, "Copied To Phone!", "Copied To Phone!");
	ADD_APPLICATION_STRING2(STR_COPIED_TO_SIM_DONE, "Copied To SIM!", "Copied To SIM!");
	ADD_APPLICATION_STRING2(STR_MOVED_NAME_MODIFIED, "Moved, Name Modified!", "Moved, Name Modified!");
	ADD_APPLICATION_STRING2(STR_MOVED_TO_PHONE_DONE, "Moved To Phone!", "Moved To Phone!");
	ADD_APPLICATION_STRING2(STR_MOVED_TO_SIM_DONE, "Moved To SIM!", "Moved To SIM!");
	ADD_APPLICATION_STRING2(STR_ENTRIES_COPIED, "Entries Copied!", "Entries Copied!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ENTRIES_DELETED, "Entries Deleted!", "Entries Deleted!");
}

void PopulateCopyAllResData(void)
{

	/*Copy All*/
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL,MAIN_MENU_PHONEBOOK_MENUID,2,
		MITEM_PBOOK_COPY_ALL_SIM,
		MITEM_PBOOK_COPY_ALL_PHONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));
	#ifdef __DOUBLE_PHONE__
	ADD_APPLICATION_STRING2(STR_TWIN_A_DELETE_ALL_SIM2 ,"From SIM2"	 ,"Menu item string for Delete All->SIM");
	#endif

	ADD_APPLICATION_STRING2(STR_MITEM104 ,"Copy All"						,"Menu item string for Copy All");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_SIM ,"From SIM"	 ,"Menu item string for Copy All->SIM");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_PHONE ,"From Phone" ,"Menu item string for Copy All->Phone");
	ADD_APPLICATION_STRING2(STR_DELETE_ALL_SIM ,"From SIM"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_DELETE_ALL_PHONE ,"From Phone" ,"Menu item string for Delete All->Phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_DELETE_ALL_ONE_BY_ONE ,"One By One" ,"Menu item string for Delete All->Phone");
	ADD_APPLICATION_STRING2(STR_SCR_COPY_ALL_MENU_CAPTION, "Copy All", "Title string for Copy All menu screen");
	ADD_APPLICATION_STRING2(STR_OVERWRITE_TARGET, "Overwrite Target Location?", "Overwrite Target Location?");
	//ADD_APPLICATION_STRING2(STR_COPY_ALL_ABORT, "Abort", "Copy All abort");
	ADD_APPLICATION_IMAGE2(IMG_COPY_ALL_ABORT, CUST_IMG_BASE_PATH"/NoImage.bmp", "Copy all abort image");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_ABORTING, "Aborting..", "Aborting Copy all");
	ADD_APPLICATION_IMAGE2(IMG_COPY_ALL_ABORTING,CUST_IMG_PATH"/MainLCD/UIElement/Progress/PROGRESS.gif","Aborting Copy all image");
}


void PopulateExtraNumberRes(void)
{
	/* Populate Special Number Resource, including Owner Number, Service Dial Number, and SOS number */
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXTRA_NUMBER,MAIN_MENU_PHONEBOOK_MENUID,3,
		MITEM105_PBOOK_OWNER_NUMBER,
		MENU_PHONEBOOK_SERVICENUMBER,
		MITEM116_PBOOK_SOS_NUMBER,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EXTRA_NUMBER,IMG_PHB_OWNER_NUMBER));

	ADD_APPLICATION_STRING2(STR_ID_PHB_EXTRA_NUMBER ,"Special Number"	,"Menu item string for Special Number");

	/*Populate Owner Number Resource*/
	ADD_APPLICATION_MENUITEM((MITEM105_PBOOK_OWNER_NUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
		SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM105,IMG_PHB_OWNER_NUMBER));

	ADD_APPLICATION_MENUITEM((MITEM105_OWNER_NUMBER_OPTIONS,0,2,
		MITEM1052_OWNER_NUMBER_EDIT,
		MITEM1051_OWNER_NUMBER_ERASE,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MITEM1051_OWNER_NUMBER_ERASE,MITEM105_OWNER_NUMBER_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ERASE_QUERY,IMG_MITEM1051));
	ADD_APPLICATION_MENUITEM((MITEM1052_OWNER_NUMBER_EDIT,MITEM105_OWNER_NUMBER_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_EDIT,IMG_MITEM1052));

	ADD_APPLICATION_STRING2(STR_MITEM105 ,"Owner Number"						,"Menu item string for Owner Number");
	//ADD_APPLICATION_STRING2(STR_MITEM1051 ,"Erase"						,"Menu item string for Owner Number Options->Erase");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1051 ,CUST_IMG_BASE_PATH"/NoImage.bmp","Menu item image for Owner Number Options->Erase");
	//ADD_APPLICATION_STRING2(STR_MITEM1052 ,"Edit"						,"Menu item string for Owner Number Options->Edit");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1052 ,CUST_IMG_BASE_PATH"/NoImage.bmp","Menu item image for Owner Number Options->Edit");
	//ADD_APPLICATION_STRING2(STR_SCR_OWNER_NUMBER_EDIT_CAPTION, "Edit", "Title screen for owner number edit screen");
	//ADD_APPLICATION_STRING2(STR_SCR_OWNER_NUMBERS_CAPTION ,"Owner Number"						,"Title string for Owner Numbers List screen");
	ADD_APPLICATION_STRING2(STR_NO_OWNER_NUMBER_MESSAGE, "Owner Number List Empty!", "No owner numbers message");
	//ADD_APPLICATION_STRING2(STR_SCR_OWNER_NUMBER_OPTIONS_CAPTION, "Owner Num. Option", "Title string for Owner Number Options screen");
	ADD_APPLICATION_STRING2(STR_OWNER_NAME_CAPTION, "Owner Name", "Owner Name caption");
	ADD_APPLICATION_STRING2(STR_ERASE_QUERY, "Erase", "Owner number erase query");

	/* Populate Service Dial Number Resource */
	ADD_APPLICATION_MENUITEM((MENU_PHONEBOOK_SERVICENUMBER, MENU_ID_PHB_EXTRA_NUMBER, 0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_SDL_MAIN_MENU, IMG_PHB_SDN));

	ADD_APPLICATION_STRING2(STR_CALL_SDL_CAPTION	,"Service Dial Number"			,"SDL DIAL LIST CAPTION ");
	ADD_APPLICATION_STRING2(STR_SDL_MAIN_MENU		,"Service Dial Number"			,"SDL NO LIST CAPTION ");
	ADD_APPLICATION_STRING2(STR_SDL_NO_LIST_TEXT	,"Not Supported!"	,"SDL NO LIST TEXT ");
	//ADD_APPLICATION_STRING2(STR_SDL_CALL_LSK		,"Dial"							,"SDL VIEW OPTION CALL ");
	ADD_APPLICATION_IMAGE2(IMG_SDL_CALL_LSK			,CUST_IMG_BASE_PATH"/NoImage.bmp", "SDL NO LIST SCREEN CAPTION ");

	/* Populate Emergency (SOS) Number Resource */
	ADD_APPLICATION_MENUITEM((MITEM116_PBOOK_SOS_NUMBER, MENU_ID_PHB_EXTRA_NUMBER, 0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_SOS_MENU_ITEM, IMG_PHB_SOS_NUMBER));

	ADD_APPLICATION_STRING2(STR_SOS_MENU_ITEM,"SOS Number","STR_SOS_MENU_ITEM");
	ADD_APPLICATION_STRING2(STR_DISPLAY_SOS_CAPTION,"SOS Number","STR_DISPLAY_SOS_CAPTION");
	//ADD_APPLICATION_STRING2(STR_SOS_OPTIONS_EDIT,"Edit","STR_SOS_OPTIONS_EDIT");
	//ADD_APPLICATION_STRING2(STR_SOS_ENTER_NUMBER, "Edit","STR_SOS_ENTER_NUMBER");
	//ADD_APPLICATION_STRING2(STR_CONFIRM_SOS_CALL_TEXT,"Dial","STR_CONFIRM_SOS_CALL_TEXT");
	//ADD_APPLICATION_STRING2(STR_NUMBER_EMPTY,"<Empty>","STR_SOSLIST_EMPTY");
	ADD_APPLICATION_STRING2(STR_SOSLIST_NVRAM,"in Phone","STR_SOSLIST_NVRAM");
	ADD_APPLICATION_STRING2(STR_SOSLIST_INCARD,"in Card","STR_SOSLIST_INCARD");
}

void PopulatePbookSettingsData(void)
{
#if 0
	ADD_APPLICATION_MENUITEM((MITEM110_PBOOK_SETTINGS,MAIN_MENU_PHONEBOOK_MENUID, MMI_PHB_SETTING_ENUM_TOTAL,
		MITEM1101_PBOOK_MEMORY_STATUS,
		MITEM1102_PBOOK_STORAGE_LOCATION,
		MITEM1103_PBOOK_VIEW_FIELDS,
#if defined(__MMI_PHB_NAME_LIST_FILTER__)
        MENU_ID_PHB_NAME_LIST_FILTER,	
#endif
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_MYCARD,
#endif
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_ID_PHB_SPEAK_NAME,
#endif
		SHOW, INSERTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM110,IMG_PHB_SETTINGS));

	ADD_APPLICATION_MENUITEM((MITEM110_PBOOK_SETTINGS_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID, MMI_PHB_SETTING_NO_SIM_ENUM_TOTAL,
		MITEM1101_PBOOK_MEMORY_STATUS,
		MITEM1103_PBOOK_VIEW_FIELDS,
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_MYCARD,
#endif
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_ID_PHB_SPEAK_NAME,
#endif
		SHOW, INSERTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM110,IMG_PHB_SETTINGS));

	ADD_APPLICATION_MENUITEM((MITEM1101_PBOOK_MEMORY_STATUS, MITEM110_PBOOK_SETTINGS,0,
		SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_MITEM1101,IMG_MITEM1101));
	ADD_APPLICATION_MENUITEM((MITEM1102_PBOOK_STORAGE_LOCATION,MITEM110_PBOOK_SETTINGS, 2,
		MITEM_STORAGE_LOCATION_SIM,
		MITEM_STORAGE_LOCATION_PHONE,
		SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_MITEM1102,IMG_MITEM1102));
	ADD_APPLICATION_MENUITEM((MITEM1103_PBOOK_VIEW_FIELDS,MITEM110_PBOOK_SETTINGS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1103,IMG_MITEM1103));

	ADD_APPLICATION_MENUITEM((MITEM_STORAGE_LOCATION_SIM,MITEM1102_PBOOK_STORAGE_LOCATION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_SIM,IMG_STORAGE_SIM));
#endif

#if defined(__MMI_PHB_NAME_LIST_FILTER__)
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NAME_LIST_FILTER,MITEM110_PBOOK_SETTINGS, 3,
        MENU_ID_PHB_NLF_SIM,
        MENU_ID_PHB_NLF_PHONE,
        MENU_ID_PHB_NLF_BOTH,
        SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_NLF,IMG_ID_PHB_NLF));

    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NLF_SIM,MENU_ID_PHB_NAME_LIST_FILTER,0,
        SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_NLF_SIM,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NLF_PHONE,MENU_ID_PHB_NAME_LIST_FILTER,0,
        SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_NLF_PHONE,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NLF_BOTH,MENU_ID_PHB_NAME_LIST_FILTER,0,
        SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_NLF_BOTH,0));
#endif /* defined(__MMI_PHB_NAME_LIST_FILTER__) */

#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SPEAK_NAME,MITEM110_PBOOK_SETTINGS,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_SPEAK_NAME,0));
#endif

	ADD_APPLICATION_STRING2(STR_MITEM110	,"Settings"	,"Menu item string for PhoneBook Setting option");
	ADD_APPLICATION_STRING2(STR_MITEM1101	,"Memory Status"		,"Menu item string for PhoneBook Setting->Memory status");
	ADD_APPLICATION_STRING2(STR_MITEM1102	,"Preferred Storage"	,"Menu item string for PhoneBook Setting->Preferred storage");
	ADD_APPLICATION_STRING2(STR_MITEM1103	,"Fields"	,"Menu item string for PhoneBook Setting->Phonebook fields");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1101	,CUST_IMG_BASE_PATH"/NoImage.bmp"		,"Menu item image for PhoneBook Settings->Memory status");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1102    ,CUST_IMG_BASE_PATH"/NoImage.bmp"		,"Menu item image for PhoneBook Settings->Preferred storage");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1103	,CUST_IMG_BASE_PATH"/NoImage.bmp"		,"Menu item image for PhoneBook Settings->Phonebook fields");
	ADD_APPLICATION_STRING2(STR_SCR_PBSETTINGS_LIST_CAPTION	,"Settings"	,"Title string for Phonebook settings screen");
	ADD_APPLICATION_STRING2(STR_SCR_VIEW_FIELDS_CAPTION	,"Fields"		,"Title string for View Fields screen");
	ADD_APPLICATION_STRING2(STR_SCR_STORAGE_LOCATION_CAPTION	,"Preferred Storage"	,"Title string for Storage Location screen");
	ADD_APPLICATION_STRING2(STR_STORAGE_SIM, "SIM", "Menu item string for Storage Location SIM");
	ADD_APPLICATION_STRING2(STR_STORAGE_PHONE, "Phone", "Menu item string for Storage Location Phone");
	ADD_APPLICATION_STRING2(STR_SCR_MEMORY_USAGE_CAPTION, "Memory Status", "Title string for Memory Status screen");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_MEMORY_USAGE_FAIL_MSG, "Memory Status Failed", "Memory status failed message");
	ADD_APPLICATION_STRING2(STR_HOME_NUMBER			,"Home Number"		, "String for view field Home Number");
	ADD_APPLICATION_STRING2(STR_COMPNAY_NAME		,"Company Name"		, "String for view field Company Name");
	ADD_APPLICATION_STRING2(STR_EMAIL_ADRESS		,"Email Address"	, "String for view field Email Address");
	ADD_APPLICATION_STRING2(STR_OFFICE_NUMBER		,"Office Number"	, "String for view field Office Number");
	ADD_APPLICATION_STRING2(STR_FAX_NUMBER			,"Fax Number"		, "String for view field Fax Number");
	ADD_APPLICATION_STRING2(STR_ASSOCIATE_PICTURE	,"Associate Picture", "String for view field Associate Picture");
	ADD_APPLICATION_STRING2(STR_ASSOCIATE_SOUND		,"Associate Sound"	, "String for view field Associate Sound");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP		,"Caller Group"		, "String for view field Caller Group");
#if defined(__MMI_PHB_BIRTHDAY_FIELD__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_BIRTHDAY		,"Birthday"		, "String for view field birthday");
#endif

#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	ADD_APPLICATION_STRING2(STR_ID_PHB_SPEAK_NAME		,"Human Voice Prompt"		, "Phonebook setting menu item");
#endif

	ADD_APPLICATION_STRING2(STR_MEMORY_STATUS_SIM, "SIM", "SIM on Memory status screen");
	ADD_APPLICATION_STRING2(STR_MEMORY_STATUS_PHONE, "Phone", "Phone on Memory status screen");
#ifdef __DOUBLE_PHONE__
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_TWIN_A_SIM_MEMORY_STATUS, "SIM2", "SIM2  on Memory status screen");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_TWIN_A_SIM2_PB_OPERATOR_HINT, "SIM2 Phonebook Is Reading,Forbid ", "SIM2 Phonebook Is Reading,Forbid");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_TWIN_A_OPERATOR_FORBID, "Current Status,Forbid ", "Current Status");
#endif
#if defined(__MMI_PHB_NAME_LIST_FILTER__)
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF ,"Name List Filter" ,"Menu item string for PhoneBook Setting->Name list filter");
    ADD_APPLICATION_IMAGE2(IMG_ID_PHB_NLF  ,CUST_IMG_BASE_PATH"/NoImage.bmp"    ,"Menu item image for PhoneBook Settings->Name list filter");
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF_SIM ,"SIM Only" ,"Menu item string for List Filter SIM");
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF_PHONE   ,"Phone Only"   ,"Menu item string for List Filter Phone");	
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF_BOTH    ,"Both" ,"Menu item string for List Filter Both");	
#endif 	/* defined(__MMI_PHB_NAME_LIST_FILTER__) */

#if defined(__MMI_PHB_INFO_FIELD__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_EDIT_DETAIL		,"Edit Detail"		, "String for view option- edit detail");
	ADD_APPLICATION_STRING2(STR_ID_PHB_TITLE		,"Title"		, "String for view field title");
	ADD_APPLICATION_STRING2(STR_ID_PHB_URL  ,"Url"		, "String for view field url");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_ADDRESS		,"Postal Address"		, "String for view field postal address");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOTE		,"Note"		, "String for view field note");
	//ADD_APPLICATION_STRING2(STR_ID_PHB_MORE		,"More"		, "String for view extra field");
#endif

#if defined(__MMI_PHB_USIM_FIELD__)
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_ANR_1  , "Additional Number 1"		, "String for view field ANR 1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_ANR_2  , "Additional Number 2"		, "String for view field ANR 2");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_ANR_3  , "Additional Number 3"		, "String for view field ANR 3");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_1, "SIM Group 1"	, "SIM Caller Group 1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_2, "SIM Group 2"	, "SIM Caller Group 2");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_3, "SIM Group 3"	, "SIM Caller Group 3");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_4, "SIM Group 4"	, "SIM Caller Group 4");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_5, "SIM Group 5"	, "SIM Caller Group 5");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SNE  , "Nick Name"		, "String for view field Nick Name");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_SAVED_ANR_FULL  , "Not Saved, Additional Number Full!"		, "Additional Number Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_MOVED_ANR_FULL  , "Not Moved, Additional Number Full!"		, "Additional Number Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_COPIED_ANR_FULL  , "Not Copied, Additional Number Full!"		, "Additional Number Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_DUPLICATED_ANR_FULL  , "Not Duplicated, Additional Number Full!"		, "Additional Number Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_SAVED_EMAIL_FULL  , "Not Saved, Email Full!"		, "Email Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_MOVED_EMAIL_FULL  , "Not Moved, Email Full!"		, "Email Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_COPIED_EMAIL_FULL  , "Not Copied, Email Full!"		, "Email Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_DUPLICATED_EMAIL_FULL  , "Not Duplicated, Email Full!"		, "Email Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_SAVED_SNE_FULL  , "Not Saved, Nick Name Full!"		, "Nick Name Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_MOVED_SNE_FULL  , "Not Moved, Nick Name Full!"		, "Nick Name Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_COPIED_SNE_FULL  , "Not Copied, Nick Name Full!"		, "Nick Name Full!");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_DUPLICATED_SNE_FULL  , "Not Duplicated, Nick Name Full!"	, "Nick Name Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_PROCESSING_USIM  , "Processing SIM"	, "Processing SIM");
#endif

#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_EDIT_SERVICE_FIELD  , "Edit Service Field"		, "String for view field IMPS ID");
#endif
#if defined(__MMI_PHB_IMPS_FIELD__)
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_IMPS_ID  , "User ID"		, "String for view field IMPS ID");
#endif

#if defined(__MMI_VOIP__)
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VOIP_ID  , "VOIP URI"		, "String for view field IMPS ID");
#endif
}


void PopulateInlineEditRes(void)
{
	//ADD_APPLICATION_STRING2(STR_EDIT_LSK,"Edit","LSK label for Inline edit screen");
	//ADD_APPLICATION_STRING2(STR_DONE_RSK,"Done","RSK label for Inline edit screen");
	ADD_APPLICATION_STRING2(STR_VIEW_LSK,"View","LSK label for Inline edit screen");
	ADD_APPLICATION_IMAGE2(IMG_EDIT_LSK,CUST_IMG_BASE_PATH"/NoImage.bmp","LSK image for Inline edit screen");
	ADD_APPLICATION_IMAGE2(IMG_DONE_RSK,CUST_IMG_BASE_PATH"/NoImage.bmp","RSK image for Inline edit screen");
	ADD_APPLICATION_IMAGE2(IMG_VIEW_LSK,CUST_IMG_BASE_PATH"/NoImage.bmp","LSK image for Inline edit screen");

	/*Associate Video Menu*/
#if defined(__MMI_INCOMING_CALL_VIDEO__)
	/*Option for video in file*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_OPTION,0,4,
		MENU_ID_PHB_VIDEO_FILE_VIEW,
		MENU_ID_PHB_VIDEO_FILE_SELECT,
		MENU_ID_PHB_VIDEO_FILE_DELETE,
		MENU_ID_PHB_VIDEO_FILE_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_VIDEO, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_VIEW,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_VIDEO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_SELECT,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_DELETE,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_SETTING,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VIDEO_AUDIO_ONOFF, 0));

	/*Option for default video*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_DEFAULT_OPTION,0,2,
		MENU_ID_PHB_VIDEO_DEFAULT_VIEW,
		MENU_ID_PHB_VIDEO_DEFAULT_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_VIDEO, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_DEFAULT_VIEW,MENU_ID_PHB_VIDEO_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_VIDEO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_DEFAULT_SETTING,MENU_ID_PHB_VIDEO_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VIDEO_AUDIO_ONOFF,0));


	ADD_APPLICATION_STRING2(STR_ID_PHB_ASSOCIATE_VIDEO		,"Associate Video"		, "String for view field Associate Video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_AUDIO_ONOFF		,"Video Audio"		, "String for view field Video Audio");
	ADD_APPLICATION_STRING2(STR_ID_PHB_WATCH_VIDEO		,"Watch Video"		, "String for watch video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CANT_VIEW_VIDEO_IN_CALL		,"Can't  preview video during call"		, "String for watch video");

	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_1, "Video 1", "Video Tag 1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_2, "Video 2", "Video Tag 2");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_3, "Video 3", "Video Tag 3");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_4, "Video 4", "Video Tag 4");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_5, "Video 5", "Video Tag 5");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_6, "Video 6", "Video Tag 6");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_7, "Video 7", "Video Tag 7");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_8, "Video 8", "Video Tag 8");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_9, "Video 9", "Video Tag 9");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_10, "Video 10", "Video Tag 10");

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_ASSOCIATE_VIDEO	,CUST_IMG_PATH"/MainLCD/Phonebook/PBView/PV_VIDEO.JPG","Assoicate Video Icon");

	/*Populate Default Video Resource*/
#if defined(MJPG_SUPPORT)
	ADD_APPLICATION_MEDIA(VDO_ID_PHB_MTCALL_1, CUST_IMG_PATH"/MainLCD/Call/Incoming/video/IC_V01.avi");
#elif defined(MP4_CODEC)
	ADD_APPLICATION_MEDIA(VDO_ID_PHB_MTCALL_1, CUST_IMG_PATH"/MainLCD/Call/Incoming/video/IC_V01.mp4");
#endif

#ifdef __MMI_SWFLASH__
	/*Option for swflash in file*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_OPTION,0,4,
		MENU_ID_PHB_SWFLASH_FILE_VIEW,
		MENU_ID_PHB_SWFLASH_FILE_SELECT,
		MENU_ID_PHB_SWFLASH_FILE_DELETE,
		MENU_ID_PHB_SWFLASH_FILE_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_SWFLASH, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_VIEW,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_SWFLASH, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_SELECT,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_DELETE,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_SETTING,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_SWFLASH_AUDIO_ONOFF, 0));

	/*Option for default video*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_DEFAULT_OPTION,0,2,
		MENU_ID_PHB_SWFLASH_DEFAULT_VIEW,
		MENU_ID_PHB_SWFLASH_DEFAULT_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_SWFLASH, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_DEFAULT_VIEW,MENU_ID_PHB_SWFLASH_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_SWFLASH, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_DEFAULT_SETTING,MENU_ID_PHB_SWFLASH_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_SWFLASH_AUDIO_ONOFF,0));

	ADD_APPLICATION_STRING2(STR_ID_PHB_ASSOCIATE_SWFLASH		,"Associate SWFlash"		, "String for view field Associate Video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_AUDIO_ONOFF		,"SWFlash Audio"		, "String for view field Video Audio");
	ADD_APPLICATION_STRING2(STR_ID_PHB_WATCH_SWFLASH		,"Watch SWFlash"		, "String for watch video");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_CANT_VIEW_SWFLASH_IN_CALL		,"Can't  preview swflash during call"		, "String for watch video");

//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_1, "SWFlash 1", "SWFlash Tag 1");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_2, "SWFlash 2", "SWFlash Tag 2");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_3, "SWFlash 3", "SWFlash Tag 3");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_4, "SWFlash 4", "SWFlash Tag 4");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_5, "SWFlash 5", "SWFlash Tag 5");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_6, "SWFlash 6", "SWFlash Tag 6");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_7, "SWFlash 7", "SWFlash Tag 7");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_8, "SWFlash 8", "SWFlash Tag 8");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_9, "SWFlash 9", "SWFlash Tag 9");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_10, "SWFlash 10", "SWFlash Tag 10");

	ADD_APPLICATION_MEDIA(MFH_ID_PHB_MTCALL_1, CUST_IMG_PATH"/MainLCD/Call/Incoming/SWFlash/IC_M01.cmp");
#endif /* __MMI_SWFLASH__ */

#endif /* __MMI_INCOMING_CALL_VIDEO__ */

#ifdef __MMI_VOIP__
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EDIT_VOIP_OPTIONS,0,2,
		MENU_ID_PHB_EDIT_VOIP_DONE,
		MENU_ID_PHB_EDIT_VOIP_INPUT_MEHTHOD,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EDIT_VOIP_DONE,MENU_ID_PHB_EDIT_VOIP_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_DONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EDIT_VOIP_INPUT_MEHTHOD,MENU_ID_PHB_EDIT_VOIP_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_INPUT_METHOD, 0));
#endif /* __MMI_VOIP__ */
}


void PopulatePhbExtraMainMenuRes(void)
{
#if defined(__MMI_PHB_CALLER_RES_SETTING__)
	/*Menu Resource*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_PIC,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_PIC, IMG_ID_PHB_CALLER_PIC));

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_RING,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_RING, IMG_ID_PHB_CALLER_RING));

	/*String Resource*/
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_PIC, "Caller Picture", "Personal Incoming Call Setting");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_RING, "Caller Ring Tone", "Personal Incoming Call Setting");

	/*Image Resource*/
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_PIC	,CUST_IMG_PATH"/MainLCD/Phonebook/SB_MTPIC.gif","Personal Incoming Call Setting Icon");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_RING	,CUST_IMG_PATH"/MainLCD/Phonebook/SB_MTRING.gif","Personal Incoming Call Setting Icon");

	/*For caller video*/
#if defined(__MMI_INCOMING_CALL_VIDEO__)
#ifdef __MMI_SWFLASH__
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO,MAIN_MENU_PHONEBOOK_MENUID, 2,
		MENU_ID_PHB_CALLER_VIDEO_FILE,
		MENU_ID_PHB_CALLER_VIDEO_SWFLASH,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO, IMG_ID_PHB_CALLER_VIDEO));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO_FILE, MENU_ID_PHB_CALLER_VIDEO,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO_FROM_FILE, IMG_MITEM1101));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO_SWFLASH, MENU_ID_PHB_CALLER_VIDEO,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO_FROM_SWFLASH, IMG_MITEM1102));
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_VIDEO_FROM_FILE, "From File", "Select Caller Video From File");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_VIDEO_FROM_SWFLASH, "From SWFlash", "Select Caller Video From SWFlash");
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO, IMG_ID_PHB_CALLER_VIDEO));
#endif /* __MMI_SWFLASH__ */
		ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_VIDEO, "Caller Video", "Personal Incoming Call Setting");
			ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_VIDEO	,CUST_IMG_PATH"/MainLCD/Phonebook/SB_MTVDO.PBM","Personal Incoming Call Setting Icon");
#endif /* __MMI_INCOMING_CALL_VIDEO__ */

#endif	/* __MMI_PHB_CALLER_RES_SETTING__ */
}


#endif


