/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of CoolSand Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#include "cs_types.h"
#include "custdatares.h"
#include "mmi_features.h" 

#include "stdc.h"
#include "customcfg.h"
#include "gui_config.h"		//guoyt added for definition of macro __MMI_VIDEO_PLAYER__

#ifdef FIRST_PASS
#include "buildcfg.h"
#endif

#include "filemanagerdef.h"
#include "funandgamesdefs.h"
#ifdef __MMI_EBOOK_READER__
#include "ebookdefs.h"
#endif

#ifdef __MMI_EXT_DEVICE__
#include "extdevicedefs.h"
#endif

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"

typedef enum {
#ifdef __MMI_MMS__
	FMGR_FWD_TO_MMS,
#endif
#if (defined( __MMI_MESSAGES_EMS__) && !defined (__MMI_FMGR_NO_FWD_SMS__))
	FMGR_FWD_TO_EMS,
#endif
#ifdef __MMI_EMAIL__
   FMGR_FWD_TO_EMAIL,
#endif
#ifdef __MMI_IRDA_SUPPORT__
	FMGR_FWD_TO_IRDA,
#endif
#ifdef __MMI_SUPPORT_BLUETOOTH__
	FMGR_FWD_TO_BT,
#endif
   FMGR_FWD_COUNT
} FMGR_FWD_ENUM;

typedef enum {
#ifdef __FS_SORT_SUPPORT__
   FMGR_GEN_OPTION_SORT,
#endif
#ifdef __FS_MOVE_SUPPORT__
   FMGR_GEN_OPTION_MOVE,
   FMGR_GEN_OPTION_COPY,
#endif
   FMGR_GEN_OPTION_COUNT
} FMGR_GEN_OPTION_ENUM;

#ifdef __MMI_FILE_MANAGER__
void populateFileManagerMenu(void)
{

	/************************************************************/
	/*																				*/
	/*			Error String													*/
	/*																				*/
	/************************************************************/
	
	ADD_APPLICATION_STRING2(FMGR_FS_ERROR_RESERVED_TEXT, "Error reserved", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_PARAM_ERROR_TEXT, "Param error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_INVALID_FILENAME_TEXT, "Invalid filename", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_DRIVE_NOT_FOUND_TEXT, "Drive not found", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_TOO_MANY_FILES_TEXT, "Too many files", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_NO_MORE_FILES_TEXT, "No more files", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_WRONG_MEDIA_TEXT, "Wrong media ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_INVALID_FILE_SYSTEM_TEXT, "Invalid file system ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_FILE_NOT_FOUND_TEXT, "File not found", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_INVALID_FILE_HANDLE_TEXT, "Invalid file handle", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_UNSUPPORTED_DEVICE_TEXT, "Unsupported device ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_UNSUPPORTED_DRIVER_FUNCTION_TEXT, "Unsupported driver function", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_CORRUPTED_PARTITION_TABLE_TEXT, "Corrupted partition table", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_TOO_MANY_DRIVES_TEXT, "Too many drives", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_INVALID_FILE_POS_TEXT, "Invalid file pos", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_ACCESS_DENIED_TEXT, "Access denied", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_STRING_BUFFER_TOO_SMALL_TEXT, "String buffer too small", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_GENERAL_FAILURE_TEXT, "General failure", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_PATH_NOT_FOUND_TEXT, "Path not found", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_FAT_ALLOC_ERROR_TEXT, "Fat alloc error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_ROOT_DIR_FULL_TEXT, "Root dir full ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_DISK_FULL_TEXT, "Disk full", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_TIMEOUT_TEXT, "Timeout", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_BAD_SECTOR_TEXT, "Bad sector", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_DATA_ERROR_TEXT, "Data error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_MEDIA_CHANGED_TEXT, "Media changed", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_SECTOR_NOT_FOUND_TEXT, "Sector not found", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_ADDRESS_MARK_NOT_FOUND_TEXT, "Address mark not found ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_DRIVE_NOT_READY_TEXT, "Drive not ready ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_WRITE_PROTECTION_TEXT, "Write protection", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_DMA_OVERRUN_TEXT, "Dma overrun ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_CRC_ERROR_TEXT, "Crc error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_DEVICE_RESOURCE_ERROR_TEXT, "Device resource error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_INVALID_SECTOR_SIZE_TEXT, "Invalid sector size ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_OUT_OF_BUFFERS_TEXT, 	"Out of buffers	", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_FILE_EXISTS_TEXT, "File exists ", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_LONG_FILE_POS_TEXT, "Long file pos", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_FILE_TOO_LARGE_TEXT, "File too large", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_BAD_DIR_ENTRY_TEXT, "Bad dir entry	", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_READ_ONLY_ERROR_TEXT, "Read only	", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_SYSTEM_CRASH_TEXT, "File system crash	", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_FAIL_GET_MEM_TEXT, "Get mem fail	", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_DEVICE_BUSY_TEXT, "Device busy	", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_ABORTED_ERROR_TEXT, "Aborted	", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_FLASH_MOUNT_ERROR_TEXT, "Disk mount error	", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_PATH_OVER_LEN_ERROR_TEXT, "Path too deep	", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_APP_QUOTA_FULL_TEXT, "Not enough resource", "File Manager String");	
	//ADD_APPLICATION_STRING2(FMGR_FS_DEVICE_EXPORTED_ERROR_TEXT, "Device in USB mode", "File Manager String");	
	ADD_APPLICATION_STRING2(FMGR_FS_MSDC_MOUNT_ERROR_TEXT, "MSDC mount error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_MSDC_READ_SECTOR_ERROR_TEXT, "MSDC read sector error	", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_MSDC_WRITE_SECTOR_ERROR_TEXT, "MSDC write sector error	", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_MSDC_DISCARD_SECTOR_ERROR_TEXT, "MSDC discard sector error", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_MSDC_PRESENT_NOT_READY_TEXT, "MSDC not ready", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_MSDC_NOT_PRESENT_TEXT, "MSDC not present", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_FLASH_ERASE_BUSY_TEXT, "Flash erase busy", "File Manager String");
	ADD_APPLICATION_STRING2(FMGR_FS_LOCK_MUTEX_FAIL_TEXT, "Lock mutex fail", "File Manager String");

	ADD_APPLICATION_STRING2(STR_FMGR_SEL_DRV_TITLE,"Storage Selection","File Manager String");
	ADD_APPLICATION_STRING2(STR_FMGR_SEL_DRV_PHONE,"From Phone","File Manager String");
	ADD_APPLICATION_STRING2(STR_FMGR_SEL_DRV_CARD,"From Card","File Manager String");
 #ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__ 
	ADD_APPLICATION_STRING2(STR_FMGR_THEME_OPTION,"Theme","THEME String");
	ADD_APPLICATION_STRING2(STR_ID_FMGR_THEME_INCORRECT_LOCATION,"Theme File Location Incorrect. Do You Want To Move?","THEME warning String");
	ADD_APPLICATION_STRING2(STR_ID_FMGR_ACTIVE_THEME_DELETE,"Active Theme Cant Be Deleted","THEME Delete warning String");
	

//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_THEME_ERROR_FAILURE,"Theme Error","Theme Error String");
	
		ADD_APPLICATION_STRING2(STR_ID_FMGR_SPACE_NOT_AVAILABLE,"Full Space","Theme space not available");
	//ADD_APPLICATION_STRING2(STR_ID_FMGR_ALREADY_ACTIVE,"Theme Already Active","THEME already active String");
	ADD_APPLICATION_STRING2(STR_ID_FMGR_MAX_COUNT_REACHED,"Maximum Count Reached","THEME max count String");
#endif
 #ifdef __MMI_THEMES_V2_SUPPORT__ 
	ADD_APPLICATION_STRING2(STR_ID_FMGR_ALREADY_ACTIVE,"Theme Already Active","THEME already active String");
#endif

	/************************************************************/
	/*																				*/
	/*			exif information												*/
	/*																				*/
	/************************************************************/
#if 0
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_MAKE,"Make","STR_ID_FMGR_EXIF_MAKE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_MODEL,"Model","STR_ID_FMGR_EXIF_MODEL");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_ORIENTATION,"Orientation","STR_ID_FMGR_EXIF_ORIENTATION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_X_RESOLUTION,"X Resolution","STR_ID_FMGR_EXIF_X_RESOLUTION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_Y_RESOLUTION,"Y Resolution","STR_ID_FMGR_EXIF_Y_RESOLUTION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_RESOLUTION_UNIT,"Resolution Unit","STR_ID_FMGR_EXIF_RESOLUTION_UNIT");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_SOFTWARE,"Software","STR_ID_FMGR_EXIF_SOFTWARE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_DATE_TIME,"Date Time","STR_ID_FMGR_EXIF_DATE_TIME");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_YCBCR_POSITIONING,"YCbCr Position","STR_ID_FMGR_EXIF_YCBCR_POSITIONING");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_EXIF_IFD,"EXIF IFD","STR_ID_FMGR_EXIF_EXIF_IFD");

//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_EXPOSURE_TIME,"Exposure Time","STR_ID_FMGR_EXIF_EXPOSURE_TIME");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_FNUMBER,"F Number","STR_ID_FMGR_EXIF_FNUMBER");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_EXPOSURE_PROGRAM,"Exposure Program","STR_ID_FMGR_EXIF_EXPOSURE_PROGRAM");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_ISO_SPEED_RATINGS,"ISO Speed Ratings","STR_ID_FMGR_EXIF_ISO_SPEED_RATINGS");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_EXIF_VERSION,"EXIF Version","STR_ID_FMGR_EXIF_EXIF_VERSION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_DATE_TIME_ORIGINAL,"Date Time Original","STR_ID_FMGR_EXIF_DATE_TIME_ORIGINAL");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_DATE_TIME_DIGITIZED,"Date Time Digitized","STR_ID_FMGR_EXIF_DATE_TIME_DIGITIZED");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_COMPONENTS_CONFIG,"Components Config","STR_ID_FMGR_EXIF_COMPONENTS_CONFIG");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_EXPOSURE_BIAS_VALUE,"Exposure Bias Value","STR_ID_FMGR_EXIF_EXPOSURE_BIAS_VALUE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_METERING_MODE,"Metering Mode","STR_ID_FMGR_EXIF_METERING_MODE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_LIGHT_SOURCE,"Light Source","STR_ID_FMGR_EXIF_LIGHT_SOURCE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_FLASH,"Flash","STR_ID_FMGR_EXIF_FLASH");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_MAKER_NOTE,"Maker Note","STR_ID_FMGR_EXIF_MAKER_NOTE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_FLASHPIX_VERSION,"Flashpix Version","STR_ID_FMGR_EXIF_FLASHPIX_VERSION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_COLOR_SPACE,"Color Space","STR_ID_FMGR_EXIF_COLOR_SPACE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_PIXEL_X_DIMENSION,"X Dimension","STR_ID_FMGR_EXIF_PIXEL_X_DIMENSION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_PIXEL_Y_DIMENSION,"Y Dimension","STR_ID_FMGR_EXIF_PIXEL_Y_DIMENSION");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_EXPOSURE_MODE,"Exposure Mode","STR_ID_FMGR_EXIF_EXPOSURE_MODE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_DIGITAL_ZOOM_RATIO,"Digital Zoom Ratio","STR_ID_FMGR_EXIF_DIGITAL_ZOOM_RATIO");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_SCENE_CAPTURE_TYPE,"Scene Capture Type","STR_ID_FMGR_EXIF_SCENE_CAPTURE_TYPE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_ID_FMGR_EXIF_NO_INFORMATION,"No Information","STR_ID_FMGR_EXIF_NO_INFORMATION");	
#endif
	/************************************************************/
	/*																				*/
	/*			Drive Option													*/
	/*																				*/
	/************************************************************/

   ADD_APPLICATION_MENUITEM2((MITEM_FMGR_DRIVE_OPTIONS,0,
   	MENU_FMGR_DRIVE_OPEN, 
   	MENU_FMGR_FOLDER_CREATE, 
		MENU_FMGR_DRIVE_FORMAT, 
#ifdef __FS_CHECKDRIVE_SUPPORT__		
		MENU_FMGR_DRIVE_CHECK,
#endif
#ifndef __MSDC_NOT_SUPPORT_HOT_PLUG__
		MENU_FMGR_DRIVE_UNMOUNT, 
#endif		
		MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_DRIVE_OPTION,0));

   ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_DRIVE_OPTIONS,0,3,
		MENU_FMGR_SELECT_DONE, MENU_FMGR_DRIVE_OPEN,
		MENU_FMGR_FOLDER_CREATE,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_DRIVE_OPTION,0));

	/************************************************************/
	/*																				*/
	/*			Folder Option													*/
	/*																				*/
	/************************************************************/

   ADD_APPLICATION_MENUITEM2((MITEM_FMGR_FOLDER_OPTIONS,0,
   	MENU_FMGR_GEN_OPTION_OPEN, 
   	MENU_FMGR_FOLDER_CREATE, 
      MENU_FMGR_GEN_OPTION_RENAME, 
      MENU_FMGR_GEN_OPTION_DELETE,
#ifdef __FS_SORT_SUPPORT__
      MENU_FMGR_GEN_OPTION_SORT, 
#endif      
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_FOLDER_OPTION,0));

   ADD_APPLICATION_MENUITEM((MITEM_FMGR_APP_FOLDER_OPTIONS,0,5,
		MENU_FMGR_SELECT_DONE, 
		MENU_FMGR_GEN_OPTION_OPEN, 
		MENU_FMGR_FOLDER_CREATE, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_FOLDER_OPTION,0));

	/************************************************************/
	/*																				*/
	/*			Tree Option														*/
	/*																				*/
	/************************************************************/

   ADD_APPLICATION_MENUITEM((MITEM_FMGR_TREE_OPTIONS,0,3,
		MENU_FMGR_TREE_SELECT, 
		MENU_FMGR_TREE_OPEN,
		MENU_FMGR_FOLDER_CREATE,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_FOLDER_OPTION,0));

	/************************************************************/
	/*																				*/
	/*			File Option														*/
	/*																				*/
	/************************************************************/

	/* Image files */
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_IMG_TYPE_OPTIONS,0,
		MENU_FMGR_IMG_OPTION_VIEW, 
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_JPG_IMG_TYPE_OPTIONS,0,
		MENU_FMGR_IMG_OPTION_VIEW, 
		MENU_FMGR_GEN_OPTION_JPG_DETAIL,
#ifdef __MMI_PHOTOEDITOR__
		MENU_FMGR_IMG_OPTION_EDIT,
#endif		
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
#if 0
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_JPG_DETAIL, MITEM_FMGR_JPG_IMG_TYPE_OPTIONS,0,
					SHOW,NONMOVEABLE,1,STR_FMGR_VIEW_IMG_JPG_DETAIL,0));
#endif

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_IMG_TYPE_NO_SIM_OPTIONS,0,
		MENU_FMGR_IMG_OPTION_VIEW, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	/* Audio files */
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_AUD_TYPE_OPTIONS,0,
		MENU_FMGR_AUD_OPTION_PLAY, 
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__				
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_AUD_TYPE_NO_FWD_OPTIONS,0,
		MENU_FMGR_AUD_OPTION_PLAY, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	/* Video files */
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_VID_TYPE_OPTIONS,0,
		MENU_FMGR_VID_OPTION_PLAY, 
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_VID_TYPE_NO_SIM_OPTIONS,0,
		MENU_FMGR_VID_OPTION_PLAY, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	/* Java files */
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_EXE_TYPE_OPTIONS,0,
		MENU_FMGR_EXE_OPTION_EXECUTE, 
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__				
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_EXE_TYPE_NO_SIM_OPTIONS,0,
		MENU_FMGR_EXE_OPTION_EXECUTE, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	
	/* downloadable theme files */
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__ //ritesh
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_THEME_TYPE_OPTIONS,0,
           MENU_FMGR_ACTIVATE_THEME, 
      MENU_FMGR_GEN_OPTION_DETAIL,
      MENU_FMGR_GEN_OPTION_RENAME,
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		      
		 MENU_FMGR_THEME_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
		MENU_ITEM_END,
		SHOW, NONMOVEABLE, DISP_LIST, STR_FMGR_THEME_OPTION,0));

	ADD_APPLICATION_MENUITEM((MENU_FMGR_ACTIVATE_THEME,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_THEMES_ACTIVATE,0));

	ADD_APPLICATION_MENUITEM((MENU_FMGR_THEME_DELETE,MITEM_FMGR_THEME_TYPE_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_DELETE,0));
#endif

	/* ebook files */
#ifdef __MMI_EBOOK_READER__
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_EBOOK_TYPE_OPTIONS,0,
      MENU_FMGR_EBK_OPTION_OPEN, 
      MENU_FMGR_GEN_OPTION_FORWARD,
      MENU_FMGR_GEN_OPTION_DETAIL,
      MENU_FMGR_GEN_OPTION_RENAME,
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		      
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
		MENU_ITEM_END,
		SHOW, NONMOVEABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_EBOOK_NO_FWD_TYPE_OPTIONS,0,
      MENU_FMGR_EBK_OPTION_OPEN, 
      MENU_FMGR_GEN_OPTION_DETAIL,
      MENU_FMGR_GEN_OPTION_RENAME,
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		      
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
		MENU_ITEM_END,
		SHOW, NONMOVEABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
		
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_EBOOK_NFO_TYPE_OPTIONS,0,2,
      MENU_FMGR_EBK_OPTION_OPEN, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		SHOW, NONMOVEABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MENU_FMGR_EBK_OPTION_OPEN,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_OPEN_EBOOK,0));

    ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_EBOOK_TYPE_OPTIONS,0,
          MENU_FMGR_EBK_OPTION_OPEN, 
          MENU_FMGR_GEN_OPTION_FORWARD,
          MENU_FMGR_GEN_OPTION_DETAIL,
          MENU_FMGR_GEN_OPTION_RENAME,
          MENU_FMGR_GEN_OPTION_DELETE, 
          MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
          MENU_FMGR_GEN_OPTION_SORT,
#endif		
          MENU_ITEM_END,
          SHOW, NONMOVEABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_EBOOK_NO_FWD_TYPE_OPTIONS,0,
      MENU_FMGR_EBK_OPTION_OPEN, 
      MENU_FMGR_GEN_OPTION_DETAIL,
      MENU_FMGR_GEN_OPTION_RENAME,
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
		MENU_ITEM_END,
		SHOW, NONMOVEABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));


#endif /* __MMI_EBOOK_READER__ */

	/* General files */
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_GEN_TYPE_OPTIONS,0,
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

   ADD_APPLICATION_MENUITEM2((MITEM_FMGR_GEN_TYPE_NO_SIM_OPTIONS,0,
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
#ifdef __FS_MOVE_SUPPORT__		
		MENU_FMGR_GEN_OPTION_COPY, 
		MENU_FMGR_GEN_OPTION_MOVE, 
#endif		
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__		
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	/* DRM files */
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_DRM_IMG_TYPE_OPTIONS,0,
		MENU_FMGR_IMG_OPTION_VIEW, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_DRM_AUD_TYPE_OPTIONS,0,
		MENU_FMGR_AUD_OPTION_PLAY, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
#if 0
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_DRM_VID_TYPE_OPTIONS,0,
		MENU_FMGR_VID_OPTION_PLAY, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
#endif
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_DRM_EXE_TYPE_OPTIONS,0,
		MENU_FMGR_EXE_OPTION_EXECUTE, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_DRM_GEN_TYPE_OPTIONS,0,
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
#if 0
	/* Download agent files */
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_IMG_TYPE_OPTIONS,0,2,
		MENU_FMGR_IMG_OPTION_VIEW, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_AUD_TYPE_OPTIONS,0,2,
		MENU_FMGR_AUD_OPTION_PLAY, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));
	
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_VID_TYPE_OPTIONS,0,2,
		MENU_FMGR_VID_OPTION_PLAY, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_EXE_TYPE_OPTIONS,0,2,
		MENU_FMGR_EXE_OPTION_EXECUTE, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_THM_TYPE_OPTIONS,0,2,
		MENU_FMGR_ACTIVATE_THEME, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_EBK_TYPE_OPTIONS,0,2,
		MENU_FMGR_EBK_OPTION_OPEN, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DA_QRV_TYPE_OPTIONS,0,2,
		MENU_ID_BARCODEREADER_TO_QRV_EDITOR, 
		MENU_FMGR_DA_OPTION_FORWARD, 
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM((MENU_FMGR_DA_OPTION_FORWARD,0,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_FORWARD,0));
#endif
#ifdef __DRM_SUPPORT__	
	/* DRM Right files Option*/
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_DRM_RIGHTS_OPTIONS,0,3,
		MENU_FMGR_DRM_RIGHTS_DETAIL, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_DRM_RIGHTS_DELETE_ALL_EXPIRED,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

    ADD_APPLICATION_MENUITEM((MENU_FMGR_DRM_RIGHTS_DETAIL,0,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_DETAIL,0));

    ADD_APPLICATION_MENUITEM((MENU_FMGR_DRM_RIGHTS_DELETE_ALL_EXPIRED,0,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_DRM_RIGHT_DELETE_ALL_EXPIRED,0));
#endif

	/********************* For reference only **********************************
	 ************ example of application file option for browse with SIM *************/
	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_TYPE_OPTIONS,0,
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL,
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__	 
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_IMG_TYPE_OPTIONS,0,
      MENU_FMGR_IMG_OPTION_VIEW,
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__	 
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_AUD_TYPE_OPTIONS,0,
      MENU_FMGR_AUD_OPTION_PLAY,
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__	 
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_EXE_TYPE_OPTIONS,0,
      MENU_FMGR_EXE_OPTION_EXECUTE,
		MENU_FMGR_GEN_OPTION_FORWARD, 
		MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__	 
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

	ADD_APPLICATION_MENUITEM2((MITEM_FMGR_APP_VID_TYPE_OPTIONS,0,
      MENU_FMGR_VID_OPTION_PLAY,
      MENU_FMGR_GEN_OPTION_FORWARD,
      MENU_FMGR_GEN_OPTION_DETAIL, 
		MENU_FMGR_GEN_OPTION_RENAME, 
		MENU_FMGR_GEN_OPTION_DELETE, 
		MENU_FMGR_GEN_OPTION_DELETE_ALL, 
#ifdef __FS_SORT_SUPPORT__	 
		MENU_FMGR_GEN_OPTION_SORT,
#endif		
      MENU_ITEM_END,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST, STR_FMGR_GEN_OPTION,0));

#ifdef __FS_MOVE_SUPPORT__			
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_COPY,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_COPY,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_GEN_OPTION_MOVE,MITEM_FMGR_GEN_TYPE_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_MOVE,0));
#endif

	/************************************************************/
	/*																				*/
	/*			Forward Option													*/
	/*																				*/
	/************************************************************/

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_IMG,MITEM_FMGR_GEN_TYPE_OPTIONS,	   
		MENU_FMGR_FWD_WALLPAPER, 
#ifdef __MMI_SUB_WALLPAPER__		
		MENU_FMGR_FWD_SUB_WALLPAPER,
#endif		
		MENU_FMGR_FWD_SCREENSAVER,
#ifdef __MMI_POWER_ON_OFF_DISPLAY__
      MENU_FMGR_FWD_POWER_ON,
      MENU_FMGR_FWD_POWER_OFF,
#endif          
		MENU_FMGR_FWD_PHB,	
#ifdef __MMI_MMS__		
		MENU_FMGR_FWD_MMS, 
#endif
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#if (defined( __MMI_MESSAGES_EMS__) && !defined (__MMI_FMGR_NO_FWD_SMS__))
		MENU_FMGR_FWD_EMS,
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
      MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_IMG_DRM,MITEM_FMGR_GEN_TYPE_OPTIONS,
		MENU_FMGR_FWD_WALLPAPER, 
#ifdef __MMI_SUB_WALLPAPER__		
		MENU_FMGR_FWD_SUB_WALLPAPER,
#endif
		MENU_FMGR_FWD_SCREENSAVER,
#ifdef __MMI_POWER_ON_OFF_DISPLAY__
		MENU_FMGR_FWD_POWER_ON, 
		MENU_FMGR_FWD_POWER_OFF,
#endif
		MENU_FMGR_FWD_PHB,	
      MENU_ITEM_END,		
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_AUD,MITEM_FMGR_GEN_TYPE_OPTIONS,
		MENU_FMGR_FWD_PROFILE,	
#ifdef __MMI_BG_SOUND_EFFECT__		
		MENU_FMGR_FWD_BGSOUND,		
#endif		
#ifdef __MMI_MMS__		
		MENU_FMGR_FWD_MMS, 
#endif
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#if (defined( __MMI_MESSAGES_EMS__) && !defined (__MMI_FMGR_NO_FWD_SMS__))
		MENU_FMGR_FWD_EMS,
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
      MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_AUD_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,
		MENU_FMGR_FWD_PROFILE,	
#ifdef __MMI_BG_SOUND_EFFECT__		
		MENU_FMGR_FWD_BGSOUND,		
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_VID,MITEM_FMGR_GEN_TYPE_OPTIONS,
#ifdef __MMI_INCOMING_CALL_VIDEO__         
         MENU_FMGR_FWD_PHB,
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
         MENU_FMGR_FWD_SCREENSAVER,
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
         MENU_FMGR_FWD_POWER_ON,
         MENU_FMGR_FWD_POWER_OFF,
#endif
#ifdef __MMI_MMS__
		MENU_FMGR_FWD_MMS,
#endif
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
      MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_VID_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,
#ifdef __MMI_INCOMING_CALL_VIDEO__         
      MENU_FMGR_FWD_PHB,
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
      MENU_FMGR_FWD_SCREENSAVER,
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
      MENU_FMGR_FWD_POWER_ON,
      MENU_FMGR_FWD_POWER_OFF,
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_VCARD,MITEM_FMGR_GEN_TYPE_OPTIONS,
		MENU_FMGR_FWD_PHB,
#if !defined (__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)
		MENU_FMGR_FWD_SMS,
#endif		
#ifdef __MMI_MMS__		
		MENU_FMGR_FWD_MMS, 
#endif
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
      MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VCARD_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,
	   1,
		MENU_FMGR_FWD_PHB,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_VCAL,MITEM_FMGR_GEN_TYPE_OPTIONS,
		MENU_FMGR_FWD_TODOLIST,
#if !defined (__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)
		MENU_FMGR_FWD_SMS,
#endif		
#ifdef __MMI_MMS__		
		MENU_FMGR_FWD_MMS, 
#endif
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
      MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_OPTION_VCAL_NO_SIM,MITEM_FMGR_GEN_TYPE_OPTIONS,
	   1,
		MENU_FMGR_FWD_TODOLIST,	
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_GEN,MITEM_FMGR_GEN_TYPE_OPTIONS,
#ifdef __MMI_MMS__		
		MENU_FMGR_FWD_MMS, 
#endif
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
      MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
#if 0
	/* Download agent fwd option */
	ADD_APPLICATION_MENUITEM2((MENU_FMGR_DA_FWD_OPTION_IMG,MENU_FMGR_DA_OPTION_FORWARD,
      MENU_FMGR_FWD_WALLPAPER, 
#ifdef __MMI_SUB_WALLPAPER__		
		MENU_FMGR_FWD_SUB_WALLPAPER,
#endif		
		MENU_FMGR_FWD_SCREENSAVER,
#ifdef __MMI_POWER_ON_OFF_DISPLAY__
      MENU_FMGR_FWD_POWER_ON,
      MENU_FMGR_FWD_POWER_OFF,
#endif
		MENU_FMGR_FWD_PHB,
#if 0		
#ifdef __MMI_MMS__		
/* under construction !*/
#endif
#ifdef __MMI_EMAIL__
/* under construction !*/
#endif
#if (defined( __MMI_MESSAGES_EMS__) && !defined (__MMI_FMGR_NO_FWD_SMS__))
/* under construction !*/
#endif
#ifdef __MMI_IRDA_SUPPORT__
/* under construction !*/
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
/* under construction !*/
#endif
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_DA_FWD_OPTION_AUD,MENU_FMGR_DA_OPTION_FORWARD,
      MENU_FMGR_FWD_PROFILE, 
#ifdef __MMI_BG_SOUND_EFFECT__		
		MENU_FMGR_FWD_BGSOUND,		
#endif		
#if 0
#ifdef __MMI_MMS__		
/* under construction !*/
#endif
#ifdef __MMI_EMAIL__
/* under construction !*/
#endif
#if (defined( __MMI_MESSAGES_EMS__) && !defined (__MMI_FMGR_NO_FWD_SMS__))
/* under construction !*/
#endif
#ifdef __MMI_IRDA_SUPPORT__
/* under construction !*/
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
/* under construction !*/
#endif
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_DA_FWD_OPTION_VID,MENU_FMGR_DA_OPTION_FORWARD,
#ifdef __MMI_INCOMING_CALL_VIDEO__         
      MENU_FMGR_FWD_PHB,
#endif         
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
      MENU_FMGR_FWD_SCREENSAVER,
#endif
#ifdef __MMI_POWER_ON_OFF_DISPLAY_VIDEO__
      MENU_FMGR_FWD_POWER_ON,
      MENU_FMGR_FWD_POWER_OFF,
#endif
#if 0
#ifdef __MMI_MMS__		
/* under construction !*/
#endif
#ifdef __MMI_EMAIL__
/* under construction !*/
#endif
#ifdef __MMI_IRDA_SUPPORT__
/* under construction !*/
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
/* under construction !*/
#endif
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_DA_FWD_OPTION_VCARD,MENU_FMGR_DA_OPTION_FORWARD,
      MENU_FMGR_FWD_PHB,
#if 0      
#if !defined (__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)      
/* under construction !*/
#endif      
#ifdef __MMI_MMS__		
/* under construction !*/
#endif
#ifdef __MMI_EMAIL__
/* under construction !*/
#endif
#ifdef __MMI_IRDA_SUPPORT__
/* under construction !*/
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
/* under construction !*/
#endif
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_DA_FWD_OPTION_VCAL,MENU_FMGR_DA_OPTION_FORWARD,
      MENU_FMGR_FWD_TODOLIST,
#if 0      
#if !defined (__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)      
/* under construction !*/
#endif      
#ifdef __MMI_MMS__		
/* under construction !*/
#endif
#ifdef __MMI_EMAIL__
/* under construction !*/
#endif
#ifdef __MMI_IRDA_SUPPORT__
/* under construction !*/
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
/* under construction !*/
#endif
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

	ADD_APPLICATION_MENUITEM2((MENU_FMGR_DA_FWD_OPTION_GEN,MENU_FMGR_DA_OPTION_FORWARD,
#ifdef __MMI_EMAIL__
		MENU_FMGR_FWD_EMAIL, 
#endif
#ifdef __MMI_IRDA_SUPPORT__
		MENU_FMGR_FWD_IRDA, 
#endif		
#ifdef __MMI_SUPPORT_BLUETOOTH__
		MENU_FMGR_FWD_BT,
#endif
		MENU_ITEM_END,
		SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));

    ADD_APPLICATION_MENUITEM2((MENU_FMGR_FWD_OPTION_MFH,MENU_FMGR_DA_OPTION_FORWARD,
          MENU_FMGR_FWD_WALLPAPER, 
          MENU_FMGR_FWD_SCREENSAVER,
#ifdef __MMI_POWER_ON_OFF_DISPLAY__
          MENU_FMGR_FWD_POWER_ON,
          MENU_FMGR_FWD_POWER_OFF,
#endif
          MENU_FMGR_FWD_PHB,
          MENU_ITEM_END,
            SHOW, MOVEABLEWITHINPARENT|INSERTABLE, DISP_LIST, STR_FMGR_FORWARD,0));
#endif
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_SMS,MENU_FMGR_FWD_OPTION_VCARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_SMS,0));
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_TODOLIST,MENU_FMGR_FWD_OPTION_VCAL,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_TODOLIST,0));
#ifdef __MMI_IRDA_SUPPORT__
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_IRDA,MENU_FMGR_FWD_OPTION_GEN,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_IRDA,0));
#endif
#if 0
#ifdef __MMI_BT_SUPPORT__
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_BT,MENU_FMGR_FWD_OPTION_GEN,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_BT,0));
#endif
#endif
#ifdef __MMI_MMS__
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_MMS,MENU_FMGR_FWD_OPTION_GEN,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_MMS,0));
#endif
#ifdef __MMI_MESSAGES_EMS__
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_EMS,MENU_FMGR_FWD_OPTION_GEN,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_EMS,0));
#endif
#ifdef __MMI_EMAIL__
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_EMAIL,MENU_FMGR_FWD_OPTION_GEN,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_EMAIL,0));
#endif
#ifdef __MMI_BG_SOUND_EFFECT__
	ADD_APPLICATION_MENUITEM((MENU_FMGR_FWD_BGSOUND,MENU_FMGR_FWD_OPTION_GEN,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_FMGR_BGSOUND,0));
#endif
	/************************************************************/
	/*																				*/
	/*			Sort Option														*/
	/*																				*/
	/************************************************************/
	
	ADD_APPLICATION_MENUITEM((MITEM_FMGR_EDITOR_OPTION,0,2,
		MENU_FMGR_EDITOR_DONE,
		MENU_FMGR_INPUT_METHOD,
		SHOW, NONMOVEABLE|INSERTABLE, DISP_LIST,STR_FMGR_REN_OPTION,IMG_GLOBAL_OPTIONS));

	/************************************************************/
	/*																				*/
	/*			Strings															*/
	/*																				*/
	/************************************************************/

   ADD_APPLICATION_STRING2(STR_FMGR_REMOVABLE_PLUGIN,"Card Plugged In", "STR_FMGR_REMOVABLE_PLUGIN");
	ADD_APPLICATION_STRING2(STR_FMGR_REMOVABLE_PLUGOUT,"Card Plugged Out", "STR_FMGR_REMOVABLE_PLUGOUT");
   
#ifdef __OTG_ENABLE__
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_OTG_UNSUPPORT,"OTG Unsupport", "STR_FMGR_OTG_UNSUPPORT");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_OTG_CONNECTING,"OTG Connecting", "STR_FMGR_OTG_CONNECTING");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_OTG_STOP_CONNECTING,"OTG Stop Connecting", "STR_FMGR_OTG_STOP_CONNECTING");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_OTG_NO_RESPONSE,"OTG No Response", "STR_FMGR_OTG_NO_RESPONSE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_OTG_HNP_PROCESS,"OTG HNP Processing", "STR_FMGR_OTG_HNP_PROCESS");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_OTG_HNP_STOP,"OTG HNP Stop", "STR_FMGR_OTG_HNP_STOP");
#endif

	ADD_APPLICATION_STRING2(STR_FMGR_TITLE,"File Manager", "STR_FMGR_TITLE");

   ADD_APPLICATION_STRING2(STR_FMGR_NAND_FLASH,"Phone", "STR_FMGR_NAND_FLASH");
   ADD_APPLICATION_STRING2(STR_FMGR_NOR_FLASH,"Phone Storage 2", "STR_FMGR_NOR_FLASH");
   ADD_APPLICATION_STRING2(STR_FMGR_REM_DEVICE,"Memory Card", "STR_FMGR_REM_DEVICE");
   ADD_APPLICATION_STRING2(STR_FMGR_DRM_RIGHTS,"DRM Rights", "STR_FMGR_DRM_RIGHTS");
   ADD_APPLICATION_STRING2(STR_FMGR_DRM_DATA,"DRM Content", "STR_FMGR_DRM_DATA");
#ifdef __SIM_PLUS__
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_FMGR_SIM_PLUS, "SIM+ Card", "STR_FMGR_SIM_PLUS");
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_FMGR_SIM_PLUS2, "SIM+ Card 2", "STR_FMGR_SIM_PLUS");
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_FMGR_SIM_PLUS3, "SIM+ Card 3", "STR_FMGR_SIM_PLUS");
//del by reslim v0.1    ADD_APPLICATION_STRING2(STR_FMGR_SIM_PLUS4, "SIM+ Card 4", "STR_FMGR_SIM_PLUS");    
#endif     
   
	ADD_APPLICATION_STRING2(STR_FMGR_FOLDER_OPTION,"Folder Option", "STR_FMGR_FOLDER_OPTION");
	ADD_APPLICATION_STRING2(STR_FMGR_GEN_OPTION,"File Option", "STR_FMGR_GEN_OPTION");

	ADD_APPLICATION_STRING2(STR_FMGR_FOLDER_CREATE, "Create Folder", "STR_FMGR_FOLDER_CREATE" );
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_FOLDER_RENAME, "Rename Folder", "STR_FMGR_FOLDER_RENAME" );
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_FOLDER_DELETE, "Delete Folder", "STR_FMGR_FOLDER_DELETE" );
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_DELETE_CONFIRM, "Delete", "STR_FMGR_FOLDER_DELETE" );
	ADD_APPLICATION_STRING2(STR_FMGR_OPEN,"Open", "STR_FMGR_OPEN");
	ADD_APPLICATION_STRING2(STR_FMGR_FORMAT,"Format", "STR_FMGR_FORMAT");
	ADD_APPLICATION_STRING2(STR_FMGR_CHECK_DRIVE,"Scan Disk", "STR_FMGR_CHECK_DRIVE");	
	ADD_APPLICATION_STRING2(STR_FMGR_FORMATING,"Formating", "STR_FMGR_FORMATING");
	ADD_APPLICATION_STRING2(STR_FMGR_FORMAT_CONFIRM,"This will erase Email, MMS... data. Continue?", "STR_FMGR_FORMAT_CONFIRM");	
	ADD_APPLICATION_STRING2(STR_FMGR_UNMOUNT,"Remove", "STR_FMGR_UNMOUNT");
	ADD_APPLICATION_STRING2(STR_FMGR_UNMOUNTING,"Removing", "STR_FMGR_UNMOUNT");
	ADD_APPLICATION_STRING2(STR_FMGR_TREE_SELECT,"Done", "STR_FMGR_TREE_SELECT");
	
	ADD_APPLICATION_STRING2(STR_FMGR_VIEW_IMG,"View", "STR_FMGR_VIEW_IMG");
	//ADD_APPLICATION_STRING2(STR_FMGR_VIEW_IMG_JPG_DETAIL,"Image Info", "STR_FMGR_VIEW_IMG_JPG_DETAIL");
	ADD_APPLICATION_STRING2(STR_FMGR_PLAY_AUDIO,"Play", "STR_FMGR_PLAY_AUDIO");
	ADD_APPLICATION_STRING2(STR_FMGR_PLAY_VIDEO,"Play", "STR_FMGR_PLAY_VIDEO");
	ADD_APPLICATION_STRING2(STR_FMGR_EXECUTE,"Install", "STR_FMGR_EXECUTE");
	
	ADD_APPLICATION_STRING2(STR_FMGR_SORT,"Sort", "STR_FMGR_SORT");
	ADD_APPLICATION_STRING2(STR_FMGR_FORWARD, "Forward", "STR_FMGR_FORWARD" );
	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL, "Detail", "STR_FMGR_DETAIL" );	
	ADD_APPLICATION_STRING2(STR_FMGR_RENAME, "Rename", "STR_FMGR_RENAME" );
	ADD_APPLICATION_STRING2(STR_FMGR_DELETING, "Deleting", "STR_FMGR_DELETING" );
	ADD_APPLICATION_STRING2(STR_FMGR_DELETE_ALL, "Delete All Files", "STR_FMGR_DELETE_ALL" );
	ADD_APPLICATION_STRING2(STR_FMGR_COPY,"Copy", "STR_FMGR_COPY");
	ADD_APPLICATION_STRING2(STR_FMGR_COPYING,"Copying", "STR_FMGR_COPY");
	ADD_APPLICATION_STRING2(STR_FMGR_MOVE,"Move", "STR_FMGR_MOVE");
	ADD_APPLICATION_STRING2(STR_FMGR_MOVING,"Moving", "STR_FMGR_MOVE");

//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL_DATE,"Date", "STR_FMGR_DETAIL_DATE");
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL_SIZE,"Size", "STR_FMGR_DETAIL_SIZE");	
#ifdef __DRM_SUPPORT__	
	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL_RIGHT,"Copyright", "STR_FMGR_DETAIL_RIGHT");
	ADD_APPLICATION_STRING2(STR_FMGR_DRM_PROTECTED,"Protected", "STR_FMGR_DRM_PROTECTED");
	ADD_APPLICATION_STRING2(STR_FMGR_DRM_NOT_PROTECTED,"Not Protected", "STR_FMGR_DRM_NOT_PROTECTED");
	ADD_APPLICATION_STRING2(STR_FMGR_DRM_UNLIMITED,"Unlimited", "STR_FMGR_DRM_UNLIMITED");	
	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL_COUNT,"Count", "STR_FMGR_DETAIL_COUNT");
	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL_START,"Start Time", "STR_FMGR_DETAIL_START");
	ADD_APPLICATION_STRING2(STR_FMGR_DETAIL_END,"End Time", "STR_FMGR_DETAIL_END");
	ADD_APPLICATION_STRING2(STR_FMGR_LSK_ACTIVATE,"Actv.", "STR_FMGR_LSK_ACTIVATE");
	ADD_APPLICATION_STRING2(STR_FMGR_REQ_RIGHTS,"Request Rights?", "STR_FMGR_REQ_RIGHTS");
	ADD_APPLICATION_STRING2(STR_FMGR_INVALID_REQ_RIGHTS,"Content Type Not Supported, Request Rights?", "STR_FMGR_INVALID_REQ_RIGHTS");
	ADD_APPLICATION_STRING2(STR_FMGR_DRM_RIGHT_DELETE_ALL_EXPIRED,"Delete All Expired", "STR_FMGR_DRM_RIGHT_DELETE_ALL_EXPIRED");
#endif

	ADD_APPLICATION_STRING2(STR_FMGR_WALLPAPER, "To Wallpaper", "STR_FMGR_WALLPAPER" );
	ADD_APPLICATION_STRING2(STR_FMGR_SUB_WALLPAPER, "To Sub Wallpaper", "STR_FMGR_SUB_WALLPAPER" );
	ADD_APPLICATION_STRING2(STR_FMGR_SCREENSAVER, "To Screen Saver", "STR_FMGR_SCREENSAVER" );
	ADD_APPLICATION_STRING2(STR_FMGR_POWER_ON, "To Power On Display", "STR_FMGR_POWER_ON" );
	ADD_APPLICATION_STRING2(STR_FMGR_POWER_OFF, "To Power Off Display", "STR_FMGR_POWER_OFF" );	
	ADD_APPLICATION_STRING2(STR_FMGR_PHB, "To PhoneBook", "STR_FMGR_PHB" );
	ADD_APPLICATION_STRING2(STR_FMGR_PROFILE, "To User Profile", "STR_FMGR_PROFILE" );
	ADD_APPLICATION_STRING2(STR_FMGR_SMS, "To SMS", "STR_FMGR_SMS" );
	ADD_APPLICATION_STRING2(STR_FMGR_TODOLIST, "To To Do List", "STR_FMGR_TODOLIST" );
#if (defined( __MMI_MESSAGES_EMS__) && !defined (__MMI_FMGR_NO_FWD_SMS__))
	ADD_APPLICATION_STRING2(STR_FMGR_EMS, "To EMS", "STR_FMGR_EMS" );
#endif
#ifdef __MMI_MMS__
	ADD_APPLICATION_STRING2(STR_FMGR_MMS,"To MMS", "STR_FMGR_MMS");
#endif
#ifdef __MMI_EMAIL__
	ADD_APPLICATION_STRING2(STR_FMGR_EMAIL, "To Email", "STR_FMGR_EMAIL" );
#endif
#ifdef __MMI_IRDA_SUPPORT__
	ADD_APPLICATION_STRING2(STR_FMGR_IRDA, "To Irda", "STR_FMGR_IRDA" );
#endif
#ifdef __MMI_SUPPORT_BLUETOOTH__
	ADD_APPLICATION_STRING2(STR_FMGR_BT, "To Bluetooth", "STR_FMGR_BT" );
#endif
#ifdef __MMI_BG_SOUND_EFFECT__
	ADD_APPLICATION_STRING2(STR_FMGR_BGSOUND, "To Backgound Sound", "STR_FMGR_BGSOUND" );
#endif

	ADD_APPLICATION_STRING2(STR_FMGR_SORT_BY_NAME, "By Name", "STR_FMGR_SORT_BY_NAME" );
	ADD_APPLICATION_STRING2(STR_FMGR_SORT_BY_TYPE, "By Type", "STR_FMGR_SORT_BY_TYPE" );
	ADD_APPLICATION_STRING2(STR_FMGR_SORT_BY_TIME, "By Time", "STR_FMGR_SORT_BY_TIME" );
	ADD_APPLICATION_STRING2(STR_FMGR_SORT_BY_SIZE, "By Size", "STR_FMGR_SORT_BY_SIZE" );
	ADD_APPLICATION_STRING2(STR_FMGR_SORT_NONE, "None", "STR_FMGR_SORT_NONE" );

	ADD_APPLICATION_STRING2(STR_FMGR_REN_OPTION, "Rename Option", "STR_FMGR_REN_OPTION" );
//del by reslim v0.1	ADD_APPLICATION_STRING2(STR_FMGR_FILENAME_EDITOR, "Name", "STR_FMGR_FILENAME_EDITOR" );
   
   ADD_APPLICATION_STRING2(STR_FMGR_INVALID_FORMAT, "Unsupported Format", "STR_FMGR_INVALID_FORMAT" );
   ADD_APPLICATION_STRING2(STR_FMGR_INVALID_EMS_FORMAT, "EMS file only", "STR_FMGR_INVALID_EMS_FORMAT" );
   ADD_APPLICATION_STRING2(STR_FMGR_INVALID_WALLPAPER_FORMAT, "BMP, JPEG, GIF file only", "STR_FMGR_INVALID_WALLPAPER_FORMAT" );   
   ADD_APPLICATION_STRING2(STR_FMGR_INVALID_WALLPAPER_FORMAT_NOJPG, "BMP, GIF file only", "STR_FMGR_INVALID_WALLPAPER_FORMAT" );   
//del by reslim v0.1   ADD_APPLICATION_STRING2(STR_FMGR_NO_DRM_RIGHTS, "No Rights", "STR_FMGR_NO_DRM_RIGHTS" );      
   ADD_APPLICATION_STRING2(STR_FMGR_EMPTY_FILENAME, "Empty filename", "STR_FMGR_EMPTY_FILENAME" );         
   
   ADD_APPLICATION_STRING2(STR_ID_FMGR_DRV_FREE_SPACE, "Free:", "STR_ID_FMGR_CATEGORY_FREE_SPACE" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_DRV_TOTAL_SPACE, "Total:", "STR_ID_FMGR_CATEGORY_FREE_SPACE" );

   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_DATE, "Date:", "STR_ID_FMGR_FILE_DATE" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_SIZE, "Size:", "STR_ID_FMGR_FILE_SIZE" );

//del by reslim v0.1   ADD_APPLICATION_STRING2(STR_ID_FMGR_DRIVE_PHONE, "[Phone]", "STR_ID_FMGR_DRV_PHONE" );
//del by reslim v0.1   ADD_APPLICATION_STRING2(STR_ID_FMGR_DRIVE_MEM_CARD, "[Memory Card]", "STR_ID_FMGR_DRV_MEM_CAR" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_EMPTY_FOLDER, "[Empty Folder]", "STR_ID_FMGR_EMPTY_FOLDER" );
	ADD_APPLICATION_STRING2(STR_ID_FMGR_INVALID_IMAGE_FORMAT, "[Invalid Format]", "STR_ID_FMGR_INVALID_IMAGE_FORMAT" );
	//ADD_APPLICATION_STRING2(STR_ID_FMGR_SYSTEM_BUSY_TO_DECODE, "[system too busy to decode]", "STR_ID_FMGR_SYSTEM_BUSY_TO_DECODE" );

   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_LIMIT_IMAGE_TOO_LARGE, "Image too large\nLimit", "STR_ID_FMGR_FILE_LIMIT_IMAGE_TOO_LARGE" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_LIMIT_VIDEO_TOO_LARGE, "Video too large\nLimit", "STR_ID_FMGR_FILE_LIMIT_VIDEO_TOO_LARGE" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_LIMIT_VIDEO_TOO_LONG, "Video too long\nLimit", "STR_ID_FMGR_FILE_LIMIT_VIDEO_TOO_LONG" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_LIMIT_FILE_TOO_LARGE, "File too large\nLimit", "STR_ID_FMGR_FILE_LIMIT_FILE_TOO_LARGE" );

   ADD_APPLICATION_STRING2(STR_ID_FMGR_IMAGE_TOO_LARGE_NO_DISPLAY, "Image too large\nUnable to decode", "STR_ID_FMGR_IMAGE_TOO_LARGE_NO_DISPLAY" );
   ADD_APPLICATION_STRING2(STR_ID_FMGR_FILE_TOO_LARGE_NO_DISPLAY, "File too large\nUnable to decode", "STR_ID_FMGR_FILE_TOO_LARGE_NO_DISPLAY" );
//del by reslim v0.1   ADD_APPLICATION_STRING2(STR_ID_FMGR_VIDEO_TOO_LARGE_NO_DISPLAY, "Video too large\nUnable to decode", "STR_ID_FMGR_VIDEO_TOO_LARGE_NO_DISPLAY" );
   ADD_APPLICATION_STRING2(STR_GLOBAL_POWER_ON_PROCESSING,"Power On Processing","Power On Processing");   
	/************************************************************/
	/*																				*/
	/*			Images															*/
	/*																				*/
	/************************************************************/

	/******** drive Big icon *********/
#ifndef __MMI_SLIM_FILE_MANAGER__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_0,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG0.gif", "Drive Free space 0%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_10,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG10.gif", "Drive Free space 10%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_20,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG20.gif", "Drive Free space 20%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_30,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG30.gif", "Drive Free space 30%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_40,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG40.gif", "Drive Free space 40%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_50,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG50.gif", "Drive Free space 50%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_60,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG60.gif", "Drive Free space 60%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_70,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG70.gif", "Drive Free space 70%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_80,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG80.gif", "Drive Free space 80%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_90,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG90.gif", "Drive Free space 90%" );

//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_SPACE_100,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG100.gif", "Drive Free space 100%" );

#endif

	/********* drive icon **********/
#ifdef __FS_CARD_SUPPORT__	
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_MEM_CARD,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_card.pbm", "mem card icon" );
#endif
//	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRIVE_PHONE,
//		CUST_IMG_PATH"/MainLCD/FileManager/FM_phone.gif", "phone icon" );

	/********* small icon *********/
#if defined(MEM_ULC_3216)
ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_FOLDER,
	CUST_IMG_PATH"/MainLCD/FileManager/FM_SIDIR.JPG", "folder icon" );

ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_FOLDERUP,
	CUST_IMG_PATH"/MainLCD/FileManager/FM_SIDIR.JPG", "folder icon" );
ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_UNKNOWN,
	CUST_IMG_PATH"/MainLCD/FileManager/FM_SIFILE.JPG", "unknown icon" );
#else
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_IMG,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIIMAGE.gif", "image icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_MSG,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIMSG.gif", "message icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_AUD,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIAUDIO.gif", "audio icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_FOLDER,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIFOLDER.gif", "folder icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_FOLDERUP,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIFOLDERUP.gif", "folder icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_UNKNOWN,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIUNKNOWN.gif", "unknown icon" );

#ifdef __MMI_VIDEO_PLAYER__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_VDO,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIvideo.gif", "video icon" );
#endif

#ifdef __J2ME__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_JAVA,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIJAVA.pbm", "java icon" );
#endif

#ifdef __MMI_VCARD__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_VCF,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIVCF.gif", "vcf icon" );
#endif

#ifdef __MMI_VCALENDAR__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_VCS,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIVCS.pbm", "vcs icon" );
#endif

#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_THEME,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIIMAGE.gif", "theme icon" );
#endif

#ifdef __MMI_SVG__
/* under construction !*/
/* under construction !*/
#endif


#ifdef __MMI_BARCODEREADER__
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_QRV,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_SIQRV.gif", "QRV icon" );
#endif

#ifdef __MMI_SWFLASH__
//del by reslim v0.1    ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_ICON_FILE_TYPE_SWFLASH,
//del cont.        CUST_IMG_PATH"/MainLCD/FileManager/FM_Sianimation.gif", "swflash icon" );
#endif

#endif
	/********* large icon **********/
#if defined(MEM_ULC_3216)
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_UNKNOWN,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIFILE.jpg", "unknown large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_FOLDER,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIFOLDER.gif", "folder large icon" );
#else
	/* image */
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_BMP,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIBMP.gif", "bmp large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_JPG,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIJPG.gif", "jpg large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_GIF,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIGIF.gif", "gif large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_PNG,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIPNG.gif", "png large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_WBMP,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIWBMP.gif", "wbmp large icon" );

#ifdef M3D_MMI_SUPPORT
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_M3D,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIM3D.gif", "m3d large icon" );
#endif /* M3D_MMI_SUPPORT */

	/* message */
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_EMS,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIEMS.gif", "ems large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_ANM,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIANM.gif", "anm large icon" );


	/* audio */
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_DAF,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIDAF.gif", "daf large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_IMY,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIIMY.gif", "imy large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_MID,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIMIDI.gif", "midi large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_WAV,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIWAV.gif", "wav large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_AMR,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIAMR.gif", "amr large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_AAC,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIAAC.gif", "aac large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_VM,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIVM.gif", "vm large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_AWB,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIAWB.gif", "awb large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_AIF,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIAIF.gif", "aif large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_AU,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIAU.gif", "au large icon" );

#if defined(MP4_CODEC) && defined(AAC_DECODE)
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_M4A,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIM4A.gif", "m4a large icon" );
#endif 


#ifdef __MMI_VIDEO_PLAYER__
	/* video */
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_3GP,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LI3GP.gif", "large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_MP4,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIMP4.gif", "large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_AVI,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIAVI.gif", "large icon" );	
#endif

	/* others */
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_UNKNOWN,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIUNKNOWN.gif", "unknown large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_FOLDER,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIFOLDER.gif", "folder large icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_FOLDERUP,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIFOLDERUP.gif", "folder up large icon" );
	
#ifdef __J2ME__	
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_JAD,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIJAD.gif", "jad large icon" );
	
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_JAR,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIJAR.gif", "jar large icon" );
#endif

#ifdef __MMI_VCARD__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_VCF,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIVCF.gif", "vcf large icon" );
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_CSV,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LICSV.gif", "csv large icon" );
#endif
																
#ifdef __MMI_VCALENDAR__
	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_VCS,
		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIVCS.gif", "vcs large icon" );
#endif

#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_THEME,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LITHM.gif", "theme large icon" );
#endif

#ifdef __MMI_SVG__
/* under construction !*/
/* under construction !*/
#endif

#ifdef __MMI_BARCODEREADER__
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_QRV,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIQRV.gif", "QRV icon" );
#endif

#ifdef __MMI_EBOOK_READER__ //Rajat
	ADD_APPLICATION_IMAGE2(IMG_EBOOK_FMGR_TXT_LARGE_TYPE,
		CUST_IMG_PATH"/MainLCD/FileManager/EBOOK_TXT.gif", "Text icon" );

	ADD_APPLICATION_IMAGE2(IMG_EBOOK_FMGR_PDB_LARGE_TYPE,
		CUST_IMG_PATH"/MainLCD/FileManager/EBOOK_PDB.gif", "PDB icon" );

	ADD_APPLICATION_IMAGE2(IMG_EBOOK_FMGR_TXT_SMALL_TYPE,
		CUST_IMG_PATH"/MainLCD/FileManager/EBOOK_SMALL_TXT.gif", "Text icon" );

	ADD_APPLICATION_IMAGE2(IMG_EBOOK_FMGR_PDB_SMALL_TYPE,
		CUST_IMG_PATH"/MainLCD/FileManager/EBOOK_SMALL_PDB.gif", "PDB icon" );
#endif

#ifdef __MMI_SWFLASH__
//del by reslim v0.1	ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_CMP,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LICMP.gif", "cmp large icon" );
#endif

    /* image for drm locked file */
#ifdef __DRM_SUPPORT__
//del by reslim v0.1    ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_DRM_LOCKED,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_DRM_LOCKED.gif", "locked img" );    
#endif /* __DRM_SUPPORT__ */

#ifdef __MMI_VIDEO_STREAM__
//del by reslim v0.1    ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_SDP,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LISDP.gif", "SDP large icon" );    
//del by reslim v0.1    ADD_APPLICATION_IMAGE2(IMG_ID_FMGR_FILE_TYPE_RAM,
//del cont.		CUST_IMG_PATH"/MainLCD/FileManager/FM_LIRAM.gif", "RAM large icon" );    
#endif
#endif /* MEM_ULC_3216 */
}
#endif /* __MMI_FILE_MANAGER__ */

#endif


