/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	mmiapi_sap.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *	MMI related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/
 ADD_MAG(MSG_ID_MMIAPI_ACTION_REGISTER_IND = MSG_ID_MMIAPI_CODE_BEGIN),
ADD_MAG(MSG_ID_MMIAPI_ACTION_NOTIFY_IND),
ADD_MAG(MSG_ID_MMIAPI_UNREAD_PUSH_ICON_IND),
ADD_MAG(MSG_ID_MMIAPI_MMS_IND),
ADD_MAG(MSG_ID_MMIAPI_DEVICE_GET_CTRL_REQ),
ADD_MAG(MSG_ID_MMIAPI_DEVICE_GET_CTRL_RSP),
ADD_MAG(MSG_ID_MMIAPI_DEVICE_PLAY_REQ),
ADD_MAG(MSG_ID_MMIAPI_DEVICE_PLAY_RSP),

// Remote procedure call
ADD_MAG(MSG_ID_MMIAPI_REMOTE_PROC_CALL_REQ),

// Short message Service
ADD_MAG(MSG_ID_MMIAPI_SMS_SEND_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_SEND_RSP),

ADD_MAG(MSG_ID_MMIAPI_SMS_IND),

ADD_MAG(MSG_ID_MMIAPI_SMS_REGISTER_PORT_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_REGISTER_PORT_RSP),

ADD_MAG(MSG_ID_MMIAPI_SMS_CHECK_INCOMING_MSG_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_CHECK_INCOMING_MSG_RSP),

ADD_MAG(MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_TIMESTAMP_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_TIMESTAMP_RSP),

ADD_MAG(MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_ADDRESS_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_ADDRESS_RSP),

ADD_MAG(MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_RSP),

ADD_MAG(MSG_ID_MMIAPI_SMS_GET_HOST_ADDRESS_REQ),
ADD_MAG(MSG_ID_MMIAPI_SMS_GET_HOST_ADDRESS_RSP),

// UI service
ADD_MAG(MSG_ID_MMIAPI_UI_ENTER_FULLSCREEN_EDITOR_REQ),
ADD_MAG(MSG_ID_MMIAPI_UI_ENTER_FULLSCREEN_EDITOR_RSP),
ADD_MAG(MSG_ID_MMIAPI_UI_ENTER_IDLE_SCREEN_REQ),
ADD_MAG(MSG_ID_MMIAPI_UI_ENTER_IDLE_SCREEN_RSP),
ADD_MAG(MSG_ID_MMI_READY_TO_IDLE_SCREEN_IND),

ADD_MAG(MSG_ID_MMIAPI_BACKLIGHT_CONTROL_REQ),
ADD_MAG(MSG_ID_MMIAPI_BACKLIGHT_CONTROL_RSP),

ADD_MAG(MSG_ID_MMIAPI_LED_CONTROL_REQ),
ADD_MAG(MSG_ID_MMIAPI_LED_CONTROL_RSP),

ADD_MAG(MSG_ID_MMI_SHOW_ASM_DIALOG_REQ),

ADD_MAG(MSG_ID_MMIAPI_CODE_END),


