/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
 /*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of COOLSAND Inc. (C) 2003
 *
 *******************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   med_sap.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   Media task related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

	/*------------------------MED_MSG_CODE_BEGIN ---------------*/
   		ADD_MAG(MSG_ID_MED_STARTUP_REQ=MSG_ID_MED_CODE_BEGIN),
		ADD_MAG(MSG_ID_MED_STARTUP_CNF),
		ADD_MAG(MSG_ID_MEDIA_GET_BUFFER_REQ),
		ADD_MAG(MSG_ID_MEDIA_FREE_BUFFER_REQ),
		ADD_MAG(MSG_ID_MEDIA_TEMP_1),
		ADD_MAG(MSG_ID_MEDIA_TEMP_2),

		ADD_MAG(MSG_ID_MED_AUD_CODE_BEGIN),
		ADD_MAG(MSG_ID_L4AUD_GET_AUDIO_MODE_REQ),
		ADD_MAG(MSG_ID_L4AUD_GET_AUDIO_MODE_CNF),
		ADD_MAG(MSG_ID_L4AUD_SET_AUDIO_MODE_REQ),
		ADD_MAG(MSG_ID_L4AUD_SET_AUDIO_MODE_CNF),
		ADD_MAG(MSG_ID_L4AUD_GPIO_DETECT_IND),
		ADD_MAG(MSG_ID_L4AUD_GET_AUDIO_PROFILE_REQ),
		ADD_MAG(MSG_ID_L4AUD_GET_AUDIO_PROFILE_CNF),
		ADD_MAG(MSG_ID_L4AUD_SET_AUDIO_PROFILE_REQ),
		ADD_MAG(MSG_ID_L4AUD_SET_AUDIO_PROFILE_CNF),
		ADD_MAG(MSG_ID_L4AUD_GET_AUDIO_PARAM_REQ),
		ADD_MAG(MSG_ID_L4AUD_GET_AUDIO_PARAM_CNF),
		ADD_MAG(MSG_ID_L4AUD_SET_AUDIO_PARAM_REQ),
		ADD_MAG(MSG_ID_L4AUD_SET_AUDIO_PARAM_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_GET_VOLUME_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_GET_VOLUME_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_VOLUME_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_VOLUME_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_GAIN_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_GAIN_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_DEVICE_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_DEVICE_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_BY_NAME_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_BY_NAME_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_BY_NAME_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_BY_NAME_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_BY_STRING_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_BY_STRING_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_BY_STRING_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_BY_STRING_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_TONE_SEQ_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_TONE_SEQ_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_TONE_SEQ_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_STOP_TONE_SEQ_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_DEMO_IMY_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_DEMO_IMY_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_PLAY_FINISH_IND),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_MUTE_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_MUTE_CNF),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_FIR_REQ),
		ADD_MAG(MSG_ID_L4AUD_AUDIO_SET_FIR_CNF),
		ADD_MAG(MSG_ID_L4AUD_SP_SET_INPUT_MODE_REQ),
		ADD_MAG(MSG_ID_L4AUD_SP_SET_INPUT_MODE_CNF),
		ADD_MAG(MSG_ID_L4AUD_SP_SET_MODE_REQ),
		ADD_MAG(MSG_ID_L4AUD_SP_SET_MODE_CNF),
		ADD_MAG(MSG_ID_L4AUD_SP_SET_BT_PATH_REQ),
		ADD_MAG(MSG_ID_L4AUD_SP_SET_BT_PATH_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_RECORD_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_RECORD_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_PLAY_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_PLAY_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_STOP_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_STOP_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_DELETE_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_DELETE_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_ABORT_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_ABORT_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_PAUSE_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_PAUSE_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_RESUME_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_RESUME_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_APPEND_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_APPEND_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_GET_INFO_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_GET_INFO_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_RENAME_REQ),
		ADD_MAG(MSG_ID_L4AUD_VM_RENAME_CNF),
		ADD_MAG(MSG_ID_L4AUD_VM_RECORD_FINISH_IND),
		ADD_MAG(MSG_ID_L4AUD_VM_PLAY_FINISH_IND),
		ADD_MAG(MSG_ID_AUD_VM_READ_DATA_IND),
		ADD_MAG(MSG_ID_AUD_VM_WRITE_DATA_IND),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_RECORD_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_RECORD_CNF),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_PLAY_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_PLAY_CNF),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_STOP_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_STOP_CNF),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_PAUSE_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_PAUSE_CNF),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_RESUME_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_RESUME_CNF),
		ADD_MAG(MSG_ID_AUD_MEDIA_READ_DATA_IND),
		ADD_MAG(MSG_ID_AUD_MEDIA_WRITE_DATA_IND),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_RECORD_FINISH_IND),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_PLAY_FINISH_IND),
		ADD_MAG(MSG_ID_AUD_MEDIA_PLAY_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_AUD_BLOCK_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_STORE_REQ),
		ADD_MAG(MSG_ID_L4AUD_MEDIA_RESTORE_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_SET_MUTE_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_MPLAY_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_MSTOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_SET_VIBRATOR_ENABLED_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_SET_EQUALIZER_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_GET_FILE_DATA_LENGTH_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_GET_FILE_DATA_PROGRESS_REQ),
		ADD_MAG(MSG_ID_MEDIA_AUD_SET_FILE_DATA_PROGRESS_REQ),
		ADD_MAG(MSG_ID_MED_AUD_CODE_END),

		ADD_MAG(MSG_ID_MED_CAM_CODE_BEGIN),
		ADD_MAG(MSG_ID_MEDIA_CAM_POWER_UP_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_POWER_DOWN_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_READY_IND),
		ADD_MAG(MSG_ID_MEDIA_CAM_PREVIEW_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_PREVIEW_FAIL_IND),
		ADD_MAG(MSG_ID_MEDIA_CAM_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_CAPTURE_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_SAVE_PHOTO),
		ADD_MAG(MSG_ID_MEDIA_CAM_SET_PARAM_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_SET_FLASH_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_CAPTURE_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_CAM_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_CAM_MD_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_MD_OPEN_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_MD_CLOSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_CAM_MD_WORK_IND),
		ADD_MAG(MSG_ID_MED_CAM_CODE_END),

		ADD_MAG(MSG_ID_MED_IMG_CODE_BEGIN),
		ADD_MAG(MSG_ID_MEDIA_IMG_DECODE_REQ),
		ADD_MAG(MSG_ID_MEDIA_IMG_DECODE_FINISH_IND),
		ADD_MAG(MSG_ID_MEDIA_IMG_DECODE_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_IMG_ENCODE_REQ),
		ADD_MAG(MSG_ID_MEDIA_IMG_ENCODE_FINISH_IND),
		ADD_MAG(MSG_ID_MEDIA_IMG_ENCODE_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_IMG_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_IMG_RESIZE_REQ),
		ADD_MAG(MSG_ID_MEDIA_IMG_RESIZE_DONE_IND),
		ADD_MAG(MSG_ID_MEDIA_IMG_TEMP_1),
		ADD_MAG(MSG_ID_MEDIA_IMG_TEMP_2),
		ADD_MAG(MSG_ID_MED_IMG_CODE_END),

		ADD_MAG(MSG_ID_MED_VID_CODE_BEGIN),
		ADD_MAG(MSG_ID_MEDIA_VID_PREVIEW_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_RECORD_REQ),
//chenheforjasperII
		ADD_MAG(MSG_ID_MEDIA_VIDREC_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_VIDREC_PAUSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VIDREC_RESUME_REQ),
		ADD_MAG(MSG_ID_MEDIA_VIDREC_PREVIEW_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_VIDREC_SET_PARAM_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_DISPLAY_SET_REQ),
//chenheforjasperII
		ADD_MAG(MSG_ID_MEDIA_VID_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_RECORD_FINISH_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_ENCODE_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_ENCODE_AUDIO_DATA_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_FILE_MERGE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_FILE_MERGE_DONE_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_OPEN_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_CLOSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_OPEN_FILE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_FILE_READY_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_CLOSE_FILE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_PLAY_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_PLAY_FINISH_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_PLAY_GET_PLAY_TIME_REQ),//guojianaddedforjaspervideoplayer
		ADD_MAG(MSG_ID_MEDIA_VID_PLAY_GET_PLAY_TIME_BLOCK_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_PLAY_TIME_IND),//guojianaddedforjaspervideoplayer
		ADD_MAG(MSG_ID_MEDIA_VID_DECODE_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_DECODE_AUDIO_DATA_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_PAUSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_DISPLAY_INTERFACE_REQ),//guojianaddedforGreenStonevideoplayer
		ADD_MAG(MSG_ID_MEDIA_VID_RESUME_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_SEEK_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_SEEK_DONE_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_SNAPSHOT_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_GET_INFO_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_GET_IFRAME_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_IFRAME_READY_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_ERROR_RECOVER_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_PLAY_RESTART_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_AUDIO_PLAY_FINISH_IND),
		ADD_MAG(MSG_ID_MEDIA_VID_SET_DISPLAY_REQ),
		ADD_MAG(MSG_ID_MEDIA_VID_TEMP_2),
		ADD_MAG(MSG_ID_MED_VID_CODE_END),

		ADD_MAG(MSG_ID_MED_TVO_CODE_BEGIN),
		ADD_MAG(MSG_ID_MEDIA_TVO_START_REQ),
		ADD_MAG(MSG_ID_MEDIA_TVO_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_TVO_SET_MODE_REQ),
		ADD_MAG(MSG_ID_MEDIA_TVO_TV_CONNECT_IND),
		ADD_MAG(MSG_ID_MEDIA_TVO_AV_CABLE_DETECT_IND),
		ADD_MAG(MSG_ID_MEDIA_TVO_TEMP_1),
		ADD_MAG(MSG_ID_MEDIA_TVO_TEMP_2),
		ADD_MAG(MSG_ID_MED_TVO_CODE_END),

		ADD_MAG(MSG_ID_MED_WEBCAM_CODE_BEGIN),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_START_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_START_CNF),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_PAUSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_RESUME_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_CAPTURE_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_ROTATE_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_ABORT_IND),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_ENCODE_REQ),
		ADD_MAG(MSG_ID_MEDIA_WEBCAM_TEMP_2),
		ADD_MAG(MSG_ID_MED_WEBCAM_CODE_END),

		ADD_MAG(MSG_ID_MED_MMA_CODE_BEGIN),
		ADD_MAG(MSG_ID_MEDIA_MMA_OPEN_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_CLOSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_PLAY_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_PAUSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_RESUME_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_START_TIME_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_STOP_TIME_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_RATE_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_TEMPO_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_PITCH_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_VOLUME_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SEND_LONG_MSG_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SEND_SHORT_MSG_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_OPEN_DEVICE_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_CLOSE_DEVICE_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_CHANNEL_VOLUME_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_PROGRAM_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_SET_DATA_REQ),
		ADD_MAG(MSG_ID_MEDIA_MMA_PLAY_EVENT_IND),
		ADD_MAG(MSG_ID_MEDIA_MMA_TEMP_1),
		ADD_MAG(MSG_ID_MEDIA_MMA_TEMP_2),
		ADD_MAG(MSG_ID_MEDIA_MMA_TEMP_3),
		ADD_MAG(MSG_ID_MED_MMA_CODE_END),

		ADD_MAG(MSG_ID_MEDIA_FMR_POWER_ON_REQ),
		ADD_MAG(MSG_ID_MEDIA_FMR_POWER_OFF_REQ),
		ADD_MAG(MSG_ID_MEDIA_FMR_SET_FREQ_REQ),
		ADD_MAG(MSG_ID_MEDIA_FMR_MUTE_REQ),
		ADD_MAG(MSG_ID_MEDIA_FMR_CHECK_IS_VALID_STOP_REQ),
		ADD_MAG(MSG_ID_MEDIA_FMR_CHECK_IS_VALID_STOP_CNF),
		ADD_MAG(MSG_ID_MEDIA_FMR_GET_SIGNAL_LEVEL_REQ),
		ADD_MAG(MSG_ID_MEDIA_FMR_GET_SIGNAL_LEVEL_CNF),

		ADD_MAG(MSG_ID_MEDIA_AUD_SET_HEADSET_MODE_OUTPUT_PATH),

	    ADD_MAG(MSG_ID_MEDIA_AUD_EQ_SET_MAGNITUDE_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_EQ_TURN_ON_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_EQ_TURN_OFF_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_SET_ATTR_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_PLAY_EVENT_IND),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_PLAY_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_STOP_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_PAUSE_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_RESUME_REQ),
	    ADD_MAG(MSG_ID_MEDIA_AUD_TTS_UPDATE_INFO_IND),

		ADD_MAG(MSG_ID_MEDIA_VR_GET_VERSION_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_GET_PARAM_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_SET_PARAM_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_INIT_RCG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_RCG_PROCESS_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_RCG_RESULT_IND),
		ADD_MAG(MSG_ID_MEDIA_VR_INIT_TRN_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_TRN_PROCESS_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_TRN_RESULT_IND),
		ADD_MAG(MSG_ID_MEDIA_VR_VOICE_IN_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_DEL_TAG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_CHECK_TAG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_SYNC_DB_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_PLAY_TAG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_GET_DIR_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_ADD_TAG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_ABORT_REQ),
		ADD_MAG(MSG_ID_MEDIA_VR_ABORT_IND),
		ADD_MAG(MSG_ID_MED_VR_CODE_END),

		ADD_MAG(MSG_ID_MEDIA_VRSI_INIT_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_ADD_TAGS_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_START_TRN_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_START_RCG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_PLAY_TAG_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_PLAY_TTS_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_GET_TAGNUM_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_GET_TAGINFO_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_DEL_TAGS_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_RESET_TAGS_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_SYNC_DB_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_ABORT_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_CLOSE_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_PROCESS_IND),
		ADD_MAG(MSG_ID_MEDIA_VRSI_TRN_PROMPT_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_TRN_RESULT_IND),
		ADD_MAG(MSG_ID_MEDIA_VRSI_RCG_PROMPT_REQ),
		ADD_MAG(MSG_ID_MEDIA_VRSI_RCG_RESULT_IND),
		ADD_MAG(MSG_ID_MEDIA_VRSI_ERR_IND),
		ADD_MAG(MSG_ID_MEDIA_VRSI_PLAY_TAG_FINISH_IND),
		ADD_MAG(MSG_ID_MEDIA_VRSI_PLAY_TTS_FINISH_IND),
		ADD_MAG(MSG_ID_MED_VRSI_CODE_END=MSG_ID_MEDIA_VRSI_PLAY_TTS_FINISH_IND),
		ADD_MAG(MSG_ID_MED_CODE_END = MSG_ID_MED_VRSI_CODE_END),
   
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_OPEN_REQ),
    		ADD_MAG(MSG_ID_MED_BT_AUDIO_CODE_START = MSG_ID_MEDIA_BT_AUDIO_OPEN_REQ),
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_OPEN_CNF),
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_OPEN_IND),
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_CLOSE_REQ),
   		ADD_MAG( MSG_ID_MEDIA_BT_AUDIO_CLOSE_CNF),
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_CLOSE_IND),
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_TURN_ON_REQ),
    		ADD_MAG(MSG_ID_MEDIA_BT_AUDIO_TURN_OFF_REQ),
    		ADD_MAG(MSG_ID_MED_BT_AUDIO_CODE_END = MSG_ID_MEDIA_BT_AUDIO_TURN_OFF_REQ),
    		ADD_MAG(MSG_ID_MEDIA_IN_PROC_CALL_REQ),
    		ADD_MAG(MSG_ID_MEDIA_BT_OPEN_CODEC_REQ),
    		ADD_MAG(MSG_ID_MEDIA_BT_CLOSE_CODEC_REQ),
    		ADD_MAG(MSG_ID_MEDIA_BT_CLOSE_CODEC_IND),

		ADD_MAG(MSG_ID_MEDIA_AUD_AE_REQ),

	/*------------------------MED_MSG_CODE_END -----------------*/


