#include "cs_types.h"
#include "custdatares.h"
#include "mmi_features.h" 

#ifdef __MMI_AB_REPEATER__

#include "stdc.h"
#include "customcfg.h"

#ifdef FIRST_PASS
#include "buildcfg.h"
#endif

#include "funandgamesdefs.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"

#include "abrepeaterdef.h"
void populateABRepeaterMenu(void)
{
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_TITLE, "AB Repeater", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABENTER_TITLE, "Enter AB", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_SWITCH, "Switch Screen", "AB Repeater String" );
	ADD_APPLICATION_STRING2(STR_ID_ABREPEAT_NO_CARD,"Drive Not Found", "AB Repeater String");
	ADD_APPLICATION_STRING2(STR_ID_ABREPEAT_STORAGE,"Storage", "AB Repeater String");
	ADD_APPLICATION_STRING2(STR_ID_ABREPEAT_STORAGE_PHONE,"Phone", "AB Repeater String");
	ADD_APPLICATION_STRING2(STR_ID_ABREPEAT_STORAGE_CARD,"Card", "AB Repeater String");
	
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_DISC_FULL, "Disc Full", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_OPEN_FILE_ERROR, "Can't Open", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_CANNOT_PAUSE, "Can't Pause", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_COMMAND_ERROR, "Failed To Play", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_DEVICE_BUSY, "Device Busy", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_BAD_FORMAT, "Bad Format", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_INVALID_FORMAT, "Invalid Format", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_NO_SPACE, "Exceed File Limit", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_ERROR, "Audio Content Error!!", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_UNSUPPORTED_CHANNEL, "Unsupported Channel", "AB Repeater String" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_UNSUPPORTED_FREQ, "Unsupported Frequency", "AB Repeater StringA" );
	ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_UNSUPPORTED_TYPE, "Unsupported Type", "AB Repeater String" );
    //ADD_APPLICATION_STRING2( STR_ID_ABREPEAT_BUILDING_CACHE, "Building Cache", "AB Repeater String" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_MAIN_SKIN1_BG, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_MAIN_BG.gif", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PROGRESS_BAR, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_progress_bar.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_INDICATOR, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_INDICATOR.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON0, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON0.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON1, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON1.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON2, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON2.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON3, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON3.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON4, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON4.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON5, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON5.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON6, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON6.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON7, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON7.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON8, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON8.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_BUTTON9, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_BUTTON9.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_ABSECTION_PLAYING, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_PLAY.pbm", "ab repeater image" );
	
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_ABSECTION_RECORDING, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_REC_UP.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_ABSECTION_RECORDING_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_REC_DOWN.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_AB_SETSECTION, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_SET_UP.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_AB_SETSECTION_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_SET_DOWN.pbm", "ab repeater image" );
	
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_AB_NONSETSECTION, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_NONSET_UP.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_AB_NONSETSECTION_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_SECTION_NONSET_DOWN.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_VOLUME, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_VOLUME.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_STOP_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_STOP_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_STOP_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_STOP_UP.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PROG_BAR_EMPTY, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_PROG_BAR_RECT_EMPTY.pbm", "ab repeater image" );
//	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PROG_BAR_FILL, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_PROG_BAR_RECT_FILL.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_FWD_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_FWD_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_FWD_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_FWD_UP.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REW_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REW_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REW_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REW_UP.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PAUSE_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_PAUSE_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PAUSE_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_PAUSE_UP.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PLAY_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_PLAY_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_PLAY_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_PLAY_UP.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REPEAT_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REPEAT_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REPEAT_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REPEAT_UP.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REPEAT_OFF_DOWN, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REPEAT_OFF_DOWN.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REPEAT_OFF_UP, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REPEAT_OFF_UP.pbm", "ab repeater image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_REPEAT_DISABLE, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_REPEAT_DISABLE.pbm", "ab repeater image" );
	
	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_SUBMENU_ICON, CUST_IMG_PATH"/MainLCD/ABRepeater/SB_ABrepeater.pbm", "ab repeater image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ABREPEAT_STORAGE, CUST_IMG_PATH"/MainLCD/ABRepeater/AB_STORAGE_ICON.pbm", "ab repeater image" );




	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEATER_MAIN, MAIN_MENU_MULTIMEDIA_MENUID, 0,
		SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, 0, STR_ID_ABREPEAT_TITLE, IMG_ID_ABREPEAT_SUBMENU_ICON ));
	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEATER_OPTION, 0,2, 
		MENU_ID_AB_REPEAT_ENTER,
		MENU_ID_AB_REPEAT_STORAGE,
		SHOW, NONMOVEABLE, 0, STR_ID_ABREPEAT_TITLE, 0 ));

	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEAT_ENTER, MENU_ID_AB_REPEATER_OPTION, 0,
		SHOW, MOVEABLEWITHINPARENT, 0, STR_ID_ABENTER_TITLE, 0 ));
		
	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEAT_EMPTY_FOLDER_OPTION, 0,1, 
		MENU_ID_AB_REPEAT_STORAGE,
		SHOW, MOVEABLEWITHINPARENT, 0, STR_ID_ABREPEAT_TITLE, 0 ));

	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEAT_STORAGE, 0,2, 
		MENU_ID_AB_REPEAT_PHONE,
		MENU_ID_AB_REPEAT_CARD,
		SHOW, MOVEABLEWITHINPARENT, 0, STR_ID_ABREPEAT_STORAGE, 0 ));

	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEAT_PHONE, MENU_ID_AB_REPEAT_STORAGE, 0,
		SHOW, MOVEABLEWITHINPARENT, 0, 0, 0 ));
	ADD_APPLICATION_MENUITEM((MENU_ID_AB_REPEAT_CARD, MENU_ID_AB_REPEAT_STORAGE, 0,
		SHOW, MOVEABLEWITHINPARENT, 0, 0, 0 ));

}

#endif
#endif /* __MMI_AB_REPEATER__ */


