/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *	 Res_AnalogTV.c
 *
 * Project:
 * --------
 *
 * Description:
 * ------------
 *  Generate AnalogTV Resources
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 *============================================================================
 ****************************************************************************/
#include "cs_types.h"
#include "custdatares.h"
#include "mmi_features.h" 

#include "stdc.h"
#include "customcfg.h"

#if defined(__MMI_ANALOGTV__)


#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "populateres.h"

// dependent headers for AudioPlayerDef.h"
#include "frameworkstruct.h"
#include "globalconstants.h"
#include "globalmenuitems.h"

#include "filemgr.h"
#ifdef __MMI_BI_DEGREE_MAIN_MENU_STYLE__
#include "mainmenudef.h"
#endif
#include "analogtvresdefs.h"
#include "imageviewerresdefs.h"
#include "messagesresourcedata.h"
#include "filemanagerdef.h"

void PopulateAnalogTVRes(void)
{
//menu tree	 XXX
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_MAIN, MAIN_MENU_MULTIMEDIA_MENUID, 0,
		SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, 0, STR_MENU_ID_ANALOGTV_MAIN, IMG_ID_ANALOGTV_MENU_ICON ));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION,0,4,
		MENU_ID_ANALOGTV_CHANNEL_LIST,
		MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,
		MENU_ID_ANALOGTV_OPTION_SEARCH_AREA,
		MENU_ID_ANALOGTV_OPTION_SETTING,
		//MENU_ID_ANALOGTV_OPTION_EFFECT,
		//MENU_ID_ANALOGTV_OPTION_RECORDER,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_GLOBAL_OPTIONS,0));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,MENU_ID_ANALOGTV_OPTION,2,
		MENU_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,
		MENU_ID_ANALOGTV_CHANNEL_MANUAL_SEARCH,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_LIST,MENU_ID_ANALOGTV_OPTION,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_LIST,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_ADD_USER_CHANNEL,MENU_ID_ANALOGTV_OPTION,0,	
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_OPTION_ADD_USER_CHANNEL,0));
	//For TV169
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_SEARCH_AREA,MENU_ID_ANALOGTV_OPTION, 0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_OPTION_SEARCH_AREA,0));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_EFFECT,MENU_ID_ANALOGTV_OPTION_SETTING,2,
		MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,
		MENU_ID_ANALOGTV_OPTION_EFFECT_COLOR_DEPTH,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_OPTION_EFFECT,0));
//	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_RECORDER,MENU_ID_ANALOGTV_OPTION,0,
//		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
//		STR_MENU_ID_ANALOGTV_OPTION_RECORDER,0));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_MANUAL_SEARCH,MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_MANUAL_SEARCH,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,MENU_ID_ANALOGTV_OPTION_CHANNEL_SELECT, 3,//2,//navy for tvs
		MENU_ID_ANALOGTV_CHANNEL_LIST_PLAY,
		MENU_ID_ANALOGTV_CHANNEL_LIST_RENAME,
		MENU_ID_ANALOGTV_CHANNEL_LIST_DELETE,//navy for tv
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,0));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED,MENU_ID_ANALOGTV_OPTION_CHANNEL_SELECT,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_OPTION,0,2,
		MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_PLAY,
		MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_RENAME,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,MENU_ID_ANALOGTV_OPTION_EFFECT,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_EFFECT_COLOR_DEPTH,MENU_ID_ANALOGTV_OPTION_EFFECT,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_OPTION_EFFECT_COLOR_DEPTH,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_LIST_PLAY,MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_LIST_PLAY,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_LIST_RENAME,MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_FMGR_RENAME,0));
	//navy for tv
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_LIST_DELETE,MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_GLOBAL_DELETE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_PLAY,MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_OPTION,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_PLAY,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_RENAME,MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_OPTION,0,
		SHOW,MOVEABLEACROSSPARENT|INSERTABLE|SHORTCUTABLE,DISP_LIST,
		STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_RENAME,0));

	//SETTING
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_OPTION_SETTING, MENU_ID_ANALOGTV_OPTION, 
	2,
	MENU_ID_ANALOGTV_SETTING_DELETE_ALL_CHANNEL,
//	MENU_ID_ANALOGTV_SETTING_STORAGE,
//	MENU_ID_ANALOGTV_OPTION_EFFECT,
        MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,
	SHOW,MOVEABLEACROSSPARENT|INSERTABLE,DISP_LIST,STR_MENU_ID_ANALOGTV_OPTION_SETTING, NULL));



	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_SETTING_STORAGE,MENU_ID_ANALOGTV_OPTION_SETTING,2,
		MENU_ID_ANALOGTV_SETTING_STORAGE_PHONE,
		MENU_ID_ANALOGTV_SETTING_STORAGE_CARD,
		SHOW, MOVEABLEWITHINPARENT|SHORTCUTABLE, DISP_LIST,STR_MENU_ID_ANALOGTV_SETTING_STORAGE,NULL));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_SETTING_STORAGE_PHONE ,MENU_ID_ANALOGTV_SETTING_STORAGE,0,
		SHOW, MOVEABLEWITHINPARENT|SHORTCUTABLE, DISP_LIST,STR_ID_IMGVIEW_STORAGE_PHONE,NULL));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_SETTING_STORAGE_CARD ,MENU_ID_ANALOGTV_SETTING_STORAGE,0,
		SHOW, MOVEABLEWITHINPARENT|SHORTCUTABLE, DISP_LIST,STR_ID_IMGVIEW_STORAGE_MEMORY_CARD,NULL));
	ADD_APPLICATION_MENUITEM((MENU_ID_ANALOGTV_SETTING_DELETE_ALL_CHANNEL,MENU_ID_ANALOGTV_OPTION_SETTING,0,
		SHOW, MOVEABLEWITHINPARENT|SHORTCUTABLE, DISP_LIST,STR_MENU_ID_ANALOGTV_SETTING_DELETE_ALL_CHANNEL,NULL));
	
//string resource		

	/***********AnalogTV App *************/
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_MAIN,	"TV", "[AnalogTV App Name]");

	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION,	"Option", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CHANNEL_SEARCH,	"Channel Search", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CHANNEL_SELECT,	"Select Channel", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_ADD_USER_CHANNEL,	"Add to My Channel", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SEARCH_AREA,	"Search Area", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_EFFECT,	"Play Effect", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SETTING,	"Setting", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_SETTING_STORAGE,	"Storage", "[AnalogTV App Name]");
//	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_RECORDER,	"Record", "[AnalogTV App Name]");

	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_AUTO_SEARCH,	"Auto Search", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_MANUAL_SEARCH,	"Manual Search", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_LIST,	"Channel List", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED,	"My channel", "[AnalogTV App Name]");
//For TV169	
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CHINA_AREA,	"China", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SHENZHEN_AREA,	"ShenZhen", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CHINA_TAIWAN_AREA,	"China Taiwan", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_EUROP_AREA,	"Europ", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_AMERICA_AREA,	"America", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CHINA_MACAO_AREA,	"China Macao", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_INDIA_AREA,	"India", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_PAKISTAN_AREA,	"Pakistan", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_INDONESIA_AREA,	"Indonesia", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_HONGKONG_AREA,	"HongKong", "[AnalogTV App Name]");
	/*ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_IRAN_AREA,	"Iran", "[AnalogTV App Name]");*/
	/*ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_IRAQ_AREA,	"Iraq", "[AnalogTV App Name]");*/
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_YEMEN_AREA,	"Yemen", "[AnalogTV App Name]");
	/*ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SAUDI_ARABIA_AREA,	"Saudi arabia", "[AnalogTV App Name]");*/
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_BAHRAIN_AREA,	"Bahrain", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_ABU_DHABI_AREA,	"Abu dhabi", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_KUWAIT_AREA,	"Kuwait", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_THAI_AREA,	"Thai", "[AnalogTV App Name]");
	/*ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_RUSSIAN_AREA,	"Russian", "[AnalogTV App Name]");*/
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_PORTUGAL_AREA,	"Portugal", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SPAIN_AREA,	"Spain", "[AnalogTV App Name]");
	/*ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_FRANCE_AREA,	"France", "[AnalogTV App Name]");*/
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_PHILIPINES_AREA,	"Philipines", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_MALAYSIA_AREA,	"Malaysia", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_VIETNAM_AREA,	"Vietnam", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_BRAZIL_AREA,	"Brazil", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_UK_AREA,	"United Kingdom", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SOUTH_AFRICA_AREA,	"South Africa", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_TURKEY_AREA,	"Turkey", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_SINGAPORE_AREA,	"Singapore", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CAMBODIA_AREA,	"Cambodia", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_LAOS_AREA,	"Laos", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_AFGHANISTA_AREA,	"Afghanista", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CANADA_AREA,	"Canada", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_KOREA_AREA,	"Korea", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_MEXICO_AREA,	"Mexio", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_CHILE_AREA,	"Chile", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_VENEZUELA_AREA,	"Venezuela", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_JAPAN_AREA,	"Japan", "[AnalogTV App Name]");
//add by xiang rong on 2009-2-23
#if 1//defined(TLG1120)	//change by Speed 2009.12.04
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_BURMA_AREA,	"Burma", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_RUSSIA_AREA,	"Russia", "[AnalogTV App Name]");
#endif
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_ARGENTINA_AREA,	"Argentina", "[AnalogTV App Name]");
	
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_EFFECT_BRIGHTNESS,	"Brightness", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_OPTION_EFFECT_COLOR_DEPTH,	"Color Depth", "[AnalogTV App Name]");

	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_LIST_PLAY,	"Play", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_LIST_RENAME,	"Rename", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_LIST_DELETE,	"Delete", "[AnalogTV App Delete]");
	
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_LIST_ADD_USER_CHANNEL,	"Add My Channel", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_PLAY,	"Play", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_USER_DEFINED_RENAME,	"Rename", "[AnalogTV App Name]");

	ADD_APPLICATION_STRING2(STR_ID_CHANNEL_NAME,	"Channel", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_CHANNEL_LIST_OPTION,	"Option", "[AnalogTV App Name]");
	
	ADD_APPLICATION_STRING2(STR_MENU_ID_ANALOGTV_SETTING_DELETE_ALL_CHANNEL,	"Delete All Channel", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_ID_ANALOGTV_ERROR_FULL,	"Full disk", "[AnalogTV App Name]");
	ADD_APPLICATION_STRING2(STR_GLOBAL_SNAPSHOTTING,	"Snapshot, saved to Image viewer", "Snapshot, saved to Image viewer"); /*renxing for snap*/

//image resource
#ifdef __T800_MAIN_MENU__
      ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_MENU_ICON, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/tv.gif", "analogTV");
#endif

	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_PANNEL_BG, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_MAIN.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_CHANNEL_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_CHANNEL_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_CHANNEL_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_CHANNEL_PRESSED.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_CHANNEL_PRE_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_CHANNEL_PRE_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_CHANNEL_PRE_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_CHANNEL_PRE_PRESSED.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_CHANNEL_NEXT_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_CHANNEL_NEXT_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_CHANNEL_NEXT_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_CHANNEL_NEXT_PRESSED.gif", "audio player image" );


	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_DEC_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_DEC_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_DEC_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_DEC_PRESSED.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_INC_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_INC_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_INC_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_INC_PRESSED.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL1, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL1.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL2, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL2.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL3, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL3.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL4, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL4.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL5, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL5.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL6, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL6.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_VOL_LEVEL7, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_VOL_LEVEL7.gif", "audio player image" );



	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_MY_CHANNEL_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_MY_CHANNEL_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_MY_CHANNEL_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_MY_CHANNEL_PRESSED.gif", "audio player image" );

       ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_BRIGHTNESS_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_BRIGHTNESS_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_BRIGHTNESS_WEAK, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_BRIGHTNESS_WEAK.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_BRIGHTNESS_HIGH, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_BRIGHTNESS_HIGH.gif", "audio player image" );

       ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_BRIGHTNESS_DEC_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_BRIGHTNESS_DEC_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_BRIGHTNESS_INC_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_BRIGHTNESS_INC_NORMAL.gif", "audio player image" );



	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_COL_DEPTH_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_COL_DEPTH_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_COL_DEPTH_WEAK, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_COL_DEPTH_WEAK.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_COL_DEPTH_HIGH, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_COL_DEPTH_HIGH.gif", "audio player image" );


	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_RECORD_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_RECORD_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_RECORD_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_RECORD_PRESSED.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_LSK_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_LSK_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_LSK_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_LSK_PRESSED.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_RSK_NORMAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_RSK_NORMAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_RSK_PRESSED, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_RSK_PRESSED.gif", "audio player image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_PANNEL_BG_SEARCH, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_PANNEL_BG_SEARCH.gif", "audio player image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SPEAKER_VOICE, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SPEAKER_VOICE.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SPEAKER_MUTE, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SPEAKER_MUTE.gif", "audio player image" );

	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SEARCH_PROGRESS_BG, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SEARCH_PROGRESS_BG.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SEARCH_PROGRESS_TIC, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SEARCH_PROGRESS_TIC.gif", "audio player image" );
	
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL0, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL_LEVEL0.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL1, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL_LEVEL1.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL2, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL_LEVEL2.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL3, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL_LEVEL3.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL4, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL_LEVEL4.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_ANALOGTV_SIGNAL5, CUST_IMG_PATH"/MainLCD/AnalogTV/Skin1/ANALOGTV_SIGNAL_LEVEL5.gif", "audio player image" );

}
#endif//DEVELOPER_BUILD_FIRST_PASS
#endif /* __MMI_ANALOGTV__  */



