//==============================================================================
//                                                                              
//            Copyright (C) 2003-2007, Coolsand Technologies, Inc.              
//                            All Rights Reserved                               
//                                                                              
//      This source code is the property of Coolsand Technologies and is        
//      confidential.  Any  modification, distribution,  reproduction or        
//      exploitation  of  any content of this file is totally forbidden,        
//      except  with the  written permission  of  Coolsand Technologies.        
//                                                                              
//==============================================================================

#ifndef _VOISP_MAP_H_
#define _VOISP_MAP_H_

#include "cs_types.h"

#include "voisp_version.h"
#include "vois_map.h"

#include "hal_map_engine.h"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_voisMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
EXPORT PROTECTED HAL_MAP_VERSION_T g_voisMapVersion;



// =============================================================================
// g_voisCtx
// -----------------------------------------------------------------------------
/// VoiS context, holding global variables, to be watched through CoolWatcher.
// =============================================================================
EXPORT PROTECTED VOIS_CONTEXT_T g_voisCtx;



#endif // _VOISP_MAP_

