/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * ScreenSaverDefs.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   This file is intends for Resource IDs for the FunAndGames Application
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/

/**************************************************************

	FILENAME	: ScreenSaverDefs.h

  	PURPOSE		: Resource IDs for the FunAndGames Application

 

 

	DATE		: 

**************************************************************/


#ifndef SCREENSAVERDEFS_H
#define SCREENSAVERDEFS_H

#include "mmi_features.h"   


typedef enum
{
	SCR_MAIN_SCREENSAVER = SCREENSAVER_BASE + 1,
	SCR_SCREENSAVER_SETTING,
	SCR_SCREENSAVER_SELECT,
	SCR_SCREENSAVER_SYSTEM_LIST,
	SCR_SCREENSAVER_DOWNLOAD_LIST,
	SCR_SCREENSAVER_VIEW,
	SCR_SCREENSAVER_DOWNLOAD_VIEW
}SCREENSAVER_SCR_ID;

typedef enum
{
	STR_SCR_SCREENSAVER_CAPTION = SCREENSAVER_BASE + 1,
	STR_SCR_SCREENSAVER_SETTINGS,
//	STR_SCR_SCREENSAVER_SELECT,
	SCR_SCREENSAVER_SETTING_CAPTION,
	STR_SCR_SCREENSAVER_SYSTEM,
	STR_SCR_SCREENSAVER_DOWNLOAD,
//	STR_SCREENSAVER_SELECT_CAPTION,
//	STR_VIEW_SCREENSAVER,
	STR_SCREENSAVER_VIEW_CAPTION,
	STR_NO_SCREENSAVER_AVAIL,
//	STR_SETTING_SCREENSAVER,
//	STR_SET_ACTIVE_SCREENSAVER,
	STR_SCREENSAVER_EMPTY,
//	STR_SCREENSAVER_OFF,
//	STR_SCREENSAVER_ON,
	STR_SCREENSAVER_5SEC,
	STR_SCREENSAVER_15SEC,
	STR_SCREENSAVER_30SEC,
	STR_SCREENSAVER_1MINUTE,
	STR_SCREENSAVER_STATUS,
	STR_SCREENSAVER_WAITING,
	STR_SCREENSAVER_SS1,
	STR_SCREENSAVER_SS2,
	STR_SCREENSAVER_SS3,
	STR_SCREENSAVER_SS4,
	STR_SCREENSAVER_SS5,
	STR_SCREENSAVER_SS6,
	STR_SCREENSAVER_SS7,
	STR_SCREENSAVER_SS8,
	STR_SCREENSAVER_SS9,
	STR_SCREENSAVER_SS10,
	STR_SCREENSAVER_SS11,
	STR_SCREENSAVER_SS12,
	STR_SCREENSAVER_SS13,
	STR_SCREENSAVER_SS14,
	STR_SCREENSAVER_SS15,
     STR_SCREENSAVER_SS16,
	STR_SCREENSAVER_ANALOG,
	STR_SCREENSAVER_DIGITAL,
#ifdef __MMI_THEMES_V2_SUPPORT__
	STR_SCREENSAVER_CURR_THEME,
#endif
	STR_SCREENSAVER_DISPLAY_TIME,
   	STR_IDLE_SS_DECODE_ERR,
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
	STR_SCREENSAVER_VIDEO1,
#else
    STR_SCREENSAVER_VIDEO1_dummy,
#endif	 //modified by lin for screen saver @20070628

}SCREENSAVER_STRING_ID;

typedef enum
{
	SCREENSAVER_1 = SCREENSAVER_BASE + 1,
	SCREENSAVER_2,
#if defined(__PROJECT_GALLITE_C01__)
	SCREENSAVER_3,
#endif
#if !defined( __MMI_RESOURCE_SLIM_ON_128X160__)
	SCREENSAVER_3,
	#if !defined( __MMI_RESOURCE_SLIM__)
	SCREENSAVER_4,
	SCREENSAVER_5,
	SCREENSAVER_6,
	SCREENSAVER_7,
	SCREENSAVER_8,
	SCREENSAVER_9,
	#endif
#endif
       SCREENSAVER_VIDEO_START,
	SCREENSAVER_VIDEO_MAX,
#ifdef __MMI_ANALOG_CLOCK__
       ANALOG_CLOCK = SCREENSAVER_BASE+21,
#endif

#ifdef __MMI_DIGITAL_CLOCK__
	DIGITAL_CLOCK = SCREENSAVER_BASE+22,
#endif
#ifdef __MMI_THEMES_V2_SUPPORT__
	CURRENT_THEME_SCREENSAVER = SCREENSAVER_BASE+24,
#endif
	IMAGE_SETTING_TIME,
	IMG_ID_DISPCHAR_DIGITAL_CLK,
#ifdef __MMI_SCREENSAVER_DISPLAY_VIDEO__
	SCREENSAVER_VIDEO1,
#else 
	SCREENSAVER_VIDEO1_dummy, //modified by lin for screen saver@20070628
#endif

}_DOWNLOAD_IMAGE_LIST;
#if !defined( __MMI_RESOURCE_SLIM_ON_128X160__)
#if !defined( __MMI_RESOURCE_SLIM__)	
#define MAX_SCREENSAVER_VIDEO	(SCREENSAVER_VIDEO_START-SCREENSAVER_9 -1)
#else
#define MAX_SCREENSAVER_VIDEO	(SCREENSAVER_VIDEO_START-SCREENSAVER_3 -1)
#endif
#else
#define MAX_SCREENSAVER_VIDEO	(SCREENSAVER_VIDEO_START-SCREENSAVER_2 -1)
#endif
#endif	// SCREENSAVERDEFS_H

