/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *	RichesDefs.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  Riches game id defines
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/

#ifndef RICHESDEFS_H
#define RICHESDEFS_H


typedef enum
{
	STR_GX_RICHES_GAME_NAME = GAME_RICHES_BASE+1,
	STR_GX_RICHES_HELP_DESCRIPTION,
	STR_GX_RICHES_EASY,
	STR_GX_RICHES_NORMAL,
	STR_GX_RICHES_HARD
}RICHES_STR_IDS;

typedef enum
{
	IMG_GX_RICHES_GAME_ICON = GAME_RICHES_BASE+1,
	IMG_GX_RICHES_BASKET, 
	IMG_GX_RICHES_OBJECT_APPLE,					// 10
	IMG_GX_RICHES_OBJECT_BOMB,					// 30
	IMG_GX_RICHES_OBJECT_GIFT,					// 100
	IMG_GX_RICHES_OBJECT_GOLDNOTE,				// 30
	IMG_GX_RICHES_OBJECT_SPIDER,				// 20
	IMG_GX_RICHES_OBJECT_ENERGY20,
	IMG_GX_RICHES_OBJECT_ENERGY40,
	IMG_GX_RICHES_OBJECT_ENERGY60,
	IMG_GX_RICHES_OBJECT_ENERGY80,
	IMG_GX_RICHES_OBJECT_ENERGY100,
	IMG_GX_RICHES_OBJECT_LEVEL,
	IMG_GX_RICHES_OBJECT_ANGLE,
	IMG_GX_RICHES_OBJECT_BATTERY20,
	IMG_GX_RICHES_OBJECT_DENONATOR,
	IMG_GX_RICHES_OBJECT_EVIL,
	IMG_GX_RICHES_OBJECT_MONEY,
	IMG_GX_RICHES_OBJECT_BATTERYFULL,
	IMG_GX_RICHES_OBJECT_THEIF,
	IMG_GX_RICHES_OBJECT_BAT,
	IMG_GX_RICHES_ENERGYBG,
	IMG_GX_RICHES_ENERGYBAR,
	IMG_GX_RICHES_BACKGROUND,
	IMG_GX_RICHES_BACKGROUND_TIMER,
	IMG_GX_RICHES_BACKGROUND_LEVEL,
	IMG_GX_RICHES_GOTEXT,
	IMG_GX_RICHES_GRADESMAP,
	IMG_GX_RICHES_GOPIC
}RICHES_IMG_IDS;

#endif /* RICHESDEFS_H */


