/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#ifndef __DECLARE__H_
#define __DECLARE__H_

#define		AND			&&
#define		NO_OF_VERTRAMES	2
#define		NO_OF_HORZFRAMES	2

#define		MAX_FILE_SIZE		2048000
#define		DEFAULT_IMAGE_PATH			_T("../../Customer/IMAGES/DEFAULT.BMP")
#define		CUSTOM_IMAGE_PATH			_T("../../Customer/IMAGES/CUSTOMIMAGES/")
#define		TEMP_IMAGES_PATH			_T("../../Customer/IMAGES/")
#define		FONT_FILES_PATH				_T("../../Customer/Customize/Fonts/")
#define		FONT_INCLUDE_FILES_PATH		_T("../../Customer/CustResource/")
#define		SMALL				_T("Small")
#define		MEDIUM				_T("Medium")
#define		LARGE				_T("Large")

#define	DELETE_MEM(x) if(x) delete x; x=NULL;

#define LOG_MESSAGE(x)	
#define	DELETE_MEM_ARR(x) if(x) delete [] x; x=NULL;
#define FREE_LIST(x)	if(x)\
						{		\
							int iCount = ((CPtrList*)x)->GetCount();\
							while(iCount)\
							{\
								LPVOID pNodeInfo = (LPVOID)((CPtrList*)x)->RemoveHead();\
								DELETE_MEM(pNodeInfo);\
								iCount--;\
							}\
							delete x; x=NULL;\
						}

enum PANE_TYPE{LOG_PANE,LEFT_TREE_PANE,THEME_PANE,LANG_PANE};
enum MESSAGE_TYPE{ ERROR_MESSAGE = 0,INFORMATION_MESSAGE,INFORMATION_STRING_MESSAGE};


enum ERR{SUCCESS =0,FAILURE,UNSUFFICIENT_SIZE,CD_NOT_OPENFILE,ALREADY_EXISTS,OVERLAPPING_RANGE};


// wangbei del start 20060724
//typedef	unsigned char	BYTE;
//typedef	unsigned short	UINT16;
//typedef	short			INT16;
//typedef	BYTE			UINT8;
//typedef char			INT8;
// wangbei del end
typedef unsigned long	ULONG;

typedef void (*MMI_CALLBACK)(void*);
#endif

