// THIS FILE HAS BEEN CREATED WITH COOL PROFILE --- PLEASE DO NOT EDIT
#ifndef COOL_PROFILE_LCDD_PROFILE_CODES_H
#define COOL_PROFILE_LCDD_PROFILE_CODES_H


#define CP_lcdd_TransferData 0x1280
#define CP_LCDD_TRANSFER_START_REDO 0x3138
#define CP_lcdd_BlitWin 0x3930



#endif
