/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  CommonScreensenum.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

/**************************************************************

	FILENAME	: CommonScreensenum.h

  	PURPOSE		: This file defines enum value for global resources used in Common Screens.

 

	AUTHOR		: CSD00866

	DATE		: 05-23-2005

**************************************************************/
#ifndef __COMMONSCREENSENUM_H__
#define __COMMONSCREENSENUM_H__

#include "globaldefs.h"
#define COMMON_SCREENS_BASE		(DEMO_APP_BASE+340)

#ifdef __cplusplus
extern "C"
{
#endif
typedef enum {
	SCR_INPUT_METHOD_LIST=COMMON_SCREENS_BASE,
	SCR_SYMBOL_PICKER_SCREEN,
	SCR_INPUT_METHOD_AND_DONE,
	SCR_POPUP_SCREEN,
	SCR_CONFIRM_SCREEN,
	SCR_CONFIRM_WINDOW_SCREEN,
	SCR_QUICK_SEARCH_INPUT_METHOD_LIST,
      SCR_IN_LINE_MULTI_LINE_INPUT_METHOD_AND_DONE,
	SCR_ID_ASM_MEM_FULL
} SCREENID_LIST_COMMON_SCREENS;

typedef enum {
	//STR_INPUT_METHOD_CAPTION=COMMON_SCREENS_BASE,==> replaced by Global String
	STR_INPUT_METHOD_MENU_MULTITAP_ABC=COMMON_SCREENS_BASE,
	STR_INPUT_METHOD_MENU_MULTITAP_abc,
	STR_INPUT_METHOD_MENU_SMART_ABC,
	STR_INPUT_METHOD_MENU_SMART_abc,
	STR_INPUT_METHOD_MENU_NUMERIC,
	STR_INPUT_METHOD_MENU_MULTITAP_BOPOMO,
	STR_INPUT_METHOD_MENU_BOPOMO,
	STR_INPUT_METHOD_MENU_TRADITIONAL_CHINESE_STROKE,
	STR_INPUT_METHOD_MENU_MULTITAP_PINYIN,
	STR_INPUT_METHOD_MENU_PINYIN,
	STR_INPUT_METHOD_MENU_SIMPLIFIED_CHINESE_STROKE,
	STR_INPUT_METHOD_MENU_INSERT_SYMBOLS,
	STR_INPUT_METHOD_MENU_SELECT_SYMBOL,
	STR_INPUT_METHOD_MENU_MULTITAP_HINDI,
	STR_INPUT_METHOD_MENU_SMART_HINDI,
	STR_INPUT_METHOD_MENU_MULTITAP_U_SPANISH,
	STR_INPUT_METHOD_MENU_MULTITAP_L_SPANISH,
 
	STR_INPUT_METHOD_MENU_MULTITAP_U_DANISH,
	STR_INPUT_METHOD_MENU_MULTITAP_L_DANISH,
	STR_INPUT_METHOD_MENU_SMART_U_DANISH,
	STR_INPUT_METHOD_MENU_SMART_L_DANISH,
 
	STR_INPUT_METHOD_MENU_MULTITAP_U_FRENCH,
	STR_INPUT_METHOD_MENU_MULTITAP_L_FRENCH,
	STR_INPUT_METHOD_MENU_SMART_U_FRENCH,
	STR_INPUT_METHOD_MENU_SMART_L_FRENCH,
	STR_INPUT_METHOD_MENU_MULTITAP_U_GERMAN,
	STR_INPUT_METHOD_MENU_MULTITAP_L_GERMAN,
	STR_INPUT_METHOD_MENU_MULTITAP_U_RUSSIAN,
	STR_INPUT_METHOD_MENU_MULTITAP_L_RUSSIAN,
	STR_INPUT_METHOD_MENU_SMART_U_RUSSIAN,
	STR_INPUT_METHOD_MENU_SMART_L_RUSSIAN,
	STR_INPUT_METHOD_MENU_MULTITAP_THAI,
	STR_INPUT_METHOD_MENU_MULTITAP_ARABIC,
	STR_INPUT_METHOD_MENU_SMART_THAI,
	STR_INPUT_METHOD_MENU_SMART_ARABIC,
	STR_INPUT_METHOD_MENU_SMART_PERSIAN,
	STR_INPUT_METHOD_MENU_MULTITAP_U_TURKISH,
	STR_INPUT_METHOD_MENU_MULTITAP_L_TURKISH,
	STR_INPUT_METHOD_MENU_SMART_U_TURKISH,
	STR_INPUT_METHOD_MENU_SMART_L_TURKISH,
	STR_INPUT_METHOD_MENU_MULTITAP_U_PORTUGUESE,
	STR_INPUT_METHOD_MENU_MULTITAP_L_PORTUGUESE,
	STR_INPUT_METHOD_MENU_SMART_U_PORTUGUESE,
	STR_INPUT_METHOD_MENU_SMART_L_PORTUGUESE,
	STR_INPUT_METHOD_MENU_MULTITAP_U_INDONESIAN,
	STR_INPUT_METHOD_MENU_MULTITAP_L_INDONESIAN,
	STR_INPUT_METHOD_MENU_SMART_U_INDONESIAN,
	STR_INPUT_METHOD_MENU_SMART_L_INDONESIAN,
	STR_INPUT_METHOD_MENU_MULTITAP_U_MALAY,
	STR_INPUT_METHOD_MENU_MULTITAP_L_MALAY,
	STR_INPUT_METHOD_MENU_SMART_U_MALAY,
	STR_INPUT_METHOD_MENU_SMART_L_MALAY,
	STR_INPUT_METHOD_MENU_MULTITAP_U_VIETNAMESE,
	STR_INPUT_METHOD_MENU_MULTITAP_L_VIETNAMESE,
	STR_INPUT_METHOD_MENU_SMART_U_VIETNAMESE,
	STR_INPUT_METHOD_MENU_SMART_L_VIETNAMESE,
//START 
#if defined(__MMI_LANG_HINDI__)
	STR_INPUT_METHOD_MENU_SELECT_VOWEL,
#endif
//END 
	/* please insert before here */
	STR_INPUT_METHOD_MENU_TOTAL,
#ifdef APPMEM_SUPPORT
	STR_ID_ASM_MEM_FULL_1,
	STR_ID_ASM_MEM_FULL_2,
	STR_ID_ASM_MEM_FULL_3,
	STR_ID_ASM_MEM_FULL_TITLE,
#endif /* APPMEM_SUPPORT */
	STR_INPUT_METHOD_MENU_MULTITAP_PERSIAN,
	STR_INPUT_METHOD_MENU_SMART_URDU,
	STR_INPUT_METHOD_MENU_MULTITAP_MYANMAR,
	STR_INPUT_METHOD_MENU_SMART_TAMIL,
	STR_INPUT_METHOD_MENU_SMART_BENGALI,
	STR_INPUT_METHOD_MENU_SMART_PUNJABI,
	STR_ID_COMMONSCREEN_STR_END
} STRINGID_LIST_COMMON_SCREENS;
#ifdef __cplusplus
}
#endif
#endif

