/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	XXX.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *   This file is intends for ¡K.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/

/**************************************************************

	FILENAME	: Calls_Defs.h

  	PURPOSE		: Call application 

 

	DATE		: Jan 15,02

**************************************************************/

#ifndef _COOLSAND_CALLHISTORYENUM_H
#define _COOLSAND_CALLHISTORYENUM_H

#define CALL_LOG_RESULT_OK    L4C_OK
#define CALL_LOG_RESULT_FAIL  L4C_ERROR

typedef enum
{
   ITEM_NONE,
   ITEM_DIALED_CALL,
   ITEM_MISSED_CALL,
   ITEM_RECVD_CALL,
   ITEM_REJECTED_CALL,
   ITEM_MIXED_CALL
} CALL_LOG_ITEM;

typedef enum {
	CALL_LOG_PROC_NONE,
	CALL_LOG_PROC_READ,
	CALL_LOG_PROC_WRITE,
	CALL_LOG_PROC_SYNC
} CALL_LOG_PROCESS_ENUM;

typedef enum {
IMG_SCR_CALL_HISTORY_MAIN_MENU_CAPTION	= CALL_HISTORY+1,
IMG_SCR_CALL_COST_MAIN_CAP		,
IMG_SCR_CALL_COST_PRICEANDUNIT_SET_CAPTION		,
IMG_SCR_MAX_COST_GET_CAPTION					,
IMG_MENU_CALL_TIMES,
IMG_SCR8520_CAPTION,
IMG_SCR8008_CAPTION,
IMG_SCR8006_CAPTION,
IMG_SCR8054_CAPTION,
IMG_SCR8055_CAPTION,
IMG_SCR8056_CAPTION,
IMG_SCR8057_CAPTION,
IMG_SCR_RESETCALLS_CONFIRM ,
IMG_MENU8101_RECEIVED_CALLS,
IMG_MENU8102_DIALED_CALLS,
IMG_MENU8103_MISSED_CALLS,
MISSED_LSK_ICN,
IMG_CM_STATE_MISSED,
IMG_MENU_RECEIVED_CALLS,
IMG_SCR_RESETCALLS,
IMG_MENU_DIALED_CALLS,
IMG_MENU_MISSED_CALLS,
IMG_SCR8069_CAPTION,
IMG_SCR8070_CAPTION,
IMG_SCR8071_CAPTION,
IMG_SCR8072_CAPTION,
IMG_SMS_COUNTER_MENU ,
#ifdef __MMI_GPRS_FEATURES__
IMG_GPRS_COUNTER_MENU,
#endif
IMG_CALL_COST_MAIN_MENU,
IMG_CALL_TIMES_MAIN_MENU,
IMG_QUICK_END_MAIN_MENU,
IMG_TIME_ENTRY,
IMG_DATE_ENTRY,
IMG_NAME_ENTRY,
IMG_NUMBER_ENTRY,
IMG_COUNT_ENTRY,
IMG_ID_CHIST_DURATION,
#ifdef __MMI_UI_CALL_LOG_IN_TAB_PANE__
TAB_MIXED_CALLS,
TAB_MISSED_CALLS,
TAB_RECIEVED_CALLS,
TAB_DIALED_CALLS,
#endif
IMG_MENU8104_REJECTED_CALLS,
#ifdef __MMI_MULTI_SIM__
IMG_CALL_SIM_SELECT_CAPTION,
#endif
} CALL_HISTORY_IMG ;

typedef enum {
STR_SCR_CALL_HISTORY_MAIN_MENU_CAPTION  = CALL_HISTORY+1 ,
STR_MENU_CALL_COST_MAIN			,
STR_MENU_CALL_COST_LASTCALL		,
STR_MENU_CALL_COST_ALLCOST		,
STR_MENU_CALL_COST_RESETCOUNTER,
STR_MENU_CALL_COST_MAXCOUNT	,
STR_MENU_CALL_COST_PRICEUNIT	,
STR_ALL_CALL_COSTS_ERROR_MSG					,
STR_MENU_CALL_COST_PRICEANDUNIT_SET_PRICE,
STR_MENU_CALL_COST_PRICEANDUNIT_SET_UNIT,
STR_CALL_COST_PRICEANDUNIT_VIEW_LSK				,
STR_MENU_SCR_CALL_COST_PRICEANDUNIT_SET		,
STR_MAX_COST_SET_CAPTION						,
STR_SCR8069_CAPTION						,
STR_SCR8069_CAPTION1,
STR_RECD_SAVE_MENUENTRY					,
STR_SCR8070_CAPTION				,
STR_DIALED_SAVE_MENUENTRY		,
STR_SCR8071_CAPTION			,
STR_RejectedSCR_CAPTION			,
STR_MISSED_SAVE_MENUENTRY		,
STR_EMPTY_LIST_NOTIFICATION	,
STR_SCR8008_CAPTION			,
STR_SCR8006_CAPTION			,
STR_SCR8520_CAPTION			,
STR_SCR8054_CAPTION			,
STR_SCR8055_CAPTION			,
STR_SCR8056_CAPTION			,
STR_SCR8057_CAPTION    ,
STR_MENU8101_RECEIVED_CALLS	,
STR_MENU8102_DIALED_CALLS		,
STR_MENU8103_MISSED_CALLS		,
STR_MENU_RECEIVED_CALLS	,
STR_MENU_DIALED_CALLS		,
STR_MENU_MISSED_CALLS		,
STR_MISSED_CALL,
STR_MISSED_CALLS,
MISSED_LSK_STR,
STR_UNKNOWN_NUMBER,
STR_NO_NUMBER,
STR_NO_ENTRY,
STR_ENTRIES,
STR_TIMES,
STR_SCR_RESETCALLS_CONFIRM_CAPTION		,
STR_MENU8113_CALLHISTORY_RESETCALL		,
STR_SMS_CAPTION				,
STR_SENT_SMS_COUNT			,
STR_RECV_SMS_COUNT			,
STR_SCR_RESET_RCVD_SMS_CONFIRM_TEXT,
STR_SMS_COUNTER_LSK			,
STR_SMS_NO_NUMBER,
STR_SMS_STRING,
#ifdef __MMI_GPRS_FEATURES__
 STR_GPRS_CAPTION				,
 STR_GPRS_LAST_SENT			,	
 STR_GPRS_LAST_RECEIVED		,	
 STR_GPRS_ALL_SENT			,	
 STR_GPRS_ALL_RECEIVED		,	
 STR_GPRS_RESET_COUNTER		,
#endif
STR_MENU_LAST_CALL_TIME			,
STR_MENU_CALL_OUT_TIME			,
STR_MENU_CALL_IN_TIME			,
STR_MENU_ALL_CALL_TIME			,
STR_RESET_ALL_CALL_TIME,
STR_RESET_ALL_CALL_TIME_CONFIRM,
STR_MENU_CALL_TIME_SETUP		,
STR_MENU_QUICK_END,
STR_MENU_QUICK_END_SET,
STR_MENU_QUICK_END_DURATION,
STR_ENTRY_DELETED_CONFIRM,
STR_NONUMBER_TO_DIAL,
STR_CALLS_IN_PROGRESS_TEXT,
STR_MENU_ADD_TO_BLACKLIST,  //24615
STR_MENU_REJECT_CALL,
STR_MENU_BLACK_CALL,
} CALL_HISTORY_STRING ;
#if 0
typedef enum {
  MENU_CALL_HISTORY_MAIN_MENU = CALL_HISTORY+1 ,
  MISSED_CALL_MENU_ADD_TO_BLACKLIST,  //24552
  RECEIVED_CALL_MENU_ADD_TO_BLACKLIST, 
  DIALED_CALL_MENU_ADD_TO_BLACKLIST  
}CALL_HISTORY_MENU;
#endif 

typedef enum {
SCR_CALL_HISTORY_MAIN_MENU = CALL_HISTORY+1 ,
SCR_CALL_COST_MAIN,
SCR_CALL_COST_PRICEANDUNIT_SET,
SCR_MAX_COST_SET,
SCR_CALL_LOG_NOT_READY,
SCR8004_DELETE_MISSED_CALL_CONFIRM,
SCR8004_DELETE_DIALED_CALL_CONFIRM,
SCR8004_DELETE_RECEIVED_CALL_CONFIRM,
SCR8006_CALL_RECEIVED					,
SCR8007_RECEIVED_CALL_OPTIONS			,
SCR8008_CALL_DIALED					,
SCR8009_DIALED_CALL_OPTIONS			,
SCR8520_CALL_MISSED					,
SCR8521_MISSED_CALL_OPTIONS			,
SCR8522_CALL_REJECTED					,
SCR8523_REJECTED_CALL_OPTIONS			,
ITEM_SCR_MISSED_CALL,
SUB_LCD_ITEM_SCR_MISSED_CALL,
SCR8054_CALLS_LIST_RECEIVED			,
SCR8055_CALLS_LIST_DIALED				,
SCR8056_CALLS_LIST_MISSED				,
SCR8057_CALLS_LIST_MIXED        ,
SCR8058_CALLS_LIST_REJECTED     ,
SCR8004_SMS_COUNTER					,
 #ifdef __MMI_GPRS_FEATURES__
 SCR8004_GPRS_COUNTER	,	
 SCR8004_GPRS_COUNTER_RESET_CONFIRM,
 #endif
SCR_CALLHISTORY_RESETCALL,
SCR8004_SMS_SENT_COUNTER_RESET_CONFIRM,
SCR8004_SMS_RECV_COUNTER_RESET_CONFIRM,
SCR_DIALED_LIST_RESET_CONFIRM,
SCR_RECEIVED_LIST_RESET_CONFIRM,
SCR_MISSED_LIST_RESET_CONFIRM,
SCR_CALLTIME_RESET_CONFIRM,
SCR_UNIT_PRICE_SET_CONFIRM,
SCR_CALL_TIME_SETUP_MAIN,
SCR_CALL_TIME_QUICK_END,
/*+ zhouqin 2011-02-16 modify for q6 320X240 */
#ifdef __MMI_SYMBIAN_STYLE_IDLE__
	 SCR_CALLLOG_MISSED_PDA,
#endif
/*- zhouqin 2011-02-16 modify for q6 320X240 */

SCR_CHIS_DUMMY
} CALL_HISTORY_SCR  ;

#endif


