/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *	 PhotoEditor.c
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  PhotoEditor Header
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 
 *============================================================================
 ****************************************************************************/
#ifndef _PHOTOEDITOR_STR_H_
#define _PHOTOEDITOR_STR_H_


/***************************************************************************** 
* Define 
*****************************************************************************/

#define PHOART_EFFECT_COUNT 			(PHOART_EFFECT_END-PHOART_EFFECT_START-1)
#define PHOART_FRAME_COUNT 			(PHOART_FRAME_END-PHOART_FRAME_START-1)
#define PHOART_ICON_COUNT	 			(PHOART_ICON_END-PHOART_ICON_START-1)




/* features - shall move to a feature file */
	/* effect */
	#define PHOART_FEATURE_EFFECT_GRAYSCALE
	#define PHOART_FEATURE_EFFECT_SEPIA
	#define PHOART_FEATURE_EFFECT_SEPIA_GREEN
	#define PHOART_FEATURE_EFFECT_SEPIA_BLUE
	#define PHOART_FEATURE_EFFECT_COLOR_INVERT
	#define PHOART_FEATURE_EFFECT_GRAY_INVERT
	#define PHOART_FEATURE_EFFECT_WATER_COLOR
//	#define PHOART_FEATURE_EFFECT_LIGHT_BLUR	/* HW has problem */
	#define PHOART_FEATURE_EFFECT_BLUR
	#define PHOART_FEATURE_EFFECT_STRONG_BLUR
//	#define PHOART_FEATURE_EFFECT_UNSHARP		/* HW has problem */
//	#define PHOART_FEATURE_EFFECT_SHARPEN		/* HW has problem */
	#define PHOART_FEATURE_EFFECT_MORE_SHARPEN
	#define PHOART_FEATURE_EFFECT_MEDIAN
	#define PHOART_FEATURE_EFFECT_DILATION
	#define PHOART_FEATURE_EFFECT_EROSION



/***************************************************************************** 
* typedef 
*****************************************************************************/
typedef enum{
	PHOART_EFFECT_START,
		
#ifdef PHOART_FEATURE_EFFECT_GRAYSCALE
	PHOART_EFFECT_GRAYSCALE,
#endif

#ifdef PHOART_FEATURE_EFFECT_SEPIA
	PHOART_EFFECT_SEPIA,
#endif 

#ifdef PHOART_FEATURE_EFFECT_SEPIA_GREEN
	PHOART_EFFECT_SEPIA_GREEN,
#endif 

#ifdef PHOART_FEATURE_EFFECT_SEPIA_BLUE
	PHOART_EFFECT_SEPIA_BLUE,
#endif

#ifdef PHOART_FEATURE_EFFECT_COLOR_INVERT
	PHOART_EFFECT_COLOR_INVERT,
#endif 

#ifdef PHOART_FEATURE_EFFECT_GRAY_INVERT
	PHOART_EFFECT_GRAY_INVERT,
#endif 

#ifdef PHOART_FEATURE_EFFECT_WATER_COLOR
	PHOART_EFFECT_WATER_COLOR,
#endif

#ifdef PHOART_FEATURE_EFFECT_LIGHT_BLUR
	PHOART_EFFECT_LIGHT_BLUR,
#endif 

#ifdef PHOART_FEATURE_EFFECT_BLUR
	PHOART_EFFECT_BLUR,
#endif

#ifdef PHOART_FEATURE_EFFECT_STRONG_BLUR
	PHOART_EFFECT_STRONG_BLUR,
#endif

#ifdef PHOART_FEATURE_EFFECT_UNSHARP
	PHOART_EFFECT_UNSHARP,
#endif

#ifdef PHOART_FEATURE_EFFECT_SHARPEN
	PHOART_EFFECT_SHARPEN,
#endif

#ifdef PHOART_FEATURE_EFFECT_MORE_SHARPEN
	PHOART_EFFECT_MORE_SHARPEN,
#endif

#ifdef PHOART_FEATURE_EFFECT_MEDIAN
	PHOART_EFFECT_MEDIAN,
#endif

#ifdef PHOART_FEATURE_EFFECT_DILATION
	PHOART_EFFECT_DILATION,
#endif

#ifdef PHOART_FEATURE_EFFECT_EROSION
	PHOART_EFFECT_EROSION,
#endif

	PHOART_EFFECT_END
} phoart_effect_enum;


typedef enum{
	PHOART_FRAME_START,
	PHOART_FRAME_1,
	PHOART_FRAME_2,
#if 0
	PHOART_FRAME_3,
	PHOART_FRAME_4,
	PHOART_FRAME_5,
	PHOART_FRAME_6,
	PHOART_FRAME_7,
	PHOART_FRAME_8,
	PHOART_FRAME_9,
	PHOART_FRAME_10,
#endif
	PHOART_FRAME_END
} phoart_frame_enum;

typedef enum{
	PHOART_ICON_START,
	PHOART_ICON_1,
	PHOART_ICON_2,
	PHOART_ICON_3,
	PHOART_ICON_4,
	PHOART_ICON_5,
	PHOART_ICON_6,
	PHOART_ICON_7,
	PHOART_ICON_8,
	PHOART_ICON_9,
	PHOART_ICON_10,
	PHOART_ICON_11,
	PHOART_ICON_12,
	PHOART_ICON_13,
	PHOART_ICON_14,
	PHOART_ICON_15,
	PHOART_ICON_16,
	PHOART_ICON_17,
	PHOART_ICON_18,
	PHOART_ICON_END
} phoart_icon_enum;


/***************************************************************************** 
* Sting ID
*****************************************************************************/
typedef enum {

	/************* Photo Editor **************/
	STR_ID_PHOEDT_APP_NAME = PHOEDT_BASE+1,

	
	/************* Photo Art **************/
	STR_ID_PHOART_APP,  //41602

	/* clip menu */
	STR_ID_PHOART_CLIP,
	STR_ID_PHOART_AUTO_RESIZE,
	STR_ID_PHOART_MAINLCD_CLIP,
	STR_ID_PHOART_SUBLCD_CLIP,

	/* main menu */
	STR_ID_PHOART_EXIT,
	
	/* option menu */
	STR_ID_PHOART_SAVE_AS,
	STR_ID_PHOART_ADD_EFFECT,
	STR_ID_PHOART_ADD_FRAME,
	STR_ID_PHOART_ADD_ICON,
	STR_ID_PHOART_ADD_TEXT,
	STR_ID_PHOART_ADJUST,
	STR_ID_PHOART_FLIP,
	STR_ID_PHOART_EXPAND_CANVAS,
	STR_ID_PHOART_HELP,

	/* selection title */
	STR_ID_PHOART_ADD_EFFECT_TITLE,
	STR_ID_PHOART_ADD_FRAME_TITLE,
	STR_ID_PHOART_ADD_ICON_TITLE,
	STR_ID_PHOART_ADD_TEXT_TITLE,

	STR_ID_PHOART_ADJUST_IMAGE_TITLE_START,
	STR_ID_PHOART_ADJUST_BRIGHT_TITLE,
	STR_ID_PHOART_ADJUST_CONTRAST_TITLE,
	STR_ID_PHOART_ADJUST_SATURATION_TITLE,	
	STR_ID_PHOART_ADJUST_HUE_TITLE,

	STR_ID_PHOART_ADJUST_COLOR_TITLE_START,	
	STR_ID_PHOART_ADJUST_COLOR_R_TITLE,
	STR_ID_PHOART_ADJUST_COLOR_G_TITLE,
	STR_ID_PHOART_ADJUST_COLOR_B_TITLE,	
	
	STR_ID_PHOART_FLIP_TITLE,

	/* save */
	STR_ID_PHOART_EDIT_FILENAME,

	/* add effect menu */
	STR_ID_PHOART_EFFECT_START,		 
#ifdef PHOART_FEATURE_EFFECT_GRAYSCALE
	STR_ID_PHOART_EFFECT_GRAYSCALE,
#endif
#ifdef PHOART_FEATURE_EFFECT_SEPIA
	STR_ID_PHOART_EFFECT_SEPIA,
#endif 
#ifdef PHOART_FEATURE_EFFECT_SEPIA_GREEN
	STR_ID_PHOART_EFFECT_SEPIA_GREEN,
#endif 
#ifdef PHOART_FEATURE_EFFECT_SEPIA_BLUE
	STR_ID_PHOART_EFFECT_SEPIA_BLUE,
#endif
#ifdef PHOART_FEATURE_EFFECT_COLOR_INVERT
	STR_ID_PHOART_EFFECT_COLOR_INVERT,
#endif 
#ifdef PHOART_FEATURE_EFFECT_GRAY_INVERT
	STR_ID_PHOART_EFFECT_GRAY_INVERT,
#endif 
#ifdef PHOART_FEATURE_EFFECT_WATER_COLOR
	STR_ID_PHOART_EFFECT_WATER_COLOR,
#endif
#ifdef PHOART_FEATURE_EFFECT_LIGHT_BLUR
	STR_ID_PHOART_EFFECT_LIGHT_BLUR,
#endif 
#ifdef PHOART_FEATURE_EFFECT_BLUR
	STR_ID_PHOART_EFFECT_BLUR,
#endif
#ifdef PHOART_FEATURE_EFFECT_STRONG_BLUR
	STR_ID_PHOART_EFFECT_STRONG_BLUR,
#endif
#ifdef PHOART_FEATURE_EFFECT_UNSHARP
	STR_ID_PHOART_EFFECT_UNSHARP,
#endif
#ifdef PHOART_FEATURE_EFFECT_SHARPEN
	STR_ID_PHOART_EFFECT_SHARPEN,
#endif
#ifdef PHOART_FEATURE_EFFECT_MORE_SHARPEN
	STR_ID_PHOART_EFFECT_MORE_SHARPEN,
#endif
#ifdef PHOART_FEATURE_EFFECT_MEDIAN
	STR_ID_PHOART_EFFECT_MEDIAN,
#endif
#ifdef PHOART_FEATURE_EFFECT_DILATION
	STR_ID_PHOART_EFFECT_DILATION,
#endif
#ifdef PHOART_FEATURE_EFFECT_EROSION
	STR_ID_PHOART_EFFECT_EROSION,
#endif

	/* add frame menu */
	STR_ID_PHOART_FRAME_START,
	STR_ID_PHOART_FRAME_1,
	STR_ID_PHOART_FRAME_2,
	STR_ID_PHOART_FRAME_3,
	STR_ID_PHOART_FRAME_4,
	STR_ID_PHOART_FRAME_5,
	STR_ID_PHOART_FRAME_6,
	STR_ID_PHOART_FRAME_7,
	STR_ID_PHOART_FRAME_8,
	STR_ID_PHOART_FRAME_9,
	STR_ID_PHOART_FRAME_10,

	/* add text */
	STR_ID_PHOART_TEXT_EDITOR,
	
	STR_ID_PHOART_TEXT_TEXT_COLOR,
	STR_ID_PHOART_TEXT_BORDER_COLOR,
	STR_ID_PHOART_TEXT_SHADOW_COLOR,
	STR_ID_PHOART_TEXT_SIZE,
	STR_ID_PHOART_TEXT_ITALIC,
	STR_ID_PHOART_TEXT_STYLE,
	STR_ID_PHOART_TEXT_SIZE_SMALL,
	STR_ID_PHOART_TEXT_SIZE_MEDIUM,
	STR_ID_PHOART_TEXT_SIZE_LARGE,	

	/* Adjust */
	STR_ID_PHOART_ADJUST_IMAGE,
	STR_ID_PHOART_ADJUST_COLOR,
 
	/* help */
	STR_ID_PHOART_HELP_TITLE,
	STR_ID_PHOART_HELP_DESC,

	/* notify */
	STR_ID_PHOART_NOTIFY_FREE_SPACE_NOT_ENOUGH,
	STR_ID_PHOART_NOTIFY_UNLOCK_MEMORY_CARD,
	STR_ID_PHOART_NOTIFY_EXIT_CONFIRM,
	STR_ID_PHOART_NOTIFY_FILE_NOT_SAVED,	
	STR_ID_PHOART_NOTIFY_CARD_LOCK_SAVE_FAILED,
	STR_ID_PHOART_NOTIFY_DISK_FULL_SAVE_FAILED,
	STR_ID_PHOART_NOTIFY_SAVE_FAILED,
	STR_ID_PHOART_NOTIFY_EMPTY_STRING,
	STR_ID_PHOART_NOTIFY_ALREADY_FULL_SCREEN,
	STR_ID_PHOART_NOTIFY_ASK_EXPAND_CANVAS,
	STR_ID_PHOART_NOTIFY_IMAGE_TOO_WIDE,
	STR_ID_PHOART_NOTIFY_CANCELED,
	
	/************* Scene Master **************/
	STR_ID_SCENMAST_APP,

	
	/************* Image Tile **************/	
	STR_ID_IMGTILE_APP,

	
	/************* Slide Show **************/	
	STR_ID_SLIDSHOW_APP
	
} phoedt_str_id_enum;

#endif /* _PHOTOEDITOR_STR_H_ */


