/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of COOLSAND Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("COOLSAND SOFTWARE")
*  RECEIVED FROM COOLSAND AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. COOLSAND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES COOLSAND PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE COOLSAND SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. COOLSAND SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY COOLSAND SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND COOLSAND'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE COOLSAND SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT COOLSAND'S OPTION, TO REVISE OR REPLACE THE COOLSAND SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  COOLSAND FOR SUCH COOLSAND SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  j2me_sap.h
 *
 * Project:
 * --------
 
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 * 				HISTORY
 
 *------------------------------------------------------------------------------
 *
 *
 *------------------------------------------------------------------------------
 
 *==============================================================================
 *******************************************************************************/


#ifdef __SUN_RI__
	ADD_MAG(MSG_ID_MMI_J2ME_ACTIVATE_REQ = MSG_ID_J2ME_CODE_BEGIN),
	ADD_MAG(MSG_ID_MMI_J2ME_PAUSE_REQ),
	ADD_MAG(MSG_ID_MMI_J2ME_RESUME_REQ),
	ADD_MAG(MSG_ID_MMI_J2ME_DEACTIVATE_REQ),
#else
	/*************************************************************************** 
	 * For message table implementation simplicity), 
	 * request/indication input messages are put together. 
	 **************************************************************************/		

	/**************************************************************************
	 * Request or Indication Messages (Input
	 **************************************************************************/		
	 
	/* Get MIDlet Suite/MIDlet List */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_GETLIST_REQ = MSG_ID_J2ME_CODE_BEGIN),
	ADD_MAG(MSG_ID_MMI_JAVA_MID_GETLIST_REQ),

	/* MIDlet Start/Stop notification */	
	ADD_MAG(MSG_ID_MMI_JAVA_MID_START_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_MID_STOP_RES),	
	
	/* Get MIDlet Suite information */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_GETINFO_REQ),

	/* Get/Set MIDlet Suite settings */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_GET_SETTING_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_SET_SETTING_REQ),

	/* Update MIDlet Suite */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_UPDATE_REQ),

	/* Remove MIDlet Suite */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_REMOVE_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_REMOVE_CONFIRM_RES),

	/* Install MIDlet Suite */
	ADD_MAG(MSG_ID_JAVA_WAP_INSTALL_MIDS_IND),
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_MIDS_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_MIDS_RES),	
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_CONFIRM_RES),	
	ADD_MAG(MSG_ID_MMI_WAP_GET_FILE_AND_SAVE_IND),
	ADD_MAG(MSG_ID_JAVA_WAP_GET_FILE_AND_SAVE_CNF),	
	ADD_MAG(MSG_ID_MMI_JAVA_GET_FILE_AND_SAVE_RES),		
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_RESET_RMS_RES),
	ADD_MAG(MSG_ID_JAVA_WAP_POST_DATA_CNF),
	ADD_MAG(MSG_ID_JAVA_WAP_DATA_ACCOUNT_IND),
	ADD_MAG(MSG_ID_MMI_JAVA_GET_FILE_AND_SAVE_PROGRESS_RES),

	/* Local installation */
	ADD_MAG(MSG_ID_JAVA_LOCAL_INSTALL_REQ),
    
	/* ABORT */
	ADD_MAG(MSG_ID_MMI_JAVA_ABORT_REQ),
	ADD_MAG(MSG_ID_JAVA_WAP_ABORT_CNF),
	ADD_MAG(MSG_ID_MMI_WAP_ABORT_REQ),

	/* PUSH */
	ADD_MAG(MSG_ID_JAVA_MMI_TIMEALARM_PUSH_RES),
	/* Push timeout message is system timeout message */

	/**************************************************************************
	* Confirm or Response Messages (Output)
	**************************************************************************/		

	/* Get MIDlet Suite List */	
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_GETLIST_CNF),
	ADD_MAG(MSG_ID_MMI_JAVA_MID_GETLIST_CNF),

	/* MIDlet Start/Stop notification */		
	ADD_MAG(MSG_ID_MMI_JAVA_MID_START_CNF),	
	ADD_MAG(MSG_ID_MMI_JAVA_MID_STOP_IND),	

	/* Get MIDlet Suite information */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_GETINFO_CNF),

	/* Get/Set MIDlet Suite settings */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_GET_SETTING_CNF),
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_SET_SETTING_CNF),

	/* Update MIDlet Suite */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_UPDATE_CNF),

	/* Remove MIDlet Suite */
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_REMOVE_CONFIRM_IND),
	ADD_MAG(MSG_ID_MMI_JAVA_MIDS_REMOVE_CNF),

	/* Install MIDlet Suite */
	ADD_MAG(MSG_ID_JAVA_WAP_INSTALL_MIDS_RES),
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_MIDS_CNF),
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_MIDS_IND),	
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_CONFIRM_IND),	
	ADD_MAG(MSG_ID_JAVA_WAP_GET_FILE_AND_SAVE_REQ),
	ADD_MAG(MSG_ID_MMI_WAP_GET_FILE_AND_SAVE_RES),	
	ADD_MAG(MSG_ID_MMI_JAVA_GET_FILE_AND_SAVE_IND),	
	ADD_MAG(MSG_ID_MMI_JAVA_INSTALL_RESET_RMS_IND),
	ADD_MAG(MSG_ID_JAVA_WAP_POST_DATA_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_GET_FILE_AND_SAVE_PROGRESS_IND),

	/* Local installation */
	ADD_MAG(MSG_ID_JAVA_LOCAL_INSTALL_CNF),

	/* ABORT */
	ADD_MAG(MSG_ID_MMI_JAVA_ABORT_CNF),
	ADD_MAG(MSG_ID_JAVA_WAP_ABORT_REQ),
	ADD_MAG(MSG_ID_MMI_WAP_ABORT_CNF),

	/* PUSH & TimeAlarm */
	ADD_MAG(MSG_ID_JAVA_MMI_TIMEALARM_PUSH_IND),
	ADD_MAG(MSG_ID_JAVA_JAVA_MID_START_REQ),	

	/* get user permission */
	ADD_MAG(MSG_ID_MMI_JAVA_GET_PERMISSION_IND),  // add by eric

#endif /* __SUN_RI__ */	

	ADD_MAG(MSG_ID_MMI_J2ME_EXIT_SCREEN_REQ),

	/* Set Java mode to execute */
	ADD_MAG(MSG_ID_MMI_JAVA_SET_MODE_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_SET_MODE_CNF),

	/* Unit test */
	ADD_MAG(MSG_ID_MMI_JAM_UT_GETLIST_REQ),

	/* Interwork */
	ADD_MAG(MSG_ID_JAM_JASYN_PUSHUT_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_SHOW_ALERT_USER_DIALOG_REQ),
	ADD_MAG(MSG_ID_MMI_JAVA_PLAY_TONE_REQ),
	ADD_MAG(MSG_ID_JAVA_MMA_EVENT_CALLBACK),
	ADD_MAG(MSG_ID_JAVA_KEYPAD_NOTIFY_IND),
	ADD_MAG(MSG_ID_MMI_JAVA_RUN_WAP_REQ),
	/* CMCC PHB */
	ADD_MAG(MSG_ID_MMI_PHB_JAVA_SET_ENTRY_REQ),	
	ADD_MAG(MSG_ID_MMI_PHB_JAVA_SET_ENTRY_RSP),
	ADD_MAG(MSG_ID_MMI_PHB_JAVA_GET_ENTRY_REQ),
	ADD_MAG(MSG_ID_MMI_PHB_JAVA_GET_ENTRY_RSP),
	ADD_MAG(MSG_ID_MMI_PHB_JAVA_SEARCH_ENTRY_REQ),
	ADD_MAG(MSG_ID_MMI_PHB_JAVA_SEARCH_ENTRY_RSP),

#ifdef __NATIVE_JAVA__

	/* native editer */
	ADD_MAG(MSG_ID_GCJ_ENTRY_NATIVE_EDITER_REQ),
	/* network api */
	ADD_MAG(MSG_ID_GCJ_PREPARE_GPRS_REQ),
	ADD_MAG(MSG_ID_GCJ_STOP_GPRS_REQ),
	ADD_MAG(MSG_ID_GCJ_GET_TCPIP_SOCKET_REQ),
	ADD_MAG(MSG_ID_GCJ_SET_SOCKET_OPT_REQ),
	ADD_MAG(MSG_ID_GCJ_GET_HOST_NAME_REQ),
	ADD_MAG(MSG_ID_GCJ_SOCKET_CONNECT_REQ),
	ADD_MAG(MSG_ID_GCJ_SOCKET_READ_REQ),
	ADD_MAG(MSG_ID_GCJ_SOCKET_WRITE_REQ),
	ADD_MAG(MSG_ID_GCJ_SOCKET_CLOSE_REQ),
	
	/* file system api */
	ADD_MAG(MSG_ID_GCJ_FILE_OPEN_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_CLOSE_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_READ_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_WRITE_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_SEEK_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_CHANGE_SZIE_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_GET_FILE_SZIE_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_GET_FILE_NAME_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_DISK_INFO_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_GET_FIRST_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_GET_NEXT_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_GET_CLOSE_REQ),
	ADD_MAG(MSG_ID_GCJ_FILE_DELETE_REQ), 
	ADD_MAG(MSG_ID_GCJ_FILE_RENAME_REQ), 
#endif

