/***************************************************************************
 * $Id: jdi_browserapp.h,v 1.123 2009/07/20 05:06:42 kavithadevhtmlbrow Exp $
 * $Revision: 1.123 $
 * $Date: 2009/07/20 05:06:42 $
 * 
 * IMPORTANT NOTICE
 *
 * Please note that any and all title and/or intellectual property rights 
 * in and to this Software or any part of this (including without limitation 
 * any images, photographs, animations, video, audio, music, text and/or 
 * "applets," incorporated into the Software), herein mentioned to as 
 * "Software", the accompanying printed materials, and any copies of the 
 * Software, are owned by Jataayu Software (P) Ltd., Bangalore ("Jataayu") 
 * or Jataayu's suppliers as the case may be. The Software is protected by 
 * copyright, including without limitation by applicable copyright laws, 
 * international treaty provisions, other intellectual property laws and 
 * applicable laws in the country in which the Software is being used. 
 * You shall not modify, adapt or translate the Software, without prior 
 * express written consent from Jataayu. You shall not reverse engineer, 
 * decompile, disassemble or otherwise alter the Software, except and 
 * only to the extent that such activity is expressly permitted by 
 * applicable law notwithstanding this limitation. Unauthorized reproduction 
 * or redistribution of this program or any portion of it may result in severe 
 * civil and criminal penalties and will be prosecuted to the maximum extent 
 * possible under the law. Jataayu reserves all rights not expressly granted. 
 * 
 * THIS SOFTWARE IS PROVIDED TO YOU "AS IS" WITHOUT WARRANTY OF ANY 
 * KIND AND ANY AND ALL REPRESENTATION AND WARRANTIES, EITHER EXPRESS 
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY ACCURACY OF INFORMATIONAL CONTENT, AND/OR FITNESS 
 * FOR A PARTICULAR PURPOSE OR USE, TITLE OR INFRINGEMENT ARE EXPRESSLY 
 * DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. YOU ASSUME THE 
 * ENTIRE RISK AS TO THE ACCURACY AND THE USE OF THIS SOFTWARE. JATAAYU 
 * SHALL NOT BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, 
 * EXEMPLARY, SPECIAL OR PUNITIVE DAMAGES INCLUDING WITHOUT LIMITATION 
 * ANY LOSS OF DATA, OR; LOSS OF PROFIT, SAVINGS BUSINESS OR GOODWILL 
 * OR OTHER SIMILAR LOSS RESULTING FROM OR OUT OF THE USE OR INABILITY 
 * TO USE THIS SOFTWARE, EVEN IF JATAAYU HAS BEEN ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE, OR FOR ANY CLAIM BY ANY THIRD PARTY.
 *
 ***************************************************************************
 *
 * Revision Details
 * ----------------
 * $Log: jdi_browserapp.h,v $
 * Revision 1.123  2009/07/20 05:06:42  kavithadevhtmlbrow
 * Debug Size To in Appllication
 *
 * Revision 1.122  2009/02/25 13:29:38  arpitadevhtmlbrow
 * self event for window close
 *
 * Revision 1.121  2009/02/12 14:14:42  arpitadevhtmlbrow
 * Network Confirmation and Image optmize ARR
 *
 * Revision 1.120  2009/01/21 14:32:13  kavithadevhtmlbrow
 * Popup Blocker for Window.Open
 *
 * Revision 1.119  2009/01/12 13:01:52  arpitadevhtmlbrow
 * Error handling for JC_ERR_DE_STACK_OVERFLOW
 *
 * Revision 1.118  2008/12/16 07:23:53  kavithadevhtmlbrow
 * DE_WINDOW_OPEN_ENABLE to BROWSER_WINDOW_OPEN
 *
 * Revision 1.117  2008/12/10 14:46:16  kavithadevhtmlbrow
 * window.open Support - DE_WINDOW_OPEN_ENABLE
 *
 * Revision 1.116  2008/11/18 10:23:11  arpitadevhtmlbrow
 * Fixed Postion ARR addition
 *
 * Revision 1.115  2008/11/08 12:13:16  arpitadevhtmlbrow
 * For multiple file storage special character validation for category and URL title name on the application side.
 *
 *  
 ***************************************************************************/

#ifndef _JDI_BROWSER_APP_H
#define _JDI_BROWSER_APP_H

#include <ddl.h>
#include <jcal.h>
#include <jdi_arr.h>
#include <jdi_pushmsg.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MENU_MORE_VALUE			9
#define	MAX_CSS_MEDIA_TYPES		10

#define MIN_FONT_SIZE			"9"

#define BROWSER_LOAD_TEST_EVENT					750 
#define BROWSER_LOAD_TEST_STOP_REQ_EVENT		751
#define BROWSER_LOAD_TEST_SCROLL_EVENT			752
#define BROWSER_LOAD_TEST_REQUEST_EVENT			753
#define BROWSER_SCHEME_RESPONSE_EVENT			754
#define BROWSER_SIZE_TO_EVENT					755

#ifdef BROWSER_APP_WEBSPIDER_CHANGEMODE
#define BROWSER_LOAD_TEST_CHANGEMODE_EVENT		755
#endif

#ifdef BROWSER_WINDOW_OPEN
#define BROWSER_WINDOW_CLOSE_EVENT				800
#endif

#define	FONT_TO_PIXEL(x)				((JC_UINT32)x * 96 / 72) 

#define VER_STR_LEN						16

typedef struct _browser_app_attribute
{
	JC_RECT			stRectMain ;
	JC_RECT			stRectTitle ;
	JC_RECT			stRectTitleText ;
	JC_RECT			stRectTitleImage ;
	JC_RECT			stRectPrimary ;
	JC_RECT			stRectPrimaryMenu ;
	JC_RECT			stRectSoftKey ;
	JC_RECT			stRectVertScroll ;
	JC_RECT			stRectHorzScroll ;
	JC_BOOLEAN		bIsAttributeFile ;
	JC_INT8			acVersion[VER_STR_LEN] ;
	
} ST_BROWSER_APP_ATTRIBUTE ;

typedef struct _control_attribute
{
	JC_RECT						stCtrlRect ;
	JC_CONTROL_PROPERTIES		stCtrlProp ;
	
} ST_CONTROL_ATTRIBUTE ;

typedef struct _color_attribute
{
	JC_UINT32	uiForegroundColor ;
	JC_UINT32	uiBackgroundColor ;
} ST_COLOR_ATTRB ;

typedef struct _title_attrb
{
	ST_CONTROL_ATTRIBUTE	stIconAttrb ;
	ST_CONTROL_ATTRIBUTE	stTextAttrb ;
	ST_CONTROL_ATTRIBUTE	stStartImageAttrb ;
	ST_CONTROL_ATTRIBUTE	stStopImageAttrb ;
} ST_TITLE_ATTRB ;

typedef struct _softkey_attrb
{
	ST_CONTROL_ATTRIBUTE	stLeftAttrb ;
	ST_CONTROL_ATTRIBUTE	stRightAttrb ;
} ST_SOFTKEY_ATTRB ;

typedef struct _select_menu_attrb
{
	ST_CONTROL_ATTRIBUTE	stIconAttrb ;
	ST_CONTROL_ATTRIBUTE	stTextAttrb ;
	ST_CONTROL_ATTRIBUTE	stEditAttrb ;
	ST_CONTROL_ATTRIBUTE	stComboAttrb ;
	ST_CONTROL_ATTRIBUTE	stImageAttrb ;
	ST_CONTROL_ATTRIBUTE	stCheckAttrb ;
	ST_CONTROL_ATTRIBUTE	stListAttrb ;

} ST_MENU_ATTRB ;

typedef struct _scroll_attrb
{
	ST_CONTROL_ATTRIBUTE	stScrollAttrb ;
} ST_SCROLLBAR_ATTRB ;

typedef struct _st_prymary_image_list
{
	JC_CHAR							*pmFileName ;
	JC_CHAR							*pmFilePath ;
	JC_CHAR							*pmFileNameNSize ;
	JC_UINT8						*pucImageBuffer ;
	JC_UINT32						uiImageSize ;
	EWallpaperProperty				eProperty ;
	JC_RECT							stRect ;
	struct _st_prymary_image_list	*pstNext ;
} ST_PRIMARYIMAGE_LIST ;

typedef enum _e_primary_image_list
{
	E_IMAGE_CONFIRMATION,
	E_IMAGE_INFORMATION,
	E_IMAGE_ERROR,
	E_IMAGE_EXCLAMATION,

} E_PRIMARYWINDOW_IMAGE ;

typedef struct _primary_attrb
{
	JC_RECT					stRectMenu ;
	ST_COLOR_ATTRB			stColorActiveMenuAttrb ;
	ST_MENU_ATTRB			stMenuAttrb ;
	ST_PRIMARYIMAGE_LIST	staImageList[E_IMAGE_EXCLAMATION + 1] ;

} ST_PRIMARY_ATTRB ;

typedef struct primary_text
{
	JC_CHAR		*pmIconText ;
	JC_CHAR		*pmMenuText ;
	struct primary_text *pNext ;
} ST_PRIMARY_TEXT ;

typedef enum _error_text
{
	E_ERROR_NOERROR	= 0 ,

#ifdef APP_WALLET_ENABLE
	E_ERROR_WALLETENTRY_TEXT ,
#endif
	E_ERROR_EMPTYPROFILENAME_TEXT,
	E_ERROR_INVALIDPROFILENAME_TEXT ,
	E_ERROR_DUPLICATEPROFILENAME_TEXT ,
	E_ERROR_EMPTYIPADDRESS_TEXT ,

	E_ERROR_INVALIDIPADDRESS_TEXT ,
	E_ERROR_EMPTYPORTNUMBER_TEXT ,
	E_ERROR_INVALIDPORTNUMBER_TEXT ,
	E_ERROR_EMPTYBEARERNAME_TEXT ,
	E_ERROR_INVALIDBEARERNAME_TEXT ,

	E_ERROR_DUPLICATEBEARERNAME_TEXT ,
	E_ERROR_CSDEMPTYPHONENO_TEXT ,
	E_ERROR_BOOKMARKLIMITCATEGORY_TEXT ,
	E_ERROR_BOOKMARKLIMITBOOKAMRK_TEXT ,
	E_ERROR_BOOKMARKEXISTCATEGORY_TEXT ,
	E_ERROR_BOOKMARKREADONLYCATEGORY_TEXT,

	E_ERROR_BOOKMARKEXISTBOOKAMRK_TEXT ,
	E_ERROR_INVALIDURL  ,
	E_ERROR_EMPTYCATEGORYNAME_TEXT ,
	E_ERROR_SPECCHARCATEGORY_TEXT,
	E_ERROR_EMPTYFAVORITNAME_TEXT ,
	E_ERROR_EMPTYCATEGORY ,
	E_ERROR_NO_CATEGORY_TEXT,

	E_ERROR_EMPTYSHORTCUTS ,
	E_ERROR_EMPTYURL ,
	E_ERROR_ALREDYASSINGLE ,
	E_ERROR_NOTALLOWEDTOMOVECATEGORY ,
	E_ERROR_NOTALLOWEDTODELETEACTIVEPROFILE ,

	E_ERROR_CSDINVALIDEPHONENO_TEXT ,
	E_ERROR_EMPTYPROFILE_TEXT  ,

	E_ERROR_ACCESSDENIED,
	E_ERROR_UNSUPPORTED_CONTENT,
	E_ERROR_PAGESIZE_EXCEEDS,
	E_ERROR_INVALID_INPUT,
	E_ERROR_MAX_REDIRECTION,
	E_ERROR_HISTORY_NOT_FOUND,
	E_ERROR_HISTORY_FULL ,

	E_ERROR_HTTP_CREATED,
	E_ERROR_HTTP_ACCEPTED,
	E_ERROR_HTTP_NON_AUTHORITATIVE,
	E_ERROR_HTTP_NO_CONTENT,
	E_ERROR_HTTP_RESET_CONTENT,
	E_ERROR_HTTP_PARTIAL_CONTENT,
	E_ERROR_HTTP_MULTIPLE_CHOICES,
	E_ERROR_HTTP_MOVED_PERMANENTLY,			
	E_ERROR_HTTP_MOVED_TEMPORARILY,			
	E_ERROR_HTTP_SEE_OTHER,			
	E_ERROR_HTTP_NOT_MODIFIED,
	E_ERROR_HTTP_USE_PROXY,				
	E_ERROR_HTTP_TEMPORARY_REDIRECT,
	E_ERROR_HTTP_BAD_REQUEST,			
	E_ERROR_HTTP_UNAUTHORIZED,					
	E_ERROR_HTTP_PAYMENT,				
	E_ERROR_HTTP_FORBIDDEN,
	E_ERROR_HTTP_NOT_FOUND,					
	E_ERROR_HTTP_METHOD_NOT_ALLOWED,
	E_ERROR_HTTP_NOT_ACCEPTABLE,			
	E_ERROR_HTTP_PROXY_AUTHENTICATION_REQD,
	E_ERROR_HTTP_REQUEST_TIMEOUT,	
	E_ERROR_HTTP_CONFLICT,				
	E_ERROR_HTTP_GONE,					
	E_ERROR_HTTP_LENGTH_REQD,
	E_ERROR_HTTP_PRECONDITION_FAILED,
	E_ERROR_HTTP_REQUEST_ENTITY_TOO_LARGE,
	E_ERROR_HTTP_REQUEST_URI_TOO_LARGE,	
	E_ERROR_HTTP_UNSUPPORTED_MEDIA_TYPE,		
	E_ERROR_HTTP_REQUEST_RANGE_NOT_SATISFIABLE,
	E_ERROR_HTTP_EXPECTATION_FAILED,
#ifdef IMODE_HTTP_EX_STATUS_CODE
	E_ERROR_HTTP_MAX_SIZE_ERROR,
#endif
	E_ERROR_HTTP_INTERNAL_SERVER_ERROR,
	E_ERROR_HTTP_NOT_IMPLEMENTED,		
	E_ERROR_HTTP_BAD_GATEWAY,				
	E_ERROR_HTTP_SERVICE_UNAVAILABLE,
	E_ERROR_HTTP_GATEWAY_TIMEOUT,			
	E_ERROR_HTTP_BAD_VERSION,
	E_ERROR_HTTP_UNKNOWN,
	
	E_ERROR_GENERAL ,
	E_ERROR_EMPTYUSERNAME ,
	E_ERROR_INVALIDSCHEME ,
	E_ERROR_EMPTYDOMAIN ,
	E_ERROR_DOMAIN_NOT_FOUND,
	E_ERROR_EMPTYHISTORY ,
	E_ERROR_EMPTYPAGE,

	E_ERROR_INVALIDHOMEPAGEURL,
	E_ERROR_EMPTYHOMEPAGEURL,
	E_ERROR_INVALIDTIMEOUT_TEXT ,
	E_ERROR_SCHEMENOTSUPPORTED_TEXT ,
	E_ERROR_INVALIDKEYWORD,
	E_ERROR_EMPTYKEYWORD ,
	E_ERROR_KEYWORD_NOT_FOUND,
	E_ERROR_EMPTYFILENAME ,
	E_ERROR_EMPTYBOOKMARK ,

	E_ERROR_INVALIDPUSHURL,
	E_ERROR_EMPTYPUSHINBOX,
	E_ERROR_PUSHINBOXLIMITMSG_TEXT,

	E_ERROR_PASSWORDMISSMATCH_TEXT,

	E_ERROR_EMPTYLINKELEMENTS,
	
	E_ERROR_PREVIOUSPAGENOTFOUND,
	E_ERROR_PAGENOTFOUND,
	E_ERROR_FILENOTFOUND,
	E_ERROR_NEXTPAGENOTFOUND,

	E_ERROR_DOWNLOADFAILED,
	E_ERROR_DOWNLOADCANCELLED,
	E_ERROR_UNSUPPORTEDTYPE,
	E_ERROR_INSUFFICIENTMEMORY,
	E_ERROR_UNSUPPORTEDDDVERSION,
	E_ERROR_INVALIDDD,
	E_ERROR_NOTIFICATIONFAILURE,
	E_ERROR_AUTHORIZATIONFAILURE,
	E_ERROR_INVALIDCATEGORYNAME_TEXT,
	E_ERROR_INVALIDTITLENAME_TEXT,
	E_ERROR_SPECCHARTITLENAME_TEXT,
	E_ERROR_OBJECTEXISTS,

	E_ERROR_SAVEPAGE,
	E_ERROR_OPTIONNOTAVAILABLE,
	E_ERROR_INVALIDFONTSIZE,
	
	E_ERROR_SCRIPT_IN_PROGRESS,

	E_ERROR_NO_ACTION,

	E_ERROR_RSSFAILED,

	E_ERROR_INVALIDACCELERATORURL,	
	E_ERROR_COMPLETED_SEARCH,

#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_ERROR_DOWNLOADCLIENT,
#endif

#if (defined DE_PPP_READWRITE_WIDGET && defined APP_WIDGET_ENABLE)
	E_ERROR_WIDGETINITIALIZE,
#endif

	E_ERROR_BOOKMARKEXPORT,
	/*Write all the error code above this line*/

	E_ERROR_STACK_OVERFLOW,

#ifdef BROWSER_WINDOW_OPEN
	E_ERROR_MAXWINDOW,
	E_ERROR_WINDOWOPEN,
#endif

	E_ERROR_MAX
} E_ERROR_TEXT ;

typedef enum _information_text
{
	E_INFORMATION_NOINFORMATION = 0,

	E_INFORMATION_INFORMATIONACTIVEDPROFILE  ,
	E_INFORMATION_INFORMATIONUPDATEDSUCCESSFULLY = 2,
	E_INFORMATION_INFORMATIONADDEDSUCCESSFULLY = 3,
	E_INFORMATION_INFORMATIONSETTINGSCHANGEDTODEFAULT ,
	E_INFORMATION_INFORMATIONEXPORTEDSUCCESSFULLY ,
	E_INFORMATION_INFORMATIONEXPORTEDALLSUCCESSFULLY ,
	E_INFORMATION_RECEIVEDSERVICEINDICATIONMSG ,
	E_INFORMATION_RECEIVEDSERVICELOADINGMSG ,
	E_INFORMATION_DOWNLOADEDSUCCESSFULLY ,
	E_INFORMATION_CACHECLEAREDSUCCESSFULLY,
	E_INFORMATION_COOKIECLEAREDSUCCESSFULLY,
	E_INFORMATION_PROFILEALREADYACTIVATED,
	E_INFORMATION_SAVEDSUCCESSFULLY,
	E_INFORMATION_SAVEASSINGLEFILE,
	E_INFORMATION_PUSHLIST_FULL,
	E_INFORMATION_CSSUPDATEDSUCCESSFULLY,
	E_INFORMATION_CSSCHANGEDTODEFAULT,
	E_INFORMATION_ACTIVATEDSUCCESSFULLY,
	E_INFORMATION_ACCELERATOR_ENABLED,
	E_INFORMATION_ACCELERATOR_DISABLED,
	E_INFORMATION_PAGEPREVIEWNOTPOSSIBLE,
#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_INFORMATION_DELETEDSUCCESSFULLY,
	E_INFORMATION_UPDATENOTPOSSIBLE,
	E_INFORMATION_UPDATESUCCESSFULL,
	E_INFORMATION_UPDATEDINITIATED,
#endif
	E_INFORMATION_NOCUSTOMIZEOPTIONS,
	E_INFORMATION_NOWIDGETSAVAILABLE,
	E_INFORMATION_PEAKMEMDISPLAY,
#ifdef BROWSER_WINDOW_OPEN
	E_INFORMATION_NOWINDOWSAVAILABLE,
	E_INFORMATION_POPUPBLOCKED,
#endif
	/*Write all the information code above this line*/
	E_INFORMATION_MAX
} E_INFORMATION_TEXT ;

typedef enum _exclamtion_text
{
	E_EXCLAMATION_NOEXCLAMATION = 0 ,

	E_EXCLAMATION_EMPTYHOMEPAGE_TEXT ,
	E_EXCLAMATION_EMPTYUSERNAME_TEXT ,
	E_EXCLAMATION_EMPTYPASSWORD_TEXT ,
	E_EXCLAMATION_EMPTYTIMEOUT_TEXT ,
	E_EXCLAMATION_GPRSEMPTYAPN_TEXT = 5 ,

	E_EXCLAMATION_INVALIDHOMEPAGE_TEXT ,
	E_EXCLAMATION_INVALIDTIMEOUT_TEXT = 7 ,
	E_EXCLAMATION_NOTFOUND_TEXT,

	/*Write all the Exclamation code above this line*/
	E_EXCLAMATION_MAX

} E_EXCLAMATION_TEXT ;

typedef enum _confirmation_text
{
	E_CONFIRMATION_NOCONFIRMATION = 0 ,
	
	E_CONFIRMATION_DELETEPROFILENAME_TEXT ,
	E_CONFIRMATION_DELETEBEARERNAME_TEXT ,
	E_CONFIRMATION_DELETEBOOKMARKCATEGORY_TEXT ,
	E_CONFIRMATION_DELTEBOOKMARKFAVORITE_TEXT  ,
	E_CONFIRMATION_DELTEALLBOOKMARKCATEGORY_TEXT ,
	E_CONFIRMATION_DELTEALLBOOKMARKFAVORITE_TEXT ,

	E_CONFIRMATION_CLEARCACHE_TEXT ,
	E_CONFIRMATION_CLEARCOOKIE_TEXT ,

	E_CONFIRMATION_CLEARDOMAIN_TEXT ,
	E_CONFIRMATION_CLEARALLDOMAIN_TEXT ,
	E_CONFIRMATION_CLEARURL_TEXT ,
	E_CONFIRMATION_CLEARALLURL_TEXT ,

	E_CONFRIMATION_DOYOUWANTTOREPLACEHOMEURL,
	E_CONFIRMATION_UNABLETOAUTHENTICATE,
	E_CONFIRMATION_PROCEEDWITHANONYMOUS,
	E_CONFIRMATION_PROCEEDWITHSECURITY,
	E_CONFIRMATION_SWITCHTOSECURE,
	E_CONFIRMATION_SWITCHTONONSECURE,
	E_CONFIRMATION_SECUREINLINE_INNONSECURE,
	E_CONFIRMATION_NONSECUREINLINE_INSECURE,
	E_CONFIRMATION_NONSECUREPOST,
	E_CONFIRMATION_PROCEEDWITHOUTTITLE,

#ifdef RSS_WITH_INBOX
	E_CONFIRMATION_RSSSTORETOINBOX,
#endif
	
	E_CONFIRMATION_DELETEPUSHMSG_TEXT  ,
	E_CONFIRMATION_DELETEALLPUSHMSG_TEXT ,

	E_CONFIRMATION_OVERWRITE_FILE,
#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_CONFIRMATION_DELETE_OBJECT_WARNING,
	E_CONFIRMATION_DELETE_OBJECT,
	E_CONFIRMATION_CHANGE_FILENAME,
#endif

	E_CONFIRMATION_SCRIPT_EXECUTE,
	E_CONFIRMATION_BOM_SCRIPT_EXECUTE,
	E_CONFIRMATION_SCRIPT_ABORT,
	
	E_CONFIRMATION_MAKE_CALL,
	E_CONFIRMATION_SEND_DTMF,
	E_CONFIRMATION_PHONE_BOOK,

	E_CONFIRMATION_ENDOFFILE,
	E_CONFIRMATION_BEGINOFFILE,
	E_CONFIRMATION_NETWORK,

#ifdef DE_PPP_READWRITE_PWDMGR
	E_CONFIRMATION_SAVE_PASSWORD,
	E_CONFIRMATION_OVERRIDE_PASSWORD,
#endif

#ifdef BROWSER_WINDOW_OPEN
	E_CONFIRMATION_POPUPWINDOW,
#endif

	/*Write all the conformation code above this line*/
	E_CONFIRMATION_MAX

} E_CONFIRMATION_TEXT ;

typedef struct _messagebox_list
{
	JC_CHAR		*pamErrorText[E_ERROR_MAX] ;
	JC_CHAR		*pamInformationText[E_INFORMATION_MAX] ;
	JC_CHAR		*pamExclamationText[E_EXCLAMATION_MAX] ;
	JC_CHAR		*pamConfirmationText[E_CONFIRMATION_MAX] ;

	JC_UINT32	uiTotalError ;
	JC_UINT32	uiTotalInformation ;
	JC_UINT32	uiTotalExclamation ;
	JC_UINT32	uiTotalConfirmation ;

} ST_MESSAGEBOX_TEXT ;

typedef enum _title_text
{
	E_TITLE_TITLE			= 0 ,

	E_TITLE_HOME			= 1 ,
	E_TITLE_ENTERURL ,
	E_TITLE_URLOPTION ,
	E_TITLE_URLSHORTCUT ,
	E_TITLE_URLGO			= 5 ,

	E_TITLE_EMPTYBOOKMARK	= 6 ,
	E_TITLE_EDITCATEGORY	,
	E_TITLE_EDITFAVORITE ,
	E_TITLE_EDITFAVORITEOPTION ,
	E_TITLE_SETTINGS		= 10 ,

	E_TITLE_EMPTYPROFILE    = 11 ,
	E_TITLE_EDITPROFILE	,
	E_TITLE_EMPTYBEARER ,
	E_TITLE_EDITBEARER ,
	E_TITLE_CSDSETTING		= 15 ,

	E_TITLE_GPRSSETTING		= 16 , 
	E_TITLE_DISPLAY	 ,
	E_TITLE_DISPLAYOPTION ,
	E_TITLE_PUSH ,
	E_TITLE_PUSHOPTION		= 20 ,

	E_TITLE_CACHECOOKIE		= 21 ,
	E_TITLE_CACHECOOKIEOPTION  ,
	E_TITLE_SHORTCUTS ,
	E_TITLE_SHORTCUTSOPTION ,
#ifdef APP_WALLET_ENABLE
	E_TITLE_WALLETENTRY		= 25 ,
	E_TITLE_WALLET			= 26,
	E_TITLE_EMPTYACCOUNTINFORMATION ,
	E_TITLE_EDITACCOUNTINFORMATION ,
	E_TITLE_EDITADDRESSINFORMATION ,
#endif

	E_TITLE_PROFILE			= 30 ,
	E_TITLE_PROFILEOPTION  = 31 ,
	E_TITLE_ERROR ,
	E_TITLE_INFORMATION	,
	E_TITLE_EXCLAMATION ,
	E_TITLE_CONFIRMATION	= 35,
	
	E_TITLE_EDITPROFILEOPTION = 36 ,
	E_TITLE_BEARER ,
	E_TITLE_BEAREROPTION,
	E_TITLE_BOOKMARK ,
	E_TITLE_BOOKMARKCATEGORYOPTION = 40 ,

	E_TITLE_BOOKMARKMOVETO = 41 ,
	E_TITLE_BOOKMARKMOVETOOPTION ,
	E_TITLE_BOOKMARKFAVORITEOPTION ,
	E_TITLE_URLGOOPTION,
	E_TITLE_URLNAVIGATION		= 45 ,

	E_TITLE_URLBOOKMARK = 46 ,
	E_TITLE_URLTOOLS ,
	E_TITLE_URLIMAGE ,
	E_TITLE_URLINPUT ,
	E_TITLE_AUTHENTICATION = 50 ,

	E_TITLE_AUTHENTICATIONOPTION = 51 ,
	E_TITLE_STARTDOWNLOADING ,
	E_TITLE_STOPDOWNLOADING ,
	E_TITLE_URLGOOPTIONWOIMAGE ,

	E_TITLE_HISTORY ,

	E_TITLE_HISTORYOPTION = 56,
	E_TITLE_HISTORYDETAILS ,
	E_TITLE_HISTORYURLLIST ,
	E_TITLE_HISTORYURLLISTOPTION ,
	E_TITLE_HISTORYURLLISTSORT ,

	E_TITLE_HISTORYURLLISTDETAILS ,
	E_TITLE_PROMPT  ,
	E_TITLE_HISTORYURLLISTSHOWURL ,
	E_TITLE_SCROLL ,
	E_TITLE_SCROLLMORE = 65 ,
	
	E_TITLE_CERTIFICATE = 66 ,
	E_TITLE_ROOTCERTIFICATE ,
	E_TITLE_ROOTCERTIFICATEOPTION ,
	E_TITLE_ROOTCERTIFICATEDETAILS ,
	E_TITLE_USERCERTIFICATE ,
	
	E_TITLE_SECURITY = 71 ,
	E_TITLE_CONTENT ,
	E_TITLE_CONTENTOPTION ,
	E_TITLE_PUSHINBOX ,
	E_TITLE_PUSHINBOXOPTION ,

	E_TITLE_PUSHINBOXSORT = 76,
	E_TITLE_PUSHMSGDETAILS ,
	E_TITLE_PUSHMSGDETAILSOPTION ,
	E_TITLE_FIND ,
	E_TITLE_FINDMODE ,

	E_TITLE_FINDMODEOPTION = 81,
	E_TITLE_SAVEPAGE  ,
	E_TITLE_SAVEOBJECT ,
	E_TITLE_USEFORM ,
	E_TITLE_DOWNLOADCONFIRMATION ,

	E_TITLE_ARR ,
	E_TITLE_ARROPTION ,
	E_TITLE_IMPORTEXPORT ,
	E_TITLE_EXPORTBOOKMARK ,
	E_TITLE_EXPORTCATEGORYOPTION ,
	E_TITLE_EXPORTFAVORITEOPTION ,
	E_TITLE_EXPORTEDITFAVORITEOPTION ,

	E_TITLE_PERSONALCATEGORY,
	E_TITLE_ENTERPASSWORD,
	E_TITLE_CHANGEPASSWORD,

	E_TITLE_PERSONALFAVORITE ,
	E_TITLE_PERSONALCATEGORYOPTION,
	E_TITLE_PERSONALFAVORITEOPTION,
	E_TITLE_LINKELEMENTS,

	E_TITLE_CSS,
	E_TITLE_CSSOPTION,

	E_TITLE_USEVALUE,

	E_TITLE_DISPLAYMODES,
	E_TITLE_JAVASCRIPTOPTIONS,
	E_TITLE_ACCELERATOR_URL,
	E_TITLE_ANTIBANNER,

#ifdef DE_PPP_READWRITE_CUSTOMIZE
	E_TITLE_CUSTOMIZE,
	E_TITLE_WIKIPEDIA,
	E_TITLE_CUSTOMIZEMENU,
#endif
#if (defined DE_PPP_READWRITE_WIDGET && defined APP_WIDGET_ENABLE)
	E_TITLE_WIDGETS,
	E_TITLE_WIDGETSDISPLAY,
	E_TITLE_WIDGETMENU,
#endif

#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_TITLE_DOWNLOADCLIENT,
	E_TITLE_DOWNLOADCLIENTOPTIONS,
#endif

#ifdef BROWSER_WINDOW_OPEN
	E_TITLE_WINDOWS,
	E_TITLE_WINDOWOPTIONS,
	E_TITLE_POPUP_BLOCKER,
#endif
        /*Write all TitleText above this*/
	E_TITLE_MAX

} E_TITLE_TEXT ;

typedef enum _soft_key_text
{
	E_SK_SELECT ,
	E_SK_EXIT ,
	E_SK_OPTIONS ,
	E_SK_CANCEL ,
	E_SK_BACK ,
	E_SK_OK ,
	E_SK_YES ,
	E_SK_NO ,
	E_SK_STOP ,
	E_SK_SAVE ,
	E_SK_USE ,
	E_SK_OPEN ,
	E_SK_PROCEED ,
	E_SK_RIGHTARROW ,
	E_SK_LEFTARROW ,
	E_SK_DELETE ,
	E_SK_SEARCH ,
	E_SK_NEXT ,
	E_SK_PREV ,
	E_SK_ENABLE,
#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_SK_UPDATE,
#endif
	/*Write all  softkey value above this*/
	E_SOFTKEY_MAX

} E_SOFTKEY_TEXT ;

typedef enum _primary_content
{
	/*[MORE-3]*/
	E_TEXT_NULL ,
	E_TEXT_MORE ,
	E_ICON_MORE ,
	
	/*[Title Page-12]*/
	E_TEXT_HOME ,
	E_TEXT_ENTERURL ,
	E_TEXT_BOOKMARKS ,
	E_TEXT_SETTINGS ,
	E_TEXT_PUSHINBOX ,
	E_TEXT_HISTORY,
	E_TEXT_CUSTOMIZE,
	E_TEXT_WIDGETS,
	E_TEXT_DOWNLOADCLIENT,
	E_TEXT_IMPORTEXPORT ,
	E_ICON_HOME ,
	E_ICON_ENTERURL ,
	E_ICON_BOOKMARKS ,
	E_ICON_SETTINGS ,
	E_ICON_PUSHINBOX ,
	E_ICON_HISTORY,
	E_ICON_CUSTOMIZE,
	E_ICON_WIDGETS,
	E_ICON_DOWNLOADCLIENT,

	/*[URLOPTION-14]*/
	E_TEXT_SHORTCUT,
	E_TEXT_GO ,
#ifdef BROWSER_WINDOW_OPEN
	E_TEXT_GONEWWINDOW,
#endif
	E_TEXT_ADDTOFAVORITE ,
	E_TEXT_SEARCHINHISTORY ,
	E_TEXT_AUTOFILL ,
	E_TEXT_SEND ,
	E_TEXT_CLEARURL ,
	E_TEXT_CANCEL ,
	/*IconPart*/
	E_ICON_SHORTCUT,
	E_ICON_GO ,
	E_ICON_ADDTOFAVORITE ,
	E_ICON_SEARCHINHISTORY ,
	E_ICON_AUTOFILL ,
	E_ICON_SEND ,
	E_ICON_CLEAR ,
	E_ICON_CANCEL ,

	 
	E_TEXT_ADDTOCATEGORY ,
	E_TEXT_ADDCATEGORY ,
	E_TEXT_CHANGEPASSWORD,
	E_TEXT_ADDFAVORITE ,
	E_ICON_ADDTOCATEGORY ,
	
	/*[AddCategory-1]*/
	E_TEXT_NAME ,

	/*[AddFavorite-1]*/
	E_TEXT_FAVROITETITLE ,
	
	/*[AddFavoriteOption-3]*/
	E_TEXT_SETFOCUSTITLE ,
	E_TEXT_SAVE ,
	E_TEXT_CLEARTITLE ,

	/*[Settings-9]*/
	E_TEXT_PROFILE ,
	E_TEXT_BEARER ,
	E_TEXT_DISPLAY ,
	E_TEXT_CSSPROPERTIES,
	E_TEXT_JAVASCRIPTOPTIONS,
	E_TEXT_PUSH ,
	E_TEXT_CACHECOOKIE ,
	E_TEXT_CERTIFICATE ,
	E_TEXT_SHORTCUTS ,
#ifdef APP_WALLET_ENABLE
	E_TEXT_WALLET ,
#endif
	E_TEXT_ACCELERATOR_URL,
	E_TEXT_ACITVATEWIZARD,
	
	/*EmptyProfile-1*/
	E_TEXT_ADDPROFILE ,

	/*Add/EditProfile-4*/
	E_TEXT_HOMEPAGE ,
	E_TEXT_MODE ,
	E_TEXT_IPADDRESS ,
	E_TEXT_PORTNUMBER ,
	E_TEXT_USERAGENTPROF,

	/*EmptyBearer-1*/
	E_TEXT_ADDBEARER ,

	/*Add/EditProfile-4*/
	E_TEXT_USERNAME ,
	E_TEXT_PASSWORD ,
	E_TEXT_TIMEOUT ,
	E_TEXT_ADDBEARERDETAILS ,

	/*CSDSETTING-3*/
	E_TEXT_PHONENO ,
	E_TEXT_CALLTYPE ,
	E_TEXT_CALLSPEED ,

	/*GPRSSETTING-1*/
	E_TEXT_APN ,

	/*Display-7*/
	E_TEXT_IMAGE ,
	E_TEXT_SELECTABLEIMAGES ,
	E_TEXT_DIRECTIMAGES,
	E_TEXT_FULLSCREEN ,
	E_TEXT_SIZE ,
	E_TEXT_AUDIO ,
	E_TEXT_POPUPWINDOWS ,
	E_TEXT_ACCESSKEYS ,
	E_TEXT_MAXDISPLAYWIDTH,
	E_TEXT_AUTHORCSS,
	E_TEXT_EMBEDDEDSTYLE,
	E_TEXT_MEDIATYPES,
	E_TEXT_METAREFRESH,
	E_TEXT_JAVASCRIPT,
	E_TEXT_SETTIMEOUT,
	E_TEXT_MINFONTSIZE,
	E_TEXT_ANTIBANNER,
	E_TEXT_STRICTXHTML,

	/*DisplayOption-1*/
	E_TEXT_SETTODEFAULT ,

	/*Push - 3*/
	E_TEXT_SERVICEINDICATION ,
	E_TEXT_SERVICELOADING ,
	E_TEXT_CACHEOPERATION ,

	/*Cache/Cookie-2*/
	E_TEXT_CACHE ,
	E_TEXT_COOKIE ,
	
	/*/Cache/CookieOption-2*/
	E_TEXT_CLEARCACHE ,
	E_TEXT_CLEARCOOKIE ,

	/*///shortcuts-2*/
	E_TEXT_SCHEME ,
	E_TEXT_KEYWORDS,
	E_TEXT_NUMBERS,
	E_TEXT_TELNUMBERS,
	E_TEXT_CURRENCY,
	E_TEXT_EMAILIDS,

#ifdef APP_WALLET_ENABLE
	/*WalletEntry-1*/
	E_TEXT_ENTERCODE ,
	/*WallerError-1*/
	E_TEXT_WALLETERRORCODE ,
	/*WALLET-4*/
	E_TEXT_ACCOUNTINFORMATION ,
	E_TEXT_ADDRESSINFORMATION ,

	E_ICON_ACCOUNTINFORMATION ,
	E_ICON_ADDRESSINFORMATION ,

	/*Empty Account-1*/
	E_TEXT_ADDACCOUNTINFORMATION ,

	/*EditAccountInformation-3*/
	E_TEXT_ACCOUNTNAME ,
	E_TEXT_VERIFYPASSWORD ,
	E_TEXT_OTHERINFORMATION ,


	/*EditAddressInformation-10*/
	E_TEXT_FIRSTNAME ,
	E_TEXT_MIDDLENAME ,
	E_TEXT_LASTNAME ,
	E_TEXT_COMPANY ,
	E_TEXT_STREETADDRESS ,
	E_TEXT_CITY ,
	E_TEXT_STATE ,
	E_TEXT_POSTALZIPCODE ,
	E_TEXT_COUNTRY ,
	E_TEXT_EMAILADDRESS ,
#endif

	/*Error-1*/
	E_TEXT_ERROR ,
	/*Information-1*/
	E_TEXT_INFORMATION ,
	/*Exclamation -1*/
	E_TEXT_EXCLAMATION ,
	/*Confirmation -1*/
	E_TEXT_CONFIRMATION ,

	/*ProfileOPtion - 4*/
	E_TEXT_EDIT ,
	E_TEXT_SETASACTIVE ,
	E_TEXT_DELETE ,
	E_TEXT_ADDNEW ,

	/*CategoryOption & Favorite Option - 3*/
	E_TEXT_OPEN ,
	E_TEXT_DELETEALL ,
	E_TEXT_MOVETO ,

	/*Move to Option-3*/
	E_TEXT_THISCATEGORY ,
	E_TEXT_OPENTHISCATEGORY,
	E_TEXT_ADDASSINGLE ,

	/*URL-GO Option PAGE -4 */
	E_TEXT_NAVIGATION ,
	E_TEXT_SCROLL ,
	E_TEXT_TOOLS ,
#ifdef BROWSER_WINDOW_OPEN
	E_TEXT_WINDOWS,
	E_TEXT_CLOSE,
	E_TEXT_SELECT,
	E_TEXT_POPUP_BLOCKER,
	E_TEXT_POPUP_BLOCKER_ACTION,
#endif
	E_TEXT_INPUT ,
	

	//URL Navigation - 6
	E_TEXT_BACK ,
	E_TEXT_FORWARD ,
	E_TEXT_REFRESH ,
	E_TEXT_TOP ,
	E_TEXT_BOTTOM ,
	E_TEXT_MAINMENU ,
	
	 
	//E_TEXT_OPEN ,
	E_TEXT_ADDTOBOOKMARK ,
	E_TEXT_ADDTOHIGHLIGHTEDLINK ,

	//URL - Tools - 7
	E_TEXT_SETASHOMEPAGE ,
	E_TEXT_PAGEPROPERTIES ,
	E_TEXT_SAVEPAGE ,
	E_TEXT_SENDAS ,
	E_TEXT_FIND ,
	E_TEXT_SEARCH ,
	E_TEXT_STATISTICS ,
	E_TEXT_ABOUTUS ,

	//URL- Image- 1
	E_TEXT_PROPERTIES ,
	
	//URL_Input - 2
#ifdef APP_WALLET_ENABLE
	E_TEXT_USEWALLET ,
#endif
	E_TEXT_USEFORMCONTENT ,

	//Authentication
	E_TEXT_REMEMBERPASSWORD ,
	
	//Authentication Option
	E_TEXT_OK ,
	E_TEXT_CLEARUSERNAME ,
	E_TEXT_CLEARPASSWORD ,

	/*History option*/
	//E_TEXT_OPEN
	E_TEXT_CLEAR ,
	E_TEXT_CLEARALL ,
	E_TEXT_SORTASCENDING ,
	E_TEXT_SORTDESCENDING ,
	E_TEXT_DETAILS ,

	/*History Details*/
	E_TEXT_DOMAINNAME ,
	E_TEXT_TOTALURL ,

	/*url Details option*/
	E_TEXT_LOADURL ,
	//E_TEXT_DETAILS ,
	//E_TEXT_CLEAR ,
	//E_TEXT_CLERALL
	//E_TEXT_ADDTOFAVORITE ,
	E_TEXT_SHOWURL ,
	E_TEXT_SORT ,

	/*History Sort*/
	E_TEXT_ORDER ,
	E_TEXT_BASE ,

	/*Url Details*/
	//E_TEXT_TITLE ,
	E_TEXT_URL ,
	E_TEXT_TITLE ,
	E_TEXT_LASTACCESSEDTIME ,
	
	/*Scroll*/
	E_TEXT_SCROLLUP ,
	E_TEXT_SCROLLDOWN ,
	E_TEXT_SCROLLLEFT ,
	E_TEXT_SCROLLRIGHT ,
	E_TEXT_PAGEUP ,	
	E_TEXT_PAGEDOWN ,
	E_TEXT_SCROLLMORE ,

	/*SctrollMore*/
	E_TEXT_PAGETOPLEFT ,
	E_TEXT_PAGETOPCENTER ,
	E_TEXT_PAGETOPRIGHT ,
	E_TEXT_PAGECENTERLEFT ,
	E_TEXT_PAGECENTERCENTER ,
	E_TEXT_PAGECENTERRIGHT ,
	E_TEXT_PAGEBOTTOMLEFT ,
	E_TEXT_PAGEBOTTOMCENTER ,
	E_TEXT_PAGEBOTTOMRIGHT ,

	E_TEXT_ROOTCERTIFICATE ,
	E_TEXT_USERCERTIFICATE ,

	/*RootCertificate*/

	/*RootCertificateOption*/
	/*E_TEXT_DETAILS*/
	/*E_TEXT_DELTE*/
	/*E_TEXT_DELETEALL*/

	/*RootCertificate Details*/
	E_TEXT_ISSUERNAME ,
	E_TEXT_VALIDITYPERIOD ,

	/*User Details*/

	/*Security*/
	E_TEXT_POSTDATA ,
	E_TEXT_SECURETONONSECURE ,
	E_TEXT_DOWNLOADNONSECURE ,

	/*Content*/
	E_TEXT_SAVEFORMCONTENT ,

	/*ContentOption*/
	/*E_TEXT_SAVE*/
	E_TEXT_CLEARFORMCONTENT ,
	/*E_TEXT_SETTODEFAULT*/
	/*Push Inbox*/
	
	/*Push Inbox Option*/
	/*E_TEXT_LOADURL ,*/
	/*E_TEXT_DETAILS*/
	/*E_TEXT_DELTE*/
	/*E_TEXT_ADDTOFAVORITE*/
	/*E_TEXT_DELETEALLL*/
	/*E_TEXT_SORT*/

	/*PushInboxSort*/
	/*E_TEXT_ORDER ,*/
	/*E_TEXT_BASE */

	/*PushInboxMessageDetails*/
	E_TEXT_MESSAGE ,
	/*E_TEXT_URL*/
	E_TEXT_TIME ,

	/*PushInboxMessageDetailsOption*/
	/*E_TEXT_LOADURL ,*/
	/*E_TEXT_DELTE*/
	/*E_TEXT_DELTEALL*/

	/*Find*/
	E_TEXT_DIRECTION ,
	E_TEXT_MATCHCASE ,
	E_TEXT_MATCHWHOLEWORD ,
	E_TEXT_FINDTYPE ,

	/*Find Mode*/

	/*FindModeOption*/
	E_TEXT_FINDMODEUSE,
	E_TEXT_FINDMODECHANGEDIRECTION,
	E_TEXT_FINDMENU,
	E_TEXT_FINDMODECANCEL,

	/*SavePage*/
	E_TEXT_CONTENTTYPE ,
	E_TEXT_FILENAME ,
	E_TEXT_SAVEASTYPE ,

	/*SaveObject*/
	/*E_TEXT_FILENAME*/
	E_TEXT_OBJECTTYPE ,
	E_TEXT_OBJECTSIZE ,

	/*UseFormValue*/

	/*DownloadConfirmation*/
	E_TEXT_TYPE ,
	/*E_TEXT_SIZE ,*/
	/*E_TEXT_NAME ,*/
	E_TEXT_DESCRIPTION ,
#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_TEXT_VERSION,
	E_TEXT_PRODUCT,
#endif

	/*Arr Rules*/
	E_TEXT_ARR,
	E_TEXT_GENERAL,
	E_TEXT_FORM,
	E_TEXT_BUTTON,
	/*E_TEXT_IMAGE,*/
	E_TEXT_TABLE,
	E_TEXT_IMAGEMAP,
	E_TEXT_AREAR,
	E_TEXT_FRAME,
	E_TEXT_NOFRAME,
	E_TEXT_IFRAME,
	E_TEXT_LINK,
	E_TEXT_FONTSIZE,
	E_TEXT_MARGIN,
	E_TEXT_PADDING,
	E_TEXT_POSITION,
	E_TEXT_FLOATTEXT,
	E_TEXT_BGIMAGE,
	E_TEXT_TEXTINDENTATION,
	E_TEXT_OVERFLOW,
	E_TEXT_HIDDEN,
	E_TEXT_MOUSEOVER,
	E_TEXT_FIXEDPOSITION,
#ifdef UNSUPPORTED_ARR_RULES
	E_TEXT_MOUSECLICK,
#endif
	E_TEXT_PERCENTAGE,
	E_TEXT_INDENTATION,
	E_TEXT_WRAPTEXT,
	E_TEXT_LINEHEIGHT,
	/*ImportExport Page*/
	E_TEXT_IMPORTBOOKMARK ,
	E_TEXT_EXPORTBOOKMARK ,
	 
	E_TEXT_EXPORT ,

	/*PersonalCategory*/
	E_TEXT_CATEGORYNAME,
	E_TEXT_ENTERPASSWORD,
	E_TEXT_REENTERYOURPASSWORD,

	/*Enter Password*/
	/*Change Password*/
	E_TEXT_ENTEROLDPASSWORD,

	/*LinkElement Added in Opton*/
	E_TEXT_LINKELEMENTS,
	E_TEXT_EXIT,

	E_TEXT_F2S_MODE,
	E_TEXT_NATURAL_MODE,
	E_TEXT_CONFORMANCE_MODE,

	E_TEXT_OPTION,

#ifdef BROWSER_MOBILE_WEB
	E_TEXT_MOBILEWEB_MODE,
#endif

	/*/ICON-9*/
	E_ICON_NO1 ,
	E_ICON_NO2 ,
	E_ICON_NO3 ,
	E_ICON_NO4 ,
	E_ICON_NO5 ,
	E_ICON_NO6 ,
	E_ICON_NO7 ,
	E_ICON_NO8 ,
	E_ICON_NO9 ,
	
#ifdef DOWNLOAD_CLIENT2_ENABLE
	E_TEXT_UPDATE,
#endif

	/*Write all the primary message above this*/
	E_PRIMARY_MAX 
			//(150)
	
} E_PRIMARY_CONTENT;

typedef enum _e_combobox_content
{
	/*Find*/
	E_COMBO_UP,
	E_COMBO_DOWN,
	E_COMBO_ON,
	E_COMBO_OFF,
	E_COMBO_PAGEONLY,
	E_COMBO_MULTIPLEFILE,
	E_COMBO_SINGLEFILE,
	
	E_COMBO_FITONEXCEED,
	E_COMBO_ALWAYSFIT,
	E_COMBO_PAGEINST,
	E_COMBO_OPTIMIZE,

	E_COMBO_TRUNCATECOMBO,
	E_COMBO_MULTILINE,
	E_COMBO_MARQUEE,
	//E_COMBO_PAGEINST,

	E_COMBO_ASPECTFIT,
	//E_COMBO_PAGEINST,

	E_COMBO_2DHSCROLLTABLE,
	E_COMBO_2DFITSCREEN,
	E_COMBO_1DROWORDER,
	E_COMBO_1DCOLORDER,

	E_COMBO_IGNORE,
	E_COMBO_NEWWINDOW,
	E_COMBO_SAMEWINDOW,
	E_COMBO_POLYLINE_SAMEWINDOW,
	E_COMBO_LINKSSAMEWINDOW,
	E_COMBO_LINKSNEWWINDOW,

	E_COMBO_ADJUSTASPECT,
	E_COMBO_COORDINATE,

	E_COMBO_LINKS,
	E_COMBO_DIV,
	//COMBO_IGNORE,

	/*NoFrame*/
	//E_COMBO_IGNORE,
	E_COMBO_RENDER,
	
	/*IFrame*/
	E_COMBO_LINK,
	//E_COMBO_DIV,
	E_COMBO_CONTENT,

	/*Link*/
	//E_COMBO_IGNORE,
	E_COMBO_DISPLAY_TOP,
	E_COMBO_DISPLAY_MENU,

	/*Font Size*/
    //E_COMBO_PAGEINST,
	//E_COMBO_IGNORE,

	/*Margin*/
	//E_COMBO_PAGEINST,
	//E_COMBO_IGNORE,
	E_COMBO_SCALE_RATIO,
	E_COMBO_SCALE_ON_EXCEED,
	E_COMBO_IGNORE_ON_EXCEED,

	/*Paddding*/
	//E_COMBO_PAGEINST,
	//E_COMBO_IGNORE,
	//E_COMBO_SCALE_RATIO,

	/*Postion*/
	//E_COMBO_PAGEINST,
	//E_COMBO_IGNORE,
	
	/*OverFlow*/
	E_COMBO_EXTEND,
	E_COMBO_HIDE,
	/*Percentage*/
	//E_COMBO_PAGEINST,
	//E_COMBO_IGNORE,
	/*Indentation*/
	E_COMBO_MAXLEVEL,
	E_COMBO_ALLLEVEL,
	/*FloatText*/
	E_COMBO_ALONGSIDE,
	E_COMBO_MOVEBEYOND,
	/*Wrap Text*/
	//E_COMBO_PAGEINST,
	E_COMBO_WRAP,
	E_COMBO_MARQUEEONFOCUS,
	/*Mouse Over*/
	E_COMBO_ASSOCIATEACTION,
	//E_COMBO_IGNORE,
	/*Mouse Click*/
	//E_COMBO_PAGEINST,
	E_COMBO_MENU,
	/*Search Page*/
	E_COMBO_START ,
	E_COMBO_CURRENT ,
	E_COMBO_HIGHLIGHT ,

	/*Line Height*/
	E_COMBO_OVERFLOW,

	/*Hidden*/
	E_COMBO_COLLAPSE,

	/* Customize */
	E_COMBO_WIKIPEDIA,
	E_COMBO_ORKUT,
	E_COMBO_FACEBOOK,

	/*Wirte all the Combo message above this*/
	E_COMBO_MAX

} E_COMBOBOX_CONTENT ;

typedef enum _e_checkbox_content
{

	E_CHECK_NULL ,

	/*Wirte all the Combo message above this*/
	E_CHECK_MAX ,

} E_CHECKBOX_CONTENT ;

typedef enum _e_pathname_content
{

	E_PATHNAME_BOOKMARK ,
	/*Wirte all the path names above this*/
	E_PATHNAME_MAX ,

} E_PATHNAME_CONTENT ;

typedef struct _interface_attrb
{
	JC_CHAR				*pamTitleText[E_TITLE_MAX] ;
	JC_CHAR				*pamSoftKeyText[E_SOFTKEY_MAX] ;
	JC_CHAR				*pamPrimaryText[E_PRIMARY_MAX] ;
	JC_CHAR				*pamComboBoxText[E_COMBO_MAX] ;
	JC_CHAR				*pamCheckBoxText[E_CHECK_MAX] ;
	JC_CHAR				*pamPathName[E_PATHNAME_MAX] ;
	/*JC_UINT8			*pucStartPrgImageBuffer ;
	JC_UINT32			 uiStartPrgImageSize ;*/
	

	JC_UINT32			uiTotalSoftKeyText ;
	
    ST_SCROLLBAR_ATTRB		stVertScrollAttrb ;
	ST_SCROLLBAR_ATTRB		stHorzScrollAttrb ;
	ST_TITLE_ATTRB			stTitleAttrb ;
	ST_SOFTKEY_ATTRB		stSoftKeyAttrb ;
	ST_PRIMARY_ATTRB		stPrimaryAttrb ;
	ST_MESSAGEBOX_TEXT		stMessageBoxText ;

	

} ST_INTERFACE_ATTRB ;

typedef enum _e_setting_mode
{
	E_SETTINGS_DEFAULT_ON ,
	E_SETTINGS_DEFAULT_OFF 

} E_SETTINGS_MODE ;

typedef struct _settings_file_name
{
	JC_CHAR			*pmDefaultOn ;
	JC_CHAR			*pmDefaultOff ;
	JC_CHAR			*pmProfileFile ;
	JC_CHAR			*pmBearerFile ;
	JDD_FSHANDLE	vFSHandleDefaultOn ;
	JDD_FSHANDLE	vFSHandleDefaultOff ;
	JDD_FSHANDLE	vFSHandleProfileFile ;
	JDD_FSHANDLE	vFSHandleBearerFile ;

} ST_SETTINGS_FILENAME ;

typedef enum _e_mode_value
{
	E_MODE_VALUE_NATURAL ,
	E_MODE_VALUE_F2S,
	E_MODE_VALUE_CONFORMANCE,
#ifdef BROWSER_MOBILE_WEB
	E_MODE_VALUE_MOBILEWEB
#endif
} E_MODE_VALUE ;

typedef enum _e_image_value
{
	E_IMAGE_VALUE_ENABLE ,
	E_IMAGE_VALUE_DISABLE ,
	E_IMAGE_VALUE_SMARTIMAGE

} E_IMAGE_VALUE ;

typedef enum _e_selectable_image_value
{
	E_SELECTABLEIMAGE_VALUE_ON ,
	E_SELECTABLEIMAGE_VALUE_OFF

} E_SELECTABLEIMAGE_VALUE ;

typedef enum _e_direct_image_value
{
	E_DIRECTIMAGE_VALUE_ON ,
	E_DIRECTIMAGE_VALUE_OFF

} E_DIRECTIMAGE_VALUE ;

typedef enum _e_fullscreen_value
{
	E_FULLSCREEN_VALUE_ON ,
	E_FULLSCREEN_VALUE_OFF 	
	
} E_FULLSCREEN_VALUE	;

typedef enum e_textsize_value
{
	E_TEXTSIZE_VALUE_LARGEST ,
	E_TEXTSIZE_VALUE_LARGER ,
	E_TEXTSIZE_VALUE_MEDIUM ,
	E_TEXTSIZE_VALUE_SMALLER ,
	E_TEXTSIZE_VALUE_SMALLEST

} E_TEXTSIZE_VALUE ;

typedef enum _e_audio_value
{
	E_AUDIO_VALUE_ENABLE ,
	E_AUDIO_VALUE_DISABLE

} E_AUDIO_VALUE ;

typedef enum _e_scriptiong_value
{
	E_SCRIPTING_VALUE_ENABLE ,
	E_SCRIPTING_VALUE_DISABLE 

} E_SCRIPTING_VALUE ;

typedef enum _e_popupwindow_value
{
	E_POPUPWINDOW_VALUE_ENABLE ,
	E_POPUPWINDOW_VALUE_DISABLE  
} E_POPUPWINDOW_VALUE ;

typedef enum _e_accesskey_value
{
	E_ACCESSKEY_DISPLAY_END ,
	E_ACCESSKEY_DISPLAY_FRONT ,
	E_ACCESSKEY_DISPLAY_NONE ,
	E_ACCESSKEY_DISABLED
} E_ACCESSKEY_VALUE ;

typedef enum _e_max_display_width_value
{
	E_MAX_DISPLAY_WIDTH_400 ,
	E_MAX_DISPLAY_WIDTH_800
} E_MAX_DISPLAY_WIDTH_VALUE ;

typedef enum _e_meta_refresh_value
{
	E_META_REFRESH_ENABLE,
	E_META_REFRESH_DISABLE
} E_META_REFRESH_VALUE ;

typedef enum e_author_css_value
{
	E_AUTHOR_CSS_ENABLE,
	E_AUTHOR_CSS_DISABLE
} E_AUTHOR_CSS_VALUE ;

typedef enum e_javascript_value
{
	E_JAVASCRIPT_ENABLE,
	E_JAVASCRIPT_DISABLE,
	E_JAVASCRIPT_ENABLE_NOCONFIRM
} E_JAVASCRIPT_VALUE ;

typedef enum e_embedded_style_value
{
	E_EMBEDDED_STYLE_BLOCK_LEVEL,
	E_EMBEDDED_STYLE_PAGE_LEVEL
} E_EMBEDDED_STYLE_VALUE ;

typedef enum e_set_time_out_value
{
	E_SET_TIME_OUT_ENABLE,
	E_SET_TIME_OUT_DISABLE
} E_SET_TIME_OUT_VALUE ;

typedef enum _e_strict_xhtml_value
{
	E_STRICT_XHTML_DISABLE,
	E_STRICT_XHTML_ENABLE
} E_STRICT_XHTML_VALUE ;

/*static JC_INT8 *gpacCSSMediaTypes [] =
{
	"all",
	"screen",
	"handheld",
	"aural",
	"braille",
	"embossed",
	"print",
	"projection",
	"tty",
	"tv",
	JC_NULL
} ;*/

typedef struct _settings_display 
{
	E_MODE_VALUE				eModeValue ;
	E_IMAGE_VALUE				eImageValue ;
	E_SELECTABLEIMAGE_VALUE		eSelectableImageValue ;
	E_DIRECTIMAGE_VALUE			eDirectImageValue ;
	E_FULLSCREEN_VALUE			eFullScreenValue ;
	E_TEXTSIZE_VALUE			eTextSizeValue ;
	E_AUDIO_VALUE				eAudioValue ;
	E_POPUPWINDOW_VALUE			ePopupWindowValue ;
	E_ACCESSKEY_VALUE			eAccesskeyValue ;
	E_MAX_DISPLAY_WIDTH_VALUE	eMaxDisplayWidth ;
	E_META_REFRESH_VALUE		eMetaRefreshValue ;
	E_STRICT_XHTML_VALUE		eStrictXhtmlValue ;
	JC_CHAR						*pmMinFontSize ;
} ST_SETTINGS_DISPLAY ;

typedef struct _settings_css
{
	E_AUTHOR_CSS_VALUE			eAuthorCSSValue ;
	E_EMBEDDED_STYLE_VALUE		eEmbeddedStyleValue ;
	JC_INT8						*pacCSSMediaTypes [MAX_CSS_MEDIA_TYPES] ;
	JC_UINT32					uiSelectTypeCount ;
} ST_SETTINGS_CSS ;

typedef struct _settings_javascript
{
	E_JAVASCRIPT_VALUE			eJavaScriptValue ;
	E_SET_TIME_OUT_VALUE		eSetTimeOutValue ;
} ST_SETTINGS_JAVASCRIPT ;

typedef enum _serviceindication_value
{
	E_SERVICEINDICATION_VALUE_VISUALALERT ,
	E_SERVICEINDICATION_VALUE_AUDIOALERT ,
	E_SERVICEINDICATION_VALUE_VIBRATEALERT ,
	E_SERVICEINDICATION_VALUE_SILENT ,
	E_SERVICEINDICATION_VALUE_IGNORE

} E_SERVICEINDICATION_VALUE	;

typedef enum _serviceloading_value
{
	E_SERVICELOADING_VALUE_AUTOLOAD ,
	E_SERVICELOADING_VALUE_VISUALALERT ,
	E_SERVICELOADING_VALUE_AUDIOALERT ,
	E_SERVICELOADING_VALUE_VIBRATEALERT ,
	E_SERVICELOADING_VALUE_SILENT ,
	E_SERVICELOADING_VALUE_IGNORE

} E_SERVICELOADING_VALUE ;

typedef enum e_cache_operation_value
{
	E_CACHEOPERATION_VALUE_ALLOW ,
	E_CACHEOPERATION_VALUE_IGONORE 

} E_CACHEOPERATION_VALUE ;

typedef struct _settings_push
{
	JC_CHAR						*pmPushMsgFileName ;
	JC_UINT32					uiMaxPushMsgCount ;
	E_SERVICEINDICATION_VALUE	eServiceIndicationValue ;
	E_SERVICELOADING_VALUE		eServiceLoadingValue ;
	E_CACHEOPERATION_VALUE		eCacheOperationValue ;
	E_PUSH_SORT_ORDER			ePushSortOrder ;
	E_PUSH_SORT_ITEM_LIST		ePushSortItemList ;
} ST_SETTINGS_PUSH ;

typedef enum _e_cache_value
{
	E_CACHE_VALUE_ENABLE ,
	E_CACHE_VALUE_DISABLE
} E_CACHE_VALUE ;

typedef enum _e_cookie_value
{
	E_COOKIE_VALUE_ENABLE ,
	E_COOKIE_VALUE_DISABLE
} E_COOKIE_VALUE ;

typedef struct _settings_cachecookie
{
	E_CACHE_VALUE		eCacheValue ;
	E_COOKIE_VALUE		eCookieValue ;
} ST_SETTINGS_CACHECOOKIE ;

typedef struct _settings_shortcuts
{
	JC_CHAR		*pmScheme ;
	JC_CHAR		*pmKeyWords ;
	
} ST_SETTINGS_SHORTCUTS ;

typedef enum e_connenctionmode
{
	E_CONNECTIONMODE_CONNECTIONORIENTED ,
	E_CONNECTIONMODE_CONNECTIONSECUREORIENTED ,
	E_CONNECTIONMODE_HTTPPROXY ,
	E_CONNECTIONMODE_HTTPDIRECT
} E_CONNECTIONMODE ;

typedef enum e_useragentprof
{
	E_JB5_BROWSER_PROF ,
	E_MOZILLA_BROWSER_PROF
} E_USERAGENTPROF ;

typedef enum _e_app_uaprof_change
{
	E_APP_NO_CHANGE,
	E_APP_JB5_TO_MOZILLA,
	E_APP_MOZILLA_TO_JB5
} E_APP_UAPROF_CHANGE ;

typedef struct _settings_profile
{
	JC_CHAR						*pmName ;
	JC_CHAR						*pmHomePage ;
	E_CONNECTIONMODE			eConnectionMode ;
	E_USERAGENTPROF				eUAProf ;
	E_APP_UAPROF_CHANGE			eUAProfChange ;
	JC_CHAR						*pmIPAddress ;
	JC_CHAR						*pmBearerName ;
	JC_UINT32					uiPortNumber ;
	JC_UINT32					uiMinPortNumber ;
	JC_UINT32					uiMaxPortNumber ;
	struct _settings_profile	*pNext ;
} ST_SETTINGS_PROFILE ;

typedef enum e_bearermode
{
	E_BEARERMODE_CSD ,
	E_BEARERMODE_GPRS ,
	E_BEARERMODE_3G

} E_BEARERMODE ;

typedef struct _berarer_mode_gprs
{
	JC_CHAR		*pmAPN ;

} ST_BEARERMODE_GPRS ;

typedef enum _e_call_type_value
{
	E_CALLTYPE_ANALOGUE ,
	E_CALLTYPE_ISDN

} E_CALLTYPE ;

typedef enum _e_call_speed_value
{
	E_CALLSPEED_4400 ,
	E_CALLSPEED_9600 ,
	E_CALLSPEED_14400

} E_CALLSPEED ;

typedef struct _bearer_mode_csd
{
	JC_CHAR			*pmPhoneNumber ;
	E_CALLTYPE		eCallType ;
	E_CALLSPEED		eCallSpeed ;

} ST_BREARERMODE_CSD ;

typedef struct _settings_bearer
{
	JC_CHAR				*pmName ;
	JC_CHAR				*pmUserName ;
	JC_CHAR				*pmPassword ;
	JC_UINT32			uiTimeOut ;
	E_BEARERMODE		eBearerMode ;
	JC_BOOLEAN			bOpenBearerMode ;

	union 
	{
		ST_BEARERMODE_GPRS	stBearerModeGPRS ;
		ST_BREARERMODE_CSD	stBearerModeCSD ;

	} unBearerMode ;

	struct _settings_bearer	*pNext ;

} ST_SETTINGS_BEARER ;

typedef struct _settings_text
{
	JC_CHAR		*pmNullText ;
	JC_CHAR		*pmActiveText ;
	JC_CHAR		*pmNotActiveText ;
} ST_SETTINGS_TEXT ;

typedef struct _settings_active_profile
{
	JC_UINT8		ucActiveProfileID ;
	JC_UINT8		ucActivePageID ;
	JC_UINT32		uiBackgroundColor ;
	JC_UINT32		uiForegroundColor ;

} ST_SETTINGS_ACTIVEPROFILE ;

typedef struct _settings_connection
{
	JC_UINT8		ucActiveMenuID ;
	JC_UINT8		ucActivePageID ;
	JC_UINT32		uiBackgroundColor ;
	JC_UINT32		uiForegroundColor ;

} ST_SETTINGS_ACTIVECONNECTION ;

typedef enum _e_browser_history_sort_order
{
	E_BROWSER_HISTORY_ORIGINAL_ORDER ,
	E_BROWSER_HISTORY_ASCENDING_ORDER ,
	E_BROWSER_HISTORY_DESCENDING_ORDER
} E_BROWSER_HISTORY_SORT_ORDER ;

typedef enum _e_browser_history_sort_item
{
	E_BROWSER_HISTORY_SORT_URL ,
	E_BROWSER_HISTORY_SORT_ACCESSED_TIME ,
} E_BROWSER_HISTORY_SORT_ITEM ;

typedef struct _settings_history
{
	E_BROWSER_HISTORY_SORT_ORDER	eSortOrderDomain ;
	E_BROWSER_HISTORY_SORT_ORDER	eSortOrderURL ;
	E_BROWSER_HISTORY_SORT_ITEM		eSortItem ;
} ST_SETTINGS_HISTORY ;

typedef struct _settings_category
{
	JC_CHAR		*pmCategoryName ;
	JC_CHAR		*pmPassword ;
} ST_SETTINGS_CATEGORY ;

#ifdef BROWSER_WINDOW_OPEN
typedef enum _e_popupblocker_options
{
	E_POPUPBLOCKER_ENABLE,
	E_POPUPBLOCKER_ENABLE_CONFIRMATION,
	E_POPUPBLOCKER_DISABLE
} E_POPUPBLOCKER_OPTIONS ;

typedef enum _e_popupblocker_settings
{
	E_POPUPBLOCKER_BLOCK_UNWANTED,
	E_POPUPBLOCKER_BLOCK
} E_POPUPBLOCKER_SETTINGS ;

typedef struct _settings_popupblocker
{
	E_POPUPBLOCKER_OPTIONS	ePopUpBlockerOptions ;
	E_POPUPBLOCKER_SETTINGS	ePopUpBlockerSettings ;
} ST_SETTINGS_POPUPBLOCKER ;
#endif

typedef struct _browser_settings
{
	JC_BOOLEAN						bAntiBannerEnable ;
	JC_BOOLEAN						bAcceleratorEnable ;
	JC_CHAR							*pmAcceleratorURL ;

	JC_CHAR							*pmPrimaryText [E_COMBO_MAX] ;
	JC_CHAR							*pamComboBoxText[E_COMBO_MAX] ;
	JC_UINT8						ucTotalProfile ;
	JC_UINT8						ucTotalBearer ;

	E_SETTINGS_MODE					eSettingsMode ;
	ST_SETTINGS_FILENAME			stSettingsFileName ;
	
	ST_SETTINGS_DISPLAY				stSettingsDisplay ;
	ST_SETTINGS_CSS					stSettingsCSS ;
	ST_SETTINGS_JAVASCRIPT			stSettingsJavaScript ;
	ST_SETTINGS_PUSH				stSettingsPush ;
	ST_SETTINGS_CACHECOOKIE			stSettingsCacheCookie ;
	ST_SETTINGS_SHORTCUTS			stSettingsShortcuts ;

	
	ST_SETTINGS_PROFILE				stSettingsProfile ;
	ST_SETTINGS_BEARER				stSettingsBearer ;
	ST_SETTINGS_TEXT				stSettingsText ;
	ST_SETTINGS_ACTIVEPROFILE		stSettingsActiveProfile ;
	ST_SETTINGS_ACTIVECONNECTION	stSettingsActiveBearer ;

	ST_SETTINGS_HISTORY				stSettingsHistory ;
	ST_ARR_RULES					stSettingsArrNatural ;
	ST_ARR_RULES					stSettingsArrF2S ;
	ST_ARR_RULES					stSettingsArrConformance ;
#ifdef BROWSER_MOBILE_WEB
	ST_ARR_RULES					stSettingsArrMobileWeb ;
#endif
	ST_SETTINGS_CATEGORY			stSettingsPersonalCategory ;
#ifdef BROWSER_WINDOW_OPEN
	ST_SETTINGS_POPUPBLOCKER		stSettingsPopUpBlocker ;
#endif
	
} ST_BROWSER_SETTINGS ;


typedef struct _st_bookmark_attrb
{
	JC_CHAR			*pmBookmarkFileName ;
	JC_UINT32		uiMaxCategory ;
	JC_UINT32		uiMaxBookmark ;
	JC_BOOLEAN		bFileMultiStorage ;
} ST_BOOKMARK_SETTINGS ;


	
JC_RETCODE  jdi_BrowserHandleInitialize (JC_HANDLE				*pvBrAppHandle,
										 ST_BROWSER_SETTINGS	*pstBrSettings) ;

JC_RETCODE  jdi_BrowserHandleDeInitialize (JC_HANDLE vBrAppHandle) ;

JC_RETCODE	jdi_BrowserBookmarkInitialize (JC_HANDLE			vBrAppHandle,
										   ST_BOOKMARK_SETTINGS	*pstBookmarkSettings) ;
JC_RETCODE	jdi_BrowserBookmarkDeInitialize (JC_HANDLE			vBrAppHandle) ;

JC_RETCODE	jdi_BrowserPushMsgInitialize (JC_HANDLE				vBrAppHandle,
									      ST_SETTINGS_PUSH		*pstSettingsPushMsg) ;

JC_RETCODE	jdi_BrowserPushMsgDeInitialize (JC_HANDLE	vBrAppHandle) ;

JC_RETCODE	jdi_BrowserDownloadClientInitialize (JC_HANDLE	vBrAppHandle) ;

JC_RETCODE	jdi_BrowserDownloadClientDeInitialize (JC_HANDLE	vBrAppHandle) ;

JC_RETCODE jdi_BrowserRSSClientInitialize (JC_HANDLE		vBrAppHandle) ;

JC_RETCODE	jdi_BrowserRSSClientDeInitialize (JC_HANDLE	vBrAppHandle) ;

JC_RETCODE jdi_BrowserAppInitialize (JC_HANDLE					vAppHandle ,
									 JC_UINT32					uiWindowID , 
									 ST_BROWSER_APP_ATTRIBUTE	*pstBrowserAttr,
									 ST_INTERFACE_ATTRB			*pstIntAttrb ) ;

#ifdef BROWSER_APP_LOAD_TESTING_ON
JC_RETCODE jdi_BrowserLoadTestInitialize (JC_HANDLE		vAppHandle, 
										  JC_BOOLEAN	bIsContinue) ;
#endif
JC_RETCODE jdi_BrowserAppDeInitialize (JC_HANDLE				vAppHandle , 
								 ST_INTERFACE_ATTRB	*pstIntAttrb) ;


JC_RETCODE jdi_BrowserAppEvent (JC_HANDLE vAppHandle, JC_EVENT_DATA *pstEvent) ;

#ifdef BROWSER_DEBUG_ENABLE
typedef enum _e_browser_debug_type
{
	E_DEBUG_XML,
	E_DEBUG_CSS,
	E_DEBUG_LAYOUT
} E_BROWSER_DEBUG_TYPE ;

typedef void (* CB_DEBUG_DISPLAY) (JC_UINT32, E_BROWSER_DEBUG_TYPE, JC_HANDLE) ;
JC_RETCODE jdi_BrowserSetDebugCallback (JC_HANDLE			vAppHandle, 
										CB_DEBUG_DISPLAY	cbDebugDisplay) ;
#endif


#ifdef __cplusplus
}
#endif

#endif


